//Maya ASCII 2012 scene
//Name: Bomb.ma
//Last modified: Mon, Aug 22, 2011 11:45:21 AM
//Codeset: ISO-8859-1
requires maya "2012";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2012";
fileInfo "version" "2012 x64";
fileInfo "cutIdentifier" "201108212005-808605";
fileInfo "osv" "Linux 2.6.23.15-137.fc8 #1 SMP Sun Feb 10 17:03:13 EST 2008 x86_64";
createNode transform -s -n "persp";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 7.4671171572587802 2.6947731301829942 1.1450790130827762 ;
	setAttr ".r" -type "double3" -14.738352729599118 -278.20000000000255 0 ;
createNode camera -s -n "perspShape" -p "persp";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 9.6070122493509533;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 100.1 0 ;
	setAttr ".r" -type "double3" -89.999999999999986 0 0 ;
createNode camera -s -n "topShape" -p "top";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 100.1 ;
createNode camera -s -n "frontShape" -p "front";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 100.1 0 0 ;
	setAttr ".r" -type "double3" 0 89.999999999999986 0 ;
createNode camera -s -n "sideShape" -p "side";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode transform -n "BombGroup";
createNode transform -n "ejectaNParticle1" -p "BombGroup";
createNode nParticle -n "ejectaNParticleShape1" -p "ejectaNParticle1";
	addAttr -ci true -sn "lifespanPP" -ln "lifespanPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "lifespanPP0" -ln "lifespanPP0" -dt "doubleArray";
	addAttr -ci true -sn "lifespan" -ln "lifespan" -at "double";
	addAttr -ci true -sn "rgbPP" -ln "rgbPP" -dt "vectorArray";
	addAttr -ci true -h true -sn "rgbPP0" -ln "rgbPP0" -dt "vectorArray";
	addAttr -ci true -sn "opacityPP" -ln "opacityPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "opacityPP0" -ln "opacityPP0" -dt "doubleArray";
	addAttr -is true -ci true -sn "betterIllumination" -ln "betterIllumination" -min 
		0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "surfaceShading" -ln "surfaceShading" -min 0 -max 
		1 -at "float";
	addAttr -is true -ci true -sn "colorAccum" -ln "colorAccum" -min 0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "useLighting" -ln "useLighting" -min 0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "pointSize" -ln "pointSize" -dv 2 -min 1 -max 60 -at "long";
	addAttr -is true -ci true -sn "normalDir" -ln "normalDir" -dv 2 -min 1 -max 3 -at "long";
	addAttr -ci true -sn "ejectaFluidEmitter1RatePP" -ln "ejectaFluidEmitter1RatePP" 
		-dt "doubleArray";
	addAttr -ci true -h true -sn "ejectaFluidEmitter1RatePP0" -ln "ejectaFluidEmitter1RatePP0" 
		-dt "doubleArray";
	addAttr -ci true -h true -sn "ejectaFluidEmitter1RemainderPP" -ln "ejectaFluidEmitter1RemainderPP" 
		-dt "doubleArray";
	addAttr -ci true -h true -sn "ejectaFluidEmitter1RemainderPP0" -ln "ejectaFluidEmitter1RemainderPP0" 
		-dt "doubleArray";
	setAttr -k off ".v";
	setAttr ".io" yes;
	setAttr ".gf" -type "Int32Array" 0 ;
	setAttr ".pos0" -type "vectorArray" 0 ;
	setAttr ".vel0" -type "vectorArray" 0 ;
	setAttr ".acc0" -type "vectorArray" 0 ;
	setAttr ".mas0" -type "doubleArray" 0 ;
	setAttr ".id0" -type "doubleArray" 0 ;
	setAttr ".bt0" -type "doubleArray" 0 ;
	setAttr ".ag0" -type "doubleArray" 0 ;
	setAttr ".lfm" 1;
	setAttr ".irbx" -type "string" ".O[0] = .I[0] * 100;";
	setAttr ".irax" -type "string" "";
	setAttr ".icx" -type "string" "";
	setAttr ".cts" 1;
	setAttr ".chw" 1000;
	setAttr ".cofl" 1;
	setAttr ".scld" no;
	setAttr -s 2 ".fsc[0:1]"  0 1 1 1 0 1;
	setAttr -s 2 ".pfdo[0:1]"  0 1 1 1 0 1;
	setAttr ".vssc[0]"  0 1 1;
	setAttr ".stns[0]"  0 1 1;
	setAttr ".ra" 0.05000000074505806;
	setAttr ".rdc[0]"  0 1 1;
	setAttr -s 4 ".mssc[0:3]"  0 1 1 1 0.02 1 0.26087001 0.34 1 0.48695651 0.1 1;
	setAttr ".msli" 2;
	setAttr ".pfsc[0]"  0 1 1;
	setAttr ".frsc[0]"  0 1 1;
	setAttr ".stsc[0]"  0 1 1;
	setAttr ".clsc[0]"  0 1 1;
	setAttr ".bosc[0]"  0 1 1;
	setAttr ".opc[0]"  0 1 1;
	setAttr ".oci" 1;
	setAttr -s 2 ".cl";
	setAttr ".cl[0].clp" 0;
	setAttr ".cl[0].clc" -type "float3" 1 1 1 ;
	setAttr ".cl[0].cli" 1;
	setAttr ".cl[1].clp" 1;
	setAttr ".cl[1].clc" -type "float3" 0 0.5 1 ;
	setAttr ".cl[1].cli" 1;
	setAttr ".coi" 1;
	setAttr ".inca[0].incap" 0;
	setAttr ".inca[0].incac" -type "float3" 0 0 0 ;
	setAttr ".inca[0].incai" 1;
	setAttr ".lifespanPP0" -type "doubleArray" 0 ;
	setAttr -k on ".lifespan";
	setAttr ".rgbPP0" -type "vectorArray" 0 ;
	setAttr ".opacityPP0" -type "doubleArray" 0 ;
	setAttr -k on ".colorAccum";
	setAttr -k on ".useLighting";
	setAttr -k on ".pointSize";
	setAttr -k on ".normalDir";
	setAttr ".ejectaFluidEmitter1RatePP0" -type "doubleArray" 0 ;
	setAttr ".ejectaFluidEmitter1RemainderPP0" -type "doubleArray" 0 ;
createNode fluidEmitter -n "ejectaFluidEmitter1" -p "ejectaNParticle1";
	setAttr -k off ".rat";
	setAttr -k off ".sro";
	setAttr -k off ".urpp" yes;
	setAttr -k off ".npuv";
	setAttr -k off ".dx";
	setAttr -k off ".dy";
	setAttr -k off ".dz";
	setAttr -k off ".spr";
	setAttr -k off ".spd";
	setAttr -k off ".srnd";
	setAttr -k off ".tspd";
	setAttr -k off ".nspd";
	setAttr -k off ".afc";
	setAttr -k off ".afa";
	setAttr -k off ".alx";
	setAttr -k off ".arx";
	setAttr -k off ".rnd";
	setAttr -k off ".drs";
	setAttr -k off ".ssz";
	setAttr -k off ".dss";
	setAttr ".dmth" 2;
	setAttr ".hmth" 0;
	setAttr ".fhe" 1;
	setAttr ".fmth" 0;
	setAttr ".ffe" 1;
	setAttr ".smth" 2;
	setAttr ".invl" 0.58959537574946019;
	setAttr ".mstr" yes;
createNode transform -n "blastGroup1" -p "BombGroup";
	setAttr ".dh" yes;
createNode fluidEmitter -n "blastFluidEmitter1" -p "blastGroup1";
	setAttr ".emt" 4;
	setAttr -k off ".rat";
	setAttr -k off ".sro";
	setAttr -l on -k off ".urpp";
	setAttr -k off ".npuv";
	setAttr ".max" 1;
	setAttr -k off ".dx";
	setAttr -k off ".dy";
	setAttr -k off ".dz";
	setAttr -k off ".spr";
	setAttr -k off ".spd";
	setAttr -k off ".srnd";
	setAttr -k off ".tspd";
	setAttr -k off ".nspd";
	setAttr ".vol" 1;
	setAttr -k off ".afc";
	setAttr -k off ".afa";
	setAttr -k off ".alx";
	setAttr -k off ".arx";
	setAttr -k off ".rnd";
	setAttr -k off ".drs";
	setAttr -k off ".ssz";
	setAttr -k off ".dss";
	setAttr ".fdo" 0.1;
	setAttr ".dmth" 0;
	setAttr ".fde" 100;
	setAttr ".fhe" 51.445086675593792;
	setAttr ".fmth" 0;
	setAttr ".ffe" 1;
	setAttr ".mstr" yes;
createNode pointEmitter -n "ejectaEmitter1" -p "blastFluidEmitter1";
	setAttr ".v" no;
	setAttr ".s" -type "double3" 0.10277778136644848 0.058160756955767771 0.10277778136644848 ;
	setAttr ".emt" 4;
	setAttr ".sro" no;
	setAttr -l on ".urpp";
	setAttr ".afa" 0;
createNode transform -n "annotationLocator1" -p "blastFluidEmitter1";
createNode locator -n "annotationLocator1Shape" -p "annotationLocator1";
	setAttr -k off ".v";
createNode transform -n "annotation1" -p "annotationLocator1";
	setAttr ".t" -type "double3" -0.17174961967199304 1.2867678684689472 -0.03728765388742189 ;
createNode annotationShape -n "blastAttrs1" -p "annotation1";
	addAttr -ci true -sn "scale" -ln "scale" -dv 1 -at "double";
	addAttr -ci true -sn "resolution" -ln "resolution" -dv 1 -min 0 -max 10 -at "double";
	addAttr -ci true -sn "blastPower" -ln "blastPower" -dv 1 -min 0 -max 10 -at "double";
	addAttr -ci true -sn "dissipation" -ln "dissipation" -dv 1 -min 0 -max 10 -at "double";
	addAttr -ci true -sn "turbulence" -ln "turbulence" -dv 1 -min 0 -max 10 -at "double";
	addAttr -ci true -sn "heatGlow" -ln "heatGlow" -dv 1 -min 0 -max 10 -at "double";
	addAttr -ci true -sn "ashContent" -ln "ashContent" -dv 0.5 -min 0 -max 1 -at "double";
	addAttr -ci true -sn "density" -ln "density" -dv 1 -min 0 -max 10 -at "double";
	addAttr -ci true -sn "ejecta" -ln "ejecta" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "ejectaCount" -ln "ejectaCount" -dv 10 -min 0 -max 1000 -at "double";
	addAttr -ci true -sn "ejectaDensity" -ln "ejectaDensity" -dv 1 -min 0 -max 10 -at "double";
	addAttr -ci true -sn "ejectaDissipation" -ln "ejectaDissipation" -dv 10 -min 0 -max 
		1 -at "double";
	addAttr -ci true -sn "ejectaSpeed" -ln "ejectaSpeed" -dv 1 -min 0 -max 10 -at "double";
	addAttr -ci true -uac -sn "ejectaColor" -ln "ejectaColor" -at "float3" -nc 3;
	addAttr -ci true -sn "ejectaColorR" -ln "ejectaColorR" -at "float" -p "ejectaColor";
	addAttr -ci true -sn "ejectaColorG" -ln "ejectaColorG" -at "float" -p "ejectaColor";
	addAttr -ci true -sn "ejectaColorB" -ln "ejectaColorB" -at "float" -p "ejectaColor";
	addAttr -ci true -sn "groundDeflection" -ln "groundDeflection" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "detonationFrame" -ln "detonationFrame" -dv 1 -at "long";
	addAttr -ci true -sn "ejectaLifespan" -ln "ejectaLifespan" -dv 1 -min 0 -max 10 
		-at "double";
	addAttr -ci true -sn "ejectaSize" -ln "ejectaSize" -dv 3 -min 0 -max 10 -at "double";
	addAttr -ci true -sn "ejectaAirDrag" -ln "ejectaAirDrag" -dv 0.1 -min 0 -max 1 -at "double";
	addAttr -ci true -sn "speed" -ln "speed" -dv 1 -min 0.01 -max 2 -at "double";
	addAttr -ci true -sn "buoyancy" -ln "buoyancy" -dv 2 -min 0 -max 10 -at "double";
	setAttr -k off ".v";
	setAttr ".txt" -type "string" "settings";
	setAttr -k on ".scale";
	setAttr -k on ".resolution" 1.693121691594127;
	setAttr -k on ".blastPower" 2;
	setAttr -k on ".dissipation" 0.95238095326792627;
	setAttr -k on ".turbulence" 1.5873015887798771;
	setAttr -k on ".heatGlow" 5.3968253925383562;
	setAttr -k on ".ashContent" 0.67724867756897333;
	setAttr -k on ".density" 8.7830687850398359;
	setAttr -k on ".ejecta" yes;
	setAttr -k on ".ejectaCount" 31.746031775597544;
	setAttr -k on ".ejectaDensity" 3.6507936541937172;
	setAttr -k on ".ejectaDissipation" 0.13227513270876395;
	setAttr -k on ".ejectaSpeed" 2.3809523831698156;
	setAttr ".ejectaColor" -type "float3" 0.22981612 0.21423666 0.19394217 ;
	setAttr -k on ".groundDeflection" yes;
	setAttr -k on ".detonationFrame";
	setAttr -k on ".ejectaLifespan" 2.1164021121643524;
	setAttr -k on ".ejectaSize";
	setAttr -k on ".ejectaAirDrag" 0.17989417944083769;
	setAttr -k on ".speed";
	setAttr -k on ".buoyancy" 4;
createNode transform -n "ejectaFluid1" -p "blastGroup1";
	setAttr ".ovdt" 2;
	setAttr ".ove" yes;
	setAttr ".t" -type "double3" 0 0.25610894919610205 0 ;
createNode fluidShape -n "ejectaFluidShape1" -p "ejectaFluid1";
	setAttr -k off ".v";
	setAttr ".rt" 1;
	setAttr ".vf" 0;
	setAttr ".vso" yes;
	setAttr ".vss" 8;
	setAttr ".dej" yes;
	setAttr ".iss" yes;
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".sqvx" yes;
	setAttr ".dw" 1;
	setAttr ".dh" 1;
	setAttr ".dd" 1;
	setAttr ".aure" yes;
	setAttr ".rcbd" no;
	setAttr ".aurt" 0.0010000000474974513;
	setAttr ".scd" 52;
	setAttr ".ssd" 3;
	setAttr ".hds" 3;
	setAttr ".bndx" 0;
	setAttr ".bndz" 0;
	setAttr ".dsc" 0.75;
	setAttr ".ddf" 0.001;
	setAttr ".dsb" -10;
	setAttr ".tfr" 1.5263158082962036;
	setAttr ".tbs" 0.44736841320991516;
	setAttr ".ss" yes;
	setAttr ".rin" 3;
	setAttr ".cl[0].clp" 0;
	setAttr ".cl[0].cli" 1;
	setAttr -s 2 ".opa[0:1]"  0.0086956518 0 1 1 1 1;
	setAttr ".oib" 0.26050421595573425;
	setAttr ".t" -type "float3" 0.012817578 0.012817578 0.012817578 ;
	setAttr ".shp" 0.88461536169052124;
	setAttr ".abrt" 0.12582781910896301;
	setAttr ".adfu" 1.8543046712875366;
	setAttr ".i[3].ip" 0;
	setAttr ".i[3].ic" -type "float3" 0 0 0 ;
	setAttr ".i[3].ii" 1;
	setAttr ".ili" 0;
	setAttr ".iib" 0.76470589637756348;
	setAttr ".env[0].envp" 0;
	setAttr ".env[0].envc" -type "float3" 0 0 0 ;
	setAttr ".env[0].envi" 1;
	setAttr ".dos" 0;
	setAttr ".otxg" 0.87005650997161865;
createNode transform -n "blastFluid1" -p "blastGroup1";
	setAttr ".ovdt" 2;
	setAttr ".ove" yes;
	setAttr ".t" -type "double3" 0 0.25610685701897329 0 ;
createNode fluidShape -n "blastFluidShape1" -p "blastFluid1";
	setAttr -k off ".v";
	setAttr ".rt" 1;
	setAttr ".vf" 0;
	setAttr ".vss" 4;
	setAttr ".iss" yes;
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".sqvx" yes;
	setAttr ".dw" 1;
	setAttr ".dh" 1;
	setAttr ".dd" 1;
	setAttr ".aure" yes;
	setAttr ".rcbd" no;
	setAttr ".sli" 1;
	setAttr ".vqu" 2;
	setAttr ".scd" 26;
	setAttr ".ssd" 3;
	setAttr ".sql" 17;
	setAttr ".hds" 3;
	setAttr ".bndx" 0;
	setAttr ".bndz" 0;
	setAttr ".dmt" 0;
	setAttr ".dsc" 0.55263155698776245;
	setAttr ".dds" 5.3967702749999997;
	setAttr ".dsb" 0;
	setAttr ".vdp" 0.004999999888241291;
	setAttr ".tfr" 0.56578946113586426;
	setAttr ".tbs" 0.1315789520740509;
	setAttr ".tmet" 2;
	setAttr ".tmsc" 0.5;
	setAttr ".tdf" 0;
	setAttr ".ss" yes;
	setAttr ".rin" 3;
	setAttr ".cl[0].clp" 0;
	setAttr ".cl[0].cli" 1;
	setAttr ".cib" -0.21008403599262238;
	setAttr -s 2 ".opa[0:1]"  0 0 1 1 1 1;
	setAttr ".opi" 6;
	setAttr ".shp" 1;
	setAttr ".lbrt" 1.2000000476837158;
	setAttr ".flic" -type "float3" 1 0.921 0.86500001 ;
	setAttr ".abrt" 0.044871795922517776;
	setAttr ".adfu" 2.8248586654663086;
	setAttr -s 4 ".i";
	setAttr ".i[0].ip" 0.31304347515106201;
	setAttr ".i[0].ic" -type "float3" 0 0 0 ;
	setAttr ".i[0].ii" 1;
	setAttr ".i[1].ip" 0.84347826242446899;
	setAttr ".i[1].ic" -type "float3" 5 1.3333334 0 ;
	setAttr ".i[1].ii" 1;
	setAttr ".i[2].ip" 0.74782609939575195;
	setAttr ".i[2].ic" -type "float3" 0.91836798 0.24489801 0 ;
	setAttr ".i[2].ii" 1;
	setAttr ".i[3].ip" 0.73913043737411499;
	setAttr ".i[3].ic" -type "float3" 0.35114101 0.093637504 0 ;
	setAttr ".i[3].ii" 1;
	setAttr ".env[0].envp" 0;
	setAttr ".env[0].envc" -type "float3" 0 0 0 ;
	setAttr ".env[0].envi" 1;
	setAttr ".dos" 0;
	setAttr ".edr" 0.23717948794364929;
	setAttr ".poli" -type "float3" 7.8411169 11.440446 3.9965467 ;
	setAttr ".itx" yes;
	setAttr ".itxg" 1.6610169410705566;
	setAttr ".otx" yes;
	setAttr ".otxg" 0.74576270580291748;
	setAttr ".a" 0.93220341205596924;
	setAttr ".ra" 0.66225165128707886;
	setAttr ".dm" 4;
	setAttr ".fq" 3.3898305892944336;
	setAttr ".in" yes;
createNode nucleus -n "BombNucleus";
	setAttr ".sstp" 1;
	setAttr ".mcit" 1;
createNode container -n "BombAsset";
	addAttr -ci true -h true -sn "aal" -ln "attributeAliasList" -dt "attributeAlias";
	addAttr -ci true -sn "nts" -ln "notes" -dt "string";
	setAttr ".isc" yes;
	setAttr -s 19 ".boc";
	setAttr ".ctor" -type "string" "pakalnj";
	setAttr ".cdat" -type "string" "2010/05/03 12:50:10";
	setAttr ".ctyp" -type "string" "effects";
	setAttr ".aal" -type "attributeAlias" {"scale1","borderConnections[0]","ejectaDensity"
		,"borderConnections[10]","ejectaDissipation","borderConnections[11]","ejectaSpeed"
		,"borderConnections[12]","ejectaLifespan","borderConnections[13]","ejectaSize","borderConnections[14]"
		,"ejectaAirDrag","borderConnections[15]","buoyancy","borderConnections[16]","incandescence"
		,"borderConnections[17]","detonationFrame","borderConnections[18]","resolution","borderConnections[1]"
		,"blastPower","borderConnections[2]","dissipation","borderConnections[3]","turbulence"
		,"borderConnections[4]","heatGlow","borderConnections[5]","ashContent","borderConnections[6]"
		,"density","borderConnections[7]","ejecta","borderConnections[8]","ejectaCount","borderConnections[9]"
		,"nucleusSolver","publishedNodeInfo[0]"} ;
	setAttr ".nts" -type "string" "Fluids and nParticle effect- This is an explosion effect with 3 fluids and nParticle ejecta that emits trails from the particles into one of the fluids. This is a freestanding effect that does not need to be applied to an object in the scene. It can be placed as needed. ";
createNode lightLinker -s -n "lightLinker1";
	setAttr -s 5 ".lnk";
	setAttr -s 5 ".slnk";
createNode displayLayerManager -n "layerManager";
createNode displayLayer -n "defaultLayer";
createNode renderLayerManager -n "renderLayerManager";
createNode renderLayer -n "defaultRenderLayer";
	setAttr ".g" yes;
createNode shadingEngine -n "fluidShape1SG";
	setAttr ".ihi" 0;
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo1";
createNode shadingEngine -n "fluidShape2SG";
	setAttr ".ihi" 0;
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo2";
createNode script -n "sceneConfigurationScriptNode";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 1000 -ast 1 -aet 1000 ";
	setAttr ".st" 6;
createNode shadingEngine -n "nParticleCloudSE";
	setAttr ".ihi" 0;
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo3";
createNode particleSamplerInfo -n "particleSamplerInfo1";
createNode blinn -n "npCloudBlinn";
createNode particleCloud -n "npCloudVolume";
createNode expression -n "blastExpression1";
	setAttr -k on ".nds";
	setAttr -s 23 ".in";
	setAttr -s 23 ".in";
	setAttr -s 42 ".out";
	setAttr ".ixp" -type "string" (
		"float $scale = .I[0];\nif( $scale < 0.00001 ) $scale = 0.00001;\n\nfloat $speed = .I[1];\nif( $speed < 0.01 ) $speed = 0.01;\n\n.O[0] = time * $speed;\n\nfloat $res = .I[2];\n.O[1] = $scale;\n.O[2] = $scale;\n.O[3] = $scale;\n.O[4] = 1.0/$scale;\n.O[5] = $res * 5.0;\n.O[6] = $res * 5.0;\n.O[7] = $speed;\n.O[8] = $speed;\n.O[9] = $speed;\n\nfloat $substeps = 5 * $speed;\nif( $substeps < 1 ) $substeps = 1;\n\n.O[10] = $substeps;\n$substeps = $speed;\nif( $substeps < 1 ) $substeps = 1;\n.O[11] = $substeps;\n\nint $yBound = 0;\nfloat $emitFrames = 4/ $speed;\nif ($emitFrames < 2 ) $emitFrames = 2;\n\nfloat $detonateFrame = .I[3];\n.O[12] = $detonateFrame;\n.O[13] = $detonateFrame;\n\nfloat $fps = 24;\nint $ejecta = .I[4];\n.O[14] = $ejecta;\n.O[15] = $ejecta;\n.O[16] = .I[5]/$speed;\n.O[17] = .I[6]*.1;\nint $emitting = frame >= $detonateFrame && frame < $detonateFrame + $emitFrames;\nfloat $ejectaRate =0;\nfloat $blastRate = 0;\nfloat $diss = .I[7] * 5.0;\nif( $emitting ){\n\t$blastRate = 100 * .I[8];\n\t$diss = 0;\n\tif( $ejecta  ){\n \t\t$ejectaRate = .I[9] * $fps/($emitFrames-1);\n"
		+ "\t}\n}\n.O[18] = .I[10] * 2.5;\n.O[19] =  $diss;\n.O[20] = .I[11] * 5;\n.O[21]  = .I[12] * .1;\nfloat $trans = 1.0- pow(.I[13] * .1, .1);\n.O[22] = $trans;\n.O[23] = $trans;\n.O[24] = $trans;\nfloat $bright = 1.0-.I[14];\n.O[25] = $bright;\n.O[26] = $bright;\n.O[27] = $bright;\n\n.O[28] = .I[15];\n.O[29] = .I[16];\n.O[30] = .I[17];\n//blastAttrs1.speed;\n\n.O[31] = $blastRate;\n.O[32] = $ejectaRate;\n//ejectaFluidEmitter1.rate = blastAttrs1.ejectaDensity * 0.2;\n.O[33] = .I[18] * 0.02;\nfloat $ejectSpeed = .I[19] * 4.0 * $scale;\nif( .I[20] ){\n\t$yBound = 2; // -Y side\n\t.O[34] = $ejectSpeed;\n\t.O[35] = 0;\n\t.O[36] = 3;\n} else {\n\t.O[34] = 0;\n\t.O[35] = $ejectSpeed * .5;\n\t.O[36] = 1;\n}\n.O[37] = $ejectSpeed * 0.5;\n.O[38] = .I[21]*50;\n.O[39] = .I[22] * .03;\n.O[40] = $yBound;\n.O[41] = $yBound;\n\n// force updates( no sure why needed)\ngetAttr blastFluidShape1.boundaryY;\ngetAttr ejectaFluidShape1.boundaryY;");
createNode hyperLayout -n "hyperLayout1";
	setAttr ".ihi" 0;
	setAttr -s 21 ".hyp";
select -ne :time1;
	setAttr -av -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".o" 1;
	setAttr ".unw" 1;
select -ne :renderPartition;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 5 ".st";
	setAttr -k on ".an";
	setAttr -k on ".pt";
select -ne :initialShadingGroup;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".mwc";
	setAttr -k on ".an";
	setAttr -k on ".il";
	setAttr -k on ".vo";
	setAttr -k on ".eo";
	setAttr -k on ".fo";
	setAttr -k on ".epo";
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".mwc";
	setAttr -k on ".an";
	setAttr -k on ".il";
	setAttr -k on ".vo";
	setAttr -k on ".eo";
	setAttr -k on ".fo";
	setAttr -k on ".epo";
	setAttr ".ro" yes;
select -ne :defaultShaderList1;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 6 ".s";
select -ne :postProcessList1;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
select -ne :renderGlobalsList1;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
select -ne :defaultRenderGlobals;
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultLightSet;
	setAttr -k on ".cch";
	setAttr -k on ".ihi";
	setAttr -k on ".nds";
	setAttr -k on ".bnm";
	setAttr -k on ".mwc";
	setAttr -k on ".an";
	setAttr -k on ".il";
	setAttr -k on ".vo";
	setAttr -k on ".eo";
	setAttr -k on ".fo";
	setAttr -k on ".epo";
	setAttr -k on ".ro" yes;
select -ne :hardwareRenderGlobals;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
	setAttr -k off -cb on ".ehql";
	setAttr -k off -cb on ".eams";
	setAttr -k off -cb on ".eeaa";
	setAttr -k off -cb on ".engm";
	setAttr -k off -cb on ".mes";
	setAttr -k off -cb on ".emb";
	setAttr -k off -cb on ".mbbf";
	setAttr -k off -cb on ".mbs";
	setAttr -k off -cb on ".trm";
	setAttr -k off -cb on ".tshc";
	setAttr -k off -cb on ".clmt";
	setAttr -k off -cb on ".tcov";
	setAttr -k off -cb on ".lith";
	setAttr -k off -cb on ".sobc";
	setAttr -k off -cb on ".cuth";
	setAttr -k off -cb on ".hgcd";
	setAttr -k off -cb on ".hgci";
	setAttr -k off -cb on ".mgcs";
	setAttr -k off -cb on ".twa";
	setAttr -k off -cb on ".twz";
	setAttr -k on ".hwcc";
	setAttr -k on ".hwdp";
	setAttr -k on ".hwql";
select -ne :defaultHardwareRenderGlobals;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".rp";
	setAttr -k on ".cai";
	setAttr -k on ".coi";
	setAttr -cb on ".bc";
	setAttr -av -k on ".bcb";
	setAttr -av -k on ".bcg";
	setAttr -av -k on ".bcr";
	setAttr -k on ".ei";
	setAttr -k on ".ex";
	setAttr -av -k on ".es";
	setAttr -av -k on ".ef";
	setAttr -k on ".bf";
	setAttr -k on ".fii";
	setAttr -av -k on ".sf";
	setAttr -k on ".gr";
	setAttr -k on ".li";
	setAttr -k on ".ls";
	setAttr -k on ".mb";
	setAttr -k on ".ti";
	setAttr -k on ".txt";
	setAttr -k on ".mpr";
	setAttr -k on ".wzd";
	setAttr -k on ".fn" -type "string" "im";
	setAttr -k on ".if";
	setAttr -k on ".res" -type "string" "ntsc_4d 646 485 1.333";
	setAttr -k on ".as";
	setAttr -k on ".ds";
	setAttr -k on ".lm";
	setAttr -k on ".fir";
	setAttr -k on ".aap";
	setAttr -k on ".gh";
	setAttr -cb on ".sd";
select -ne :ikSystem;
	setAttr -s 4 ".sol";
connectAttr "blastExpression1.out[16]" "ejectaNParticleShape1.lifespan";
connectAttr ":time1.o" "ejectaNParticleShape1.cti";
connectAttr "BombNucleus.noao[0]" "ejectaNParticleShape1.nxst";
connectAttr "BombNucleus.stf" "ejectaNParticleShape1.stf";
connectAttr "ejectaEmitter1.ot[0]" "ejectaNParticleShape1.npt[0]";
connectAttr "ejectaNParticleShape1.incr" "ejectaNParticleShape1.rgbPP";
connectAttr "ejectaNParticleShape1.inor" "ejectaNParticleShape1.opacityPP";
connectAttr "blastExpression1.out[15]" "ejectaNParticleShape1.isd";
connectAttr "ejectaNParticleShape1.inmr" "ejectaNParticleShape1.mas";
connectAttr "ejectaNParticleShape1.xo[0]" "ejectaNParticleShape1.ejectaFluidEmitter1RatePP"
		;
connectAttr "ejectaNParticleShape1.mas" "ejectaNParticleShape1.xi[0]";
connectAttr "blastExpression1.out[17]" "ejectaNParticleShape1.drg";
connectAttr ":time1.o" "ejectaFluidEmitter1.ct";
connectAttr "ejectaNParticleShape1.cwcn" "ejectaFluidEmitter1.ocd";
connectAttr "ejectaNParticleShape1.ctd" "ejectaFluidEmitter1.t";
connectAttr "ejectaNParticleShape1.cwps" "ejectaFluidEmitter1.opd";
connectAttr "ejectaNParticleShape1.cwvl" "ejectaFluidEmitter1.ovd";
connectAttr "ejectaNParticleShape1.id" "ejectaFluidEmitter1.paid";
connectAttr "ejectaFluidShape1.ifl" "ejectaFluidEmitter1.full[0]";
connectAttr "ejectaFluidShape1.ots" "ejectaFluidEmitter1.dt[0]";
connectAttr "ejectaFluidShape1.inh" "ejectaFluidEmitter1.inh[0]";
connectAttr "ejectaFluidShape1.sti" "ejectaFluidEmitter1.stt[0]";
connectAttr "ejectaFluidShape1.sd[0]" "ejectaFluidEmitter1.sd[0]";
connectAttr "blastExpression1.out[33]" "ejectaFluidEmitter1.fde";
connectAttr "ejectaNParticleShape1.ejectaFluidEmitter1RatePP" "ejectaFluidEmitter1.rpp"
		;
connectAttr "ejectaNParticleShape1.ejectaFluidEmitter1RemainderPP" "ejectaFluidEmitter1.ecr[0]"
		;
connectAttr "blastExpression1.out[39]" "ejectaFluidEmitter1.max";
connectAttr "blastExpression1.out[1]" "blastGroup1.sx";
connectAttr "blastExpression1.out[2]" "blastGroup1.sy";
connectAttr "blastExpression1.out[3]" "blastGroup1.sz";
connectAttr "blastExpression1.out[31]" "blastFluidEmitter1.rat";
connectAttr ":time1.o" "blastFluidEmitter1.ct";
connectAttr "blastFluidShape1.ifl" "blastFluidEmitter1.full[0]";
connectAttr "blastFluidShape1.ots" "blastFluidEmitter1.dt[0]";
connectAttr "blastFluidShape1.inh" "blastFluidEmitter1.inh[0]";
connectAttr "blastFluidShape1.sti" "blastFluidEmitter1.stt[0]";
connectAttr "blastFluidShape1.sd[0]" "blastFluidEmitter1.sd[0]";
connectAttr ":time1.o" "ejectaEmitter1.ct";
connectAttr "ejectaNParticleShape1.ifl" "ejectaEmitter1.full[0]";
connectAttr "ejectaNParticleShape1.tss" "ejectaEmitter1.dt[0]";
connectAttr "ejectaNParticleShape1.inh" "ejectaEmitter1.inh[0]";
connectAttr "ejectaNParticleShape1.stt" "ejectaEmitter1.stt[0]";
connectAttr "ejectaNParticleShape1.sd[0]" "ejectaEmitter1.sd[0]";
connectAttr "blastExpression1.out[34]" "ejectaEmitter1.alx";
connectAttr "blastExpression1.out[36]" "ejectaEmitter1.vol";
connectAttr "blastExpression1.out[35]" "ejectaEmitter1.afc";
connectAttr "blastExpression1.out[32]" "ejectaEmitter1.rat";
connectAttr "blastExpression1.out[37]" "ejectaEmitter1.srnd";
connectAttr "annotationLocator1Shape.wm" "blastAttrs1.dom" -na;
connectAttr "blastExpression1.out[14]" "ejectaFluidShape1.v";
connectAttr ":time1.o" "ejectaFluidShape1.cti";
connectAttr "ejectaFluidEmitter1.ef" "ejectaFluidShape1.eml[0].emfr";
connectAttr "ejectaFluidEmitter1.efc" "ejectaFluidShape1.fce[0]";
connectAttr "blastExpression1.out[6]" "ejectaFluidShape1.bres";
connectAttr "blastExpression1.out[41]" "ejectaFluidShape1.bndy";
connectAttr "blastExpression1.out[38]" "ejectaFluidShape1.dds";
connectAttr "blastExpression1.out[13]" "ejectaFluidShape1.stf";
connectAttr "blastExpression1.out[8]" "ejectaFluidShape1.srs";
connectAttr "blastExpression1.out[11]" "ejectaFluidShape1.sbst";
connectAttr "blastExpression1.out[28]" "ejectaFluidShape1.cl[0].clcr";
connectAttr "blastExpression1.out[29]" "ejectaFluidShape1.cl[0].clcg";
connectAttr "blastExpression1.out[30]" "ejectaFluidShape1.cl[0].clcb";
connectAttr ":time1.o" "blastFluidShape1.cti";
connectAttr "blastExpression1.out[0]" "blastFluidShape1.tti";
connectAttr "blastFluidEmitter1.ef" "blastFluidShape1.eml[0].emfr";
connectAttr "blastFluidEmitter1.efc" "blastFluidShape1.fce[0]";
connectAttr "blastExpression1.out[5]" "blastFluidShape1.bres";
connectAttr "blastExpression1.out[40]" "blastFluidShape1.bndy";
connectAttr "blastExpression1.out[12]" "blastFluidShape1.stf";
connectAttr "blastExpression1.out[18]" "blastFluidShape1.ttb";
connectAttr "blastExpression1.out[19]" "blastFluidShape1.tds";
connectAttr "blastExpression1.out[21]" "blastFluidShape1.iib";
connectAttr "blastExpression1.out[22]" "blastFluidShape1.tr";
connectAttr "blastExpression1.out[23]" "blastFluidShape1.tg";
connectAttr "blastExpression1.out[24]" "blastFluidShape1.tb";
connectAttr "blastExpression1.out[25]" "blastFluidShape1.cl[0].clcr";
connectAttr "blastExpression1.out[26]" "blastFluidShape1.cl[0].clcg";
connectAttr "blastExpression1.out[27]" "blastFluidShape1.cl[0].clcb";
connectAttr "blastExpression1.out[7]" "blastFluidShape1.srs";
connectAttr "blastExpression1.out[10]" "blastFluidShape1.sbst";
connectAttr "blastExpression1.out[20]" "blastFluidShape1.buo";
connectAttr ":time1.o" "BombNucleus.cti";
connectAttr "ejectaNParticleShape1.cust" "BombNucleus.niao[0]";
connectAttr "ejectaNParticleShape1.stst" "BombNucleus.nias[0]";
connectAttr "blastExpression1.out[4]" "BombNucleus.spsc";
connectAttr "blastExpression1.out[9]" "BombNucleus.tisc";
connectAttr "blastAttrs1.scale" "BombAsset.boc[0]";
connectAttr "blastAttrs1.resolution" "BombAsset.boc[1]";
connectAttr "blastAttrs1.blastPower" "BombAsset.boc[2]";
connectAttr "blastAttrs1.dissipation" "BombAsset.boc[3]";
connectAttr "blastAttrs1.turbulence" "BombAsset.boc[4]";
connectAttr "blastAttrs1.heatGlow" "BombAsset.boc[5]";
connectAttr "blastAttrs1.ashContent" "BombAsset.boc[6]";
connectAttr "blastAttrs1.density" "BombAsset.boc[7]";
connectAttr "blastAttrs1.ejecta" "BombAsset.boc[8]";
connectAttr "blastAttrs1.ejectaCount" "BombAsset.boc[9]";
connectAttr "blastAttrs1.ejectaDensity" "BombAsset.boc[10]";
connectAttr "blastAttrs1.ejectaDissipation" "BombAsset.boc[11]";
connectAttr "blastAttrs1.ejectaSpeed" "BombAsset.boc[12]";
connectAttr "blastAttrs1.ejectaLifespan" "BombAsset.boc[13]";
connectAttr "blastAttrs1.ejectaSize" "BombAsset.boc[14]";
connectAttr "blastAttrs1.ejectaAirDrag" "BombAsset.boc[15]";
connectAttr "blastAttrs1.buoyancy" "BombAsset.boc[16]";
connectAttr "blastFluidShape1.i" "BombAsset.boc[17]";
connectAttr "blastAttrs1.detonationFrame" "BombAsset.boc[18]";
connectAttr "hyperLayout1.msg" "BombAsset.hl";
connectAttr "BombGroup.msg" "BombAsset.rt";
connectAttr "BombNucleus.msg" "BombAsset.pni[0].pnod";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "fluidShape1SG.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "fluidShape2SG.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "nParticleCloudSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "fluidShape1SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "fluidShape2SG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "nParticleCloudSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "blastFluidShape1.ocl" "fluidShape1SG.vs";
connectAttr "blastFluidShape1.iog" "fluidShape1SG.dsm" -na;
connectAttr "fluidShape1SG.msg" "materialInfo1.sg";
connectAttr "ejectaFluidShape1.ocl" "fluidShape2SG.vs";
connectAttr "ejectaFluidShape1.iog" "fluidShape2SG.dsm" -na;
connectAttr "fluidShape2SG.msg" "materialInfo2.sg";
connectAttr "npCloudBlinn.oc" "nParticleCloudSE.ss";
connectAttr "npCloudVolume.oi" "nParticleCloudSE.vs";
connectAttr "ejectaNParticleShape1.iog" "nParticleCloudSE.dsm" -na;
connectAttr "nParticleCloudSE.msg" "materialInfo3.sg";
connectAttr "npCloudBlinn.msg" "materialInfo3.m";
connectAttr "particleSamplerInfo1.msg" "materialInfo3.t" -na;
connectAttr "particleSamplerInfo1.oc" "npCloudBlinn.c";
connectAttr "particleSamplerInfo1.ot" "npCloudBlinn.it";
connectAttr "particleSamplerInfo1.oi" "npCloudBlinn.ic";
connectAttr "particleSamplerInfo1.ot" "npCloudVolume.t";
connectAttr "particleSamplerInfo1.oc" "npCloudVolume.c";
connectAttr "particleSamplerInfo1.oi" "npCloudVolume.i";
connectAttr "blastAttrs1.scale" "blastExpression1.in[0]";
connectAttr "blastAttrs1.speed" "blastExpression1.in[1]";
connectAttr "blastAttrs1.resolution" "blastExpression1.in[2]";
connectAttr "blastAttrs1.detonationFrame" "blastExpression1.in[3]";
connectAttr "blastAttrs1.ejecta" "blastExpression1.in[4]";
connectAttr "blastAttrs1.ejectaLifespan" "blastExpression1.in[5]";
connectAttr "blastAttrs1.ejectaAirDrag" "blastExpression1.in[6]";
connectAttr "blastAttrs1.dissipation" "blastExpression1.in[7]";
connectAttr "blastAttrs1.blastPower" "blastExpression1.in[8]";
connectAttr "blastAttrs1.ejectaCount" "blastExpression1.in[9]";
connectAttr "blastAttrs1.turbulence" "blastExpression1.in[10]";
connectAttr "blastAttrs1.buoyancy" "blastExpression1.in[11]";
connectAttr "blastAttrs1.heatGlow" "blastExpression1.in[12]";
connectAttr "blastAttrs1.density" "blastExpression1.in[13]";
connectAttr "blastAttrs1.ashContent" "blastExpression1.in[14]";
connectAttr "blastAttrs1.ejectaColorR" "blastExpression1.in[15]";
connectAttr "blastAttrs1.ejectaColorG" "blastExpression1.in[16]";
connectAttr "blastAttrs1.ejectaColorB" "blastExpression1.in[17]";
connectAttr "blastAttrs1.ejectaDensity" "blastExpression1.in[18]";
connectAttr "blastAttrs1.ejectaSpeed" "blastExpression1.in[19]";
connectAttr "blastAttrs1.groundDeflection" "blastExpression1.in[20]";
connectAttr "blastAttrs1.ejectaDissipation" "blastExpression1.in[21]";
connectAttr "blastAttrs1.ejectaSize" "blastExpression1.in[22]";
connectAttr ":time1.o" "blastExpression1.tim";
connectAttr "ejectaNParticle1.msg" "hyperLayout1.hyp[0].dn";
connectAttr "blastGroup1.msg" "hyperLayout1.hyp[1].dn";
connectAttr "particleSamplerInfo1.msg" "hyperLayout1.hyp[2].dn";
connectAttr "npCloudVolume.msg" "hyperLayout1.hyp[3].dn";
connectAttr "ejectaNParticleShape1.msg" "hyperLayout1.hyp[4].dn";
connectAttr "ejectaFluidEmitter1.msg" "hyperLayout1.hyp[5].dn";
connectAttr "blastFluidEmitter1.msg" "hyperLayout1.hyp[6].dn";
connectAttr "ejectaEmitter1.msg" "hyperLayout1.hyp[7].dn";
connectAttr "annotationLocator1.msg" "hyperLayout1.hyp[8].dn";
connectAttr "annotationLocator1Shape.msg" "hyperLayout1.hyp[9].dn";
connectAttr "annotation1.msg" "hyperLayout1.hyp[10].dn";
connectAttr "blastAttrs1.msg" "hyperLayout1.hyp[11].dn";
connectAttr "ejectaFluid1.msg" "hyperLayout1.hyp[12].dn";
connectAttr "ejectaFluidShape1.msg" "hyperLayout1.hyp[13].dn";
connectAttr "blastFluid1.msg" "hyperLayout1.hyp[14].dn";
connectAttr "blastFluidShape1.msg" "hyperLayout1.hyp[15].dn";
connectAttr "BombNucleus.msg" "hyperLayout1.hyp[16].dn";
connectAttr "fluidShape2SG.msg" "hyperLayout1.hyp[17].dn";
connectAttr "fluidShape1SG.msg" "hyperLayout1.hyp[18].dn";
connectAttr "blastExpression1.msg" "hyperLayout1.hyp[19].dn";
connectAttr "BombGroup.msg" "hyperLayout1.hyp[20].dn";
connectAttr "fluidShape1SG.pa" ":renderPartition.st" -na;
connectAttr "fluidShape2SG.pa" ":renderPartition.st" -na;
connectAttr "nParticleCloudSE.pa" ":renderPartition.st" -na;
connectAttr "blastFluidShape1.msg" ":defaultShaderList1.s" -na;
connectAttr "ejectaFluidShape1.msg" ":defaultShaderList1.s" -na;
connectAttr "npCloudBlinn.msg" ":defaultShaderList1.s" -na;
connectAttr "npCloudVolume.msg" ":defaultShaderList1.s" -na;
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
// End of Bomb.ma
