//Maya ASCII 2011 scene
//Name: fireworkORingMod2.ma
//Last modified: Thu, Aug 19, 2010 05:49:27 PM
//Codeset: 1252
requires maya "2011";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2011";
fileInfo "version" "2011";
fileInfo "cutIdentifier" "201007310527-779257";
fileInfo "osv" "Microsoft Windows XP Professional Service Pack 3 (Build 2600)\n";
createNode transform -s -n "persp";
	setAttr ".t" -type "double3" -1.1390617963365659 -2.0847205249849252 40.250933175637883 ;
	setAttr ".r" -type "double3" -10.538352729603089 -6.2000000000003341 0 ;
createNode camera -s -n "perspShape" -p "persp";
	setAttr -k off ".v";
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 43.728859588090636;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 100.1 0 ;
	setAttr ".r" -type "double3" -89.999999999999986 0 0 ;
createNode camera -s -n "topShape" -p "top";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 100.1 ;
createNode camera -s -n "frontShape" -p "front";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 100.1 0 0 ;
	setAttr ".r" -type "double3" 0 89.999999999999986 0 ;
createNode camera -s -n "sideShape" -p "side";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode pointEmitter -n "primaryEmitter";
	setAttr ".r" -type "double3" -81.276116746141994 -10.923375832580813 11.332598209771215 ;
	setAttr ".s" -type "double3" 0.13333334040479167 0.13333334040479167 0.13333334040479167 ;
	setAttr ".emt" 4;
	setAttr ".sro" no;
	setAttr -l on ".urpp";
	setAttr ".spd" 7.212121218838023;
	setAttr ".srnd" 2.4579124570971587;
	setAttr ".vol" 2;
	setAttr ".afc" 15;
	setAttr ".afa" 12.632155988151126;
	setAttr ".alx" 5.59119743595015;
	setAttr ".rnd" 2.1946902613987964;
createNode transform -n "FireworksCTRL" -p "primaryEmitter";
	addAttr -ci true -sn "detonationFrame" -ln "detonationFrame" -at "double";
	setAttr ".r" -type "double3" 81.213630445373596 12.850721046405431 9.0792222357525478 ;
	setAttr ".s" -type "double3" 7.4999996022304911 7.4999996022304911 7.4999996022304929 ;
	setAttr -k on ".detonationFrame" 2;
createNode locator -n "FireworksCTRLShape" -p "FireworksCTRL";
	setAttr -k off ".v";
createNode transform -n "annotation1" -p "FireworksCTRL";
	setAttr ".r" -type "double3" 3.1805546814635152e-015 -1.9878466759146968e-015 5.5173828725626939e-032 ;
	setAttr ".s" -type "double3" 1 0.99999999999999978 0.99999999999999956 ;
createNode annotationShape -n "annotationShape1" -p "annotation1";
	setAttr -k off ".v";
	setAttr ".txt" -type "string" "FireworksCTRL";
createNode transform -n "primaryNParticle";
createNode nParticle -n "primaryNParticleShape" -p "primaryNParticle";
	addAttr -ci true -sn "lifespanPP" -ln "lifespanPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "lifespanPP0" -ln "lifespanPP0" -dt "doubleArray";
	addAttr -ci true -sn "lifespan" -ln "lifespan" -at "double";
	addAttr -ci true -sn "rgbPP" -ln "rgbPP" -dt "vectorArray";
	addAttr -ci true -h true -sn "rgbPP0" -ln "rgbPP0" -dt "vectorArray";
	addAttr -ci true -sn "opacityPP" -ln "opacityPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "opacityPP0" -ln "opacityPP0" -dt "doubleArray";
	addAttr -is true -ci true -sn "betterIllumination" -ln "betterIllumination" -min 
		0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "surfaceShading" -ln "surfaceShading" -min 0 -max 
		1 -at "float";
	addAttr -ci true -sn "incandescencePP" -ln "incandescencePP" -dt "vectorArray";
	addAttr -ci true -h true -sn "incandescencePP0" -ln "incandescencePP0" -dt "vectorArray";
	addAttr -ci true -sn "emitter2RatePP" -ln "emitter2RatePP" -dt "doubleArray";
	addAttr -ci true -h true -sn "emitter2RatePP0" -ln "emitter2RatePP0" -dt "doubleArray";
	addAttr -ci true -h true -sn "emitter2RemainderPP" -ln "emitter2RemainderPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "emitter2RemainderPP0" -ln "emitter2RemainderPP0" -dt "doubleArray";
	addAttr -ci true -sn "ageNormalized" -ln "ageNormalized" -dt "doubleArray";
	addAttr -ci true -h true -sn "ageNormalized0" -ln "ageNormalized0" -dt "doubleArray";
	setAttr -k off ".v";
	setAttr ".gf" -type "Int32Array" 0 ;
	setAttr ".pos0" -type "vectorArray" 0 ;
	setAttr ".vel0" -type "vectorArray" 0 ;
	setAttr ".acc0" -type "vectorArray" 0 ;
	setAttr ".mas0" -type "doubleArray" 0 ;
	setAttr ".id0" -type "doubleArray" 0 ;
	setAttr ".bt0" -type "doubleArray" 0 ;
	setAttr ".ag0" -type "doubleArray" 0 ;
	setAttr ".lfm" 2;
	setAttr ".lfr" 0.2;
	setAttr ".irbx" -type "string" "";
	setAttr ".irax" -type "string" "";
	setAttr ".icx" -type "string" "";
	setAttr ".cts" 1;
	setAttr ".chw" 90;
	setAttr ".prt" 8;
	setAttr ".cofl" 1;
	setAttr ".pmss" 3.2330000400543213;
	setAttr ".scld" no;
	setAttr -s 2 ".fsc[0:1]"  0 1 1 1 0 1;
	setAttr -s 2 ".pfdo[0:1]"  0 1 1 1 0 1;
	setAttr ".drg" 0.041297934949398041;
	setAttr ".vssc[0]"  0 1 1;
	setAttr ".stns[0]"  0 1 1;
	setAttr ".ra" 0.25;
	setAttr ".rdc[0]"  0 1 1;
	setAttr -s 2 ".mssc[0:1]"  0.5826087 1 1 1 0.54000002 1;
	setAttr ".msli" 2;
	setAttr ".pfsc[0]"  0 1 1;
	setAttr ".frsc[0]"  0 1 1;
	setAttr ".stsc[0]"  0 1 1;
	setAttr ".clsc[0]"  0 1 1;
	setAttr ".bosc[0]"  0 1 1;
	setAttr ".op" 0.85858585845415636;
	setAttr -s 4 ".opc[0:3]"  0 1 1 0.73913044 1 1 1 0.25999999 
		1 0.94782609 0.69999999 1;
	setAttr ".oci" 2;
	setAttr ".cl[0].clp" 0.12173912674188614;
	setAttr ".cl[0].clc" -type "float3" 0 0 0 ;
	setAttr ".cl[0].cli" 1;
	setAttr ".coi" 1;
	setAttr -s 3 ".inca";
	setAttr ".inca[0].incap" 0.34782609343528748;
	setAttr ".inca[0].incac" -type "float3" 1.02816 3.7603998 5.7119999 ;
	setAttr ".inca[0].incai" 1;
	setAttr ".inca[1].incap" 1;
	setAttr ".inca[1].incac" -type "float3" 0.29748002 0.33124802 0.33500001 ;
	setAttr ".inca[1].incai" 1;
	setAttr ".inca[2].incap" 0;
	setAttr ".inca[2].incac" -type "float3" 0.496912 1.6321645 2.3889999 ;
	setAttr ".inca[2].incai" 1;
	setAttr ".ini" 2;
	setAttr ".lifespanPP0" -type "doubleArray" 0 ;
	setAttr -k on ".lifespan" 1.5;
	setAttr ".rgbPP0" -type "vectorArray" 0 ;
	setAttr ".opacityPP0" -type "doubleArray" 0 ;
	setAttr -k on ".betterIllumination";
	setAttr -k on ".surfaceShading";
	setAttr ".incandescencePP0" -type "vectorArray" 0 ;
	setAttr ".emitter2RatePP0" -type "doubleArray" 0 ;
	setAttr ".emitter2RemainderPP0" -type "doubleArray" 0 ;
	setAttr ".ageNormalized0" -type "doubleArray" 0 ;
createNode pointEmitter -n "burstEmitter" -p "primaryNParticle";
	setAttr ".rat" 156.34218306530673;
	setAttr ".sro" no;
	setAttr ".urpp" yes;
	setAttr ".spd" 40;
	setAttr ".srnd" 0.56047197535721949;
createNode pointEmitter -n "trailsEmitter" -p "primaryNParticle";
	setAttr ".rat" 411.50442494359692;
	setAttr ".sro" no;
	setAttr -l on ".urpp";
	setAttr ".spd" 1.5634218259964545;
	setAttr ".srnd" 9.2920353995487748;
createNode transform -n "burstNParticle";
createNode nParticle -n "burstNParticleShape" -p "burstNParticle";
	addAttr -ci true -sn "lifespanPP" -ln "lifespanPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "lifespanPP0" -ln "lifespanPP0" -dt "doubleArray";
	addAttr -ci true -sn "lifespan" -ln "lifespan" -at "double";
	addAttr -ci true -sn "opacityPP" -ln "opacityPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "opacityPP0" -ln "opacityPP0" -dt "doubleArray";
	addAttr -ci true -sn "radiusPP" -ln "radiusPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "radiusPP0" -ln "radiusPP0" -dt "doubleArray";
	addAttr -is true -ci true -sn "betterIllumination" -ln "betterIllumination" -min 
		0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "surfaceShading" -ln "surfaceShading" -min 0 -max 
		1 -at "float";
	addAttr -ci true -sn "incandescencePP" -ln "incandescencePP" -dt "vectorArray";
	addAttr -ci true -h true -sn "incandescencePP0" -ln "incandescencePP0" -dt "vectorArray";
	setAttr -k off ".v";
	setAttr ".gf" -type "Int32Array" 0 ;
	setAttr ".pos0" -type "vectorArray" 0 ;
	setAttr ".vel0" -type "vectorArray" 0 ;
	setAttr ".acc0" -type "vectorArray" 0 ;
	setAttr ".mas0" -type "doubleArray" 0 ;
	setAttr ".id0" -type "doubleArray" 0 ;
	setAttr ".bt0" -type "doubleArray" 0 ;
	setAttr ".ag0" -type "doubleArray" 0 ;
	setAttr ".lfm" 2;
	setAttr ".lfr" 0.2;
	setAttr ".irbx" -type "string" "";
	setAttr ".irax" -type "string" "";
	setAttr ".icx" -type "string" "";
	setAttr ".inh" 0.26936026899024895;
	setAttr ".cts" 1;
	setAttr ".chw" 90;
	setAttr ".prt" 8;
	setAttr ".cofl" 1;
	setAttr ".cold" no;
	setAttr ".scld" no;
	setAttr -s 2 ".fsc[0:1]"  0 1 1 1 0 1;
	setAttr -s 2 ".pfdo[0:1]"  0 1 1 1 0 1;
	setAttr ".drg" 0.29498526453971863;
	setAttr ".vssc[0]"  0 1 1;
	setAttr ".stns[0]"  0 1 1;
	setAttr ".ra" 0.2199999988079071;
	setAttr -s 3 ".rdc";
	setAttr ".rdc[1:2]" 0 1 1 1 0.41999998688697815 1;
	setAttr ".rdc[5].rdcp" 0.22608695924282074;
	setAttr ".rdc[5].rdcfv" 0.63999998569488525;
	setAttr ".rdc[5].rdci" 1;
	setAttr ".rci" 6;
	setAttr ".rsr" 0.016835017161136525;
	setAttr -s 2 ".mssc[0:1]"  0 1 1 1 0.75999999 1;
	setAttr ".msli" 6;
	setAttr ".msr" 0.36026935998400555;
	setAttr ".pfsc[0]"  0 1 1;
	setAttr ".frsc[0]"  0 1 1;
	setAttr ".stsc[0]"  0 1 1;
	setAttr ".clsc[0]"  0 1 1;
	setAttr ".bosc[0]"  0 1 1;
	setAttr ".op" 0.64306784634118497;
	setAttr -s 4 ".opc[0:3]"  0 1 1 0.43478259 0.80000001 1 1 0.2 
		1 0.8347826 0.51999998 1;
	setAttr ".oci" 2;
	setAttr ".osr" 0.26599326593055067;
	setAttr ".cl[2].clp" 0.23478260636329651;
	setAttr ".cl[2].clc" -type "float3" 0.493 0.43778402 0.43778402 ;
	setAttr ".cl[2].cli" 1;
	setAttr ".inca[2].incap" 0.35652199387550354;
	setAttr ".inca[2].incac" -type "float3" 41.241001 5.5675349 5.5675349 ;
	setAttr ".inca[2].incai" 1;
	setAttr ".ini" 2;
	setAttr ".lifespanPP0" -type "doubleArray" 0 ;
	setAttr -k on ".lifespan" 0.5;
	setAttr ".opacityPP0" -type "doubleArray" 0 ;
	setAttr ".radiusPP0" -type "doubleArray" 0 ;
	setAttr -k on ".betterIllumination";
	setAttr -k on ".surfaceShading";
	setAttr ".incandescencePP0" -type "vectorArray" 0 ;
createNode pointEmitter -n "secondaryEmitter" -p "burstNParticle";
	setAttr ".rat" 112.09439507144391;
	setAttr ".sro" no;
	setAttr -l on ".urpp";
	setAttr ".spd" 0.64896755041362264;
	setAttr ".srnd" 0.29498525018801031;
createNode transform -n "secondaryNParticle";
createNode nParticle -n "secondaryNParticleShape" -p "secondaryNParticle";
	addAttr -ci true -sn "lifespanPP" -ln "lifespanPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "lifespanPP0" -ln "lifespanPP0" -dt "doubleArray";
	addAttr -ci true -sn "lifespan" -ln "lifespan" -at "double";
	addAttr -ci true -sn "opacityPP" -ln "opacityPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "opacityPP0" -ln "opacityPP0" -dt "doubleArray";
	addAttr -ci true -sn "radiusPP" -ln "radiusPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "radiusPP0" -ln "radiusPP0" -dt "doubleArray";
	addAttr -is true -ci true -sn "betterIllumination" -ln "betterIllumination" -min 
		0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "surfaceShading" -ln "surfaceShading" -min 0 -max 
		1 -at "float";
	addAttr -ci true -sn "incandescencePP" -ln "incandescencePP" -dt "vectorArray";
	addAttr -ci true -h true -sn "incandescencePP0" -ln "incandescencePP0" -dt "vectorArray";
	setAttr -k off ".v";
	setAttr ".gf" -type "Int32Array" 0 ;
	setAttr ".pos0" -type "vectorArray" 0 ;
	setAttr ".vel0" -type "vectorArray" 0 ;
	setAttr ".acc0" -type "vectorArray" 0 ;
	setAttr ".mas0" -type "doubleArray" 0 ;
	setAttr ".id0" -type "doubleArray" 0 ;
	setAttr ".bt0" -type "doubleArray" 0 ;
	setAttr ".ag0" -type "doubleArray" 0 ;
	setAttr ".lfm" 2;
	setAttr ".lfr" 0.3;
	setAttr ".irbx" -type "string" "";
	setAttr ".irax" -type "string" "";
	setAttr ".icx" -type "string" "";
	setAttr ".sd[0]"  9;
	setAttr ".cts" 1;
	setAttr ".chw" 90;
	setAttr ".prt" 8;
	setAttr ".cofl" 1;
	setAttr ".cold" no;
	setAttr ".scld" no;
	setAttr -s 2 ".fsc[0:1]"  0 1 1 1 0 1;
	setAttr -s 2 ".pfdo[0:1]"  0 1 1 1 0 1;
	setAttr ".drg" 0.076696164906024933;
	setAttr ".vssc[0]"  0 1 1;
	setAttr ".stns[0]"  0 1 1;
	setAttr -s 2 ".rdc[2:3]"  0 0.46000001 1 1 1 1;
	setAttr ".rci" 2;
	setAttr ".mssc[0]"  0 1 1;
	setAttr ".pfsc[0]"  0 1 1;
	setAttr ".frsc[0]"  0 1 1;
	setAttr ".stsc[0]"  0 1 1;
	setAttr ".clsc[0]"  0 1 1;
	setAttr ".bosc[0]"  0 1 1;
	setAttr ".op" 0.26599326593055067;
	setAttr -s 4 ".opc[0:3]"  0 1 1 0.19130434 0.77999997 1 1 0.1 
		1 0.44347826 0.5 1;
	setAttr ".oci" 2;
	setAttr ".cl[0].clp" 0.29565218091011047;
	setAttr ".cl[0].clc" -type "float3" 0.51700002 0.31071702 0.31071702 ;
	setAttr ".cl[0].cli" 1;
	setAttr -s 3 ".inca";
	setAttr ".inca[0].incap" 0;
	setAttr ".inca[0].incac" -type "float3" 14.25 6.2300992 0.88349968 ;
	setAttr ".inca[0].incai" 3;
	setAttr ".inca[1].incap" 0.51304346323013306;
	setAttr ".inca[1].incac" -type "float3" 0 0 0 ;
	setAttr ".inca[1].incai" 3;
	setAttr ".inca[2].incap" 0.14782609045505524;
	setAttr ".inca[2].incac" -type "float3" 1.75229 0.766101 0.108642 ;
	setAttr ".inca[2].incai" 3;
	setAttr ".ini" 2;
	setAttr ".lifespanPP0" -type "doubleArray" 0 ;
	setAttr -k on ".lifespan" 0.8;
	setAttr ".opacityPP0" -type "doubleArray" 0 ;
	setAttr ".radiusPP0" -type "doubleArray" 0 ;
	setAttr -k on ".betterIllumination";
	setAttr -k on ".surfaceShading";
	setAttr ".incandescencePP0" -type "vectorArray" 0 ;
createNode transform -n "trailsNParticle";
createNode nParticle -n "trailsNParticleShape" -p "trailsNParticle";
	addAttr -ci true -sn "lifespanPP" -ln "lifespanPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "lifespanPP0" -ln "lifespanPP0" -dt "doubleArray";
	addAttr -ci true -sn "lifespan" -ln "lifespan" -at "double";
	addAttr -ci true -sn "rgbPP" -ln "rgbPP" -dt "vectorArray";
	addAttr -ci true -h true -sn "rgbPP0" -ln "rgbPP0" -dt "vectorArray";
	addAttr -ci true -sn "opacityPP" -ln "opacityPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "opacityPP0" -ln "opacityPP0" -dt "doubleArray";
	addAttr -ci true -sn "radiusPP" -ln "radiusPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "radiusPP0" -ln "radiusPP0" -dt "doubleArray";
	addAttr -is true -ci true -sn "betterIllumination" -ln "betterIllumination" -min 
		0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "surfaceShading" -ln "surfaceShading" -min 0 -max 
		1 -at "float";
	addAttr -ci true -sn "incandescencePP" -ln "incandescencePP" -dt "vectorArray";
	addAttr -ci true -h true -sn "incandescencePP0" -ln "incandescencePP0" -dt "vectorArray";
	setAttr -k off ".v";
	setAttr ".gf" -type "Int32Array" 0 ;
	setAttr ".pos0" -type "vectorArray" 0 ;
	setAttr ".vel0" -type "vectorArray" 0 ;
	setAttr ".acc0" -type "vectorArray" 0 ;
	setAttr ".mas0" -type "doubleArray" 0 ;
	setAttr ".id0" -type "doubleArray" 0 ;
	setAttr ".bt0" -type "doubleArray" 0 ;
	setAttr ".ag0" -type "doubleArray" 0 ;
	setAttr ".lfm" 2;
	setAttr ".lfr" 0.3;
	setAttr ".irbx" -type "string" "";
	setAttr ".irax" -type "string" "";
	setAttr ".icx" -type "string" "";
	setAttr ".cts" 1;
	setAttr ".chw" 90;
	setAttr ".prt" 8;
	setAttr ".cofl" 1;
	setAttr ".cold" no;
	setAttr ".scld" no;
	setAttr -s 2 ".fsc[0:1]"  0 1 1 1 0 1;
	setAttr -s 2 ".pfdo[0:1]"  0 1 1 1 0 1;
	setAttr ".igsg" yes;
	setAttr ".drg" 0.13569322228431702;
	setAttr ".vssc[0]"  0 1 1;
	setAttr ".stns[0]"  0 1 1;
	setAttr -s 2 ".rdc[0:1]"  0 1 1 0.31304348 0.5 1;
	setAttr ".rci" 2;
	setAttr ".mssc[0]"  0 1 1;
	setAttr ".pfsc[0]"  0 1 1;
	setAttr ".frsc[0]"  0 1 1;
	setAttr ".stsc[0]"  0 1 1;
	setAttr ".clsc[0]"  0 1 1;
	setAttr ".bosc[0]"  0 1 1;
	setAttr ".op" 0.22123893764100772;
	setAttr -s 3 ".opc[0:2]"  0 1 1 1 0.2 1 0.69565219 0.77999997 
		1;
	setAttr ".oci" 2;
	setAttr ".cl[1].clp" 1;
	setAttr ".cl[1].clc" -type "float3" 0 0.050500002 0.101 ;
	setAttr ".cl[1].cli" 1;
	setAttr ".coi" 1;
	setAttr -s 4 ".inca";
	setAttr ".inca[0].incap" 0;
	setAttr ".inca[0].incac" -type "float3" 0.48000008 1.0073328 5 ;
	setAttr ".inca[0].incai" 1;
	setAttr ".inca[1].incap" 1;
	setAttr ".inca[1].incac" -type "float3" 0 0 0 ;
	setAttr ".inca[1].incai" 1;
	setAttr ".inca[2].incap" 0.66956520080566406;
	setAttr ".inca[2].incac" -type "float3" 0.054260898 0.113872 0.56521702 ;
	setAttr ".inca[2].incai" 1;
	setAttr ".inca[3].incap" 0.40000000596046448;
	setAttr ".inca[3].incac" -type "float3" 0.182658 0.38332799 1.902691 ;
	setAttr ".inca[3].incai" 1;
	setAttr ".ini" 2;
	setAttr ".lifespanPP0" -type "doubleArray" 0 ;
	setAttr -k on ".lifespan" 0.3;
	setAttr ".rgbPP0" -type "vectorArray" 0 ;
	setAttr ".opacityPP0" -type "doubleArray" 0 ;
	setAttr ".radiusPP0" -type "doubleArray" 0 ;
	setAttr -k on ".betterIllumination";
	setAttr -k on ".surfaceShading";
	setAttr ".incandescencePP0" -type "vectorArray" 0 ;
createNode lightLinker -s -n "lightLinker1";
	setAttr -s 3 ".lnk";
	setAttr -s 3 ".slnk";
createNode displayLayerManager -n "layerManager";
createNode displayLayer -n "defaultLayer";
createNode renderLayerManager -n "renderLayerManager";
createNode renderLayer -n "defaultRenderLayer";
	setAttr ".g" yes;
createNode nucleus -n "FireworksORingNucleus";
	setAttr -s 4 ".niao";
	setAttr -s 4 ".nias";
	setAttr -s 4 ".noao";
	setAttr ".wisp" 0.28169015049934387;
	setAttr ".wnoi" 0.42253521084785461;
	setAttr ".sstp" 1;
	setAttr ".mcit" 0;
createNode shadingEngine -n "nParticleCloudSE";
	setAttr ".ihi" 0;
	setAttr -s 4 ".dsm";
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo1";
createNode particleSamplerInfo -n "particleSamplerInfo1";
createNode blinn -n "npCloudBlinn";
createNode particleCloud -n "npCloudVolume";
	setAttr ".gi" 0.371747225522995;
	setAttr ".rdns" 0.8401486873626709;
createNode animCurveTU -n "emitter1_rate";
	setAttr ".tan" 10;
	setAttr ".wgt" no;
	setAttr -s 2 ".ktv[0:1]"  1.92 1500 2.88 0;
createNode imagePlane -n "imagePlane1";
	setAttr ".t" 1;
	setAttr ".fc" 12;
	setAttr ".s" -type "double2" 1.4173200000000001 1.0629900633591451 ;
	setAttr ".c" -type "double3" 1.8554930823462756 -5.1451482582208108 0.9874048504893338 ;
	setAttr ".w" 10;
	setAttr ".h" 10;
createNode ramp -n "ramp1";
	setAttr -s 2 ".cel";
	setAttr ".cel[2].ep" 0;
	setAttr ".cel[2].ec" -type "float3" 0.056122683 0.10530251 0.16960403 ;
	setAttr ".cel[3].ep" 0.4699999988079071;
	setAttr ".cel[3].ec" -type "float3" 0 0 0 ;
createNode place2dTexture -n "place2dTexture1";
createNode script -n "sceneConfigurationScriptNode";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 90 -ast 0.96 -aet 192 ";
	setAttr ".st" 6;
createNode arrayMapper -n "arrayMapper1";
	setAttr ".max" 500;
createNode ramp -n "ramp2";
	setAttr -s 2 ".cel";
	setAttr ".cel[0].ep" 0.93500000238418579;
	setAttr ".cel[0].ec" -type "float3" 1 1 1 ;
	setAttr ".cel[2].ep" 0.88499999046325684;
	setAttr ".cel[2].ec" -type "float3" 0 0 0 ;
createNode expression -n "expression1";
	setAttr -k on ".nds";
	setAttr ".ixp" -type "string" "float $detonateFrame = .I[0];\n\n.O[0] = 0;\nif( frame >= $detonateFrame && frame < $detonateFrame + 1) {\n\t.O[0] = 1500;\n}";
createNode container -n "FireworksORingAsset";
	addAttr -ci true -h true -sn "aal" -ln "attributeAliasList" -dt "attributeAlias";
	addAttr -ci true -sn "nts" -ln "notes" -dt "string";
	setAttr -s 4 ".boc";
	setAttr ".ctor" -type "string" "";
	setAttr ".cdat" -type "string" "2010/08/18 15:38:32";
	setAttr ".ctyp" -type "string" "effects";
	setAttr ".aal" -type "attributeAlias" {"detonationFrame","borderConnections[0]","incandescence"
		,"borderConnections[1]","incandescence1","borderConnections[2]","incandescence2","borderConnections[3]"
		,"nucleusSolver","publishedNodeInfo[0]"} ;
	setAttr ".nts" -type "string" "nParticle effect - This is a fireworks effect with 4 cascading nParticles. It is a freestanding effect that does not need to be applied to an object in the scene: it can be placed as needed, by positioning the primary emitter.";
createNode hyperLayout -n "hyperLayout1";
	setAttr ".ihi" 0;
	setAttr -s 20 ".hyp";
	setAttr ".hyp[0].x" 591;
	setAttr ".hyp[0].y" 567;
	setAttr ".hyp[0].isf" yes;
	setAttr ".hyp[1].x" 71;
	setAttr ".hyp[1].y" 567;
	setAttr ".hyp[1].isf" yes;
	setAttr ".hyp[2].x" 2332;
	setAttr ".hyp[2].y" 747;
	setAttr ".hyp[2].isf" yes;
	setAttr ".hyp[3].x" 2332;
	setAttr ".hyp[3].y" 747;
	setAttr ".hyp[3].isf" yes;
	setAttr ".hyp[4].x" 2332;
	setAttr ".hyp[4].y" 747;
	setAttr ".hyp[4].isf" yes;
	setAttr ".hyp[5].x" 2332;
	setAttr ".hyp[5].y" 747;
	setAttr ".hyp[5].isf" yes;
	setAttr ".hyp[6].x" 2332;
	setAttr ".hyp[6].y" 747;
	setAttr ".hyp[6].isf" yes;
	setAttr ".hyp[7].x" 887;
	setAttr ".hyp[7].y" 591;
	setAttr ".hyp[7].isf" yes;
	setAttr ".hyp[8].x" 355;
	setAttr ".hyp[8].y" 419;
	setAttr ".hyp[8].isf" yes;
	setAttr ".hyp[9].x" 1563;
	setAttr ".hyp[9].y" 591;
	setAttr ".hyp[9].isf" yes;
	setAttr ".hyp[10].x" 1563;
	setAttr ".hyp[10].y" 723;
	setAttr ".hyp[10].isf" yes;
	setAttr ".hyp[11].x" 591;
	setAttr ".hyp[11].y" 401;
	setAttr ".hyp[11].isf" yes;
	setAttr ".hyp[12].x" 591;
	setAttr ".hyp[12].y" 643;
	setAttr ".hyp[12].isf" yes;
	setAttr ".hyp[13].x" 355;
	setAttr ".hyp[13].y" 567;
	setAttr ".hyp[13].isf" yes;
	setAttr ".hyp[14].x" 71;
	setAttr ".hyp[14].y" 401;
	setAttr ".hyp[14].isf" yes;
	setAttr ".hyp[15].x" 1183;
	setAttr ".hyp[15].y" 699;
	setAttr ".hyp[15].isf" yes;
	setAttr ".hyp[16].x" 1183;
	setAttr ".hyp[16].y" 567;
	setAttr ".hyp[16].isf" yes;
	setAttr ".hyp[17].x" 2520;
	setAttr ".hyp[17].y" 747;
	setAttr ".hyp[17].isf" yes;
	setAttr ".hyp[18].x" 355;
	setAttr ".hyp[18].y" 643;
	setAttr ".hyp[18].isf" yes;
	setAttr ".anf" yes;
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :renderPartition;
	setAttr -s 3 ".st";
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultShaderList1;
	setAttr -s 4 ".s";
select -ne :defaultTextureList1;
	setAttr -s 2 ".tx";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
select -ne :renderGlobalsList1;
select -ne :shaderGlow1;
	setAttr ".gi" 1.0780669450759888;
	setAttr ".gs" 0.019568772986531258;
	setAttr ".gfw" 10;
	setAttr ".hi" 0.26022306084632874;
	setAttr ".hs" 0.22304832935333252;
	setAttr ".qual" 50;
	setAttr ".th" 0.39033457636833191;
select -ne :defaultRenderGlobals;
	setAttr ".mcfr" 25;
	setAttr ".an" yes;
	setAttr ".fs" 0.96;
	setAttr ".ef" 96;
	setAttr ".ofc" 1;
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
	setAttr ".hwfr" 25;
select -ne :defaultHardwareRenderGlobals;
	setAttr ".fn" -type "string" "im";
	setAttr ".res" -type "string" "ntsc_4d 646 485 1.333";
connectAttr "imagePlane1.msg" ":perspShape.ip" -na;
connectAttr ":time1.o" "primaryEmitter.ct";
connectAttr "primaryNParticleShape.ifl" "primaryEmitter.full[0]";
connectAttr "primaryNParticleShape.tss" "primaryEmitter.dt[0]";
connectAttr "primaryNParticleShape.inh" "primaryEmitter.inh[0]";
connectAttr "primaryNParticleShape.stt" "primaryEmitter.stt[0]";
connectAttr "primaryNParticleShape.sd[0]" "primaryEmitter.sd[0]";
connectAttr "expression1.out[0]" "primaryEmitter.rat";
connectAttr "FireworksCTRLShape.wm" "annotationShape1.dom" -na;
connectAttr ":time1.o" "primaryNParticleShape.cti";
connectAttr "FireworksORingNucleus.noao[0]" "primaryNParticleShape.nxst";
connectAttr "FireworksORingNucleus.stf" "primaryNParticleShape.stf";
connectAttr "primaryEmitter.ot[0]" "primaryNParticleShape.npt[0]";
connectAttr "primaryNParticleShape.incr" "primaryNParticleShape.rgbPP";
connectAttr "primaryNParticleShape.inor" "primaryNParticleShape.opacityPP";
connectAttr "primaryNParticleShape.inmr" "primaryNParticleShape.mas";
connectAttr "primaryNParticleShape.inir" "primaryNParticleShape.incandescencePP"
		;
connectAttr "arrayMapper1.ovpp" "primaryNParticleShape.emitter2RatePP";
connectAttr ":time1.o" "burstEmitter.ct";
connectAttr "primaryNParticleShape.cwcn" "burstEmitter.ocd";
connectAttr "primaryNParticleShape.ctd" "burstEmitter.t";
connectAttr "primaryNParticleShape.pos" "burstEmitter.opd";
connectAttr "primaryNParticleShape.vel" "burstEmitter.ovd";
connectAttr "primaryNParticleShape.id" "burstEmitter.paid";
connectAttr "burstNParticleShape.ifl" "burstEmitter.full[0]";
connectAttr "burstNParticleShape.tss" "burstEmitter.dt[0]";
connectAttr "burstNParticleShape.inh" "burstEmitter.inh[0]";
connectAttr "burstNParticleShape.stt" "burstEmitter.stt[0]";
connectAttr "burstNParticleShape.sd[0]" "burstEmitter.sd[0]";
connectAttr "primaryNParticleShape.emitter2RatePP" "burstEmitter.rpp";
connectAttr "primaryNParticleShape.emitter2RemainderPP" "burstEmitter.ecr[0]";
connectAttr ":time1.o" "trailsEmitter.ct";
connectAttr "primaryNParticleShape.cwcn" "trailsEmitter.ocd";
connectAttr "primaryNParticleShape.ctd" "trailsEmitter.t";
connectAttr "primaryNParticleShape.cwps" "trailsEmitter.opd";
connectAttr "primaryNParticleShape.cwvl" "trailsEmitter.ovd";
connectAttr "primaryNParticleShape.id" "trailsEmitter.paid";
connectAttr "trailsNParticleShape.ifl" "trailsEmitter.full[0]";
connectAttr "trailsNParticleShape.tss" "trailsEmitter.dt[0]";
connectAttr "trailsNParticleShape.inh" "trailsEmitter.inh[0]";
connectAttr "trailsNParticleShape.stt" "trailsEmitter.stt[0]";
connectAttr "trailsNParticleShape.sd[0]" "trailsEmitter.sd[0]";
connectAttr ":time1.o" "burstNParticleShape.cti";
connectAttr "FireworksORingNucleus.noao[1]" "burstNParticleShape.nxst";
connectAttr "FireworksORingNucleus.stf" "burstNParticleShape.stf";
connectAttr "burstEmitter.ot[0]" "burstNParticleShape.npt[0]";
connectAttr "burstNParticleShape.inor" "burstNParticleShape.opacityPP";
connectAttr "burstNParticleShape.inrr" "burstNParticleShape.radiusPP";
connectAttr "burstNParticleShape.inir" "burstNParticleShape.incandescencePP";
connectAttr "burstNParticleShape.inmr" "burstNParticleShape.mas";
connectAttr ":time1.o" "secondaryEmitter.ct";
connectAttr "burstNParticleShape.cwcn" "secondaryEmitter.ocd";
connectAttr "burstNParticleShape.ctd" "secondaryEmitter.t";
connectAttr "burstNParticleShape.cwps" "secondaryEmitter.opd";
connectAttr "burstNParticleShape.cwvl" "secondaryEmitter.ovd";
connectAttr "burstNParticleShape.id" "secondaryEmitter.paid";
connectAttr "secondaryNParticleShape.ifl" "secondaryEmitter.full[0]";
connectAttr "secondaryNParticleShape.tss" "secondaryEmitter.dt[0]";
connectAttr "secondaryNParticleShape.inh" "secondaryEmitter.inh[0]";
connectAttr "secondaryNParticleShape.stt" "secondaryEmitter.stt[0]";
connectAttr "secondaryNParticleShape.sd[0]" "secondaryEmitter.sd[0]";
connectAttr ":time1.o" "secondaryNParticleShape.cti";
connectAttr "FireworksORingNucleus.noao[2]" "secondaryNParticleShape.nxst";
connectAttr "FireworksORingNucleus.stf" "secondaryNParticleShape.stf";
connectAttr "secondaryEmitter.ot[0]" "secondaryNParticleShape.npt[0]";
connectAttr "secondaryNParticleShape.inor" "secondaryNParticleShape.opacityPP";
connectAttr "secondaryNParticleShape.inrr" "secondaryNParticleShape.radiusPP";
connectAttr "secondaryNParticleShape.inir" "secondaryNParticleShape.incandescencePP"
		;
connectAttr ":time1.o" "trailsNParticleShape.cti";
connectAttr "FireworksORingNucleus.noao[3]" "trailsNParticleShape.nxst";
connectAttr "FireworksORingNucleus.stf" "trailsNParticleShape.stf";
connectAttr "trailsEmitter.ot[0]" "trailsNParticleShape.npt[0]";
connectAttr "trailsNParticleShape.incr" "trailsNParticleShape.rgbPP";
connectAttr "trailsNParticleShape.inor" "trailsNParticleShape.opacityPP";
connectAttr "trailsNParticleShape.inrr" "trailsNParticleShape.radiusPP";
connectAttr "trailsNParticleShape.inir" "trailsNParticleShape.incandescencePP";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "nParticleCloudSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "nParticleCloudSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr ":time1.o" "FireworksORingNucleus.cti";
connectAttr "primaryNParticleShape.cust" "FireworksORingNucleus.niao[0]";
connectAttr "burstNParticleShape.cust" "FireworksORingNucleus.niao[1]";
connectAttr "secondaryNParticleShape.cust" "FireworksORingNucleus.niao[2]";
connectAttr "trailsNParticleShape.cust" "FireworksORingNucleus.niao[3]";
connectAttr "primaryNParticleShape.stst" "FireworksORingNucleus.nias[0]";
connectAttr "burstNParticleShape.stst" "FireworksORingNucleus.nias[1]";
connectAttr "secondaryNParticleShape.stst" "FireworksORingNucleus.nias[2]";
connectAttr "trailsNParticleShape.stst" "FireworksORingNucleus.nias[3]";
connectAttr "npCloudBlinn.oc" "nParticleCloudSE.ss";
connectAttr "npCloudVolume.oi" "nParticleCloudSE.vs";
connectAttr "primaryNParticleShape.iog" "nParticleCloudSE.dsm" -na;
connectAttr "burstNParticleShape.iog" "nParticleCloudSE.dsm" -na;
connectAttr "secondaryNParticleShape.iog" "nParticleCloudSE.dsm" -na;
connectAttr "trailsNParticleShape.iog" "nParticleCloudSE.dsm" -na;
connectAttr "nParticleCloudSE.msg" "materialInfo1.sg";
connectAttr "npCloudBlinn.msg" "materialInfo1.m";
connectAttr "particleSamplerInfo1.msg" "materialInfo1.t" -na;
connectAttr "particleSamplerInfo1.oc" "npCloudBlinn.c";
connectAttr "particleSamplerInfo1.ot" "npCloudBlinn.it";
connectAttr "particleSamplerInfo1.oi" "npCloudBlinn.ic";
connectAttr "particleSamplerInfo1.ot" "npCloudVolume.t";
connectAttr "particleSamplerInfo1.oc" "npCloudVolume.c";
connectAttr "particleSamplerInfo1.oi" "npCloudVolume.i";
connectAttr "ramp1.oc" "imagePlane1.stx";
connectAttr "place2dTexture1.o" "ramp1.uv";
connectAttr "place2dTexture1.ofs" "ramp1.fs";
connectAttr "ramp2.msg" "arrayMapper1.cn";
connectAttr "ramp2.oc" "arrayMapper1.cnc";
connectAttr "primaryNParticleShape.ageNormalized" "arrayMapper1.vpp";
connectAttr "FireworksCTRL.detonationFrame" "expression1.in[0]";
connectAttr ":time1.o" "expression1.tim";
connectAttr "primaryEmitter.msg" "expression1.obm";
connectAttr "FireworksCTRL.detonationFrame" "FireworksORingAsset.boc[0]";
connectAttr "primaryNParticleShape.inca" "FireworksORingAsset.boc[1]";
connectAttr "secondaryNParticleShape.inca" "FireworksORingAsset.boc[2]";
connectAttr "trailsNParticleShape.inca" "FireworksORingAsset.boc[3]";
connectAttr "hyperLayout1.msg" "FireworksORingAsset.hl";
connectAttr "primaryEmitter.msg" "FireworksORingAsset.rt";
connectAttr "FireworksORingNucleus.msg" "FireworksORingAsset.pni[0].pnod";
connectAttr "primaryEmitter.msg" "hyperLayout1.hyp[0].dn";
connectAttr "FireworksCTRL.msg" "hyperLayout1.hyp[1].dn";
connectAttr "primaryNParticle.msg" "hyperLayout1.hyp[2].dn";
connectAttr "secondaryNParticle.msg" "hyperLayout1.hyp[3].dn";
connectAttr "burstNParticle.msg" "hyperLayout1.hyp[4].dn";
connectAttr "trailsNParticle.msg" "hyperLayout1.hyp[5].dn";
connectAttr "FireworksCTRLShape.msg" "hyperLayout1.hyp[6].dn";
connectAttr "primaryNParticleShape.msg" "hyperLayout1.hyp[7].dn";
connectAttr "secondaryNParticleShape.msg" "hyperLayout1.hyp[8].dn";
connectAttr "burstNParticleShape.msg" "hyperLayout1.hyp[9].dn";
connectAttr "trailsNParticleShape.msg" "hyperLayout1.hyp[10].dn";
connectAttr "FireworksORingNucleus.msg" "hyperLayout1.hyp[11].dn";
connectAttr "arrayMapper1.msg" "hyperLayout1.hyp[12].dn";
connectAttr "expression1.msg" "hyperLayout1.hyp[13].dn";
connectAttr "secondaryEmitter.msg" "hyperLayout1.hyp[14].dn";
connectAttr "trailsEmitter.msg" "hyperLayout1.hyp[15].dn";
connectAttr "burstEmitter.msg" "hyperLayout1.hyp[16].dn";
connectAttr "annotationShape1.msg" "hyperLayout1.hyp[17].dn";
connectAttr "ramp2.msg" "hyperLayout1.hyp[18].dn";
connectAttr "annotation1.msg" "hyperLayout1.hyp[19].dn";
connectAttr "nParticleCloudSE.pa" ":renderPartition.st" -na;
connectAttr "npCloudBlinn.msg" ":defaultShaderList1.s" -na;
connectAttr "npCloudVolume.msg" ":defaultShaderList1.s" -na;
connectAttr "ramp1.msg" ":defaultTextureList1.tx" -na;
connectAttr "ramp2.msg" ":defaultTextureList1.tx" -na;
connectAttr "place2dTexture1.msg" ":defaultRenderUtilityList1.u" -na;
// End of fireworkORingMod2.ma
