//Maya ASCII 2011 scene
//Name: fireworkSimpleMod2.ma
//Last modified: Thu, Aug 19, 2010 05:57:20 PM
//Codeset: 1252
requires maya "2011";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2011";
fileInfo "version" "2011";
fileInfo "cutIdentifier" "201007310527-779257";
fileInfo "osv" "Microsoft Windows XP Professional Service Pack 3 (Build 2600)\n";
createNode transform -s -n "persp";
	setAttr ".t" -type "double3" 14.090514608058848 -27.240130733274022 57.951135607149553 ;
	setAttr ".r" -type "double3" 16.461647270397656 13.40000000000024 0 ;
createNode camera -s -n "perspShape" -p "persp";
	setAttr -k off ".v";
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 62.586803559471235;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 100.1 0 ;
	setAttr ".r" -type "double3" -89.999999999999986 0 0 ;
createNode camera -s -n "topShape" -p "top";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 100.1 ;
createNode camera -s -n "frontShape" -p "front";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 100.1 0 0 ;
	setAttr ".r" -type "double3" 0 89.999999999999986 0 ;
createNode camera -s -n "sideShape" -p "side";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 100.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode pointEmitter -n "primaryEmitter";
	setAttr ".sro" no;
	setAttr -l on ".urpp";
	setAttr ".spd" 30;
createNode transform -n "FireworksCTRL" -p "primaryEmitter";
	addAttr -ci true -sn "detonationFrame" -ln "detonationFrame" -at "double";
	setAttr -k on ".detonationFrame" 2;
createNode locator -n "FireworksCTRLShape" -p "FireworksCTRL";
	setAttr -k off ".v";
createNode transform -n "annotation1" -p "FireworksCTRL";
createNode annotationShape -n "annotationShape1" -p "annotation1";
	setAttr -k off ".v";
	setAttr ".txt" -type "string" "FireworksCTRL";
createNode transform -n "primaryNParticle";
createNode nParticle -n "primaryNParticleShape" -p "primaryNParticle";
	addAttr -ci true -sn "lifespanPP" -ln "lifespanPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "lifespanPP0" -ln "lifespanPP0" -dt "doubleArray";
	addAttr -ci true -sn "lifespan" -ln "lifespan" -at "double";
	addAttr -ci true -sn "rgbPP" -ln "rgbPP" -dt "vectorArray";
	addAttr -ci true -h true -sn "rgbPP0" -ln "rgbPP0" -dt "vectorArray";
	addAttr -ci true -sn "opacityPP" -ln "opacityPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "opacityPP0" -ln "opacityPP0" -dt "doubleArray";
	addAttr -ci true -sn "radiusPP" -ln "radiusPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "radiusPP0" -ln "radiusPP0" -dt "doubleArray";
	addAttr -is true -ci true -sn "betterIllumination" -ln "betterIllumination" -min 
		0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "surfaceShading" -ln "surfaceShading" -min 0 -max 
		1 -at "float";
	addAttr -ci true -sn "incandescencePP" -ln "incandescencePP" -dt "vectorArray";
	addAttr -ci true -h true -sn "incandescencePP0" -ln "incandescencePP0" -dt "vectorArray";
	setAttr -k off ".v";
	setAttr ".gf" -type "Int32Array" 0 ;
	setAttr ".pos0" -type "vectorArray" 0 ;
	setAttr ".vel0" -type "vectorArray" 0 ;
	setAttr ".acc0" -type "vectorArray" 0 ;
	setAttr ".mas0" -type "doubleArray" 0 ;
	setAttr ".id0" -type "doubleArray" 0 ;
	setAttr ".bt0" -type "doubleArray" 0 ;
	setAttr ".ag0" -type "doubleArray" 0 ;
	setAttr ".lfm" 2;
	setAttr ".lfr" 2;
	setAttr ".irbx" -type "string" "";
	setAttr ".irax" -type "string" "";
	setAttr ".icx" -type "string" "";
	setAttr ".cts" 1;
	setAttr ".chw" 100;
	setAttr ".prt" 8;
	setAttr ".cofl" 1;
	setAttr ".pmss" 3.2330000400543213;
	setAttr ".scld" no;
	setAttr -s 2 ".fsc[0:1]"  0 1 1 1 0 1;
	setAttr -s 2 ".pfdo[0:1]"  0 1 1 1 0 1;
	setAttr ".drg" 0.15488216280937195;
	setAttr ".vssc[0]"  0 1 1;
	setAttr ".stns[0]"  0 1 1;
	setAttr ".ra" 0.30000001192092896;
	setAttr ".rdc[0]"  0 1 1;
	setAttr ".rci" 1;
	setAttr -s 2 ".mssc[0:1]"  0.5826087 1 1 1 0.1 1;
	setAttr ".msli" 2;
	setAttr ".pfsc[0]"  0 1 1;
	setAttr ".frsc[0]"  0 1 1;
	setAttr ".stsc[0]"  0 1 1;
	setAttr ".clsc[0]"  0 1 1;
	setAttr ".bosc[0]"  0 1 1;
	setAttr ".op" 0.85858585845415636;
	setAttr -s 4 ".opc[0:3]"  0 1 1 0.73913044 1 1 1 0.25999999 
		1 0.94782609 0.69999999 1;
	setAttr ".oci" 2;
	setAttr ".cl[0].clp" 0.12173912674188614;
	setAttr ".cl[0].clc" -type "float3" 0.156 0.154284 0.154284 ;
	setAttr ".cl[0].cli" 1;
	setAttr ".coi" 1;
	setAttr -s 3 ".inca";
	setAttr ".inca[0].incap" 0;
	setAttr ".inca[0].incac" -type "float3" 10 2.6783335 0.45000017 ;
	setAttr ".inca[0].incai" 1;
	setAttr ".inca[1].incap" 1;
	setAttr ".inca[1].incac" -type "float3" 1.24 0.33211336 0.055800021 ;
	setAttr ".inca[1].incai" 1;
	setAttr ".inca[2].incap" 0.6608695387840271;
	setAttr ".inca[2].incac" -type "float3" 20 3.128 1.6 ;
	setAttr ".inca[2].incai" 1;
	setAttr ".ini" 2;
	setAttr ".lifespanPP0" -type "doubleArray" 0 ;
	setAttr -k on ".lifespan" 2;
	setAttr ".rgbPP0" -type "vectorArray" 0 ;
	setAttr ".opacityPP0" -type "doubleArray" 0 ;
	setAttr ".radiusPP0" -type "doubleArray" 0 ;
	setAttr -k on ".betterIllumination";
	setAttr -k on ".surfaceShading";
	setAttr ".incandescencePP0" -type "vectorArray" 0 ;
createNode pointEmitter -n "trailsEmitter" -p "primaryNParticle";
	setAttr ".sro" no;
	setAttr -l on ".urpp";
	setAttr ".spd" 0.47138047492388724;
	setAttr ".srnd" 0.37037037381971327;
createNode transform -n "trailsNParticle";
createNode nParticle -n "trailsNParticleShape" -p "trailsNParticle";
	addAttr -ci true -sn "lifespanPP" -ln "lifespanPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "lifespanPP0" -ln "lifespanPP0" -dt "doubleArray";
	addAttr -ci true -sn "lifespan" -ln "lifespan" -at "double";
	addAttr -ci true -sn "rgbPP" -ln "rgbPP" -dt "vectorArray";
	addAttr -ci true -h true -sn "rgbPP0" -ln "rgbPP0" -dt "vectorArray";
	addAttr -ci true -sn "opacityPP" -ln "opacityPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "opacityPP0" -ln "opacityPP0" -dt "doubleArray";
	addAttr -ci true -sn "radiusPP" -ln "radiusPP" -dt "doubleArray";
	addAttr -ci true -h true -sn "radiusPP0" -ln "radiusPP0" -dt "doubleArray";
	addAttr -is true -ci true -sn "betterIllumination" -ln "betterIllumination" -min 
		0 -max 1 -at "bool";
	addAttr -is true -ci true -sn "surfaceShading" -ln "surfaceShading" -min 0 -max 
		1 -at "float";
	addAttr -ci true -sn "incandescencePP" -ln "incandescencePP" -dt "vectorArray";
	addAttr -ci true -h true -sn "incandescencePP0" -ln "incandescencePP0" -dt "vectorArray";
	setAttr -k off ".v";
	setAttr ".gf" -type "Int32Array" 0 ;
	setAttr ".pos0" -type "vectorArray" 0 ;
	setAttr ".vel0" -type "vectorArray" 0 ;
	setAttr ".acc0" -type "vectorArray" 0 ;
	setAttr ".mas0" -type "doubleArray" 0 ;
	setAttr ".id0" -type "doubleArray" 0 ;
	setAttr ".bt0" -type "doubleArray" 0 ;
	setAttr ".ag0" -type "doubleArray" 0 ;
	setAttr ".lfm" 2;
	setAttr ".lfr" 0.7;
	setAttr ".irbx" -type "string" "";
	setAttr ".irax" -type "string" "";
	setAttr ".icx" -type "string" "";
	setAttr ".cts" 1;
	setAttr ".chw" 100;
	setAttr ".prt" 8;
	setAttr ".cofl" 1;
	setAttr ".cold" no;
	setAttr ".scld" no;
	setAttr -s 2 ".fsc[0:1]"  0 1 1 1 0 1;
	setAttr -s 2 ".pfdo[0:1]"  0 1 1 1 0 1;
	setAttr ".igsg" yes;
	setAttr ".vssc[0]"  0 1 1;
	setAttr ".stns[0]"  0 1 1;
	setAttr ".ra" 0.94276094436645508;
	setAttr -s 3 ".rdc[0:2]"  0 0.25999999 1 1 1 1 0.26956522 0.51999998 
		1;
	setAttr ".rci" 1;
	setAttr ".mssc[0]"  0 1 1;
	setAttr ".pfsc[0]"  0 1 1;
	setAttr ".frsc[0]"  0 1 1;
	setAttr ".stsc[0]"  0 1 1;
	setAttr ".clsc[0]"  0 1 1;
	setAttr ".bosc[0]"  0 1 1;
	setAttr ".op" 0.067340067713223525;
	setAttr -s 4 ".opc[0:3]"  0 1 1 1 0.02 1 0.17391305 0.44 1 
		0.54782599 0.2 1;
	setAttr ".oci" 1;
	setAttr ".cl[2].clp" 0.0086956517770886421;
	setAttr ".cl[2].clc" -type "float3" 0.101 0.092657402 0.089082003 ;
	setAttr ".cl[2].cli" 1;
	setAttr ".coi" 1;
	setAttr -s 4 ".inca";
	setAttr ".inca[0].incap" 0.13913042843341827;
	setAttr ".inca[0].incac" -type "float3" 1 0.039000001 0.056000002 ;
	setAttr ".inca[0].incai" 1;
	setAttr ".inca[1].incap" 0;
	setAttr ".inca[1].incac" -type "float3" 10 2.9200001 1.2 ;
	setAttr ".inca[1].incai" 1;
	setAttr ".inca[2].incap" 0.41739130020141602;
	setAttr ".inca[2].incac" -type "float3" 0.15099999 0.044091996 0.0084559992 ;
	setAttr ".inca[2].incai" 1;
	setAttr ".inca[3].incap" 1;
	setAttr ".inca[3].incac" -type "float3" 0.039000001 0.011388 0.0021839999 ;
	setAttr ".inca[3].incai" 1;
	setAttr ".ini" 2;
	setAttr ".lifespanPP0" -type "doubleArray" 0 ;
	setAttr -k on ".lifespan" 0.8;
	setAttr ".rgbPP0" -type "vectorArray" 0 ;
	setAttr ".opacityPP0" -type "doubleArray" 0 ;
	setAttr ".radiusPP0" -type "doubleArray" 0 ;
	setAttr -k on ".betterIllumination";
	setAttr -k on ".surfaceShading";
	setAttr ".incandescencePP0" -type "vectorArray" 0 ;
createNode lightLinker -s -n "lightLinker1";
	setAttr -s 3 ".lnk";
	setAttr -s 3 ".slnk";
createNode displayLayerManager -n "layerManager";
createNode displayLayer -n "defaultLayer";
createNode renderLayerManager -n "renderLayerManager";
createNode renderLayer -n "defaultRenderLayer";
	setAttr ".g" yes;
createNode nucleus -n "FireworksSimpleNucleus";
	setAttr -s 2 ".niao";
	setAttr -s 2 ".nias";
	setAttr -s 2 ".noao";
	setAttr ".sstp" 1;
	setAttr ".mcit" 0;
createNode shadingEngine -n "nParticleCloudSE";
	setAttr ".ihi" 0;
	setAttr -s 2 ".dsm";
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo1";
createNode particleSamplerInfo -n "particleSamplerInfo1";
createNode blinn -n "npCloudBlinn";
createNode particleCloud -n "npCloudVolume";
	setAttr ".gi" 0.371747225522995;
	setAttr ".rdns" 0.8401486873626709;
createNode animCurveTU -n "emitter1_rate";
	setAttr ".tan" 10;
	setAttr ".wgt" no;
	setAttr -s 2 ".ktv[0:1]"  1.92 5000 2.88 0;
createNode imagePlane -n "imagePlane1";
	setAttr ".t" 1;
	setAttr ".fc" 12;
	setAttr ".s" -type "double2" 1.4173200000000001 1.0629900633591451 ;
	setAttr ".c" -type "double3" 1.8554930823462756 -5.1451482582208108 0.9874048504893338 ;
	setAttr ".w" 10;
	setAttr ".h" 10;
createNode ramp -n "ramp1";
	setAttr -s 2 ".cel";
	setAttr ".cel[2].ep" 0;
	setAttr ".cel[2].ec" -type "float3" 0.056122683 0.10530251 0.16960403 ;
	setAttr ".cel[3].ep" 0.4699999988079071;
	setAttr ".cel[3].ec" -type "float3" 0 0 0 ;
createNode place2dTexture -n "place2dTexture1";
createNode script -n "sceneConfigurationScriptNode";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 100 -ast 1 -aet 100 ";
	setAttr ".st" 6;
createNode expression -n "expression1";
	setAttr -k on ".nds";
	setAttr ".ixp" -type "string" "float $detonateFrame = .I[0];\n\n.O[0] = 0;\nif( frame >= $detonateFrame && frame < $detonateFrame + 1) {\n\t.O[0] = 5000;\n}";
createNode container -n "FireworksSimpleAsset";
	addAttr -ci true -h true -sn "aal" -ln "attributeAliasList" -dt "attributeAlias";
	addAttr -ci true -sn "nts" -ln "notes" -dt "string";
	setAttr ".isc" yes;
	setAttr -s 3 ".boc";
	setAttr ".ctor" -type "string" "";
	setAttr ".cdat" -type "string" "2010/08/18 16:53:35";
	setAttr ".ctyp" -type "string" "effects";
	setAttr ".aal" -type "attributeAlias" {"incandescence","borderConnections[0]","incandescence1"
		,"borderConnections[1]","detonationFrame","borderConnections[2]","nucleusSolver","publishedNodeInfo[0]"
		} ;
	setAttr ".nts" -type "string" "nParticle effect - This is a fireworks effect with 3 cascading nParticles. It is a freestanding effect that does not need to be applied to an object in the scene: it can be placed as needed, by positioning the primary emitter.";
createNode hyperLayout -n "hyperLayout1";
	setAttr ".ihi" 0;
	setAttr -s 12 ".hyp";
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :renderPartition;
	setAttr -s 3 ".st";
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultShaderList1;
	setAttr -s 4 ".s";
select -ne :defaultTextureList1;
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
select -ne :renderGlobalsList1;
select -ne :shaderGlow1;
	setAttr ".gi" 0.371747225522995;
	setAttr ".gs" 0.022031579166650772;
	setAttr ".gfw" 10;
	setAttr ".hi" 0.10000000149011612;
	setAttr ".hs" 0.30855017900466919;
	setAttr ".qual" 50;
	setAttr ".th" 0.42807018756866455;
select -ne :defaultRenderGlobals;
	setAttr ".an" yes;
	setAttr ".fs" 0.96;
	setAttr ".ef" 96;
	setAttr ".ofc" 1;
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
select -ne :defaultHardwareRenderGlobals;
	setAttr ".fn" -type "string" "im";
	setAttr ".res" -type "string" "ntsc_4d 646 485 1.333";
connectAttr "imagePlane1.msg" ":perspShape.ip" -na;
connectAttr ":time1.o" "primaryEmitter.ct";
connectAttr "primaryNParticleShape.ifl" "primaryEmitter.full[0]";
connectAttr "primaryNParticleShape.tss" "primaryEmitter.dt[0]";
connectAttr "primaryNParticleShape.inh" "primaryEmitter.inh[0]";
connectAttr "primaryNParticleShape.stt" "primaryEmitter.stt[0]";
connectAttr "primaryNParticleShape.sd[0]" "primaryEmitter.sd[0]";
connectAttr "expression1.out[0]" "primaryEmitter.rat";
connectAttr "FireworksCTRLShape.wm" "annotationShape1.dom" -na;
connectAttr ":time1.o" "primaryNParticleShape.cti";
connectAttr "FireworksSimpleNucleus.noao[0]" "primaryNParticleShape.nxst";
connectAttr "FireworksSimpleNucleus.stf" "primaryNParticleShape.stf";
connectAttr "primaryEmitter.ot[0]" "primaryNParticleShape.npt[0]";
connectAttr "primaryNParticleShape.incr" "primaryNParticleShape.rgbPP";
connectAttr "primaryNParticleShape.inor" "primaryNParticleShape.opacityPP";
connectAttr "primaryNParticleShape.inrr" "primaryNParticleShape.radiusPP";
connectAttr "primaryNParticleShape.inmr" "primaryNParticleShape.mas";
connectAttr "primaryNParticleShape.inir" "primaryNParticleShape.incandescencePP"
		;
connectAttr ":time1.o" "trailsEmitter.ct";
connectAttr "primaryNParticleShape.cwcn" "trailsEmitter.ocd";
connectAttr "primaryNParticleShape.ctd" "trailsEmitter.t";
connectAttr "primaryNParticleShape.cwps" "trailsEmitter.opd";
connectAttr "primaryNParticleShape.cwvl" "trailsEmitter.ovd";
connectAttr "primaryNParticleShape.id" "trailsEmitter.paid";
connectAttr "trailsNParticleShape.ifl" "trailsEmitter.full[0]";
connectAttr "trailsNParticleShape.tss" "trailsEmitter.dt[0]";
connectAttr "trailsNParticleShape.inh" "trailsEmitter.inh[0]";
connectAttr "trailsNParticleShape.stt" "trailsEmitter.stt[0]";
connectAttr "trailsNParticleShape.sd[0]" "trailsEmitter.sd[0]";
connectAttr ":time1.o" "trailsNParticleShape.cti";
connectAttr "FireworksSimpleNucleus.noao[1]" "trailsNParticleShape.nxst";
connectAttr "FireworksSimpleNucleus.stf" "trailsNParticleShape.stf";
connectAttr "trailsEmitter.ot[0]" "trailsNParticleShape.npt[0]";
connectAttr "trailsNParticleShape.incr" "trailsNParticleShape.rgbPP";
connectAttr "trailsNParticleShape.inor" "trailsNParticleShape.opacityPP";
connectAttr "trailsNParticleShape.inrr" "trailsNParticleShape.radiusPP";
connectAttr "trailsNParticleShape.inir" "trailsNParticleShape.incandescencePP";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "nParticleCloudSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "nParticleCloudSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr ":time1.o" "FireworksSimpleNucleus.cti";
connectAttr "primaryNParticleShape.cust" "FireworksSimpleNucleus.niao[0]";
connectAttr "trailsNParticleShape.cust" "FireworksSimpleNucleus.niao[1]";
connectAttr "primaryNParticleShape.stst" "FireworksSimpleNucleus.nias[0]";
connectAttr "trailsNParticleShape.stst" "FireworksSimpleNucleus.nias[1]";
connectAttr "npCloudBlinn.oc" "nParticleCloudSE.ss";
connectAttr "npCloudVolume.oi" "nParticleCloudSE.vs";
connectAttr "primaryNParticleShape.iog" "nParticleCloudSE.dsm" -na;
connectAttr "trailsNParticleShape.iog" "nParticleCloudSE.dsm" -na;
connectAttr "nParticleCloudSE.msg" "materialInfo1.sg";
connectAttr "npCloudBlinn.msg" "materialInfo1.m";
connectAttr "particleSamplerInfo1.msg" "materialInfo1.t" -na;
connectAttr "particleSamplerInfo1.oc" "npCloudBlinn.c";
connectAttr "particleSamplerInfo1.ot" "npCloudBlinn.it";
connectAttr "particleSamplerInfo1.oi" "npCloudBlinn.ic";
connectAttr "particleSamplerInfo1.ot" "npCloudVolume.t";
connectAttr "particleSamplerInfo1.oc" "npCloudVolume.c";
connectAttr "particleSamplerInfo1.oi" "npCloudVolume.i";
connectAttr "ramp1.oc" "imagePlane1.stx";
connectAttr "place2dTexture1.o" "ramp1.uv";
connectAttr "place2dTexture1.ofs" "ramp1.fs";
connectAttr "FireworksCTRL.detonationFrame" "expression1.in[0]";
connectAttr ":time1.o" "expression1.tim";
connectAttr "primaryEmitter.msg" "expression1.obm";
connectAttr "primaryNParticleShape.inca" "FireworksSimpleAsset.boc[0]";
connectAttr "trailsNParticleShape.inca" "FireworksSimpleAsset.boc[1]";
connectAttr "FireworksCTRL.detonationFrame" "FireworksSimpleAsset.boc[2]";
connectAttr "hyperLayout1.msg" "FireworksSimpleAsset.hl";
connectAttr "primaryEmitter.msg" "FireworksSimpleAsset.rt";
connectAttr "FireworksSimpleNucleus.msg" "FireworksSimpleAsset.pni[0].pnod";
connectAttr "trailsNParticle.msg" "hyperLayout1.hyp[0].dn";
connectAttr "primaryEmitter.msg" "hyperLayout1.hyp[1].dn";
connectAttr "FireworksCTRL.msg" "hyperLayout1.hyp[2].dn";
connectAttr "FireworksCTRLShape.msg" "hyperLayout1.hyp[3].dn";
connectAttr "annotation1.msg" "hyperLayout1.hyp[4].dn";
connectAttr "annotationShape1.msg" "hyperLayout1.hyp[5].dn";
connectAttr "primaryNParticle.msg" "hyperLayout1.hyp[6].dn";
connectAttr "primaryNParticleShape.msg" "hyperLayout1.hyp[7].dn";
connectAttr "trailsEmitter.msg" "hyperLayout1.hyp[8].dn";
connectAttr "trailsNParticleShape.msg" "hyperLayout1.hyp[9].dn";
connectAttr "expression1.msg" "hyperLayout1.hyp[10].dn";
connectAttr "FireworksSimpleNucleus.msg" "hyperLayout1.hyp[11].dn";
connectAttr "nParticleCloudSE.pa" ":renderPartition.st" -na;
connectAttr "npCloudBlinn.msg" ":defaultShaderList1.s" -na;
connectAttr "npCloudVolume.msg" ":defaultShaderList1.s" -na;
connectAttr "ramp1.msg" ":defaultTextureList1.tx" -na;
connectAttr "place2dTexture1.msg" ":defaultRenderUtilityList1.u" -na;
// End of fireworkSimpleMod2.ma
