// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc AEcMuscleDisplayTemplate(string $nodeName)
{

    editorTemplate -beginScrollLayout;
	editorTemplate -beginLayout (uiRes("m_AEcMuscleDisplayTemplate.kMuscleDisplayAttributes")) -collapse 0;
	    editorTemplate -addControl "index";
	    editorTemplate -addSeparator ;
	    editorTemplate -addControl "draw";
	    editorTemplate -addControl "ptSize";
	    editorTemplate -addControl "grayscale";
	    editorTemplate -addControl "colorA";
	    editorTemplate -addControl "colorB";
	    editorTemplate -addControl "colorC";
	editorTemplate -endLayout;


    editorTemplate -suppress "localPosition";

    // and these
    editorTemplate -suppress "weightList";
    editorTemplate -suppress "weights";
    editorTemplate -suppress "stickyWeightListMus";
    editorTemplate -suppress "stickyWeightsMus";
    editorTemplate -suppress "stickyWeightListMusB";
    editorTemplate -suppress "stickyWeightsMusB";
    editorTemplate -suppress "stickyWeightListMusC";
    editorTemplate -suppress "stickyWeightsMusC";
    editorTemplate -suppress "weightListMus";
    editorTemplate -suppress "weightsMus";
    editorTemplate -suppress "weightListDir";
    editorTemplate -suppress "weightsDir";
    editorTemplate -suppress "weightsForce";
    editorTemplate -suppress "weightsRelax";
    editorTemplate -suppress "jiggle";
    editorTemplate -suppress "cycle";
    editorTemplate -suppress "rest";
    editorTemplate -suppress "weightsWrinkle";
    editorTemplate -suppress "weightsDetail";
    editorTemplate -suppress "weightsSmooth";
    editorTemplate -suppress "weightsSmoothCompress";
    editorTemplate -suppress "weightsSmoothExpand";
    editorTemplate -suppress "weightsSelfCollision";
    editorTemplate -suppress "weightsSelfRigidity";
    editorTemplate -suppress "weightsSelfVolumize";

    editorTemplate -suppress "msgSystem";
    editorTemplate -suppress "geoIn";

    editorTemplate -suppress "ptColors";
    editorTemplate -suppress "ptPos";
    editorTemplate -suppress "numPts";
    editorTemplate -suppress "numCols";
    
    
    AElocatorInclude $nodeName ;

    editorTemplate -addExtraControls;
    editorTemplate -endScrollLayout;

}

