// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "// Connected \"^1s\" to \"^2s\" //\n" m_cMuscleDisplace.kConnectedCurveShapeToMuscleDisplace;
displayString -replace -value "// Connected \"^1s\" to \"^2s\" //\n" m_cMuscleDisplace.kConnectedMuscleDisplaceToMuscleSystem;
displayString -replace -value "The curve \"^1s\" is already connected to cMuscleDisplace node \"^2s\"." m_cMuscleDisplace.kCurveAlreadyConnectedToMuscleDisplace;
displayString -replace -value "The curve \"^1s\" is NOT connected to cMuscleDisplace node \"^2s\"." m_cMuscleDisplace.kCurveNotConnectedToMuscleDisplace;
displayString -replace -value "// Disconnected all cMuscleDisplace nodes from the cMuscleSystem nodes. //\n" m_cMuscleDisplace.kDisconnectedAllMuscleDisplaceFromMuscleSystem;
displayString -replace -value "// Disconnected \"^1s\" from \"^2s\" //\n" m_cMuscleDisplace.kDisconnectedCurveShapeFromMuscleDisplace;
displayString -replace -value "// Disconnected \"^1s\" from \"^2s\" //\n" m_cMuscleDisplace.kDisconnectedMuscleDisplaceFromMuscleSystem;
displayString -replace -value "cMuscleDisplace \"^1s\" is already connected to cMuscleSystem node \"^2s\"." m_cMuscleDisplace.kMuscleDisplaceAlreadyConnectedToMuscleSystem;
displayString -replace -value "cMuscleDisplace \"^1s\" is NOT connected to cMuscleSystem node \"^2s\"." m_cMuscleDisplace.kMuscleDisplaceNotConnectedToMuscleSystem;
displayString -replace -value "You must select at least one cMuscleDisplace object and one mesh deformed with cMuscleSystem to connect to." m_cMuscleDisplace.kMustSelectMuscleDisplaceAndMuscleSystemMeshToConnect;
displayString -replace -value "You must select at least one cMuscleDisplace object and one mesh deformed with cMuscleSystem to disconncect from." m_cMuscleDisplace.kMustSelectMuscleDisplaceAndMuscleSystemMeshToDisconnect;
displayString -replace -value "You must select at least one cMuscleSystem deformer or geometry." m_cMuscleDisplace.kMustSelectMuscleSystemDeformerOrGeometry;
displayString -replace -value "You must select at least one cMuscleSystem deformed object." m_cMuscleDisplace.kMustSelectMuscleSystemObject;
displayString -replace -value "You must select at least one NURBs Curve and one cMuscleDisplace object to connect to." m_cMuscleDisplace.kMustSelectNURBsCurveAndMuscleDisplaceToConnect;
displayString -replace -value "You must selectect at least one NURBs Curve and one cMuscleDisplace object to disconncect from." m_cMuscleDisplace.kMustSelectNURBsCurveAndMuscleDisplaceToDisconnect;
