// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Apply Muscle Object Values" m_cMuscleBuilder.kApplyMuscleObjectValues;
displayString -replace -value "Applies the given settings to the selected muscle objects." m_cMuscleBuilder.kApplyMuscleObjectValuesAnnot;
displayString -replace -value "At:" m_cMuscleBuilder.kAt;
displayString -replace -value "Attach Obj 1:" m_cMuscleBuilder.kAttachObj1;
displayString -replace -value "After building, selects manual adjustment mover." m_cMuscleBuilder.kAttachObj1Annot;
displayString -replace -value "Attach Obj 2:" m_cMuscleBuilder.kAttachObj2;
displayString -replace -value "After building, selects manual adjustment mover." m_cMuscleBuilder.kAttachObj2Annot;
displayString -replace -value "Build" m_cMuscleBuilder.kBuild;
displayString -replace -value "Build/Update" m_cMuscleBuilder.kBuildUpdate;
displayString -replace -value "Create muscle" m_cMuscleBuilder.kBuildUpdateAnnot;
displayString -replace -value "Cancel" m_cMuscleBuilder.kCancel;
displayString -replace -value "Capsule Axis:" m_cMuscleBuilder.kCapsuleAxis;
displayString -replace -value "circleY" m_cMuscleBuilder.kControlTypeCircleY;
displayString -replace -value "cube" m_cMuscleBuilder.kControlTypeCube;
displayString -replace -value "null" m_cMuscleBuilder.kControlTypeNull;
displayString -replace -value "Convert to Muscle" m_cMuscleBuilder.kConvertToMuscle;
displayString -replace -value "Finalizes modeling, applies deformer, and converts to muscle object." m_cMuscleBuilder.kConvertToMuscleAnnot;
displayString -replace -value "Copy from Selection" m_cMuscleBuilder.kCopyPasteCopyFromSelection;
displayString -replace -value "Copies Stretch and Jiggle settings from selected muscles." m_cMuscleBuilder.kCopyPasteCopyFromSelectionAnnot;
displayString -replace -value "Copy/Paste Muscle Settings" m_cMuscleBuilder.kCopyPasteMuscleSettings;
displayString -replace -value "Paste to Selected" m_cMuscleBuilder.kCopyPastePasteToSelected;
displayString -replace -value "Pastes copied Stretch and Jiggle settings onto selected muscles." m_cMuscleBuilder.kCopyPastePasteToSelectedAnnot;
displayString -replace -value "// Copying ^1s //\n" m_cMuscleBuilder.kCopyingMessage;
displayString -replace -value "Create Mirrored Muscle" m_cMuscleBuilder.kCreateMirroredMuscle;
displayString -replace -value "Cross Section" m_cMuscleBuilder.kCrossSection;
displayString -replace -value "Curve ^1s" m_cMuscleBuilder.kCrossSectionCurve;
displayString -replace -value "Deformer:" m_cMuscleBuilder.kDeformer;
displayString -replace -value "Delete" m_cMuscleBuilder.kDelete;
displayString -replace -value "Delete muscle" m_cMuscleBuilder.kDeleteAnnot;
displayString -replace -value "Draw:" m_cMuscleBuilder.kDraw;
displayString -replace -value "fat" m_cMuscleBuilder.kDrawFat;
displayString -replace -value "muscle" m_cMuscleBuilder.kDrawMuscle;
displayString -replace -value "off" m_cMuscleBuilder.kDrawOff;
displayString -replace -value "Edit Cross Section" m_cMuscleBuilder.kEditCrossSection;
displayString -replace -value "Edit Cross Section" m_cMuscleBuilder.kEditCrossSection2;
displayString -replace -value "Edit specified cross section" m_cMuscleBuilder.kEditCrossSectionAnnot;
displayString -replace -value "EDITING" m_cMuscleBuilder.kEditing;
displayString -replace -value "Falloff:" m_cMuscleBuilder.kFalloff;
displayString -replace -value "Fat:" m_cMuscleBuilder.kFat;
displayString -replace -value "Finalize" m_cMuscleBuilder.kFinalize;
displayString -replace -value "Highlight Shaded:" m_cMuscleBuilder.kHighlightShaded;
displayString -replace -value "Highlight Wire:" m_cMuscleBuilder.kHighlightWire;
displayString -replace -value "Apply Jiggle Values" m_cMuscleBuilder.kJiggleApplyJiggleValues;
displayString -replace -value "Applies the given settings to the selected muscle objects." m_cMuscleBuilder.kJiggleApplyJiggleValuesAnnot;
displayString -replace -value "Cycle:  " m_cMuscleBuilder.kJiggleCycle;
displayString -replace -value "Dampen on Squash:  " m_cMuscleBuilder.kJiggleDampenOnSquash;
displayString -replace -value "Dampen on Stretch:  " m_cMuscleBuilder.kJiggleDampenOnStretch;
displayString -replace -value "Default" m_cMuscleBuilder.kJiggleDefault;
displayString -replace -value "Set jiggle parameters." m_cMuscleBuilder.kJiggleDefaultAnnot;
displayString -replace -value "END" m_cMuscleBuilder.kJiggleEnd;
displayString -replace -value "Heavy" m_cMuscleBuilder.kJiggleHeavy;
displayString -replace -value "Set jiggle parameters." m_cMuscleBuilder.kJiggleHeavyAnnot;
displayString -replace -value "Jiggle:  " m_cMuscleBuilder.kJiggleJiggle;
displayString -replace -value "Light" m_cMuscleBuilder.kJiggleLight;
displayString -replace -value "Set jiggle parameters." m_cMuscleBuilder.kJiggleLightAnnot;
displayString -replace -value "Load Selected" m_cMuscleBuilder.kJiggleLoadSelected;
displayString -replace -value "Loads the given values from the selected muscle objects." m_cMuscleBuilder.kJiggleLoadSelectedAnnot;
displayString -replace -value "Medium" m_cMuscleBuilder.kJiggleMedium;
displayString -replace -value "Set jiggle parameters." m_cMuscleBuilder.kJiggleMediumAnnot;
displayString -replace -value "MID" m_cMuscleBuilder.kJiggleMid;
displayString -replace -value "OFF" m_cMuscleBuilder.kJiggleOff;
displayString -replace -value "Set jiggle parameters." m_cMuscleBuilder.kJiggleOffAnnot;
displayString -replace -value "Jiggle Presets" m_cMuscleBuilder.kJigglePresets;
displayString -replace -value "Rest:  " m_cMuscleBuilder.kJiggleReset;
displayString -replace -value "START" m_cMuscleBuilder.kJiggleStart;
displayString -replace -value "Length:" m_cMuscleBuilder.kLength;
displayString -replace -value "Load Selected" m_cMuscleBuilder.kLoadSelected;
displayString -replace -value "Loads the given values from the selected muscle objects." m_cMuscleBuilder.kLoadSelectedAnnot;
displayString -replace -value "Load selected object." m_cMuscleBuilder.kLoadSelectedObject1;
displayString -replace -value "Load selected object." m_cMuscleBuilder.kLoadSelectedObject2;
displayString -replace -value "// Loaded jiggle parameters from ^1s //\n" m_cMuscleBuilder.kLoadedJiggleParametersFromMuscleSplineDeformer;
displayString -replace -value "// Loaded jiggle parameters from ^1s //\n" m_cMuscleBuilder.kLoadedJiggleParametersFromMuscleStretch;
displayString -replace -value "// Loaded stretch parameters from ^1s //\n" m_cMuscleBuilder.kLoadedStretchParametersFromMuscleSplineDeformer;
displayString -replace -value "// Loaded stretch parameters from ^1s //\n" m_cMuscleBuilder.kLoadedStretchParametersFromMuscleStretch;
displayString -replace -value "Muscle Builder" m_cMuscleBuilder.kMuscleBuilder;
displayString -replace -value "Muscle Builder: Warning" m_cMuscleBuilder.kMuscleBuilderWarning;
displayString -replace -value "Muscle Object Settings" m_cMuscleBuilder.kMuscleObjectSettings;
displayString -replace -value "Muscle Parameters" m_cMuscleBuilder.kMuscleParameters;
displayString -replace -value "Muscle Spline Deformer" m_cMuscleBuilder.kMuscleSplineDeformer;
displayString -replace -value "Muscle Stretch" m_cMuscleBuilder.kMuscleStretch;
displayString -replace -value "You must load the Maya Muscle plug-in first." m_cMuscleBuilder.kMustLoadMusclePlugin;
displayString -replace -value "nSeg:" m_cMuscleBuilder.kNSeg;
displayString -replace -value "nSegs:" m_cMuscleBuilder.kNSegs;
displayString -replace -value "nSides:" m_cMuscleBuilder.kNSides;
displayString -replace -value "nSpans:" m_cMuscleBuilder.kNSpans;
displayString -replace -value "Neg X-Axis" m_cMuscleBuilder.kNegXAxis;
displayString -replace -value "Neg Y-Axis" m_cMuscleBuilder.kNegYAxis;
displayString -replace -value "Neg Z-Axis" m_cMuscleBuilder.kNegZAxis;
displayString -replace -value "None" m_cMuscleBuilder.kNone;
displayString -replace -value "Num Controls" m_cMuscleBuilder.kNumControls;
displayString -replace -value "OK" m_cMuscleBuilder.kOK;
displayString -replace -value "Off. X:" m_cMuscleBuilder.kOffX;
displayString -replace -value "Off. Z:" m_cMuscleBuilder.kOffZ;
displayString -replace -value "// Pasting ^1s //\n" m_cMuscleBuilder.kPastingMessage;
displayString -replace -value "Radius:" m_cMuscleBuilder.kRadius;
displayString -replace -value "Realtime Update" m_cMuscleBuilder.kRealtimeUpdate;
displayString -replace -value "Replace:" m_cMuscleBuilder.kReplace;
displayString -replace -value "Reverse Normals" m_cMuscleBuilder.kReverseNormals;
displayString -replace -value "Search:" m_cMuscleBuilder.kSearch;
displayString -replace -value "*None*" m_cMuscleBuilder.kSearchNone;
displayString -replace -value "// Set jiggle parameters for ^1s //\n" m_cMuscleBuilder.kSetJiggleParametersForMuscleSplineDeformer;
displayString -replace -value "// Set jiggle parameters for ^1s //\n" m_cMuscleBuilder.kSetJiggleParametersForMuscleStretch;
displayString -replace -value "// Set stretch parameters for ^1s //\n" m_cMuscleBuilder.kSetStretchParametersForMuscleSplineDeformer;
displayString -replace -value "// Set stretch parameters for ^1s //\n" m_cMuscleBuilder.kSetStretchParametersForMuscleStretch;
displayString -replace -value "// Setting length data for ^1s //\n" m_cMuscleBuilder.kSettingLengthDataForSpline;
displayString -replace -value "Shaded:" m_cMuscleBuilder.kShaded;
displayString -replace -value "shaded" m_cMuscleBuilder.kShadedShaded;
displayString -replace -value "wireframe-and-shaded" m_cMuscleBuilder.kShadedWireframeAndShaded;
displayString -replace -value "wireframe-only" m_cMuscleBuilder.kShadedWireframeOnly;
displayString -replace -value "Spline Length Settings" m_cMuscleBuilder.kSplineLengthSettings;
displayString -replace -value "Set Current as Default" m_cMuscleBuilder.kSplineSetCurrentAsDefault;
displayString -replace -value "Sets the current length of the spline deformer as it's default length." m_cMuscleBuilder.kSplineSetCurrentAsDefaultAnnot;
displayString -replace -value "Set Current as Squash" m_cMuscleBuilder.kSplineSetCurrentAsSquash;
displayString -replace -value "Sets the current length of the spline deformer as it's min squash length." m_cMuscleBuilder.kSplineSetCurrentAsSquashAnnot;
displayString -replace -value "Set Current as Stretch" m_cMuscleBuilder.kSplineSetCurrentAsStretch;
displayString -replace -value "Sets the current length of the spline deformer as it's max stretch length." m_cMuscleBuilder.kSplineSetCurrentAsStretchAnnot;
displayString -replace -value "Sticky Strength:" m_cMuscleBuilder.kStickyStrength;
displayString -replace -value "aimEnd:" m_cMuscleBuilder.kStretchAimEnd;
displayString -replace -value "aimStart:" m_cMuscleBuilder.kStretchAimStart;
displayString -replace -value "Apply Stretch Values" m_cMuscleBuilder.kStretchApplyStretchValues;
displayString -replace -value "Applies the given settings to the selected muscle objects." m_cMuscleBuilder.kStretchApplyStretchValuesAnnot;
displayString -replace -value "Default" m_cMuscleBuilder.kStretchDefault;
displayString -replace -value "Set stretch parameters." m_cMuscleBuilder.kStretchDefaultAnnot;
displayString -replace -value "END" m_cMuscleBuilder.kStretchEnd;
displayString -replace -value "Large" m_cMuscleBuilder.kStretchLarge;
displayString -replace -value "Set stretch parameters." m_cMuscleBuilder.kStretchLargeAnnot;
displayString -replace -value "Load Selected" m_cMuscleBuilder.kStretchLoadSelected;
displayString -replace -value "Loads the given values from the selected muscle objects." m_cMuscleBuilder.kStretchLoadSelectedAnnot;
displayString -replace -value "Medium" m_cMuscleBuilder.kStretchMedium;
displayString -replace -value "Set stretch parameters." m_cMuscleBuilder.kStretchMediumAnnot;
displayString -replace -value "MID" m_cMuscleBuilder.kStretchMid;
displayString -replace -value "Small" m_cMuscleBuilder.kStretchSmall;
displayString -replace -value "Set stretch parameters." m_cMuscleBuilder.kStretchSmallAnnot;
displayString -replace -value "Squash-X:  " m_cMuscleBuilder.kStretchSquashX;
displayString -replace -value "Squash-Z:  " m_cMuscleBuilder.kStretchSquashZ;
displayString -replace -value "START" m_cMuscleBuilder.kStretchStart;
displayString -replace -value "Stretch-X:  " m_cMuscleBuilder.kStretchStretchX;
displayString -replace -value "Stretch-Z:  " m_cMuscleBuilder.kStretchStretchZ;
displayString -replace -value "Up Axis:" m_cMuscleBuilder.kStretchUpAxis;
displayString -replace -value "Stretch Volume Presets" m_cMuscleBuilder.kStretchVolumePresets;
displayString -replace -value "X-Axis" m_cMuscleBuilder.kStretchXAxis;
displayString -replace -value "Z-Axis" m_cMuscleBuilder.kStretchZAxis;
displayString -replace -value "WARNING:  This operation will finalize model changes.\n\n    You will NOT be able to modify cross sections once done.\n    However you can always directly adjust the model with regular Maya tools.\n\nWould you like to finalize the model and apply the muscle deformer and muscle object conversion?\nIf so, please enter a new muscle NAME:" m_cMuscleBuilder.kThisOperationWillFinalizeModelChanges;
displayString -replace -value "Type:" m_cMuscleBuilder.kType;
displayString -replace -value "Width:" m_cMuscleBuilder.kWidth;
displayString -replace -value "X" m_cMuscleBuilder.kX;
displayString -replace -value "X-Axis" m_cMuscleBuilder.kXAxis;
displayString -replace -value "Y" m_cMuscleBuilder.kY;
displayString -replace -value "Y-Axis" m_cMuscleBuilder.kYAxis;
displayString -replace -value "Z" m_cMuscleBuilder.kZ;
displayString -replace -value "Z-Axis" m_cMuscleBuilder.kZAxis;
