// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "// Copy-Paste done. //\n" m_cMuscleCreatorUI.kCopyPasteDone;
displayString -replace -value "Copy/Paste" m_cMuscleCreatorUI.kCopyPasteFrame;
displayString -replace -value "Copy First Selected Muscle, Paste to Other Selected Muscles" m_cMuscleCreatorUI.kCopyPasteFrameCopyPaste;
displayString -replace -value "Copy-Paste Muscle Creator data" m_cMuscleCreatorUI.kCopyPasteFrameCopyPasteAnnot;
displayString -replace -value "Create" m_cMuscleCreatorUI.kCreateTab;
displayString -replace -value "Attach End:" m_cMuscleCreatorUI.kCreateTabAttachEnd;
displayString -replace -value "Attach Start:" m_cMuscleCreatorUI.kCreateTabAttachStart;
displayString -replace -value "Create Muscle" m_cMuscleCreatorUI.kCreateTabCreateMuscle;
displayString -replace -value "Create muscle" m_cMuscleCreatorUI.kCreateTabCreateMuscleAnnot;
displayString -replace -value "Create cMuscleObject shape node" m_cMuscleCreatorUI.kCreateTabCreateMuscleObjectShape;
displayString -replace -value "Create a cMuscleObject shape node along with the NURBs muscle so that it can be connected into a cMuscleSystem deformer." m_cMuscleCreatorUI.kCreateTabCreateMuscleObjectShapeAnnot;
displayString -replace -value "Load selected object." m_cMuscleCreatorUI.kCreateTabLoadSelectedObject;
displayString -replace -value "Load selected object." m_cMuscleCreatorUI.kCreateTabLoadSelectedObject2;
displayString -replace -value "Muscle Name:" m_cMuscleCreatorUI.kCreateTabMuscleName;
displayString -replace -value "Num. Controls / Cross Sections:" m_cMuscleCreatorUI.kCreateTabNumControlsCrossSections;
displayString -replace -value "Num. Segments Around:" m_cMuscleCreatorUI.kCreateTabNumSegments;
displayString -replace -value "Attach Locs" m_cMuscleCreatorUI.kCreatorAttachLocs;
displayString -replace -value "Attach Rest" m_cMuscleCreatorUI.kCreatorAttachRest;
displayString -replace -value "Attach Squash" m_cMuscleCreatorUI.kCreatorAttachSquash;
displayString -replace -value "Attach Stretch" m_cMuscleCreatorUI.kCreatorAttachStretch;
displayString -replace -value "CSect Rest" m_cMuscleCreatorUI.kCreatorCSestRest;
displayString -replace -value "CSect Squash" m_cMuscleCreatorUI.kCreatorCSestSquash;
displayString -replace -value "CSect Stretch" m_cMuscleCreatorUI.kCreatorCSestStretch;
displayString -replace -value "Controls" m_cMuscleCreatorUI.kCreatorContols;
displayString -replace -value "Hide" m_cMuscleCreatorUI.kCreatorHide;
displayString -replace -value "Select Creator(s)" m_cMuscleCreatorUI.kCreatorSelectCreator;
displayString -replace -value "Show" m_cMuscleCreatorUI.kCreatorShow;
displayString -replace -value "Edit" m_cMuscleCreatorUI.kEdit;
displayString -replace -value "Creator: " m_cMuscleCreatorUI.kEditTabCreator;
displayString -replace -value "Grow" m_cMuscleCreatorUI.kGrowFrame;
displayString -replace -value "Angle:" m_cMuscleCreatorUI.kGrowFrameAngle;
displayString -replace -value "Fat:" m_cMuscleCreatorUI.kGrowFrameFat;
displayString -replace -value "Grow Muscle" m_cMuscleCreatorUI.kGrowFrameGrowMuscle;
displayString -replace -value "Grow selected muscle" m_cMuscleCreatorUI.kGrowFrameGrowMuscleAnnot;
displayString -replace -value "Grow Sel Points" m_cMuscleCreatorUI.kGrowFrameGrowSelPoints;
displayString -replace -value "Grow selected points" m_cMuscleCreatorUI.kGrowFrameGrowSelPointsAnnot;
displayString -replace -value "Grow To Surface:" m_cMuscleCreatorUI.kGrowFrameGrowSurface;
displayString -replace -value "Surface muscle will grow to" m_cMuscleCreatorUI.kGrowFrameGrowSurfaceAnnot;
displayString -replace -value "Main Bone:" m_cMuscleCreatorUI.kGrowFrameMainBone;
displayString -replace -value "The main bone is used to determine how the muscle can grow" m_cMuscleCreatorUI.kGrowFrameMainBoneAnnot;
displayString -replace -value "Main BoneTip:" m_cMuscleCreatorUI.kGrowFrameMainBoneTip;
displayString -replace -value "The main bone is used to determine how the muscle can grow" m_cMuscleCreatorUI.kGrowFrameMainBoneTipAnnot;
displayString -replace -value "% Rest:" m_cMuscleCreatorUI.kGrowFrameRest;
displayString -replace -value "Select the main bone this muscle is related to." m_cMuscleCreatorUI.kGrowFrameSelectMainBone;
displayString -replace -value "Select the main bone this muscle is related to." m_cMuscleCreatorUI.kGrowFrameSelectMainBoneTip;
displayString -replace -value "Select surface for muscle growth" m_cMuscleCreatorUI.kGrowFrameSelectSurface;
displayString -replace -value "Sq:" m_cMuscleCreatorUI.kGrowFrameSq;
displayString -replace -value "St:" m_cMuscleCreatorUI.kGrowFrameSt;
displayString -replace -value "Reset to Cyl" m_cMuscleCreatorUI.kGrwFrameResetToCyl;
displayString -replace -value "Reset muscle to a simply cylindrical shape" m_cMuscleCreatorUI.kGrwFrameResetToCylAnnot;
displayString -replace -value "Mirror" m_cMuscleCreatorUI.kMirrorFrame;
displayString -replace -value "Mirror Axis: " m_cMuscleCreatorUI.kMirrorFrameMirrorAxis;
displayString -replace -value "Creates a mirrored muscle copied from the selection based on naming." m_cMuscleCreatorUI.kMirrorFrameMirrorMuscleFromSelctionAnnot;
displayString -replace -value "Mirror Muscle from Selection" m_cMuscleCreatorUI.kMirrorFrameMirrorMuscleFromSelection;
displayString -replace -value "Replace:" m_cMuscleCreatorUI.kMirrorFrameReplace;
displayString -replace -value "Search:" m_cMuscleCreatorUI.kMirrorFrameSearch;
displayString -replace -value "X" m_cMuscleCreatorUI.kMirrorFrameX;
displayString -replace -value "Y" m_cMuscleCreatorUI.kMirrorFrameY;
displayString -replace -value "Z" m_cMuscleCreatorUI.kMirrorFrameZ;
displayString -replace -value "// Mirroring ^1s BASE NAME=^2s //\n" m_cMuscleCreatorUI.kMirroringCreator;
displayString -replace -value "A replace string must be provided when mirroring muscles" m_cMuscleCreatorUI.kMirroringEmptyReplaceString;
displayString -replace -value "A search string must be provided when mirroring muscles" m_cMuscleCreatorUI.kMirroringEmptySearchString;
displayString -replace -value "The search string ^1s was not found in the locator ^2s\n" m_cMuscleCreatorUI.kMirroringSearchStringNotFound;
displayString -replace -value "A muscle with that name already exists in the system.  Please change the name and try again." m_cMuscleCreatorUI.kMuscleAlreadyExists;
displayString -replace -value "Muscle Creator" m_cMuscleCreatorUI.kMuscleCreator;
displayString -replace -value "You must load the Maya Muscle plug-in first." m_cMuscleCreatorUI.kMustLoadMusclePlugin;
displayString -replace -value "Poses" m_cMuscleCreatorUI.kPosesFrame;
displayString -replace -value "Reset Width" m_cMuscleCreatorUI.kPosesFrameResetWidth;
displayString -replace -value "Set current start/end locators as default width" m_cMuscleCreatorUI.kPosesFrameResetWidthAnnot;
displayString -replace -value "Rest" m_cMuscleCreatorUI.kPosesFrameRest;
displayString -replace -value "Set current pose as Rest" m_cMuscleCreatorUI.kPosesFrameRestAnnot;
displayString -replace -value "Set Current State As:" m_cMuscleCreatorUI.kPosesFrameSetState;
displayString -replace -value "Squash" m_cMuscleCreatorUI.kPosesFrameSquash;
displayString -replace -value "Set current pose as Squash" m_cMuscleCreatorUI.kPosesFrameSquashAnnot;
displayString -replace -value "Stretch" m_cMuscleCreatorUI.kPosesFrameStretch;
displayString -replace -value "Set current pose as Stretch" m_cMuscleCreatorUI.kPosesFrameStretchAnnot;
displayString -replace -value "Sculpting" m_cMuscleCreatorUI.kSculptingFrame;
displayString -replace -value "Affect:" m_cMuscleCreatorUI.kSculptingFrameAffect;
displayString -replace -value "X" m_cMuscleCreatorUI.kSculptingFrameAffectX;
displayString -replace -value "Affect X Axis" m_cMuscleCreatorUI.kSculptingFrameAffectXAnnot;
displayString -replace -value "Falloff:" m_cMuscleCreatorUI.kSculptingFrameFalloff;
displayString -replace -value "Location:" m_cMuscleCreatorUI.kSculptingFrameLocation;
displayString -replace -value "Rest" m_cMuscleCreatorUI.kSculptingFrameRest;
displayString -replace -value "Affect Rest Cross Sections" m_cMuscleCreatorUI.kSculptingFrameRestAnnot;
displayString -replace -value "Sculpt:" m_cMuscleCreatorUI.kSculptingFrameSculpt;
displayString -replace -value "Sq" m_cMuscleCreatorUI.kSculptingFrameSq;
displayString -replace -value "Affect Squash Cross Sections" m_cMuscleCreatorUI.kSculptingFrameSqAnnot;
displayString -replace -value "St" m_cMuscleCreatorUI.kSculptingFrameSt;
displayString -replace -value "Affect Stretch Cross Sections" m_cMuscleCreatorUI.kSculptingFrameStAnnot;
displayString -replace -value "Strength:" m_cMuscleCreatorUI.kSculptingFrameStrength;
displayString -replace -value "Y" m_cMuscleCreatorUI.kSculptingFrameY;
displayString -replace -value "Affect Y Axis" m_cMuscleCreatorUI.kSculptingFrameYAnnot;
displayString -replace -value "Z" m_cMuscleCreatorUI.kSculptingFrameZ;
displayString -replace -value "Affect Z Axis" m_cMuscleCreatorUI.kSculptingFrameZAnnot;
displayString -replace -value "*None*" m_cMuscleCreatorUI.kSearchNone;
displayString -replace -value "// Set pose as ^1s. //\n" m_cMuscleCreatorUI.kSetPoseAs;
