#!/usr/bin/python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\transfer\to_monty\the_LATEST\latest_MAYA\maya_SCRIPTS\pickrunner\view\basegui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

try:
    import PyQt4.QtCore as QtCore
    import PyQt4.QtGui as QtGui
except ImportError:    
    import PySide.QtCore as QtCore
    import PySide.QtGui as QtGui
except:
    raise

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(632, 566)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.buttonView_tp = QtGui.QWidget()
        self.buttonView_tp.setObjectName(_fromUtf8("buttonView_tp"))
        self.gridLayout_3 = QtGui.QGridLayout(self.buttonView_tp)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.selection_gridLayout = QtGui.QGridLayout()
        self.selection_gridLayout.setObjectName(_fromUtf8("selection_gridLayout"))
        self.left_pb = QtGui.QPushButton(self.buttonView_tp)
        self.left_pb.setObjectName(_fromUtf8("left_pb"))
        self.selection_gridLayout.addWidget(self.left_pb, 2, 0, 1, 1)
        self.right_pb = QtGui.QPushButton(self.buttonView_tp)
        self.right_pb.setObjectName(_fromUtf8("right_pb"))
        self.selection_gridLayout.addWidget(self.right_pb, 2, 2, 1, 1)
        self.up_pb = QtGui.QPushButton(self.buttonView_tp)
        self.up_pb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.up_pb.setObjectName(_fromUtf8("up_pb"))
        self.selection_gridLayout.addWidget(self.up_pb, 1, 1, 1, 1)
        self.down_pb = QtGui.QPushButton(self.buttonView_tp)
        self.down_pb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.down_pb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.down_pb.setObjectName(_fromUtf8("down_pb"))
        self.selection_gridLayout.addWidget(self.down_pb, 3, 1, 1, 1)
        self.loadSelection_pb = QtGui.QPushButton(self.buttonView_tp)
        self.loadSelection_pb.setStyleSheet(_fromUtf8("background-color: gray;"))
        self.loadSelection_pb.setObjectName(_fromUtf8("loadSelection_pb"))
        self.selection_gridLayout.addWidget(self.loadSelection_pb, 2, 1, 1, 1)
        self.assignLayout_pb = QtGui.QPushButton(self.buttonView_tp)
        self.assignLayout_pb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.assignLayout_pb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.assignLayout_pb.setStyleSheet(_fromUtf8("background-color: #ffcccc;"))
        self.assignLayout_pb.setObjectName(_fromUtf8("assignLayout_pb"))
        self.selection_gridLayout.addWidget(self.assignLayout_pb, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.selection_gridLayout, 3, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 3, 1, 1)
        self.currentObjPickwalkRules_l = QtGui.QLabel(self.buttonView_tp)
        self.currentObjPickwalkRules_l.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Minion Pro SmBd"))
        font.setPointSize(14)
        self.currentObjPickwalkRules_l.setFont(font)
        self.currentObjPickwalkRules_l.setAlignment(QtCore.Qt.AlignCenter)
        self.currentObjPickwalkRules_l.setObjectName(_fromUtf8("currentObjPickwalkRules_l"))
        self.gridLayout_3.addWidget(self.currentObjPickwalkRules_l, 5, 1, 1, 2)
        self.left_l = QtGui.QLabel(self.buttonView_tp)
        self.left_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.left_l.setObjectName(_fromUtf8("left_l"))
        self.gridLayout_3.addWidget(self.left_l, 8, 0, 1, 1)
        self.down_l = QtGui.QLabel(self.buttonView_tp)
        self.down_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.down_l.setObjectName(_fromUtf8("down_l"))
        self.gridLayout_3.addWidget(self.down_l, 7, 0, 1, 1)
        self.up_l = QtGui.QLabel(self.buttonView_tp)
        self.up_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.up_l.setObjectName(_fromUtf8("up_l"))
        self.gridLayout_3.addWidget(self.up_l, 6, 0, 1, 1)
        self.down_le = QtGui.QLineEdit(self.buttonView_tp)
        self.down_le.setObjectName(_fromUtf8("down_le"))
        self.gridLayout_3.addWidget(self.down_le, 7, 1, 1, 2)
        self.right_l = QtGui.QLabel(self.buttonView_tp)
        self.right_l.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.right_l.setObjectName(_fromUtf8("right_l"))
        self.gridLayout_3.addWidget(self.right_l, 9, 0, 1, 1)
        self.right_le = QtGui.QLineEdit(self.buttonView_tp)
        self.right_le.setObjectName(_fromUtf8("right_le"))
        self.gridLayout_3.addWidget(self.right_le, 9, 1, 1, 2)
        self.left_le = QtGui.QLineEdit(self.buttonView_tp)
        self.left_le.setObjectName(_fromUtf8("left_le"))
        self.gridLayout_3.addWidget(self.left_le, 8, 1, 1, 2)
        self.appTitle_l = QtGui.QLabel(self.buttonView_tp)
        self.appTitle_l.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Minion Pro SmBd"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.appTitle_l.setFont(font)
        self.appTitle_l.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitle_l.setObjectName(_fromUtf8("appTitle_l"))
        self.gridLayout_3.addWidget(self.appTitle_l, 0, 1, 1, 2)
        self.up_le = QtGui.QLineEdit(self.buttonView_tp)
        self.up_le.setObjectName(_fromUtf8("up_le"))
        self.gridLayout_3.addWidget(self.up_le, 6, 1, 1, 2)
        self.appSubtitle_l = QtGui.QLabel(self.buttonView_tp)
        self.appSubtitle_l.setAlignment(QtCore.Qt.AlignCenter)
        self.appSubtitle_l.setObjectName(_fromUtf8("appSubtitle_l"))
        self.gridLayout_3.addWidget(self.appSubtitle_l, 1, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(10, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 10, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 4, 1, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(278, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem4, 2, 1, 1, 2)
        self.tabWidget.addTab(self.buttonView_tp, _fromUtf8(""))
        self.allView_tp = QtGui.QWidget()
        self.allView_tp.setObjectName(_fromUtf8("allView_tp"))
        self.gridLayout_5 = QtGui.QGridLayout(self.allView_tp)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.connectionTree_gridLayout = QtGui.QGridLayout()
        self.connectionTree_gridLayout.setObjectName(_fromUtf8("connectionTree_gridLayout"))
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.connectionTree_gridLayout.addItem(spacerItem5, 3, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.connectionTree_gridLayout.addItem(spacerItem6, 2, 1, 1, 1)
        self.treeView_tw = QtGui.QTreeView(self.allView_tp)
        self.treeView_tw.setObjectName(_fromUtf8("treeView_tw"))
        self.connectionTree_gridLayout.addWidget(self.treeView_tw, 1, 0, 7, 1)
        self.add_pb = QtGui.QPushButton(self.allView_tp)
        self.add_pb.setObjectName(_fromUtf8("add_pb"))
        self.connectionTree_gridLayout.addWidget(self.add_pb, 1, 2, 1, 1)
        self.moveUp_pb = QtGui.QPushButton(self.allView_tp)
        self.moveUp_pb.setObjectName(_fromUtf8("moveUp_pb"))
        self.connectionTree_gridLayout.addWidget(self.moveUp_pb, 4, 2, 1, 1)
        self.delete_pb = QtGui.QPushButton(self.allView_tp)
        self.delete_pb.setObjectName(_fromUtf8("delete_pb"))
        self.connectionTree_gridLayout.addWidget(self.delete_pb, 2, 2, 1, 1)
        self.moveDown_pb = QtGui.QPushButton(self.allView_tp)
        self.moveDown_pb.setObjectName(_fromUtf8("moveDown_pb"))
        self.connectionTree_gridLayout.addWidget(self.moveDown_pb, 5, 2, 1, 1)
        self.existingSceneConnections_l = QtGui.QLabel(self.allView_tp)
        self.existingSceneConnections_l.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Minion Pro SmBd"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.existingSceneConnections_l.setFont(font)
        self.existingSceneConnections_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.existingSceneConnections_l.setAlignment(QtCore.Qt.AlignCenter)
        self.existingSceneConnections_l.setObjectName(_fromUtf8("existingSceneConnections_l"))
        self.connectionTree_gridLayout.addWidget(self.existingSceneConnections_l, 0, 0, 1, 1)
        self.moveRight_pb = QtGui.QPushButton(self.allView_tp)
        self.moveRight_pb.setObjectName(_fromUtf8("moveRight_pb"))
        self.connectionTree_gridLayout.addWidget(self.moveRight_pb, 7, 2, 1, 1)
        self.moveLeft_pb = QtGui.QPushButton(self.allView_tp)
        self.moveLeft_pb.setObjectName(_fromUtf8("moveLeft_pb"))
        self.connectionTree_gridLayout.addWidget(self.moveLeft_pb, 6, 2, 1, 1)
        self.connectionTree_gridLayout.setColumnStretch(0, 1)
        self.gridLayout_5.addLayout(self.connectionTree_gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.allView_tp, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.left_pb.setText(_translate("MainWindow", "Left", None))
        self.right_pb.setText(_translate("MainWindow", "Right", None))
        self.up_pb.setText(_translate("MainWindow", "Up", None))
        self.down_pb.setText(_translate("MainWindow", "Down", None))
        self.loadSelection_pb.setText(_translate("MainWindow", "Load Selection", None))
        self.assignLayout_pb.setText(_translate("MainWindow", " +/- Pickwalk", None))
        self.currentObjPickwalkRules_l.setText(_translate("MainWindow", "Current Object\'s Pickwalk Rules", None))
        self.left_l.setText(_translate("MainWindow", "Left", None))
        self.down_l.setText(_translate("MainWindow", "Down", None))
        self.up_l.setText(_translate("MainWindow", "Up", None))
        self.right_l.setText(_translate("MainWindow", "Right", None))
        self.appTitle_l.setText(_translate("MainWindow", "Pickrunner Selection/Assignment", None))
        self.appSubtitle_l.setText(_translate("MainWindow", "By Colin Kennedy v1.0.0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buttonView_tp), _translate("MainWindow", "Button View", None))
        self.add_pb.setText(_translate("MainWindow", "Add", None))
        self.moveUp_pb.setText(_translate("MainWindow", "Move Up", None))
        self.delete_pb.setText(_translate("MainWindow", "Delete", None))
        self.moveDown_pb.setText(_translate("MainWindow", "Move Down", None))
        self.existingSceneConnections_l.setText(_translate("MainWindow", "Existing Scene Connections", None))
        self.moveRight_pb.setText(_translate("MainWindow", "Move Right", None))
        self.moveLeft_pb.setText(_translate("MainWindow", "Move Left", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.allView_tp), _translate("MainWindow", "All View", None))