/**
 * @file AExgmSuppressTransform.mel
 * @brief Contains attribute editor ui control
 *
 * <b>CONFIDENTIAL INFORMATION: This software is the confidential and
 * proprietary information of Walt Disney Animation Studios ("WDAS").
 * This software may not be used, disclosed, reproduced or distributed
 * for any purpose without prior written authorization and license
 * from WDAS. Reproduction of any section of this software must include
 * this legend and all copyright notices.
 * Copyright Disney Enterprises, Inc. All rights reserved.</b>
 *
 * @author Lawrence Chai
 * @author Thomas V Thompson II
 *
 * @version Created 09/15/06
 */

global proc AExgmSuppressTransform()
{
    editorTemplate -suppress "caching";
    editorTemplate -suppress "nodeState";
    editorTemplate -suppress "visibility";
    editorTemplate -suppress "intermediateObject";
    editorTemplate -suppress "template";
    editorTemplate -suppress "ghosting";
    editorTemplate -suppress "instObjGroups";
    editorTemplate -suppress "useObjectColor";
    editorTemplate -suppress "objectColor";
    editorTemplate -suppress "drawOverride";
    editorTemplate -suppress "lodVisibility";
    editorTemplate -suppress "renderInfo";
    editorTemplate -suppress "renderLayerInfo";
    editorTemplate -suppress "ghostingControl";
    editorTemplate -suppress "ghostCustomSteps";
    editorTemplate -suppress "ghostFrames";
    editorTemplate -suppress "ghostRangeStart";
    editorTemplate -suppress "ghostRangeEnd";
    editorTemplate -suppress "ghostDriver";
    editorTemplate -suppress "translate";
    editorTemplate -suppress "rotate";
    editorTemplate -suppress "rotateOrder";
    editorTemplate -suppress "scale";
    editorTemplate -suppress "shear";
    editorTemplate -suppress "rotatePivot";
    editorTemplate -suppress "rotatePivotTranslate";
    editorTemplate -suppress "scalePivot";
    editorTemplate -suppress "scalePivotTranslate";
    editorTemplate -suppress "rotateAxis";
    editorTemplate -suppress "minTransLimit";
    editorTemplate -suppress "maxTransLimit";
    editorTemplate -suppress "minTransLimitEnable";
    editorTemplate -suppress "maxTransLimitEnable";
    editorTemplate -suppress "minRotLimit";
    editorTemplate -suppress "maxRotLimit";
    editorTemplate -suppress "minRotLimitEnable";
    editorTemplate -suppress "maxRotLimitEnable";
    editorTemplate -suppress "minScaleLimit";
    editorTemplate -suppress "maxScaleLimit";
    editorTemplate -suppress "minScaleLimitEnable";
    editorTemplate -suppress "maxScaleLimitEnable";
    editorTemplate -suppress "geometry";
    editorTemplate -suppress "selectHandle";
    editorTemplate -suppress "inheritsTransform";
    editorTemplate -suppress "displayHandle";
    editorTemplate -suppress "displayScalePivot";
    editorTemplate -suppress "displayRotatePivot";
    editorTemplate -suppress "displayLocalAxis";
    editorTemplate -suppress "dynamics";
    editorTemplate -suppress "showManipDefault";
    editorTemplate -suppress "rotateQuaternion";
    editorTemplate -suppress "mentalRayControls";
    editorTemplate -suppress "rotateAxis";
}
