displayString -replace -value "Copy" m_xgmCopyCurvesTool.kCopy;
displayString -replace -value "Copy the selected curve." m_xgmCopyCurvesTool.kCopyAnn;
displayString -replace -value "No curves selected." m_xgmCopyCurvesTool.kNoCurvesSelected1;
displayString -replace -value "No curves selected." m_xgmCopyCurvesTool.kNoCurvesSelected2;
displayString -replace -value "Nothing copied so nothing to paste." m_xgmCopyCurvesTool.kNothingCopiedSoNothingToPaste;
displayString -replace -value "Paste" m_xgmCopyCurvesTool.kPaste;
displayString -replace -value "Paste onto the selected curves." m_xgmCopyCurvesTool.kPasteAnn;
displayString -replace -value "Unknown state: ^1s" m_xgmCopyCurvesTool.kUnknownState;
