/**
 * @file xgmFileBrowserUI.mel
 * @brief Contains a file browser UI for XGen
 *
 * <b>CONFIDENTIAL INFORMATION: This software is the confidential and
 * proprietary information of Walt Disney Animation Studios ("WDAS").
 * This software may not be used, disclosed, reproduced or distributed
 * for any purpose without prior written authorization and license
 * from WDAS. Reproduction of any section of this software must include
 * this legend and all copyright notices.
 * Copyright Disney Enterprises, Inc. All rights reserved.</b>
 *
 * @author Ying Liu
 * @author Thomas V Thompson II
 *
 * @version Created 07/28/09
 */


/**
 * The file browser interface in mel. 
 * This is a wrapper for the python version file browser.
 *
 * @param $startDir    The start directory to appear in the browser
 * @param $fileType    The type of files to filter on
 * @param $inOrOut     To indicate whether this is a read or write operation
 * 
 * @return The selected file/directory name from the browser    
 */
global proc string xgmFileBrowserUI( string $startDir, string $fileType, 
                                     string $inOrOut )
{
    string $selected = python( "xgui.widgets.fileBrowserDlg(None, \"" + 
                               $startDir + "\", \"" + $fileType + "\", \"" + 
                               $inOrOut + "\")" );
    return $selected;    
}
