// Copyright 2014 Autodesk, Inc. All rights reserved. 
//
// Use of this software is subject to the terms of the Autodesk 
// license agreement provided at the time of installation or download, 
// or which otherwise accompanies this software in either electronic 
// or hard copy form.


//  Description:	defines behaviour and layout of guideSculptContext
//					tool property sheet
//


global proc xgmGuideSculptProperties ()
//
//	Procedure Name:
//		xgmGuideSculptProperties
//
//	Description:
//		layout of tool property sheet
//
//	Input Arguments:
//		None.
//
//	Return Value:
//		None.
//
{
	string $curctx = `currentCtx`;

	string $parent = `toolPropertyWindow -q -location`;
    setParent $parent;

    setUITemplate -pushTemplate OptionsTemplate;
    
    columnLayout xgmGuideSculpt;
    frameLayout -collapsable true -collapse false -l (uiRes("m_xgmGuideSculptProperties.kGuideSculptOptions")) xgmGuideSculptFrame;
        columnLayout xgmGuideSculptOptions;
            separator -style "none";

            checkBoxGrp
                -label (uiRes("m_xgmGuideSculptProperties.kLockLength"))
                -numberOfCheckBoxes 1
                -l1 " "
                -on1 ("xgmGuideSculptContext -e -lockLength 1 `currentCtx`")
                -of1 ("xgmGuideSculptContext -e -lockLength 0 `currentCtx`")
                lockLengthGrp;
            
            string $curDesc		= (uiRes("m_xgmGuideSculptProperties.kCurrentDescription"));
            string $allDesc     = (uiRes("m_xgmGuideSculptProperties.kAllDescInCollection"));
            string $allCollections = (uiRes("m_xgmGuideSculptProperties.kAllCollections"));
            radioButtonGrp -nrb 3 -vertical
                -label (uiRes("m_xgmGuideSculptProperties.kAffects")) 
                -labelArray3 $curDesc $allDesc $allCollections
                -annotation (uiRes("m_xgmGuideSculptProperties.kSelectionMode"))
                -on1 ("xgmGuideSculptContext -e -affect 1 `currentCtx`")
                -on2 ("xgmGuideSculptContext -e -affect 2 `currentCtx`")
                -on3 ("xgmGuideSculptContext -e -affect 3 `currentCtx`")                
                affectsRbg;
            
            floatSliderGrp -field true -pre 3
                -min 0
                -max 1000
                -fieldMaxValue 1000
                -label (uiRes("m_xgmGuideSculptProperties.kBrushSize"))  
                -annotation (uiRes("m_xgmGuideSculptProperties.kBrushSizeAnnotation"))
                -cc ( ("xgmGuideSculptContext -e -size #1 " + $curctx) )
                    sculptGuidesBrushSizeFsg;

        setParent ..; // xgmGuideSculptOptions
    setParent ..; // xgmGuideSculptFrame
    
    setParent ..; // xgmGuideSculpt

    setUITemplate -popTemplate;
}
