/**
 * @file xgmPointMatrixMult.mel
 *
 * <b>CONFIDENTIAL INFORMATION: This software is the confidential and
 * proprietary information of Walt Disney Animation Studios ("WDAS").
 * This software may not be used, disclosed, reproduced or distributed
 * for any purpose without prior written authorization and license
 * from WDAS. Reproduction of any section of this software must include
 * this legend and all copyright notices.
 * Copyright Disney Enterprises, Inc. All rights reserved.</b>
 *
 * @author Stephen D. Bowline
 *
 * @version Created 08/30/04
 */


/**
 * Maya's pointMatrixMult would seem to apply to 'vectors' only and does
 * not perform the translation column of the matrix.  Here, we do our own
 * multiplication.
 */
global proc float[] xgmPointMatrixMult( float $pt[], float $x[] )
{
    float $result[3];

    $result[0] = $pt[0] * $x[0] + $pt[1] * $x[4] + $pt[2] * $x[8] + $x[12];
    $result[1] = $pt[0] * $x[1] + $pt[1] * $x[5] + $pt[2] * $x[9] + $x[13];
    $result[2] = $pt[0] * $x[2] + $pt[1] * $x[6] + $pt[2] * $x[10] + $x[14];

    return $result;
}
