#-
# ==========================================================================
# Copyright (c) 2012 Autodesk, Inc.
# All rights reserved.
# 
# These coded instructions, statements, and computer programs contain
# unpublished proprietary information written by Autodesk, Inc., and are
# protected by Federal copyright law. They may not be disclosed to third
# parties or copied or duplicated in any form, in whole or in part, without
# the prior written consent of Autodesk, Inc.
# ==========================================================================
#+

xgenSampleModules_EXTRA_INCLUDES = -I$(MAYA_LOCATION)/plug-ins/xgen/include
xgenSampleModules_EXTRA_LFLAGS   = -L$(MAYA_LOCATION)/plug-ins/xgen/lib
