//Maya Preference 2016 (Release 1)
//
//

nameCommand
	-annotation "HotLineCommand"
	-sourceType "python"
	-command ("HotLineCommand")
	HotLineCommand;

nameCommand
	-annotation "Select Circle Tool"
	-sourceType "mel"
	-command ("print \"YES\"")
	circleToolNamedCommand;

nameCommand
	-annotation "Hotkey Test"
	-sourceType "mel"
	-command ("python(\"testing()\")")
	hotkeyTest;

nameCommand
	-annotation "HotLineCommandNameCommand"
	-sourceType "mel"
	-command ("HotLineCommand")
	HotLineCommandNameCommand;

nameCommand
	-annotation "Replaces the {} hotkey to give priority to pickRunner before trying to pickWalk"
	-sourceType "mel"
	-command ("python(\"pickRun(right, 1)\")")
	hotkeyright;

nameCommand
	-annotation "Replaces the up hotkey to give priority to pickRunner before trying to pickWalk"
	-sourceType "mel"
	-command ("python(\"import pickrunner.pickrunner as pickrunner; pickrunner.pickRun(\\\"up\\\", 1)\")")
	hotkeyUp;

nameCommand
	-annotation "Replaces the down hotkey to give priority to pickRunner before trying to pickWalk"
	-sourceType "mel"
	-command ("python(\"import pickrunner.pickrunner as pickrunner; pickrunner.pickRun(\\\"down\\\", 1)\")")
	hotkeyDown;

nameCommand
	-annotation "Replaces the left hotkey to give priority to pickRunner before trying to pickWalk"
	-sourceType "mel"
	-command ("python(\"import pickrunner.pickrunner as pickrunner; pickrunner.pickRun(\\\"left\\\", 1)\")")
	hotkeyLeft;

nameCommand
	-annotation "Replaces the right hotkey to give priority to pickRunner before trying to pickWalk"
	-sourceType "mel"
	-command ("python(\"import pickrunner.pickrunner as pickrunner; pickrunner.pickRun(\\\"right\\\", 1)\")")
	hotkeyRight;

