// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Add" m_AniDeformationsMenu.kAdd;
displayString -replace -value "Select all target objects to add then select the base object" m_AniDeformationsMenu.kAddAnnot;
displayString -replace -value "Blend shape add options" m_AniDeformationsMenu.kAddOptionAnnot;
displayString -replace -value "Bake Topology To Targets" m_AniDeformationsMenu.kBakeTopologyToTargets;
displayString -replace -value "Select the base shape whose topology differences are to be baked to targets" m_AniDeformationsMenu.kBakeTopologyToTargetsAnnot;
displayString -replace -value "Blend shape options" m_AniDeformationsMenu.kBlendShapeOptionAnnot;
displayString -replace -value "Blend Shape" m_AniDeformationsMenu.kCreateBlendShape;
displayString -replace -value "Select one or more objects, with the base shape selected last" m_AniDeformationsMenu.kCreateBlendShapeAnnot;
displayString -replace -value "Lattice" m_AniDeformationsMenu.kCreateLattice;
displayString -replace -value "Select object(s)" m_AniDeformationsMenu.kCreateLatticeAnnot;
displayString -replace -value "Create" m_AniDeformationsMenu.kDeformationCreate;
displayString -replace -value "Edit" m_AniDeformationsMenu.kDeformationEdit;
displayString -replace -value "Blend Shape" m_AniDeformationsMenu.kEditBlendShape;
displayString -replace -value "Lattice" m_AniDeformationsMenu.kEditLattice;
displayString -replace -value "Edit Normalization Groups" m_AniDeformationsMenu.kEditNormalizationGroups;
displayString -replace -value "Set up normalization groups for the blend shape" m_AniDeformationsMenu.kEditNormalizationGroupsAnnot;
displayString -replace -value "Open Full Deform Menu ..." m_AniDeformationsMenu.kFullDeformationMenu;
displayString -replace -value "Show all available rigging deformers" m_AniDeformationsMenu.kFullDeformationMenuAnnot;
displayString -replace -value "Lattice options" m_AniDeformationsMenu.kLatticeOptionAnnot;
displayString -replace -value "Remove" m_AniDeformationsMenu.kRemove;
displayString -replace -value "Select the target objects to remove" m_AniDeformationsMenu.kRemoveAnnot;
displayString -replace -value "Remove Lattice Tweaks" m_AniDeformationsMenu.kRemoveLatticeTweaks;
displayString -replace -value "Select lattice" m_AniDeformationsMenu.kRemoveLatticeTweaksAnnot;
displayString -replace -value "Blend shape remove options" m_AniDeformationsMenu.kRemoveOptionAnnot;
displayString -replace -value "Reset Lattice" m_AniDeformationsMenu.kResetLattice;
displayString -replace -value "Select lattice" m_AniDeformationsMenu.kResetLatticeAnnot;
displayString -replace -value "Swap" m_AniDeformationsMenu.kSwap;
displayString -replace -value "Select two target objects whose order you want to swap" m_AniDeformationsMenu.kSwapAnnot;
displayString -replace -value "Blend shape swap options" m_AniDeformationsMenu.kSwapOptionAnnot;
