// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Set current character to ^1s" m_buildSetCharacterMenu.kCharSetAnnotFormat;
displayString -replace -value "Character Set Editor" m_buildSetCharacterMenu.kCharacterSets;
displayString -replace -value "Open character editor" m_buildSetCharacterMenu.kCharacterSetsAnnot;
displayString -replace -value "Multiple" m_buildSetCharacterMenu.kMultiple;
displayString -replace -value "Multiple current characters set from the character editor" m_buildSetCharacterMenu.kMultipleAnnot;
displayString -replace -value "None" m_buildSetCharacterMenu.kNone;
displayString -replace -value "Clear current character list" m_buildSetCharacterMenu.kNoneAnnot;
displayString -replace -value "Sub Character" m_buildSetCharacterMenu.kSubCharacter;
displayString -replace -value "Sub character set from the character editor" m_buildSetCharacterMenu.kSubCharacterAnnot;
