// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "All Curves" m_buildSelectObjectMM.kAllCurves;
displayString -replace -value "All Deformations" m_buildSelectObjectMM.kAllDeformations;
displayString -replace -value "All Dynamics" m_buildSelectObjectMM.kAllDynamics;
displayString -replace -value "All Handles" m_buildSelectObjectMM.kAllHandles;
displayString -replace -value "All Misc." m_buildSelectObjectMM.kAllMisc;
displayString -replace -value "All Objects off" m_buildSelectObjectMM.kAllObjectsOff;
displayString -replace -value "All Objects on" m_buildSelectObjectMM.kAllObjectsOn;
displayString -replace -value "All Rendering" m_buildSelectObjectMM.kAllRendering;
displayString -replace -value "All Surfaces" m_buildSelectObjectMM.kAllSurfaces;
displayString -replace -value "Cameras" m_buildSelectObjectMM.kCameras;
displayString -replace -value "Clusters" m_buildSelectObjectMM.kClusters;
displayString -replace -value "Curves" m_buildSelectObjectMM.kCurves;
displayString -replace -value "Curves On Surface" m_buildSelectObjectMM.kCurvesOnSurface;
displayString -replace -value "Deformations" m_buildSelectObjectMM.kDeformations;
displayString -replace -value "Dimensions" m_buildSelectObjectMM.kDimensions;
displayString -replace -value "Dynamic Constraints" m_buildSelectObjectMM.kDynamicConstraints;
displayString -replace -value "Dynamics" m_buildSelectObjectMM.kDynamics;
displayString -replace -value "Emitters" m_buildSelectObjectMM.kEmitters;
displayString -replace -value "Fields" m_buildSelectObjectMM.kFields;
displayString -replace -value "Fluids" m_buildSelectObjectMM.kFluids;
displayString -replace -value "Follicles" m_buildSelectObjectMM.kFollicles;
displayString -replace -value "Hair Systems" m_buildSelectObjectMM.kHairSystems;
displayString -replace -value "Handles" m_buildSelectObjectMM.kHandles;
displayString -replace -value "IK End Effectors" m_buildSelectObjectMM.kIKEndEffectors;
displayString -replace -value "IK Handles" m_buildSelectObjectMM.kIKHandles;
displayString -replace -value "Joints" m_buildSelectObjectMM.kJoints;
displayString -replace -value "Lattices" m_buildSelectObjectMM.kLattices;
displayString -replace -value "Lights" m_buildSelectObjectMM.kLights;
displayString -replace -value "Locators" m_buildSelectObjectMM.kLocators;
displayString -replace -value "Misc." m_buildSelectObjectMM.kMisc;
displayString -replace -value "More Dynamics" m_buildSelectObjectMM.kMoreDynamics;
displayString -replace -value "NCloths" m_buildSelectObjectMM.kNCloths;
displayString -replace -value "NRigids" m_buildSelectObjectMM.kNRigids;
displayString -replace -value "NURBS Curves" m_buildSelectObjectMM.kNURBSCurves;
displayString -replace -value "NURBS Surfaces" m_buildSelectObjectMM.kNURBSSurfaces;
displayString -replace -value "Nonlinears" m_buildSelectObjectMM.kNonlinears;
displayString -replace -value "Particles" m_buildSelectObjectMM.kParticles;
displayString -replace -value "Planes" m_buildSelectObjectMM.kPlanes;
displayString -replace -value "Poly Surfaces" m_buildSelectObjectMM.kPolySurfaces;
displayString -replace -value "Rendering" m_buildSelectObjectMM.kRendering;
displayString -replace -value "Rigid Bodies" m_buildSelectObjectMM.kRigidBodies;
displayString -replace -value "Rigid Constraints" m_buildSelectObjectMM.kRigidConstraints;
displayString -replace -value "Save to shelf" m_buildSelectObjectMM.kSaveToShelf;
displayString -replace -value "Sculpt Objects" m_buildSelectObjectMM.kSculptObjects;
displayString -replace -value "Select Components" m_buildSelectObjectMM.kSelectComponents;
displayString -replace -value "Selection Handles" m_buildSelectObjectMM.kSelectionHandles;
displayString -replace -value "Springs" m_buildSelectObjectMM.kSprings;
displayString -replace -value "Surfaces" m_buildSelectObjectMM.kSurfaces;
displayString -replace -value "Textures" m_buildSelectObjectMM.kTextures;
