// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date: Jan 2000
//
//	Description:
//  Converts version 2.80 preferences to version 2.81
//
{
	// Remove defunct optionVars that are not longer
	// used because of the preference window rewrite.
	//
	catch (
		`optionVar
			-remove generalPrefSaveOnQuit
			-remove selectPrefSaveOnQuit
			-remove displayPrefSaveOnQuit
			-remove manipPrefSaveOnQuit
			-remove modelPrefSaveOnQuit
			-remove animPrefSaveOnQuit
			-remove kinPrefSaveOnQuit
			-remove dynPrefSaveOnQuit
			-remove unitPrefSaveOnQuit
			-remove saveUIPrefOnExit
			-remove saveWindowPrefOnExit
			-remove saveLinesPrefOnExit
			-remove saveMiscUIPrefOnExit
			-remove saveShelfState
			-remove savePanelState`
	);

	// There were 2 of these defined for the same thing.
	// Keeping clickBoxSize and removing this one.
	//
	catch (`optionVar -remove clickBoxSelect`);

	// The main window and command window now have their
	// positions saved like any other window.  But we need
	// to set this from the old optionVars the first time.
	//
	// Note: We can't use $gMainWindow or $gCommandWindow
	// as they have not been set yet.
	//

	if (`optionVar -exists mainWindowTopPos`) {

		windowPref 
			-tlc `optionVar -q "mainWindowTopPos"` `optionVar -q "mainWindowLeftPos"`
			-wh  `optionVar -q "mainWindowWidth"`  `optionVar -q "mainWindowHeight"`
			MayaWindow;

		windowPref 
			-tlc `optionVar -q "cmdWindowTopPos"`  `optionVar -q "cmdWindowLeftPos"`
			-wh  `optionVar -q "cmdWindowWidth"`   `optionVar -q "cmdWindowHeight"`
			CommandWindow;

		optionVar
			-remove mainWindowTopPos
			-remove mainWindowLeftPos
			-remove mainWindowWidth
			-remove mainWindowHeight
			-remove cmdWindowTopPos
			-remove cmdWindowLeftPos
			-remove cmdWindowWidth
			-remove cmdWindowHeight;
	}
}

