// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// Description:
//
//		This script, when sourced, converts version 5.01 prefs to
//		version 2016 prefs.

{
	//	In 2016 the syntax of the font name name in the textCurvesFont
	//	optionVar changed, making the old names meaningless. So if that
	//	optionVar exists, delete it. It will be reset to the appropriate
	//	default the next time Maya needs it.
	//
	if (`optionVar -ex textCurvesFont`) {
		optionVar -rm textCurvesFont;
	}

	// In 2016, UV Texture Editor was renamed as UV Editor.
	// We need to rename a panel configs and update the 
	// pref newScenePaneConfiguration if it was set to Persp/UV Texture Editor
	string $panelConfigArray[] = `getPanel -allConfigs`;
	int $i;

	for ($i = 0; $i < size($panelConfigArray); $i++) {
		string $configLabel = 
			`panelConfiguration -query -label $panelConfigArray[$i]`;
		
		if ($configLabel == "Persp/UV Texture Editor") {
			// Rename the layout
			//
			panelConfiguration 
				-edit
				//UI strings for versions of Maya earlier than 8.5 should remain unlocalized.
				-label "Persp/UV Editor" 
				$panelConfigArray[$i];
		}

		string $panelLabels[] = `panelConfiguration -query -labelStrings $panelConfigArray[$i]`;

		int $panel;

		for ($panel = 0; $panel < size($panelLabels); $panel++) {
			if ($panelLabels[$panel] == "UV Texture Editor") {
				panelConfiguration -edit -replaceLabel $panel "UV Editor" $panelConfigArray[$i];
			}
		}
	}
	
	// we also need to change one perf - newScenePanelConfiguration
	// if this pref is set to "Persp/UV Texture Editor" in pre-2015, it will fail to load
	// we need to handle this case
	//
	if(`optionVar -q "newScenePanelConfiguration"` == "Persp/UV Texture Editor") {
		optionVar -sv "newScenePanelConfiguration" "Persp/UV Editor";
	}
}
