// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  Jan 2000
//
//  Description:
//
//	All optionVars that are used for preferences that appear
//	in the Preferences window MUST be set in this file.
//	Only optionVars used in the preference file should be
//	set in this file.  Others should be set in the
//	createGlobalOptVars.mel file.
//
//	This file is used to restore the preferences back to the
//	state they were in when Maya is first used.  (The "Restore
//  Default Settings" menu item.)
//
//  It is also used to set all of these preferences on startup
//	so you can use these values in any of the init* files
//	without having to check to see if they are set yet.
//
//	Note: If adding preferences, make sure to read
//	http://torw3/maya/TechDoc/CodingGuides/addingPreferences.html
//

proc setOptVarOfCustomTabToDefault()
{
	global string $gPrefsCustomTabSetOptVarToDefault[];

	string $setOptVarToDefaultFn;
	for($setOptVarToDefaultFn in $gPrefsCustomTabSetOptVarToDefault) {
		eval $setOptVarToDefaultFn;
	}
}

{

	//----------------------------------------------------------
	// Interface Preferences
	//----------------------------------------------------------

	optionVar
		-sv mayaMode "Animation";

	optionVar
		-iv "mainWindowMenubarVis" true
		-iv "collapseIconBarsInPanels" false
		-iv "allowMenusInPanels" true
		-iv "mainWindowTitleBarVis" true
		-iv "cmdWindowTitleBarVis" true
		-iv "commandLineHoldFocus" false
		-iv "showIconsInMenus" true
		-iv "saveWindowPos" true
		-sv "clDockWidgetArea" "right"
		-sv "cbDockWidgetArea" "right"
		-sv "leDockWidgetArea" "right"
		-iv "clInMainWindow" true
		-iv "cbInMainWindow" true
		-iv "leInMainWindow" true
		-iv "EEexprEdTextEditor" 1
		-iv "mayaMacButtonMap" 3;

	optionVar
		-iv displayNewFeatureHighlights true
		-iv showHighlightNewFeaturesWindowOnStartup true;
	if( `about -mac` ) {
		optionVar
			-fv newFeatureHighlightColor 0.173
			-fva newFeatureHighlightColor 0.702
			-fva newFeatureHighlightColor 0.145;
	} else {
		optionVar
			-fv newFeatureHighlightColor 0.082
			-fva newFeatureHighlightColor 1.0
			-fva newFeatureHighlightColor 0.035;
	}

	optionVar
		-iv useScrollWheel true;


	optionVar
		-iv interfaceScalingMode 0
		-fv interfaceScalingValue 1.0;

	//----------------------------------------------------------
	// UI Elements Preferences
	//----------------------------------------------------------

	optionVar
		 -iv "statusLineVisible" true
		 -iv "LastStateStatusLineVisibility" true
		 -iv "isShelfVisible" true
		 -iv "LastStateShelfVisibility" true
		 -iv "timeSliderVisible" true
		 -iv "LastStateTimeSliderVisibility" true
		 -iv "playbackRangeVisible" true
		 -iv "LastStatePlaybackRangeVisibility" true
		 -iv "commandLineVisible" true
		 -iv "LastStateCommandLineVisibility" true
		 -iv "helpLineVisible" true
		 -iv "LastStateHelpLineVisibility" true
		 -iv "isAttributeEditorVisible" false
		 -iv "toolSettingsVisible" false
		 -iv "channelsLayersSeparate" false
		 -iv "channelsLayersVisible" true
		 -iv "LastStateChannelsLayersVisibility" true
		 -iv "channelsVisible" false
		 -iv "LastStateToolboxVisibility" false
		 -iv "layersVisible" false
		 -iv "LastStateLayersVisibility" false
		 -iv "toolboxVisible" true
		 -iv "LastStateToolboxVisibility" true;

	//----------------------------------------------------------
	// Misc UI Preferences
	//----------------------------------------------------------

	optionVar
		-intValue "toolMessageVisible" true
		-floatValue "toolMessageTime" 0.7
		-intValue "toolMessageVerticalOffset" -40
		-intValue "toolMessageHorizontalOffset" 0;

	optionVar
		-iv "inViewMessageEnable" true
		-iv "inViewMessageAssistEnable" true
		-iv "inViewMessageStatusEnable" true
		-fv "inViewMessageDisplayTime" 2.0
		-iv "inViewMessageFontSize" 12
		-iv "inViewMessageOpacity" 75;

	global string $gMayaVersionYear;
	$gMayaVersionYear = endString( (string)(`about -p`), 4 );

	optionVar
		-iv "popUpHelpMode" true
		-iv "helpBrowserUseWindow" true
		-iv "helpBrowserRaiseWindow" true
		-sv "helpLanguage" `about -uiLanguage`
		-sv "helpMode" "Autodesk Web Site"
		-sv ("localHelpUrl" + $gMayaVersionYear) ""
		-sv ("customPathHelpUrl" + $gMayaVersionYear) "";

	optionVar
		-iv "popUpSimpleHelpMode" false ;

	optionVar
		 -sv "newScenePanelConfiguration" (localizedPanelLabel("Single Perspective View"))
		 -iv "useNewScenePanelConfig" true
		 -iv "useScenePanelConfig" true
		 -iv "useSaveScenePanelConfig" true
		 -iv "ResetModelViewsOnNewScene" true;

	optionVar
		-sv "interactionModeToSuite" "undefined";

	optionVar
		-iv "editorConnectionScanLimit" 500 ;

	optionVar
		-iv "ChannelBox_ClearSelectionOnObjectSelectionChange" 0 ;


	//----------------------------------------------------------
	// Display Preferences
	//----------------------------------------------------------

	optionVar
		-iv "fastInteraction" false
		-iv "showGrid" true
		-iv "activeObjectPivots" false
		-iv "displayAffected" true
		-iv "displayRegionOfEffect" true
		-iv "wireframeOnShadedActive" 1
		-iv "maxTextureResolution" 4096
		-iv "ghostFramesBefore" 3
		-iv "ghostFramesAfter" 3
		-iv "ghostFrameStep" 1
		-iv "shadeTemplates" false
		-iv "maxImageSizeForSwatchGen" 2000
		-iv "materialLoadingMode" 1
		-iv "displayViewportGradient" false
		-fv "lineWidth"	1.0;

	optionVar
		-iv "generateUVTilePreviewsOnSceneLoad" false;

	optionVar
		-iv enableSwatchRendering 1;


	optionVar
		-iv "viewportRenderer" 2;

	//HeadsUpDisplay Toggle Values

	optionVar
		-iv "animationDetailsVisibility" false
		-iv "fbikDetailsVisibility" false
		-iv "objectDetailsVisibility" false
		-iv "particleCountVisibility" false
		-iv "polyCountVisibility" false
		-iv "viewportRendererVisibility" false
		-iv "cameraNamesVisibility" true
		-iv "materialLoadingDetailsVisibility" false
		-iv "frameRateVisibility" false
		-iv "currentFrameVisibility" false
		-iv "evaluationVisibility" false
		-iv "sceneTimecodeVisibility" false
		-iv "viewAxisVisibility" true
		-iv "capsLockVisibility" true
		-iv "toggleOriginAxis" false;

	//Image Viewer Preferences
		optionVar
		-iv "fcheckAsImageViewer" true
		-sv "userDefinedImageViewerCmdForImage" ""
		-sv "userDefinedImageViewerCmdForSequence" "" ;

	//----------------------------------------------------------
	// Kin Display Preferences
	//----------------------------------------------------------

	optionVar
		-fv "ikHandleDisplayScale" 1.0
		-fv "ikJointDisplayScale" 1.0
		-fv "ikIkFkJointDisplayScale" 0.5
		-sv "ikIkFkDisplayMethod" "ikfk";

	//----------------------------------------------------------
	// Manip Display Preferences
	//----------------------------------------------------------

	optionVar
		-fv "manipGlobalScale" 1.5
		-fv "manipHandleSize" 35.0
		-fv "manipLinePickSize" 1.0
		-fv "manipLineSize" 1.0
		-fv "manipPreviousStateSize" 6.0;

	optionVar
		-iv defaultShowManipulator 6
		-iv "manipMiddleMouseRepos" false
        -iv "manipsRememberActiveHandle" true
        -iv "manipsRememberActiveHandleAfterToolSwitch" true
		-iv "manipShowPivotRotateHandle" 1
		-iv "manipPivotRotateHandleOffset" 50
		-iv "manipShowPlaneHandles" 1
		-iv "manipPlaneHandleOffset" 75;

	optionVar
		-iv manipHideOnCtrl 0
		-iv manipHideOnShift 0
		-iv manipHideOnShiftCtrl 0;

	//----------------------------------------------------------
	// NURBS Display Preferences
	//----------------------------------------------------------

	optionVar
		-iv "newCurveDisplayEP" false
		-iv "newCurveDisplayHull" false
		-iv "newCurveDisplayCV" false
		-iv "newSurfaceDisplayEP" false
		-iv "newSurfaceDisplayHull" false
		-iv "newSurfaceDisplayCV" false
		-iv "newSurfaceDisplayOrigin" false
		-iv "newNurbsIsoparms" 0
		-iv "newNurbsPointsShaded" 4
		-iv "newNurbsPointsWire" 5;

	//----------------------------------------------------------
	// Poly Display Preferences
	//----------------------------------------------------------

	optionVar
		-iv newPolyVtxDisp false
		-iv newPolyVtxBackCull true
		-iv newPolyVertexNormals false
		-fv newPolyVertexSize 3.0
		-iv newPolyEdgeDisp 0
		-fv newPolyBorderEdgeSize 2.0
		-iv newPolyBorderEdgeHilite false
		-iv newPolyBorderMapHilite false
		-iv newPolyCreaseEdgeHilite true
		-iv newPolyCreaseVertexHilite true
		-fv newPolyUVSize 4.0
		-fv newPolyNormalSize 0.4
		-iv newPolyFacetCentreDisp false
		-iv newPolyFacetNormalDisp false
		-iv newPolyFacetTrngleDisp false
		-iv newPolyFacetWarpDisp false
		-iv newPolyNumVertexDisp false
		-iv newPolyNumEdgeDisp false
		-iv newPolyNumFacetDisp false
		-iv newPolyNumUvDisp  false
		-iv newPolyColorShaded 0
		-iv newPolyColorChannel 3
		-iv newPolyMaterialBlend 1
		-iv newPolyBackFaceCull 0
		-iv polyAutoShowColorPerVertex true
		-iv newPolyDefaultVertexNormalMethod 3
		-iv newPolyDefaultSmoothDrawType 1
		;

	//----------------------------------------------------------
	// Subdiv Display Preferences
	//----------------------------------------------------------

	optionVar
		-iv "subdivComponentDisplayStyle" 0;

	//----------------------------------------------------------
	// Font-size Display Preferences
	//----------------------------------------------------------
	optionVar
		-iv smallFontSize 10
		-iv defaultFontSize 14
		-iv fontSetOpt 0;


	//----------------------------------------------------------
	// General Application Settings Preferences
	//----------------------------------------------------------

	optionVar
		-sv upAxisDirection "y"
		-sv workingUnitLinear "cm"
		-sv workingUnitAngular "deg"
		-sv workingUnitTime "film"
		-fv positionalTolerance 0.01
		-fv tangentialTolerance 0.10;

	//----------------------------------------------------------
	// Animation Preferences
	//----------------------------------------------------------

	optionVar
		-fv "playbackMin" 1.0
		-fv "playbackMax" 120.0
		-fv "playbackMinRange" 1.0
		-fv "playbackMaxRange" 200.0
		-iv "timeSliderHeight" 28
		-sv "timeSliderShowKeys" "active"
		-iv "timeSliderShowKeysCombined" 0
		-sv "timeSliderShowFrames" "active"
		-iv "timeSliderTickSize" 1
		-iv "timeSliderTimeCode" false
		-iv "timeSliderSnapping" true
		-sv "timeSliderPlayView" "active"
		-sv "timeSliderPlayLoop" "continuous"
		-fv "timeSliderPlaySpeed" 0.0
		-fv "timeSliderMaxPlaySpeed" 0.0
		-fv "timeSliderPlayBy" 1.0
		-iv "graphEdLmbMovesSelections" 1
		-iv "graphEdSnapToAdjacentValues" 1
		-iv "timeSliderTickSpan" 0
		-iv "refAnimCurvesEditable" 0
        ;

   	//----------------------------------------------------------
	// Assets/Container Preferences
	//----------------------------------------------------------

	optionVar
		-iv "containerRootUsesCustomIcon" 1;
	optionVar
		-iv "containerSelRootsInOutliner" 1;

	// used to specify the maximum number of attributes displayed
	// for a given container in the channel box at one time
	// when viewMode is not equal to template
	//
	optionVar -intValue containerChanBoxMaxNoTemplate 400;

	// used to specify the maximum number of attributes displayed
	// for a given container in the channel box at one time
	// when the viewMode is set to template
	//
	optionVar -intValue containerChanBoxMaxWithTemplate 400;

	// If there is no view associated with the Published attributes, they'll
	// be grouped in the AE in sets of this size
	//
	optionVar -intValue containerFlatViewCap 12;

	//----------------------------------------------------------
	// Camera Preferences
	//----------------------------------------------------------

	optionVar
		-fv defaultCameraNearClipValue 0.1
		-fv defaultCameraFarClipValue 10000
		-iv animateRoll 0
		-iv animateRollFitAll 0
		-iv animateRollGotoBookmark 0
		-iv animateRollNextLastCameraView 0
		-fv totalAnimateRollTime 0.5;

	// ADSK_CLR_MGT_BEGIN
	//----------------------------------------------------------
	// Color Management Preferences
	//----------------------------------------------------------

	// source is a directive, unconditionally processed when this file
	// is sourced, so irrelevant whether source is inside conditional 
	// or not.
	source "colorManagementUtilities.mel";
	initializeColorManagementOptionVars();

	// ADSK_CLR_MGT_END

	//----------------------------------------------------------
	// ViewCube Preferences
	//----------------------------------------------------------

	optionVar
		-iv animateRollViewCompass 1
		-iv viewCubeShowCube true
		-sv viewCubeScreenPosition "topRight"
		-sv viewCubeSize "normal"
		-fv viewCubeInactiveOpacity	0.50
		-iv viewCubeSnapToClosest true
		-iv viewCubePreserveSceneUp true
		-iv viewCubeFitToView true
		-iv viewCubeShowCompass false
		-fv viewCubeCompassAngle 0.0;

	//----------------------------------------------------------
	// InViewEditor Preferences
	//----------------------------------------------------------

	optionVar -iv inViewEditorVisible true;

	//----------------------------------------------------------
	// SteeringWheels Preferences
	//----------------------------------------------------------

	if (exists("steeringWheel"))
	{
		optionVar
			-iv steeringWheelWelcomeSeen false
			-fv steeringWheelBigSize 2.0
			-iv steeringWheelBigOpacity 50
			-fv steeringWheelMiniSize 2.0
			-fv steeringWheelMiniOpacity 50
			-iv steeringWheelShowToolMessages true
			-iv steeringWheelShowToolTips true
			-iv steeringWheelShowPinnedOnStartup false
			-iv steeringWheelInvertLookAxis false
			-iv steeringWheelConstrainWalkToGround true
			-fv steeringWheelWalkSpeedFactor 1.0
			-iv steeringWheelIncrementalZoom false
			-iv steeringWheelKeepSceneUpright true
			-iv steeringWheelSelectionSensitivity on;
	}

	//----------------------------------------------------------
	// Dynamics Preferences
	//----------------------------------------------------------

	optionVar
		-iv dynPrefAutoCreate true
		-iv dynPrefRunupToCurrentTime false
		-iv dynPrefRunupFrom 1
		-iv dynPrefSaveRuntimeState true
		-iv dynPrefEchoCollision true;

	//----------------------------------------------------------
	// Hypergraph Preferences
	//----------------------------------------------------------

	optionVar
		-iv heatMapMetric 2;

	//----------------------------------------------------------
	// Keys Preferences
	//----------------------------------------------------------

	// Bug 179987
	// Set the default inTangentType and outTangentType to "clamped"
	// instead of "spline"
	optionVar
		-iv "gpuOverride" false
		-iv "evaluationMode" 3
		-iv "autoKeyframeState" false
		-iv "rotationInterpolationDefault" 1
		-iv "hikRotationInterpolationDefault" 4
		-sv "autoKeyCharacterState" "standard"
		-iv "weightedTangents" false	
		-sv "inTangentType" "auto"
		-sv "outTangentType" "auto"
		-iv "animBlendingOpt" 1;

	//----------------------------------------------------------
	// File References Preferences
	//----------------------------------------------------------
	optionVar
		-iv "refAnimCurvesEditable" 0
		-iv "refLockEditable" 0;

	//----------------------------------------------------------
	// Modeling Preferences
	//----------------------------------------------------------

	modelWithType (0);
	modelWithToolsAll (0);
	optionVar
		-intValue "polyAutoConvertAction" 1
		-intValue "polyCreateMeshesSingleSided" 0
		-intValue "polyAutoInstallAction" 0
		-intValue "polyDefaultTangentSpace" 0
		-floatValue "polyDefaultTangentSmoothingAngle" 0;

	//----------------------------------------------------------
	// Modeling Toolkit Preferences
	//----------------------------------------------------------



	//----------------------------------------------------------
	// Node Editor Preferences
	//----------------------------------------------------------
	optionVar
		-iv nodeEdAddNewNodes 1
		-iv nodeEdAdditiveGraphingMode 0
		-iv nodeEdAutoSizeNodes 1
		-iv nodeEdDefaultPinnedState 0
		-iv nodeEdDefaultNodeViewMode 0
		-iv nodeEdExtendToShapes 1
		-iv nodeEdGridSnapping 0
		-iv nodeEdGridVisibility 1
		-iv nodeEdIgnoreAssets 1
		-iv nodeEdSaveGraphInfoWithPanel 1
		-iv nodeEdShowNamespace 1
		-iv nodeEdUseAssetsAndPublishedAttributes 1
		-iv nodeEdShowSGShapes 0
		-iv nodeEdShowShapes 1
		-iv nodeEdConsistentNodeNameSize 1
		-iv nodeEdShowTransforms 1
		-iv nodeEdSyncedSelection 1;

	optionVar -sv NEGlobalView "NEDefault";


	//----------------------------------------------------------
	// Selection Preferences
	//----------------------------------------------------------

	optionVar
		-iv TrackSelectionOrder false
		-iv PreserveComponentSelections true
		-iv selectSingleMarquee false
		-iv selectClickDrag false
		-iv selectAffectsActive true
		-iv ignoreSelectionPriority false
		-iv popupMenuSelection false
		-iv expandPopupList false
		-iv clickBoxSize 4
		-iv preSelectHilite true
		-sv selectPrefPriorityMode "animation"
		-iv selectPrefUseDepth false
		-iv MT_selectDeadSpaceRange 4
		-iv MT_tweakDeadSpaceRange 120
		-iv selectPrefPreSelectBackfacing true
		-iv selectPrefPreSelectClosest true
		-iv containerCentricSelection false
		// auto-select the container when root transform
		// selected and in container centric mode
		-iv containerAutoSelectContainer true
		-iv selectionChildHighlightMode 0 ;

	optionVar
		-iv "polyFaceSensitive" true;




	optionVar -ca customSelectPriority;
	// Note: If you update this, you must also update the total count, which is
	// found in initialGUI, and is called $gCustomSelPriorityCount
	//
	optionVar
		-iva customSelectPriority 10 	// handle
		-iva customSelectPriority 10 	// ikHandle
		-iva customSelectPriority 2 	// ikEndEffector
		-iva customSelectPriority 9 	// joint
		-iva customSelectPriority 2  	// light
		-iva customSelectPriority 2  	// camera
		-iva customSelectPriority 2  	// lattice
		-iva customSelectPriority 2  	// cluster
		-iva customSelectPriority 2  	// sculpt
		-iva customSelectPriority 2  	// nonlinear
		-iva customSelectPriority 4  	// nurbsCurve
		-iva customSelectPriority 3  	// curveOnSurface
		-iva customSelectPriority 2  	// nurbsSurface
		-iva customSelectPriority 2  	// polymesh
		-iva customSelectPriority 2  	// plane
		-iva customSelectPriority 2  	// particleShape
		-iva customSelectPriority 2  	// emitter
		-iva customSelectPriority 2  	// field
		-iva customSelectPriority 2		// fluid
		-iva customSelectPriority 2  	// spring
		-iva customSelectPriority 2  	// rigidBody
		-iva customSelectPriority 2  	// rigidConstraint
		-iva customSelectPriority 2  	// locator
		-iva customSelectPriority 2  	// dimension
		-iva customSelectPriority 2    	// texture
		-iva customSelectPriority 2		// implicitGeometry
		-iva customSelectPriority 2		// controlVertex
		-iva customSelectPriority 2		// editPoint
		-iva customSelectPriority 2		// hull
		-iva customSelectPriority 2		// polymeshVertex
		-iva customSelectPriority 2		// polymeshEdge
		-iva customSelectPriority 2		// polymeshFace
		-iva customSelectPriority 2		// polymeshUV
		-iva customSelectPriority 2		// curveParameterPoint
		-iva customSelectPriority 2		// surfaceParameterPoint
		-iva customSelectPriority 2		// surfaceEdge
		-iva customSelectPriority 2		// isoparm
		-iva customSelectPriority 2		// latticePoint
		-iva customSelectPriority 2		// particle
		-iva customSelectPriority 2		// spring
		-iva customSelectPriority 2		// jointPivot
		-iva customSelectPriority 2		// scalePivot
		-iva customSelectPriority 2		// rotatePivot
		-iva customSelectPriority 2		// selectHandle
		-iva customSelectPriority 2		// localRotationAxis
		-iva customSelectPriority 2		// imagePlane
		-iva customSelectPriority 8		// animCurve
		-iva customSelectPriority 10	// animKeyframe
		-iva customSelectPriority 10	// animBreakdown
		-iva customSelectPriority 9		// animInTangent
		-iva customSelectPriority 9		// animOutTangent
		-iva customSelectPriority 2		// "subdiv"
		-iva customSelectPriority 2		// "subdivMeshPoint"
		-iva customSelectPriority 2		// "subdivMeshEdge"
		-iva customSelectPriority 2		// "subdivMeshFace"
		-iva customSelectPriority 2		// surfaceFace
		-iva customSelectPriority 2		// hairSystem
		-iva customSelectPriority 2		// follicle
		-iva customSelectPriority 2		// nCloth
		-iva customSelectPriority 2		// nRigid
		-iva customSelectPriority 2		// dynamicConstraint
-iva customSelectPriority 11	// motionTrailPoint
-iva customSelectPriority 11	// motionTrailTangent
		;

	//----------------------------------------------------------
	// Snapping Preferences
	//----------------------------------------------------------

	optionVar
		-iv useSnapTolerance false
		-iv snapTolerance 20
		-iv snapUVTolerance 25
		-iv snapMagnet 0
		-fv snapMagnetTolerance 0.1;

	//----------------------------------------------------------
	// Sound Preferences
	//----------------------------------------------------------

	optionVar
		-sv "timeSliderSoundDisplay" "both"
		-iv "timeSliderRepeatOnHold" false
		-fv "timeSliderRepeatChunk" 1.0;

	//----------------------------------------------------------
	// Advanced Preferences
	//----------------------------------------------------------

	optionVar
		-iv "undoIsEnabled" true
		-iv "undoIsInfinite" false
		-iv "undoLength" 50;

	//----------------------------------------------------------
	// Rendering Preferences
	//----------------------------------------------------------

	optionVar
		-sv "preferredRenderer" 
            "mayaSoftware";
  optionVar
		-iv "miCacheOptimFileTextures" 0;
	optionVar
		-iv "miFileTextureCacheStorageMode" 0;
	optionVar
		-sv "miFileTextureCacheLocation" "";
	optionVar
		-iv "miFileTextureCacheConversionScope" 1;
	optionVar
		-iv "miUseMayaAlphaDetection" 0;
	optionVar
		-iv "miCollapseHistoryOnProxyUpdate" 0;
    optionVar
		-iv "miEnableRayTracingForSwatch" 1;

	//----------------------------------------------------------
	// File I/O Preferences
	//----------------------------------------------------------

	optionVar
		-sv "fileCompressionMode" "asCompressed";
	optionVar
		-iv "FileDialogStyle" 2
		-iv "FileDialogHideExtension" 1
		-iv "fileIgnoreVersion" 1
		-iv "MT_autoloadTextures" 0
		-iv "displayLayerMerge" 0
		-iv "RecentFilesMaxSize" 10
		-iv "RecentBackupsMaxSize" 4
		-iv "RecentProjectsMaxSize" 10;
	optionVar
		-iv "autoSaveEnable" 0
		-iv "autoSavePrompt" 0
		-iv "autoSaveLimitBackups" 0
		-iv "autoSaveMaxBackups" 10
		-iv "autoSaveInterval" 10
		-iv "autoSaveDestination" 0
		-sv "autoSaveFolder" "";
	optionVar
		-iv "externalContentTableStorageEnabled" 0;

	//----------------------------------------------------------
	// Custom Preferences
	//----------------------------------------------------------
	setOptVarOfCustomTabToDefault();
	//----------------------------------------------------------
	// Modules Preferences
	//----------------------------------------------------------

	optionVar
		-iv "loadDynamics" true
		-iv "loadUrchin" true;

	//----------------------------------------------------------
	// OpenMaya Preferences
	//----------------------------------------------------------

	optionVar
		-iv "apiPrefLazyLoading" false
		-iv "apiPrefOldPluginWarning" true;
	//----------------------------------------------------------
	// Save Actions
	//----------------------------------------------------------

	optionVar
		-iv "saveActionsPreferences" 1;
	optionVar
		-iv "saveActionsScriptEditor" 1;

	//----------------------------------------------------------
	// Command port open by default
	//----------------------------------------------------------

	optionVar
		-iv "commandportOpenByDefault" 1;
	optionVar
		-sv "commandportDefaultName" "commandportDefault";

	//----------------------------------------------------------
	//Smooth Mesh Preview
	//----------------------------------------------------------
	optionVar -iv smpSizeOfMeshForWarning 15000;
	optionVar -iv smpSizeWarningDisabledForAllPolys 0;

	//----------------------------------------------------------
	//Sequencer Shot Double Click
	//----------------------------------------------------------
	optionVar -iv seqDoubleClickSetTimeRange 1;

	optionVar -sv ViewImageDir                "";
	optionVar -sv ViewImageCmdFormat          "";
	optionVar -sv ViewSequenceDir             "";
	optionVar -sv ViewSequenceCmdFormat       "";
	optionVar -sv PhotoshopDir                "";
	optionVar -sv EditImageDir                "";
	optionVar -sv PlayblastCmdAvi             "";
	optionVar -sv PlayblastCmdFormatAvi       "";
	optionVar -sv PlayblastCmdQuicktime       "";
	optionVar -sv PlayblastCmdFormatQuicktime "";
	optionVar -sv PlayblastCmdAvi             "";
	optionVar -sv PlayblastCmdFormatAvi       "";
	optionVar -sv PlayblastCmdQuicktime       "";
	optionVar -sv PlayblastCmdFormatQuicktime "";

	// TODO: We want to gradually move all NEX defaults into this file. Remove this line once they are all moved.
	if(`pluginInfo -q -loaded "modelingToolkit"`){
		nexOpt -d;
	}

	optionVar -iv MT_useCompModeCustCmd 0;
	optionVar -sv MT_compModeCustCmd "";

	optionVar -iv MT_freeRotate 1;
	optionVar -iv MT_prohibitNegativeScale 1;
	optionVar -iv MT_refreshActiveOnly 0;
	optionVar -iv MT_resetManipOnToolSwitch 0;
	optionVar -iv MT_resetManipOnSelChange 0;
	optionVar -fv MT_manipPickRange 4;
	optionVar -iv MT_planeHandleOffset 100;

	optionVar -iv MT_hudShowMode 0;
	optionVar -iv MT_hudShowCoordSpace 0;
	optionVar -iv MT_showDynamicHUD 1;
	optionVar -fv MT_dynamicHUDColor 1;
	optionVar -fva MT_dynamicHUDColor 1;
	optionVar -fva MT_dynamicHUDColor 0;

	optionVar -iv MT_invertedCursors 1;

	optionVar -fv MT_hiliteColorAdd 0;
	optionVar -fva MT_hiliteColorAdd 1;
	optionVar -fva MT_hiliteColorAdd 0;

	optionVar -fv MT_hiliteColorCutLine 1;
	optionVar -fva MT_hiliteColorCutLine 0.5;
	optionVar -fva MT_hiliteColorCutLine 0;
	optionVar -fva MT_hiliteColorCutLine 1;

	optionVar -fv MT_hiliteColorCutVert 1;
	optionVar -fva MT_hiliteColorCutVert 1;
	optionVar -fva MT_hiliteColorCutVert 0;
	optionVar -fva MT_hiliteColorCutVert 1;

	optionVar -fv MT_hiliteColorCutEdge 0;
	optionVar -fva MT_hiliteColorCutEdge 0;
	optionVar -fva MT_hiliteColorCutEdge 1;
	optionVar -fva MT_hiliteColorCutEdge 1;

	optionVar -fv MT_hiliteColorCutFace 1;
	optionVar -fva MT_hiliteColorCutFace 1;
	optionVar -fva MT_hiliteColorCutFace 1;
	optionVar -fva MT_hiliteColorCutFace 1;

	optionVar -fv MT_hiliteColorSubtract 1;
	optionVar -fva MT_hiliteColorSubtract 1;
	optionVar -fva MT_hiliteColorSubtract 0;

	optionVar -fv MT_paintColorAdd 0;
	optionVar -fva MT_paintColorAdd 1;
	optionVar -fva MT_paintColorAdd 0;

	optionVar -fv MT_paintColorSubtract 1;
	optionVar -fva MT_paintColorSubtract 1;
	optionVar -fva MT_paintColorSubtract 0;

	optionVar -fv MT_activeManipColor 1;
	optionVar -fva MT_activeManipColor 1;
	optionVar -fva MT_activeManipColor 0;

	optionVar -fv MT_hiliteTransparency 100;

	optionVar -iv MT_quaDrawMmbWeld 1;
	optionVar -iv MT_shiftSlide 0;
	optionVar -iv MT_shiftCtrlSlide 2;
}
