// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
// Creation Date:  Oct 1999
//
//
//<doc>
//<name createNewShelf>
//
//<synopsis>
//		createNewShelf
//
//<returns>
//		int : 1 if a shelf tab was created, otherwise 0
//
//<description>
//      Create an empty new shelf tab.  Prompt the user for the name.
//		If the name is invalid then it will re-prompt until the user cancels.
//
//<flags>
//		None.
//
//<examples>
//  createNewShelf;
//
//</doc>

global proc int createNewShelf()
{
	int $returnStatus = false;
	int $tryAgain = true;
	
	while ($tryAgain) {
		string $ok = (uiRes("m_createNewShelf.kOk"));
		string $cancel = (uiRes("m_createNewShelf.kCancel"));
		string $result = `promptDialog 
			-title (uiRes("m_createNewShelf.kCreateNewShelf"))
			-message (uiRes("m_createNewShelf.kNewShelfName"))
			-button $ok -button $cancel
			-defaultButton $ok -cancelButton $cancel
			-dismissString $cancel`;
	
		// If the result was "OK", then proceed
		//
		if ( $result == $ok ) {
			string $shelfName = `promptDialog -q`;	
			if (validateShelfName($shelfName)) {		 
				addNewShelfTab $shelfName;
				$returnStatus = true;
				$tryAgain = false;
			} else {
				$returnStatus = false;
			}
		} else {
			$tryAgain = false;
		}
	}
	
	return $returnStatus;
}
