// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  Sept 9, 2005
//
//  Description:
//      This procedure searches for, and returns the menuSet object with 
//		the given label. 
//

global proc string findMenuSetFromLabel( string $label ) 
//
//  Description:
//		This proc finds a menuSet object from a given label (shown in the
//		drop down boxes.
//
//	Arguments:
//		string $label the label of the menuSet to be found
//		
//	Return:
//		the name/object of the menuSet with that label, or an empty string
//		if there is none
//
{

	// get the list of all menuSets
	string $menuSets[] = `menuSet -allMenuSets`;

    int $i;
	int $menuSetSize = size($menuSets);
	$label = `tolower $label`;

	// and for each menuSet ... 
	for ($i = 0; $i < $menuSetSize; $i++) {
		string $lbl = `menuSet -q -label $menuSets[$i]`;
		$lbl = `tolower $lbl`;		

		// ... compare whether it is the same as the given label
		if ($label == $lbl) {
			// ... and if so, then return
			return $menuSets[$i];
		}
	}

	// if we get to this point, then we can not find a menuSet with the 
	// specified label.  So we return an empty string.
	//
	return "";
}
