// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Alt" m_listHotkeysWindow.kAlt;
displayString -replace -value "Alt " m_listHotkeysWindow.kAltKey;
displayString -replace -value "   " m_listHotkeysWindow.kAltSpace;
displayString -replace -value "Categories" m_listHotkeysWindow.kCategories;
displayString -replace -value "Close" m_listHotkeysWindow.kClose;
displayString -replace -value "Cmd " m_listHotkeysWindow.kCmdKey;
displayString -replace -value "Command" m_listHotkeysWindow.kCommand;
displayString -replace -value "command " m_listHotkeysWindow.kCommandKey;
displayString -replace -value "command" m_listHotkeysWindow.kCommmand;
displayString -replace -value "control" m_listHotkeysWindow.kControl;
displayString -replace -value "control " m_listHotkeysWindow.kControlKey;
displayString -replace -value "              " m_listHotkeysWindow.kControlOptionSpace;
displayString -replace -value "       " m_listHotkeysWindow.kControlSpace;
displayString -replace -value "Ctrl" m_listHotkeysWindow.kCtrl;
displayString -replace -value "        " m_listHotkeysWindow.kCtrlAltSpace;
displayString -replace -value "Ctrl " m_listHotkeysWindow.kCtrlKey;
displayString -replace -value "    " m_listHotkeysWindow.kCtrlSpace;
displayString -replace -value "Hotkey" m_listHotkeysWindow.kHotkey;
displayString -replace -value "Ignore release" m_listHotkeysWindow.kIgnoreRelease;
displayString -replace -value "Mapped" m_listHotkeysWindow.kKeyMapped;
displayString -replace -value "Press    " m_listHotkeysWindow.kKeyPress;
displayString -replace -value "Release  " m_listHotkeysWindow.kKeyRelease;
displayString -replace -value "Unmapped" m_listHotkeysWindow.kKeyUnmapped;
displayString -replace -value "List all" m_listHotkeysWindow.kListAll;
displayString -replace -value "List by Category" m_listHotkeysWindow.kListCategory;
displayString -replace -value "List by Keys" m_listHotkeysWindow.kListKeys;
displayString -replace -value "Mapped" m_listHotkeysWindow.kMapped;
displayString -replace -value "No modifiers" m_listHotkeysWindow.kNoModifiers;
displayString -replace -value "option" m_listHotkeysWindow.kOption;
displayString -replace -value "option " m_listHotkeysWindow.kOptionKey;
displayString -replace -value "      " m_listHotkeysWindow.kOptionSpace;
displayString -replace -value "Press" m_listHotkeysWindow.kPress;
displayString -replace -value "Category" m_listHotkeysWindow.kPrintCategory;
displayString -replace -value "Release" m_listHotkeysWindow.kRelease;
displayString -replace -value "Save to File..." m_listHotkeysWindow.kSave;
displayString -replace -value "Save" m_listHotkeysWindow.kSaveBrowserTitle;
displayString -replace -value "Unmapped" m_listHotkeysWindow.kUnmapped;
displayString -replace -value "Saving hotkeys to file is not supported in Maya PLE." m_listHotkeysWindow.kWarn;
displayString -replace -value "List Hotkeys" m_listHotkeysWindow.kWindowTitle;
