// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Append to Cache" m_NucleusCacheMenu.kAppendCache;
displayString -replace -value "Attach Cache..." m_NucleusCacheMenu.kAttachCache;
displayString -replace -value "Edit" m_NucleusCacheMenu.kCacheEdit;
displayString -replace -value "Frame" m_NucleusCacheMenu.kCacheFrame;
displayString -replace -value "Maya Fluid" m_NucleusCacheMenu.kCacheMayaFluid;
displayString -replace -value "nCloth" m_NucleusCacheMenu.kCacheNCloth;
displayString -replace -value "nObject" m_NucleusCacheMenu.kCacheNObject;
displayString -replace -value "Create New Cache" m_NucleusCacheMenu.kCreateCache;
displayString -replace -value "Create Particle Disk Cache" m_NucleusCacheMenu.kCreateParticleCache;
displayString -replace -value "Write cache files to disk for current playback range" m_NucleusCacheMenu.kCreateParticleCacheAnnot;
displayString -replace -value "Particle disk cache options" m_NucleusCacheMenu.kCreateParticleCacheOptionsAnnot;
displayString -replace -value "Delete" m_NucleusCacheMenu.kDelete;
displayString -replace -value "Remove from memory the cache for all selected particles and rigid bodies" m_NucleusCacheMenu.kDeleteAnnot;
displayString -replace -value "Delete Cache" m_NucleusCacheMenu.kDeleteCache;
displayString -replace -value "Delete Cache Frame" m_NucleusCacheMenu.kDeleteCacheFrames;
displayString -replace -value "Disable" m_NucleusCacheMenu.kDisable;
displayString -replace -value "Disable All Caches on Selected" m_NucleusCacheMenu.kDisableAllCache;
displayString -replace -value "Disable all caches on selected nCloth or nParticle objects" m_NucleusCacheMenu.kDisableAllCacheAnnot;
displayString -replace -value "Turn memory caching off for all selected particles and rigid bodies" m_NucleusCacheMenu.kDisableAnnot;
displayString -replace -value "Edit Oversampling or Cache Settings..." m_NucleusCacheMenu.kEditOversampling;
displayString -replace -value "Edit the oversampling level or particle disk cache settings" m_NucleusCacheMenu.kEditOversamplingAnnot;
displayString -replace -value "Enable" m_NucleusCacheMenu.kEnable;
displayString -replace -value "Enable All Caches on Selected" m_NucleusCacheMenu.kEnableAllCache;
displayString -replace -value "Enable all caches on selected nCloth or nParticle objects" m_NucleusCacheMenu.kEnableAllCacheAnnot;
displayString -replace -value "Turn memory caching on for all selected particles and rigid bodies" m_NucleusCacheMenu.kEnableAnnot;
displayString -replace -value "Legacy Cache" m_NucleusCacheMenu.kLegacyCache;
displayString -replace -value "Memory Caching" m_NucleusCacheMenu.kMemoryCaching;
displayString -replace -value "Merge Caches" m_NucleusCacheMenu.kMergeCache;
displayString -replace -value "Maya Fluid" m_NucleusCacheMenu.kMergeCacheMayaFluid;
displayString -replace -value "nObject" m_NucleusCacheMenu.kMergeCacheNObject;
displayString -replace -value "Move cache for selected nCloth object to a geometry cache on the nCloth input mesh" m_NucleusCacheMenu.kMoveCacheAnnot;
displayString -replace -value "Create" m_NucleusCacheMenu.kNCacheCreate;
displayString -replace -value "Paint Cache Weights Tool" m_NucleusCacheMenu.kPaintCache;
displayString -replace -value "Replace Caches" m_NucleusCacheMenu.kReplaceCache;
displayString -replace -value "Replace Cache Frame" m_NucleusCacheMenu.kReplaceCacheFrames;
displayString -replace -value "Maya Fluid" m_NucleusCacheMenu.kReplaceCacheMayaFluid;
displayString -replace -value "nObject" m_NucleusCacheMenu.kReplaceCacheNObject;
displayString -replace -value "Transfer Cache To Input Mesh" m_NucleusCacheMenu.kTransferCacheToInput;
