// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Add Members" m_NucleusConstraintMenu.kAddMembers;
displayString -replace -value "Add selected elements to constraint" m_NucleusConstraintMenu.kAddMembersAnnot;
displayString -replace -value "Attract to Matching Mesh" m_NucleusConstraintMenu.kAttractToMatch;
displayString -replace -value "Select an cloth object and a mesh with identical topology to attract to" m_NucleusConstraintMenu.kAttractToMatchAnnot;
displayString -replace -value "Exclude Collide Pairs" m_NucleusConstraintMenu.kCollisionExclusion;
displayString -replace -value "Select dynamic objects and/or cvs between which to suppress collisions" m_NucleusConstraintMenu.kCollisionExclusionAnnot;
displayString -replace -value "Component" m_NucleusConstraintMenu.kComponent;
displayString -replace -value "Create a constraint for an nCloth node or its selected components based on the mesh topology." m_NucleusConstraintMenu.kComponentAnnot;
displayString -replace -value "Component to Component" m_NucleusConstraintMenu.kComponentToComponent;
displayString -replace -value "Create a constraint between selected nucleus object vertices, edges or faces" m_NucleusConstraintMenu.kComponentToComponentAnnot;
displayString -replace -value "Create" m_NucleusConstraintMenu.kConstraintCreate;
displayString -replace -value "Edit" m_NucleusConstraintMenu.kConstraintEdit;
displayString -replace -value "Maps" m_NucleusConstraintMenu.kConstraintMaps;
displayString -replace -value "Membership" m_NucleusConstraintMenu.kConstraintMembership;
displayString -replace -value "nConstraint Membership Tool" m_NucleusConstraintMenu.kConstraintMembershipTool;
displayString -replace -value "Edit nConstraint membership" m_NucleusConstraintMenu.kConstraintMembershipToolAnnot;
displayString -replace -value "Convert Texture to Vertex Map" m_NucleusConstraintMenu.kConvertTextureMap;
displayString -replace -value "Convert texture map to vertex map." m_NucleusConstraintMenu.kConvertTextureMapAnnot;
displayString -replace -value "Convert Vertex to Texture Map" m_NucleusConstraintMenu.kConvertVtxMap;
displayString -replace -value "Convert vertex map to texture map." m_NucleusConstraintMenu.kConvertVtxMapAnnot;
displayString -replace -value "Disable Collision" m_NucleusConstraintMenu.kDisableCollision;
displayString -replace -value "Select cloth components for which to disable collision with all other objects" m_NucleusConstraintMenu.kDisableCollisionAnnot;
displayString -replace -value "Force Field" m_NucleusConstraintMenu.kForceField;
displayString -replace -value "Select cloth objects or components to apply a radial force constraint to" m_NucleusConstraintMenu.kForceFieldAnnot;
displayString -replace -value "Convert the glue strength texture map to a vertex map." m_NucleusConstraintMenu.kGlueStrengthConvertAnnot;
displayString -replace -value "Convert the glue strength vertex map to a texture map." m_NucleusConstraintMenu.kGlueStrengthConvertVertAnnot;
displayString -replace -value "Glue Strength" m_NucleusConstraintMenu.kGlueStrengthMap;
displayString -replace -value "Paint the mappable glue strength attribute" m_NucleusConstraintMenu.kGlueStrengthMapAnnot;
displayString -replace -value "Bring up the option box for painting the mappable glue strength attribute" m_NucleusConstraintMenu.kGlueStrengthMapOptionAnnot;
displayString -replace -value "Paint Properties by Texture Map" m_NucleusConstraintMenu.kPaintPropByTexture;
displayString -replace -value "Paint mappable properties by texture map" m_NucleusConstraintMenu.kPaintPropByTextureAnnot;
displayString -replace -value "Paint Properties by Vertex Map" m_NucleusConstraintMenu.kPaintPropByVertex;
displayString -replace -value "Paint mappable properties by vertex map" m_NucleusConstraintMenu.kPaintPropByVertexAnnot;
displayString -replace -value "Point to Surface" m_NucleusConstraintMenu.kPointToSurface;
displayString -replace -value "Select cloth points and a collision object to constraint to" m_NucleusConstraintMenu.kPointToSurfaceAnnot;
displayString -replace -value "Remove Dynamic Constraint" m_NucleusConstraintMenu.kRemoveDynamicConstraint;
displayString -replace -value "Remove Members" m_NucleusConstraintMenu.kRemoveMembers;
displayString -replace -value "Remove selected elements from constraint" m_NucleusConstraintMenu.kRemoveMembersAnnot;
displayString -replace -value "Replace Members" m_NucleusConstraintMenu.kReplaceMembers;
displayString -replace -value "Replace all elements for constraint with selection" m_NucleusConstraintMenu.kReplaceMembersAnnot;
displayString -replace -value "Select Members" m_NucleusConstraintMenu.kSelectMembers;
displayString -replace -value "Select all elements for selected constraint" m_NucleusConstraintMenu.kSelectMembersAnnot;
displayString -replace -value "Slide on Surface" m_NucleusConstraintMenu.kSlideOnSurface;
displayString -replace -value "Select cloth points and a collision object to constraint to" m_NucleusConstraintMenu.kSlideOnSurfaceAnnot;
displayString -replace -value "Convert the strength texture map to a vertex map." m_NucleusConstraintMenu.kStrengthConvertAnnot;
displayString -replace -value "Convert the strength vertex map to a texture map." m_NucleusConstraintMenu.kStrengthConvertVertAnnot;
displayString -replace -value "Strength" m_NucleusConstraintMenu.kStrengthMap;
displayString -replace -value "Paint the mappable strength attribute" m_NucleusConstraintMenu.kStrengthMapAnnot;
displayString -replace -value "Bring up the option box for painting the mappable strength attribute" m_NucleusConstraintMenu.kStrengthMapOptionAnnot;
displayString -replace -value "Tearable Surface" m_NucleusConstraintMenu.kTearableSurface;
displayString -replace -value "Select cloth surface to make tearable" m_NucleusConstraintMenu.kTearableSurfaceAnnot;
displayString -replace -value "Transform Constraint" m_NucleusConstraintMenu.kTransform;
displayString -replace -value "Create a transform constraint for selected nucleus object points" m_NucleusConstraintMenu.kTransformAnnot;
displayString -replace -value "Convert the weight texture map to a vertex map." m_NucleusConstraintMenu.kWeightConvertAnnot;
displayString -replace -value "Convert the weight vertex map to a texture map." m_NucleusConstraintMenu.kWeightConvertVertAnnot;
displayString -replace -value "Weight" m_NucleusConstraintMenu.kWeightMap;
displayString -replace -value "Paint the mappable weight attribute" m_NucleusConstraintMenu.kWeightMapAnnot;
displayString -replace -value "Bring up the option box for painting the mappable weight attribute" m_NucleusConstraintMenu.kWeightMapOptionAnnot;
displayString -replace -value "Weld Adjacent Borders" m_NucleusConstraintMenu.kWeldBorders;
displayString -replace -value "Select cloth objects or components to weld together" m_NucleusConstraintMenu.kWeldBordersAnnot;
