// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Automatically remap data range" m_performVisualizeMetadataOptions.kAutoColor;
displayString -replace -value "Lower range:" m_performVisualizeMetadataOptions.kColorRemapLowerRange;
displayString -replace -value "Color interpretation from:" m_performVisualizeMetadataOptions.kColorRemapType;
displayString -replace -value "Upper range:" m_performVisualizeMetadataOptions.kColorRemapUpperRange;
displayString -replace -value "Custom remapping range" m_performVisualizeMetadataOptions.kCustomColor;
displayString -replace -value "Enable color interpolation on faces" m_performVisualizeMetadataOptions.kEnableInterpolationCheck;
displayString -replace -value "0-1" m_performVisualizeMetadataOptions.kFloatColor;
displayString -replace -value "0-255" m_performVisualizeMetadataOptions.kIntColor;
displayString -replace -value "Indicate data that is out of range" m_performVisualizeMetadataOptions.kInvalidDataCheck;
displayString -replace -value "Member" m_performVisualizeMetadataOptions.kMemberToVisualize;
displayString -replace -value "Ray length scale:" m_performVisualizeMetadataOptions.kMetadataRayScaleLabel;
displayString -replace -value "Stream to visualize" m_performVisualizeMetadataOptions.kStreamToVisualize;
displayString -replace -value "Color" m_performVisualizeMetadataOptions.kVisualColor;
displayString -replace -value "Method:" m_performVisualizeMetadataOptions.kVisualMethod;
displayString -replace -value "Ray" m_performVisualizeMetadataOptions.kVisualRay;
displayString -replace -value "String" m_performVisualizeMetadataOptions.kVisualString;
displayString -replace -value "Metadata Visualization Options" m_performVisualizeMetadataOptions.kVisualizeMetadataOptions;
