// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Bake set type ^1s does not exist." m_PolygonsColorMenu.kBakeTypeError;
displayString -replace -value "^1s options" m_PolygonsColorMenu.kNewOptionBoxAnnotation;
displayString -replace -value "^1s Options" m_PolygonsColorMenu.kNewOptionBoxLabel;
displayString -replace -value "Color Material Channel" m_PolygonsColorMenu.kNewPolyColorMaterial;
displayString -replace -value "Material Blend Setting" m_PolygonsColorMenu.kNewPolyMaterialBlend;
displayString -replace -value "Add" m_PolygonsColorMenu.kPolyAdd;
displayString -replace -value "Ambient" m_PolygonsColorMenu.kPolyAmbient;
displayString -replace -value "Ambient+Diffuse" m_PolygonsColorMenu.kPolyAmbientDiffuse;
displayString -replace -value "Average" m_PolygonsColorMenu.kPolyAverage;
displayString -replace -value "Apply Color" m_PolygonsColorMenu.kPolyColorApply;
displayString -replace -value "Create Empty Color Set" m_PolygonsColorMenu.kPolyColorCreateEmptySet;
displayString -replace -value "Create an empty Color Set on selected objects." m_PolygonsColorMenu.kPolyColorCreateEmptySetAnnot;
displayString -replace -value "Create Empty Color Set Options" m_PolygonsColorMenu.kPolyColorCreateEmptySetOption;
displayString -replace -value "Delete Current Color Set" m_PolygonsColorMenu.kPolyColorDeleteCurSet;
displayString -replace -value "Delete the current Color  Set on selected objects." m_PolygonsColorMenu.kPolyColorDeleteCurSetAnnot;
displayString -replace -value "Modify Current Color Set" m_PolygonsColorMenu.kPolyColorModifyCurSet;
displayString -replace -value "Modify the current UV Set on selected objects." m_PolygonsColorMenu.kPolyColorModifyCurSetAnnot;
displayString -replace -value "Prelight (Maya)" m_PolygonsColorMenu.kPolyColorPrelight;
displayString -replace -value "Prelight polygon using the Maya software renderer" m_PolygonsColorMenu.kPolyColorPrelightAnnot;
displayString -replace -value "Options for prelighting polygon using the Maya software renderer" m_PolygonsColorMenu.kPolyColorPrelightOptAnnot;
displayString -replace -value "Paint Vertex Color Tool" m_PolygonsColorMenu.kPolyColorPtVtxTool;
displayString -replace -value "Rename Current Color Set..." m_PolygonsColorMenu.kPolyColorRenameCurSet;
displayString -replace -value "Rename the current UV Set on selected objects." m_PolygonsColorMenu.kPolyColorRenameCurSetAnnot;
displayString -replace -value "Select Shared Instances" m_PolygonsColorMenu.kPolyColorSelectShared;
displayString -replace -value "Color Set Editor" m_PolygonsColorMenu.kPolyColorSetEditor;
displayString -replace -value "Open the Color Set Editor." m_PolygonsColorMenu.kPolyColorSetEditorAnnot;
displayString -replace -value "Set Keyframe for Vertex Color" m_PolygonsColorMenu.kPolyColorSetKeyframeForVertexColor;
displayString -replace -value "Set a keyframe for colors on selected polygon components" m_PolygonsColorMenu.kPolyColorSetVtxKeyAnnot;
displayString -replace -value "Share Instances" m_PolygonsColorMenu.kPolyColorShareInstances;
displayString -replace -value "Per Instance Sharing" m_PolygonsColorMenu.kPolyColorsPerInstance;
displayString -replace -value "Diffuse" m_PolygonsColorMenu.kPolyDiffuse;
displayString -replace -value "Divide" m_PolygonsColorMenu.kPolyDivide;
displayString -replace -value "Edit Assigned Bake Set" m_PolygonsColorMenu.kPolyEditExistingBakeSet;
displayString -replace -value "Open the Attribute Editor for modifying the bake set" m_PolygonsColorMenu.kPolyEditExistingBakeSetAnnot;
displayString -replace -value "Emission" m_PolygonsColorMenu.kPolyEmission;
displayString -replace -value "Modulate2x" m_PolygonsColorMenu.kPolyModulate2x;
displayString -replace -value "Multiply" m_PolygonsColorMenu.kPolyMultiply;
displayString -replace -value "Assign bake set ^1s to selected surfaces/polygons" m_PolygonsColorMenu.kPolyNewAssignBakeSetAnnotation;
displayString -replace -value "Create a new vertex bake set" m_PolygonsColorMenu.kPolyNewCreateANew2;
displayString -replace -value "Assign Existing Bake Set" m_PolygonsColorMenu.kPolyNewExistingBakeSet;
displayString -replace -value "No bakesets defined" m_PolygonsColorMenu.kPolyNewNoBakesetsDefined;
displayString -replace -value "Assign New Vertex Bake Set" m_PolygonsColorMenu.kPolyNewVertexBakeSet;
displayString -replace -value "None" m_PolygonsColorMenu.kPolyNone;
displayString -replace -value "Overwrite" m_PolygonsColorMenu.kPolyOverwrite;
displayString -replace -value "Specular" m_PolygonsColorMenu.kPolySpecular;
displayString -replace -value "Subtract" m_PolygonsColorMenu.kPolySubtract;
displayString -replace -value "Toggle Display Colors Attribute" m_PolygonsColorMenu.kPolyToggleDisplayColorsAttribute;
displayString -replace -value "Toggle Display Colors attribute of the selected objects" m_PolygonsColorMenu.kPolyToggleDisplayColorsAttributeModeAnnot;
