// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Amplify Tool" m_PolygonsBuildToolsMenu.kAmplifyTool;
displayString -replace -value "Bulge Tool" m_PolygonsBuildToolsMenu.kBulgeTool;
displayString -replace -value "Crease" m_PolygonsBuildToolsMenu.kCreaseTool1;
displayString -replace -value "Crease Tool Options" m_PolygonsBuildToolsMenu.kCreaseToolOptions;
displayString -replace -value "Create Polygon" m_PolygonsBuildToolsMenu.kCreatePolyToo1l;
displayString -replace -value "Create polygon faces" m_PolygonsBuildToolsMenu.kCreatePolyToolAnnot;
displayString -replace -value "Create polygon tool options" m_PolygonsBuildToolsMenu.kCreatePolyToolOptionsAnnot;
displayString -replace -value "Fill Tool" m_PolygonsBuildToolsMenu.kFillTool;
displayString -replace -value "Flatten Tool" m_PolygonsBuildToolsMenu.kFlattenTool;
displayString -replace -value "Foamy Tool" m_PolygonsBuildToolsMenu.kFoamyTool;
displayString -replace -value "Freeze Tool" m_PolygonsBuildToolsMenu.kFreezeTool;
displayString -replace -value "Grab Tool" m_PolygonsBuildToolsMenu.kGrabTool;
displayString -replace -value "Imprint Tool" m_PolygonsBuildToolsMenu.kImprintTool;
displayString -replace -value "Knife Tool" m_PolygonsBuildToolsMenu.kKnifeTool;
displayString -replace -value "Connect" m_PolygonsBuildToolsMenu.kMTKConnectTool1;
displayString -replace -value "Enter Connect tool" m_PolygonsBuildToolsMenu.kMTKConnectToolAnn;
displayString -replace -value "Connect Tool Options" m_PolygonsBuildToolsMenu.kMTKConnectToolOptions;
displayString -replace -value "Multi-Cut" m_PolygonsBuildToolsMenu.kMTKMultiCutTool;
displayString -replace -value "Tools to cut, slice and insert edges on polygons" m_PolygonsBuildToolsMenu.kMTKMultiCutToolAnn;
displayString -replace -value "Multi-Cut Tool Options" m_PolygonsBuildToolsMenu.kMTKMultiCutToolOptions;
displayString -replace -value "Quad Draw" m_PolygonsBuildToolsMenu.kMTKQuadDrawTool1;
displayString -replace -value "Enter Quad Draw tool" m_PolygonsBuildToolsMenu.kMTKQuadDrawToolAnn;
displayString -replace -value "Quad Draw Tool Options" m_PolygonsBuildToolsMenu.kMTKQuadDrawToolOptions;
displayString -replace -value "Target Weld" m_PolygonsBuildToolsMenu.kMTKTargetWeldTool1;
displayString -replace -value "Target Weld Tool Options" m_PolygonsBuildToolsMenu.kMTKTargetWeldToolOptions;
displayString -replace -value "Make Hole" m_PolygonsBuildToolsMenu.kNewMakeHoleTool1;
displayString -replace -value "Paint Reduce Weights" m_PolygonsBuildToolsMenu.kNewPolyReduceWeightsTool1;
displayString -replace -value "Paint Transfer Attributes" m_PolygonsBuildToolsMenu.kPaintTransferAttributesWeightsTool1;
displayString -replace -value "Change weights on selected transferAttributes" m_PolygonsBuildToolsMenu.kPaintTransferAttributesWeightsToolAnnot1;
displayString -replace -value "Paint transfer attributes weights options" m_PolygonsBuildToolsMenu.kPaintTransferAttributesWeightsToolOptionAnnot1;
displayString -replace -value "Pinch Tool" m_PolygonsBuildToolsMenu.kPinchTool;
displayString -replace -value "Append to Polygon" m_PolygonsBuildToolsMenu.kPolyBuildApndToPolyTool1;
displayString -replace -value "Select border edges to append a face to the selected shell" m_PolygonsBuildToolsMenu.kPolyBuildApndToPolyToolAnnot;
displayString -replace -value "Append to polygon tool options" m_PolygonsBuildToolsMenu.kPolyBuildApndToPolyToolOptionsAnnot;
displayString -replace -value "Duplicate Edge Loop Tool Options" m_PolygonsBuildToolsMenu.kPolyBuildDuplicateEdgeLoopToolOptions;
displayString -replace -value "Insert Edge Loop" m_PolygonsBuildToolsMenu.kPolyBuildInsertEdgeLoopTool1;
displayString -replace -value "Offset Edge Loop" m_PolygonsBuildToolsMenu.kPolyBuildOffsetEdgeLoopTool1;
displayString -replace -value "Offset Edge Loop Tool: " m_PolygonsBuildToolsMenu.kPolyBuildOffsetEdgeLoopToolAnnot;
displayString -replace -value "Slide Edge" m_PolygonsBuildToolsMenu.kPolyBuildSlideEdgeTool1;
displayString -replace -value "Sculpting Tools" m_PolygonsBuildToolsMenu.kPolySculptTools;
displayString -replace -value "Sculpt geometry object" m_PolygonsBuildToolsMenu.kPolySculptToolsAnn;
displayString -replace -value "Relax Tool" m_PolygonsBuildToolsMenu.kRelaxTool;
displayString -replace -value "Repeat Tool" m_PolygonsBuildToolsMenu.kRepeatTool;
displayString -replace -value "Scrape Tool" m_PolygonsBuildToolsMenu.kScrapeTool;
displayString -replace -value "Sculpt Tool" m_PolygonsBuildToolsMenu.kSculptTool;
displayString -replace -value "Smear Tool" m_PolygonsBuildToolsMenu.kSmearTool;
displayString -replace -value "Smooth Tool" m_PolygonsBuildToolsMenu.kSmoothTool;
displayString -replace -value "Spray Tool" m_PolygonsBuildToolsMenu.kSprayTool;
displayString -replace -value "Tools" m_PolygonsBuildToolsMenu.kToolsDivider;
displayString -replace -value "Wax Tool" m_PolygonsBuildToolsMenu.kWaxTool;
