// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.


global proc PolygonsNormalsMenu(string $parent)
//
// Description:
//		Polygon Normals menu
//
{
	if (! `isTrue "PolygonsExists"`) return;
	
	setParent -m $parent; 

	if (`menu -q -ni $parent` == 0) {

			menuItem 
					-label (uiRes("m_PolygonsNormalsMenu.kNewVertexNormalEditTool"))
					-annotation (uiRes("m_PolygonsNormalsMenu.kNewVertexNormalEditToolAnnot"))
					-image "vertexNormalEdit.png"
					-command "PolygonNormalEditTool"
					;

			menuItem -optionBox true
					-label (uiRes("m_PolygonsNormalsMenu.kNewVertexNormalEditBoxOptions"))
					-annotation (uiRes("m_PolygonsNormalsMenu.kNewVertexNormalEditOptionsAnnot"))
					-image "vertexNormalEdit.png" 
					-command "PolygonNormalEditTool; toolPropertyWindow"
					;
					
			menuItem
					-label (uiRes("m_PolygonsNormalsMenu.kSetVertexNormal"))
					-annotation (getRunTimeCommandAnnotation("SetVertexNormal"))
					-image "polySetVertexNormal.png"
					-command "SetVertexNormal" 
					-dragMenuCommand "performPolySetNormal 2"
					-dragDoubleClickCommand "SetVertexNormalOptions"
					;

			menuItem -optionBox true 
					-annotation (getRunTimeCommandAnnotation("SetVertexNormalOptions"))
					-image "polySetVertexNormal.png"
					-command "SetVertexNormalOptions"
					;			

			menuItem -divider true;


			menuItem 
					-label (uiRes("m_PolygonsNormalsMenu.kNewLockNormal"))
					-annotation (uiRes("m_PolygonsNormalsMenu.kNewLockNormalAnnot"))
					-image "polyNormalLock.png"
					-command "polyNormalPerVertex -fn true"
					;


			menuItem 
					-label (uiRes("m_PolygonsNormalsMenu.kNewUnlockNormal"))
					-annotation (uiRes("m_PolygonsNormalsMenu.kNewUnlockNormalAnnot"))
					-image "polyNormalUnlock.png"
					-command "polyNormalPerVertex -ufn true"
					;


			menuItem
				-label (uiRes("m_PolygonsNormalsMenu.kNewAverageNormals"))
				-annotation (getRunTimeCommandAnnotation("AveragePolygonNormals"))
				-image "polyNormalAverage.png"
				-command "AveragePolygonNormals"
				-dragMenuCommand "performPolyAverageNormal 2"
				-dragDoubleClickCommand "AveragePolygonNormalsOptions"
				;

			menuItem -optionBox true
				-image "polyNormalAverage.png"
				-annotation (getRunTimeCommandAnnotation("AveragePolygonNormalsOptions"))
				-command "AveragePolygonNormalsOptions"
				;

			menuItem -divider true;

			menuItem
				-label (uiRes("m_PolygonsNormalsMenu.kNewSetToFace"))
				-annotation (getRunTimeCommandAnnotation("SetToFaceNormals"))
				-image "polyNormalSetToFace.png"
				-command "SetToFaceNormals"
				-dragMenuCommand "performPolySetToFaceNormal 2"
				-dragDoubleClickCommand "SetToFaceNormalsOptions"
				;

			menuItem -optionBox true
				-annotation (getRunTimeCommandAnnotation("SetToFaceNormalsOptions"))
				-image "polyNormalSetToFace.png"
				-command "SetToFaceNormalsOptions"
				;

			menuItem
				-label (uiRes("m_PolygonsNormalsMenu.kNewReverse"))
				-annotation (getRunTimeCommandAnnotation("ReversePolygonNormals"))
				-image "polyNormal.png" 
				-command "ReversePolygonNormals"
				-dragDoubleClickCommand "ReversePolygonNormalsOptions"
				;

			menuItem -optionBox true
				-annotation (getRunTimeCommandAnnotation("ReversePolygonNormalsOptions"))
				-image "polyNormal.png"
				-command "ReversePolygonNormalsOptions"
				;

			menuItem
				-label (uiRes("m_PolygonsNormalsMenu.kNewConform"))
				-annotation (getRunTimeCommandAnnotation("ConformPolygonNormals"))
				-image "polyNormalsConform.png"
				-command "ConformPolygonNormals"
				;


			menuItem -divider true;
			
			menuItem
				-label (uiRes("m_PolygonsNormalsMenu.kNewSoftenEdge"))
				-annotation (getRunTimeCommandAnnotation("PolygonSoftenHarden"))
				-image "polySoftEdge.png"
				-command "SoftPolyEdgeElements 1" 
				;


			menuItem
				-label (uiRes("m_PolygonsNormalsMenu.kNewHardenEdge"))
				-annotation (getRunTimeCommandAnnotation("PolygonSoftenHarden"))
				-image "polyHardEdge.png"
				-command "SoftPolyEdgeElements 0"
				;


			menuItem
				-label (uiRes("m_PolygonsNormalsMenu.kNewSetNormalAngle"))
				-annotation (getRunTimeCommandAnnotation("PolygonSoftenHarden"))
				-image "polyNormalSetAngle.png"
				-command "polySoftEdgeWin" 
				;


		setParent -m ..;

	}

}







