// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  Sept 1997
//
//  Description:
//      Set the shelf style for one shelf tab
//

global proc shelfStyle(string $style, string $size, string $shelfLayout)
{
	int $width;
	int $height;
	int $h;
	int $curSize;
	int $boxWidth;
	int $temp;
	string $curStyle;

	if ($style == "nochange")
		$style = `optionVar -q shelfItemStyle`;

	if ($size == "nochange") 
		$size = `optionVar -q shelfItemSize`;

	if ($size == "small")
		$size = "Small";
	else if ($size == "medium")
		$size = "Medium";
	else if ($size == "large")
		$size = "Large";
	else if ($size == "Large" || $size == "Medium" || $size == "Small") {
		//  okay
	} else {
		//  received bad data
		$size = "Small";
	}
	
	if ($style == "textOnly") {
		$width = 120;
		$height = 20;
		$h = 26;
		$boxWidth = 500;
	} else if ($style == "iconAndTextHorizontal") {
		if ($size == "Small") {
			$width = 150;
			$height = 34;
			$h = 40;
			$boxWidth = 504;
		} else if ($size == "Medium") {
			$width = 128;
			$height = 48;
			$h = 54;
			$boxWidth = 505;
		} else if ($size == "Large") {
			$width = 144;
			$height = 64;
			$h = 70;
			$boxWidth = 506;
		}
	} else if ($style == "iconAndTextVertical") {
		if ($size == "Small") {
			$width = 122;
			$height = 54;
			$h = 60;
			$boxWidth = 507;
		} else if ($size == "Medium") {
			$width = 80;
			$height = 68;
			$h = 74;
			$boxWidth = 508;
		} else if ($size == "Large") {
			$width = 80;
			$height = 84;
			$h = 90;
			$boxWidth = 509;
		}
	} else if ($style == "iconOnly") {	
		if ($size == "Small") {
			$width = 34;
			$height = 34;
			$h = 40;
			$boxWidth = 501;
		} else if ($size == "Medium") {
			$width = 48;
			$height = 48;
			$h = 54;
			$boxWidth = 502;
		} else if ($size == "Large") {
			$width = 64;
			$height = 64;
			$h = 70;
			$boxWidth = 503;
		}
	} else {
		// bad data
		$style = "iconOnly";
		if ($size == "Small") {
			$width = 34;
			$height = 34;
			$h = 40;
			$boxWidth = 501;
		} else if ($size == "Medium") {
			$width = 48;
			$height = 48;
			$h = 54;
			$boxWidth = 502;
		} else if ($size == "Large") {
			$width = 64;
			$height = 64;
			$h = 70;
			$boxWidth = 503;
		}
	}

	shelfLayout -e -st $style -cwh $width $height -h $h $shelfLayout;
}
