// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc string[] stringArrayAddOrRemoveItem(
										 string $originalArray[],
										 int $itemPosition,
										 int $addOrRemove,
										 string $stringToAdd
										 ){
//
//  Description:
//		This proc delets an item from a stringArray.
//
//	Arguments:
//		string $originalArray[]: the string array to modify
//		int $itemPosition: the current position in the array of the item to remove
//		int $addOrRemove: 1=add, 0=remove indexed item
//		string $stringToAdd: if adding, this is the string to add
//		
//	Return:
//		the modified string array
	string $result[];
	int $numItems = `size $originalArray`;
	
	//make sure we can delete the item
	if ($addOrRemove == 1 && $itemPosition > ($numItems - 1) ){
		error (uiRes("m_stringArrayAddOrRemoveItem.kIndexedPositionDoesNotExistInTheArray"));
		return $result;
	}
	
	int $i;//counter for result array
	int $j;//counter for original array

	for ($i=0,$j=0;$j<$numItems;$i++,$j++){
		if ($i == $itemPosition){
			//do nothing but decrement $i so this position is filled next time

			if ($addOrRemove == 0){
				print "\n";
				print (uiRes("m_stringArrayAddOrRemoveItem.kDeleting"));
				print $originalArray[$j];
				//increment $j to skip the current item
				$j++;
				if ($j < $numItems) {
					$result[$i] = $originalArray[$j];
				}
			} else {

				//decrement $j to add this item next time around
				$j--;
				$result[$i] = $stringToAdd;
			}
			
			//$result[$i] = $originalArray[$i];
		} else {
			$result[$i] = $originalArray[$j];
		}
	}

	return $result;
}
