// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  19.Dec.2001
//
//  Description:
//		Save the current visibility state of the main window UI
//		components. Used in conjuction with restoreMainWindowComponents
//		To return the visibility of the components to this state.
//
//  Input Arguments:
//      None.
//
//  Return Value:
//      None.
//
global proc updateMainWindowComponentState()
{
	//	Save the current visibility state of the UI components.
	//
	//	A call to restoreMainWindowComponents will restore the
	//	saved state.
	//
	optionVar -iv LastStateStatusLineVisibility		`isUIComponentVisible("Status Line")`;
	optionVar -iv LastStateShelfVisibility			`isUIComponentVisible("Shelf")`;
	optionVar -iv LastStateTimeSliderVisibility		`isUIComponentVisible("Time Slider")`;
	optionVar -iv LastStatePlaybackRangeVisibility	`isUIComponentVisible("Range Slider")`;
	optionVar -iv LastStateCommandLineVisibility	`isUIComponentVisible("Command Line")`;
	optionVar -iv LastStateHelpLineVisibility		`isUIComponentVisible("Help Line")`;
	optionVar -iv LastStateToolboxVisibility		`isUIComponentVisible("Tool Box")`;
	optionVar -iv LastStateAEVisibility				`isUIComponentVisible("Attribute Editor")`;
	optionVar -iv LastStateToolSettingsVisibility	`isUIComponentVisible("Tool Settings")`;
	optionVar -iv LastStateChannelsLayersVisibility	`isUIComponentVisible("Channel Box / Layer Editor")`;
	optionVar -iv LastStateChannelsVisibility		`isUIComponentVisible("Channel Box")`;
	optionVar -iv LastStateLayersVisibility			`isUIComponentVisible("Layer Editor")`;
}
