// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc
createWebBrowserPanel (string $whichPanel)
//
//  Description:
//		Define the editors that are used in this panel.
//		No controls are created at this point.
//
{
}

global proc
addWebBrowserPanel (string $whichPanel)
//
//  Description:
//		Add the panel to a layout.
//		Parent the editors to that layout and create any other
//		controls required.
//
{
	string $browserControl = ($whichPanel + "BrowserControl");

	// Make sure that there is no template active
	setUITemplate -pushTemplate NONE;

	// Define the standard panel
	//
	string $widgetList[];

	$widgetList[2] = `scriptedPanel -query -control $whichPanel`;
	$widgetList[0] = `formLayout`;
	$widgetList[3] = `frameLayout -visible true -borderVisible false
			-labelVisible false -collapsable false -collapse true
			`;
	$widgetList[4] = `formLayout -visible true`;
	setParent $widgetList[0];
	$widgetList[5] = `formLayout -visible true`;

	formLayout -edit
		-attachForm $widgetList[3] top 0 
		-attachForm $widgetList[3] right 0
		-attachForm $widgetList[3] left 0

		-attachControl $widgetList[5] top 0 $widgetList[3]
		-attachForm $widgetList[5] bottom 0
		-attachForm $widgetList[5] right 0
		-attachForm $widgetList[5] left 0
		$widgetList[0];

	setParent $widgetList[5];

	// Create dummy control
	webBrowser $browserControl;

	formLayout -edit
		-attachForm $browserControl top 0 
		-attachForm $browserControl right 0
		-attachForm $browserControl left 0
		-attachForm $browserControl bottom 0
		$widgetList[5];
	
	setParent -top;

	setUITemplate -popTemplate;
}

global proc
removeWebBrowserPanel (string $whichPanel)
//
//  Description:
//		Remove the panel from a layout.
//		Delete controls.
//
{
}

global proc
deleteWebBrowserPanel (string $whichPanel)
//
//  Description:
//		This proc will delete the contents of the panel, but not
//		the panel itself.
//
//  Note:
//		We only need to delete editors here.  Other UI will be taken care of
//		by the remove proc.
//
{
}

global proc string
saveStateWebBrowserPanel (string $whichPanel)
//
//  Description:
//		This proc returns a string that when executed will restore the
//		current state of the panel elements.
//
{
	return ("");
}

global proc
showWebBrowserPanel (string $inURL)
//
//  Description:
//		This proc replaces the currently focused panel with web browser panel
//		if it's not among visible panels, then it navigates web browser control
//		specified URL
{
}
