// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

// Description:  This procedure is called to add new bins to 
//      the hyper shade bin list.
//
global proc addBinsToHyperShadeBinList(string $newBins[])
{
    if (size($newBins) == 0)
    {
        // Nothing to add.
        //
        return;
    }

    string $binList = `getAttr defaultRenderGlobals.hyperShadeBinList`;
    
    string $binName;
    string $newBinList = $binList;
    for ($binName in $newBins)
    {
        if (!isValidBinName($binName))
        {
            continue;
        }
        if (binNameExistsInHyperShadeBinList($binName))
        {
            // This binName already exists in the bin list.  
            //
            continue;
        }
        if ($binList == "")
        {
            $newBinList = $binName;
        }
        else
        {
            $newBinList += ";"+$binName;
        }
    }

    if ($newBinList != $binList)
    {
        setAttr defaultRenderGlobals.hyperShadeBinList -type "string" $newBinList;
    }
}
