// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

// 
//  Description:
//      Define the appearance of the attribute editor for the
//      bulletRigidBodyConstraint node. 
//

global proc callUpdateConstraintUI( string $nodeName )
{
    python ("import maya.app.mayabullet.RigidBodyConstraintUI as rbcUI; rbcUI.updateConstraintUI( \"" + $nodeName + "\" )");
}


global proc AEbulletRigidBodyConstraintShapeTemplate ( string $nodeName )
{
    editorTemplate -beginScrollLayout;

    // Add
    editorTemplate -addControl constraintType callUpdateConstraintUI;
    editorTemplate -addControl useReferenceFrame;
    editorTemplate -callCustom ("AEinputNew \"RigidBodyA\"")
                               ("AEinputReplace \"RigidBodyA\"")
                                "rigidBodyA";        
    editorTemplate -callCustom ("AEinputNew \"RigidBodyB\"")
                               ("AEinputReplace \"RigidBodyB\"")
                                "rigidBodyB";        

    editorTemplate -beginLayout (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kConstraintProperties")) -collapse true;
    editorTemplate -ann (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kBreakableAnn"))
        -addControl breakable;
    editorTemplate -ann (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kBreakingThresholdAnn"))
        -addControl breakingThreshold;

    editorTemplate -addControl linearDamping;
    editorTemplate -addControl linearSoftness;
    editorTemplate -addControl linearRestitution;

    editorTemplate -addControl angularDamping;
    editorTemplate -addControl angularSoftness;
    editorTemplate -addControl angularRestitution;
    editorTemplate -endLayout;

    editorTemplate -beginLayout (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kLimits")) -collapse true;
    editorTemplate -addControl linearConstraintX;
    editorTemplate -addControl linearConstraintY;
    editorTemplate -addControl linearConstraintZ;
    editorTemplate -addControl linearConstraintMin;
    editorTemplate -addControl linearConstraintMax;

    editorTemplate -addControl angularConstraintX;
    editorTemplate -addControl angularConstraintY;
    editorTemplate -addControl angularConstraintZ;
    editorTemplate -addControl angularConstraintMin;
    editorTemplate -addControl angularConstraintMax;
    editorTemplate -endLayout;

    editorTemplate -beginLayout (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kLimitProperties")) -collapse true;
    editorTemplate -addControl linearLimitSoftness;
    editorTemplate -addControl linearLimitBias;
    editorTemplate -addControl linearLimitRelaxation;

    editorTemplate -addControl angularLimitSoftness;
    editorTemplate -addControl angularLimitBias;
    editorTemplate -addControl angularLimitRelaxation;
    editorTemplate -endLayout;    

    editorTemplate -beginLayout (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kMotors")) -collapse true;
    editorTemplate -addControl linearMotorEnabled callUpdateConstraintUI;
    editorTemplate -addControl linearMotorTargetSpeed;
    editorTemplate -addControl linearMotorMaxForce;

    editorTemplate -addControl angularMotorEnabled callUpdateConstraintUI;
    editorTemplate -addControl angularMotorTargetSpeed;
    editorTemplate -addControl angularMotorMaxForce;
    editorTemplate -endLayout;

    editorTemplate -beginLayout (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kSprings")) -collapse true;

    editorTemplate -beginNoOptimize;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kLinearSpringEnabledX")) -addControl linearSpringEnabledX;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kLinearSpringEnabledY")) -addControl linearSpringEnabledY;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kLinearSpringEnabledZ")) -addControl linearSpringEnabledZ;
    editorTemplate -endNoOptimize;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kLinearSpringStiffness")) -addControl linearSpringStiffness;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kLinearSpringDamping")) -addControl linearSpringDamping;

    editorTemplate -beginNoOptimize;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kAngularSpringEnabledX")) -addControl angularSpringEnabledX;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kAngularSpringEnabledY")) -addControl angularSpringEnabledY;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kAngularSpringEnabledZ")) -addControl angularSpringEnabledZ;
    editorTemplate -endNoOptimize;
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kAngularSpringStiffness")) -addControl angularSpringStiffness; 
    editorTemplate -label (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kAngularSpringDamping")) -addControl angularSpringDamping;

    editorTemplate -endLayout;

    // System Properties
    editorTemplate -beginLayout (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kDynamicsSystem")) -collapse true;
	string $solver = (uiRes("m_AEbulletRigidBodyConstraintShapeTemplate.kSolver"));
    editorTemplate -callCustom ("AEinputNew \"" + $solver + "\"")
                               ("AEinputReplace \"" + $solver + "\"")
                                "solverInitialized";        
    editorTemplate -endLayout;

    // Inherit
    AEshapeTemplate( $nodeName );

    // Suppress
    //editorTemplate -suppress rigidBody1;
    //editorTemplate -suppress rigidBody1;
    //editorTemplate -suppress currentTime;

    editorTemplate -addExtraControls;
    editorTemplate -endScrollLayout;
}
