// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Basic Fields" m_AEbulletSolverShapeTemplate.kBasicFields;
displayString -replace -value "Collision Filters" m_AEbulletSolverShapeTemplate.kCollisionFilters;
displayString -replace -value "Toggles the state of the solver." m_AEbulletSolverShapeTemplate.kEnableSimulation;
displayString -replace -value "Create a static ground plane at the world origin." m_AEbulletSolverShapeTemplate.kGroundPlane;
displayString -replace -value "Determines the frame rate used the simulation and is independent of the timelines playback speed. Higher values will \"speed up\" simulation" m_AEbulletSolverShapeTemplate.kInternalFixedFrameRate;
displayString -replace -value "Number of times the simulation is evaluated 'between' each frame step on the timeline. The value of 10 should work for most simulations." m_AEbulletSolverShapeTemplate.kMaxNumIterations;
displayString -replace -value "Determines whether to use the software solver or an OpenCL CPU or OpenCL GPU based-solver." m_AEbulletSolverShapeTemplate.kSolverAcceleration;
displayString -replace -value "Solver Display" m_AEbulletSolverShapeTemplate.kSolverDisplay;
displayString -replace -value "Solver Properties" m_AEbulletSolverShapeTemplate.kSolverProperties;
displayString -replace -value "Split Impulse allows the solver to apply positional corrections when deep collision penetrations occur. These corrections do not affect resulting velocities." m_AEbulletSolverShapeTemplate.kSplitImpulse;
displayString -replace -value "Defines the starting time for the simulation." m_AEbulletSolverShapeTemplate.kStartTime;
