// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//	Description:
//		Define the appearance of the attribute editor for the bulletInitialState node.
//

global proc callUpdateNeverSleep( string $nodeName )
{
	/*
	Called when the attribute editor UI for the rigid body
	needs to be updated to reflect the latest attribute
	values. Enables and disables controls.
	*/
	$neverSleeps = getAttr($nodeName+".neverSleeps");

	editorTemplate 
		-dimControl $nodeName "initiallySleeping" $neverSleeps;
}


global proc AEbulletInitialStateTemplate ( string $nodeName )
{
	editorTemplate -beginScrollLayout;

		editorTemplate -beginLayout (uiRes("m_AEbulletInitialStateTemplate.kRigidAttributes"));
			editorTemplate -addControl "defaultMass";
			editorTemplate -addControl "linearDamping";
			editorTemplate -addControl "angularDamping";
			editorTemplate -addControl "friction";
			editorTemplate -addControl "restitution";
		editorTemplate -endLayout;

		// Initial Conditions
		editorTemplate -beginLayout (uiRes("m_AEbulletInitialStateTemplate.kInitConditions")) -collapse true;
			editorTemplate -addControl "neverSleeps"			callUpdateNeverSleep;
			editorTemplate -addControl "initiallySleeping";
			editorTemplate -addControl "initialVelocity";
			editorTemplate -addControl "initialAngularVelocity";
			editorTemplate -ann (uiRes("m_AEbulletInitialStateTemplate.kGlueShapes"))
			-addControl "glueShapes";
			editorTemplate -ann (uiRes("m_AEbulletInitialStateTemplate.kBreakThreshold"))
			-addControl "glueBreakingThreshold";
			editorTemplate -label (uiRes("m_AEbulletInitialStateTemplate.kGlueMaxConstraintsPerBodyLabel"))
			-ann (uiRes("m_AEbulletInitialStateTemplate.kGlueMaxConstraintsPerBody"))
			-addControl "glueMaxConstraintsPerBody";
		editorTemplate -endLayout;

/*		WANT_BULLET_RIGIDSET_IMPULSE
		// Forces/Impulses
		editorTemplate -beginLayout (uiRes("m_AEbulletInitialStateTemplate.kForces")) -collapse true;
		editorTemplate -addControl impulse;
		editorTemplate -addControl impulsePosition;
		editorTemplate -addControl torqueImpulse;
		editorTemplate -endLayout;
*/

		// Collider Attributes
		editorTemplate -beginLayout (uiRes("m_AEbulletInitialStateTemplate.kCollisionAttributes"));
			editorTemplate -addControl "collisionShapeType";
			editorTemplate -addControl "collisionFilterGroup";
			editorTemplate -addControl "collisionFilterMask";
			editorTemplate -ann (uiRes("m_AEbulletInitialStateTemplate.kCollisionShapeMargin"))
				-addControl "collisionShapeMargin";
		editorTemplate -endLayout;
		
		// include/call base class/node attributes
		AEsurfaceShapeTemplate $nodeName;

	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;

	editorTemplate -suppress "solver";
	editorTemplate -suppress "solvedState";
    editorTemplate -suppress "collisionOffsetVelocityIncrement";
    editorTemplate -suppress "collisionDepthVelocityIncrement";
    editorTemplate -suppress "collisionOffsetVelocityMultiplier";
    editorTemplate -suppress "collisionDepthVelocityMultiplier";


	editorTemplate -suppress "bodyType";	// hidden this attribute
}



