// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "All" m_art3dPaintProperties.kAll;
displayString -replace -value "Artisan: " m_art3dPaintProperties.kArtisan;
displayString -replace -value "Artisan stamp profiles" m_art3dPaintProperties.kArtisanAnnot;
displayString -replace -value "Artisan pressure:" m_art3dPaintProperties.kArtisanPressure;
displayString -replace -value "Assign/Edit Textures" m_art3dPaintProperties.kAssignEditTextures;
displayString -replace -value "Assign/Edit file textures for a selected shader attribute to paint" m_art3dPaintProperties.kAssignEditTexturesAnnot;
displayString -replace -value "Attribute paint operation" m_art3dPaintProperties.kAttributePaintAnnot;
displayString -replace -value "Attribute to paint:" m_art3dPaintProperties.kAttributeToPaint;
displayString -replace -value "Azimuth" m_art3dPaintProperties.kAzimuth;
displayString -replace -value "Blend mode: " m_art3dPaintProperties.kBlendMode;
displayString -replace -value "Blend mode" m_art3dPaintProperties.kBlendModeAnnot;
displayString -replace -value "Blur" m_art3dPaintProperties.kBlur;
displayString -replace -value "Blur intensity:" m_art3dPaintProperties.kBlurIntensity;
displayString -replace -value "Both" m_art3dPaintProperties.kBoth;
displayString -replace -value "Brush" m_art3dPaintProperties.kBrush;
displayString -replace -value "Brush alignment: path alignment or up vector" m_art3dPaintProperties.kBrushAlignmentAnnot;
displayString -replace -value "Brush opacity" m_art3dPaintProperties.kBrushOpacityAnnot;
displayString -replace -value "Brush radius" m_art3dPaintProperties.kBrushRadiusAnnot;
displayString -replace -value "Clone" m_art3dPaintProperties.kClone;
displayString -replace -value "Clone brush mode:" m_art3dPaintProperties.kCloneBrushMode;
displayString -replace -value "Clone brush mode" m_art3dPaintProperties.kCloneBrushModeAnnot;
displayString -replace -value "Color" m_art3dPaintProperties.kColorOptions;
displayString -replace -value "Color value:" m_art3dPaintProperties.kColorValue;
displayString -replace -value "Constant" m_art3dPaintProperties.kConstant;
displayString -replace -value "Control the intensity of the blur" m_art3dPaintProperties.kControltheIntensityAnnot;
displayString -replace -value "Curl" m_art3dPaintProperties.kCurl;
displayString -replace -value "Darken" m_art3dPaintProperties.kDarken;
displayString -replace -value "Default" m_art3dPaintProperties.kDefault;
displayString -replace -value "Display" m_art3dPaintProperties.kDisplay;
displayString -replace -value "Draw brush feedback" m_art3dPaintProperties.kDrawBrushFeedback;
displayString -replace -value "Draw additional brush feedback" m_art3dPaintProperties.kDrawBrushFeedbackAnnot;
displayString -replace -value "Draw outline" m_art3dPaintProperties.kDrawOutline;
displayString -replace -value "Draw brush outline" m_art3dPaintProperties.kDrawOutlineAnnot;
displayString -replace -value "Draw outline while painting" m_art3dPaintProperties.kDrawOutlineWhilePainting;
displayString -replace -value "Turn on/off brush feedback while painting" m_art3dPaintProperties.kDrawOutlineWhilePaintingAnnot;
displayString -replace -value "Dynamic" m_art3dPaintProperties.kDynamic;
displayString -replace -value "Edit template brush" m_art3dPaintProperties.kEditTemplateBrushAnnot;
displayString -replace -value "Elevation" m_art3dPaintProperties.kElevation;
displayString -replace -value "Erase" m_art3dPaintProperties.kErase;
displayString -replace -value "Extend seam color" m_art3dPaintProperties.kExtendSeamColor;
displayString -replace -value "Average the color background pixels" m_art3dPaintProperties.kExtendSeamColorAnnot;
displayString -replace -value "File browser for shape profiles" m_art3dPaintProperties.kFileAnnot;
displayString -replace -value "File Textures" m_art3dPaintProperties.kFileTextures;
displayString -replace -value "Flood:" m_art3dPaintProperties.kFlood;
displayString -replace -value "Color:" m_art3dPaintProperties.kFloodColor;
displayString -replace -value "Flood color" m_art3dPaintProperties.kFloodColorAnnot;
displayString -replace -value "Flood Erase" m_art3dPaintProperties.kFloodErase;
displayString -replace -value "Flood erase" m_art3dPaintProperties.kFloodEraseAnnot;
displayString -replace -value "Opacity:" m_art3dPaintProperties.kFloodOpacity;
displayString -replace -value "Flood opacity" m_art3dPaintProperties.kFloodOpacityAnnot;
displayString -replace -value "Flood" m_art3dPaintProperties.kFloodOptions;
displayString -replace -value "Flood Paint" m_art3dPaintProperties.kFloodPaint;
displayString -replace -value "Flood paint" m_art3dPaintProperties.kFloodPaintAnnot;
displayString -replace -value "Flooding option" m_art3dPaintProperties.kFloodingOptionAnnot;
displayString -replace -value "Gaussian brush profile" m_art3dPaintProperties.kGaussianAnnot;
displayString -replace -value "Get brush" m_art3dPaintProperties.kGetBrushAnnot;
displayString -replace -value "Glow spread" m_art3dPaintProperties.kGlowSpread;
displayString -replace -value "Last brush" m_art3dPaintProperties.kLastBrushAnnot;
displayString -replace -value "Lighten" m_art3dPaintProperties.kLighten;
displayString -replace -value "Mapping of the tablet pressure" m_art3dPaintProperties.kMappingAnnot;
displayString -replace -value "Color" m_art3dPaintProperties.kMenuItemColor;
displayString -replace -value "Incandescence" m_art3dPaintProperties.kMenuItemIncandescence;
displayString -replace -value "Opacity" m_art3dPaintProperties.kMenuItemOpacity;
displayString -replace -value "Transparency" m_art3dPaintProperties.kMenuItemTransparency;
displayString -replace -value "Multiply" m_art3dPaintProperties.kMultiply;
displayString -replace -value "Noise" m_art3dPaintProperties.kNoise;
displayString -replace -value "Num leaves" m_art3dPaintProperties.kNumLeaves;
displayString -replace -value "Num petals" m_art3dPaintProperties.kNumPetals;
displayString -replace -value "Num twigs" m_art3dPaintProperties.kNumTwigs;
displayString -replace -value "Off" m_art3dPaintProperties.kOff;
displayString -replace -value "Opacity:" m_art3dPaintProperties.kOpacity;
displayString -replace -value "Overlay" m_art3dPaintProperties.kOverlay;
displayString -replace -value "Paint" m_art3dPaintProperties.kPaint;
displayString -replace -value "Paint Effects brushes" m_art3dPaintProperties.kPaintAnnot;
displayString -replace -value "Paint color" m_art3dPaintProperties.kPaintColorAnnot;
displayString -replace -value "Paint Effects:" m_art3dPaintProperties.kPaintEffects;
displayString -replace -value "Paint Effects pressure:" m_art3dPaintProperties.kPaintEffectsPressure;
displayString -replace -value "Paint mode" m_art3dPaintProperties.kPaintModeAnnot;
displayString -replace -value "Paint Operations" m_art3dPaintProperties.kPaintOperations;
displayString -replace -value "Path attract" m_art3dPaintProperties.kPathAttract;
displayString -replace -value "Path follow" m_art3dPaintProperties.kPathFollow;
displayString -replace -value "Pressure map 1:" m_art3dPaintProperties.kPressureMap1;
displayString -replace -value "Pressure map 2:" m_art3dPaintProperties.kPressureMap2;
displayString -replace -value "Pressure map 3:" m_art3dPaintProperties.kPressureMap3;
displayString -replace -value "Pressure max 1:" m_art3dPaintProperties.kPressureMax1;
displayString -replace -value "Pressure max 2:" m_art3dPaintProperties.kPressureMax2;
displayString -replace -value "Pressure max 3:" m_art3dPaintProperties.kPressureMax3;
displayString -replace -value "Pressure min 1:" m_art3dPaintProperties.kPressureMin1;
displayString -replace -value "Pressure min 2:" m_art3dPaintProperties.kPressureMin2;
displayString -replace -value "Pressure min 3:" m_art3dPaintProperties.kPressureMin3;
displayString -replace -value "Artisan:" m_art3dPaintProperties.kRadioBtnGroupArtisan;
displayString -replace -value "Paint Effects:" m_art3dPaintProperties.kRadioBtnGroupPaintEffects;
displayString -replace -value "Radius" m_art3dPaintProperties.kRadius;
displayString -replace -value "Radius (L):" m_art3dPaintProperties.kRadiusL;
displayString -replace -value "Lower brush radius limit" m_art3dPaintProperties.kRadiusLimitAnnot;
displayString -replace -value "Radius (U):" m_art3dPaintProperties.kRadiusU;
displayString -replace -value "Random" m_art3dPaintProperties.kRandom;
displayString -replace -value "Reflection" m_art3dPaintProperties.kReflection;
displayString -replace -value "Reflection mode" m_art3dPaintProperties.kReflectionAnnot;
displayString -replace -value "Reflection axis:" m_art3dPaintProperties.kReflectionAxis;
displayString -replace -value "Selection of reflection axis" m_art3dPaintProperties.kReflectionAxisAnnot;
displayString -replace -value "Reload File Textures" m_art3dPaintProperties.kReloadFileTextures;
displayString -replace -value "Reload textures from the disk" m_art3dPaintProperties.kReloadFileTexturesAnnot;
displayString -replace -value "Reset brushes and profiles to defaults" m_art3dPaintProperties.kResetAnnot;
displayString -replace -value "Reset Brushes" m_art3dPaintProperties.kResetBrushes;
displayString -replace -value "Rotate to stroke" m_art3dPaintProperties.kRotateToStroke;
displayString -replace -value "Save texture on stroke" m_art3dPaintProperties.kSaveTextureOnStroke;
displayString -replace -value "Save textures on disk on each stroke" m_art3dPaintProperties.kSaveTextureOnStrokeAnnot;
displayString -replace -value "Save Textures" m_art3dPaintProperties.kSaveTextures;
displayString -replace -value "Save textures to the disk" m_art3dPaintProperties.kSaveTexturesAnnot;
displayString -replace -value "Scale" m_art3dPaintProperties.kScale;
displayString -replace -value "Screen" m_art3dPaintProperties.kScreen;
displayString -replace -value "Screen projection" m_art3dPaintProperties.kScreenProjection;
displayString -replace -value "Selected faces" m_art3dPaintProperties.kSelectedFaces;
displayString -replace -value "Set Clone Source" m_art3dPaintProperties.kSetCloneSource;
displayString -replace -value "Set Erase Image" m_art3dPaintProperties.kSetEraseImage;
displayString -replace -value "Set/Update erase image for restoring" m_art3dPaintProperties.kSetUpdateAnnot;
displayString -replace -value "Shader attribute to paint" m_art3dPaintProperties.kShaderAnnot;
displayString -replace -value "Last image file - shape brush profile " m_art3dPaintProperties.kShapeBrushAnnot;
displayString -replace -value "Show wireframe" m_art3dPaintProperties.kShowWireframe;
displayString -replace -value "Draw wireframe in shaded mode" m_art3dPaintProperties.kShowWireframeAnnot;
displayString -replace -value "Smear" m_art3dPaintProperties.kSmear;
displayString -replace -value "Soft brush profile" m_art3dPaintProperties.kSoftBrushAnnot;
displayString -replace -value "Softness" m_art3dPaintProperties.kSoftness;
displayString -replace -value "Solid brush profile" m_art3dPaintProperties.kSolidBrushAnnot;
displayString -replace -value "Solo as diffuse" m_art3dPaintProperties.kSoloAsDiffuse;
displayString -replace -value "View the texture as a diffuse color texture in the viewport" m_art3dPaintProperties.kSoloAsDiffuseAnnot;
displayString -replace -value "Square brush profile" m_art3dPaintProperties.kSquareBrushAnnot;
displayString -replace -value "Stamp depth:" m_art3dPaintProperties.kStampDepth;
displayString -replace -value "Depth of a single stamp" m_art3dPaintProperties.kStampDepthAnnot;
displayString -replace -value "Stamp spacing:" m_art3dPaintProperties.kStampSpacing;
displayString -replace -value "Spacing between stamps" m_art3dPaintProperties.kStampSpacingAnnot;
displayString -replace -value "Static" m_art3dPaintProperties.kStatic;
displayString -replace -value "Stroke" m_art3dPaintProperties.kStroke;
displayString -replace -value "Stylus pressure" m_art3dPaintProperties.kStylusPressure;
displayString -replace -value "Turn on/off stylus pressure" m_art3dPaintProperties.kStylusPressureAnnot;
displayString -replace -value "Stylus Pressure" m_art3dPaintProperties.kStylusPressureOptions;
displayString -replace -value "Surface offset" m_art3dPaintProperties.kSurfaceOffset;
displayString -replace -value "Switch to clone source selection mode" m_art3dPaintProperties.kSwitchtoCloneAnnot;
displayString -replace -value "Tube length" m_art3dPaintProperties.kTubeLength;
displayString -replace -value "Tube width" m_art3dPaintProperties.kTubeWidth;
displayString -replace -value "Tubes per step" m_art3dPaintProperties.kTubesPerStep;
displayString -replace -value "Turbulence" m_art3dPaintProperties.kTurbulence;
displayString -replace -value "Update on stroke" m_art3dPaintProperties.kUpdateOnStroke;
displayString -replace -value "Update textures on disk on each stroke" m_art3dPaintProperties.kUpdateOnStrokeAnnot;
displayString -replace -value "Width" m_art3dPaintProperties.kWidth;
displayString -replace -value "Wiggle" m_art3dPaintProperties.kWiggle;
displayString -replace -value "X " m_art3dPaintProperties.kX;
displayString -replace -value "Y " m_art3dPaintProperties.kY;
displayString -replace -value "Z" m_art3dPaintProperties.kZ;
