// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  December 2005
//
//  Description:
//      Update UI values from context
//
//  Procedure Name:
//      artAttrNComponentValues
//
//  Description:
//      Initialize the option values.
//
//  Input Arguments:
//
//  Return Value:
//      None.
//

global string $gArtAttrNComponentCurrentAttr = "";

global proc artNComponentPaintValues( 
	string 	$artCommand,
	string	$currTool
)
//
//	Paint NComponentFile Weights tool values.
//
{
	// Common Attribute Paint UI.
	artAttrCommonValues( $artCommand, $currTool );
}

// =======================================================
// Main callback procedure for Paint Selecion tool.
// =======================================================
global proc artAttrNComponentValues(
	string 	$toolName
)
{
	global string $gArtAttrNComponentCurrentAttr;
 
	source "artisanCallback.mel";
    source "artisanValues.mel";

    source "artAttrValues.mel";

	string 	$artCommand	 = "artAttrCtx";
	string	$currContext = `currentCtx`;
	string	$currTool	 = `contextInfo -c $currContext`;

	// Provide a different icon for different attribute tools.
	string $icon	= "paintBlendshape.png";
	string $helpTag = "PaintNComponentWeightsTool";

	string $parent = (`toolPropertyWindow -q -location` + "|artAttrNComponent");
	setParent $parent;

	if ("" != $gArtAttrNComponentCurrentAttr) {
		if (! `exists nComponentAttributeToPaint_melToUI` ) {
			source "artAttrNComponentProperties.mel";
		}
		string $selectedItem = nComponentAttributeToPaint_melToUI($gArtAttrNComponentCurrentAttr);
		optionMenuGrp -e -value $selectedItem NComponentPaintAttrMenu;
	}
	
	toolPropertySetCommon $toolName $icon $helpTag;

	// Brush frameLayout values.
	artisanBrushValues( $artCommand, $currTool );

	// NComponentFile Paint Weights frameLayout values.
   	artNComponentPaintValues( $artCommand, $currTool );

	// Stroke frameLayout values.
	artisanStrokeValues( $artCommand, $currTool );

	// Stylus Pressure frameLayout values.
	artisanPressureValues( $artCommand, $currTool );

	// Attribute Maps frameLayout values.
	artisanAttrMapValues( $artCommand, $currTool );

	// Display frameLayout values.
	artisanDisplayValues( $artCommand, $currTool );

	toolPropertySelect artAttrNComponent;
}
