// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
// Creation Date:  December 2005
//
//  Procedure Name:
//     	artAttrNComponentToolScript	
//
//  Description:
//		Invoke the Paint NComponent Attributes Tool with or without options window.
//
//  Input Arguments:
//		4 ==> enter the tool (create if necessary)
//      3 ==> property sheet box
//
//  Return Value:
//      None.
//


global proc string artAttrNComponentToolScript( 
	int $setToTool,
	string $attr
)
//
//	Description :
//      $setToTool: 3 = open tool options, 4 = don't open tool options
//		$attr = attribute to paint
{
	global string $gArtAttrNComponentCurrentAttr;
	$gArtAttrNComponentCurrentAttr = $attr;

	makePaintable -attrType "doubleArray" "nComponent" "strengthPerVertex";
	makePaintable -attrType "doubleArray" "nComponent" "glueStrengthPerVertex";
	makePaintable -attrType "doubleArray" "nComponent" "weightPerVertex";	
	
	// NComponent Paint Attributes Tool
	string $tool = "artAttrNComponentContext";

	if( ! `artAttrCtx -exists $tool` ) {
		rememberCtxSettings 
		 `artAttrCtx -i1 "attrPaint.png" -whichTool "NComponentPaint" $tool`;
	}
	setToolTo $tool;
	NComponentPaintCallback $attr;

	if( 3 == $setToTool ) {
		toolPropertyWindow;
	}
	else if( 4 != $setToTool ) {
		warning( (uiRes("m_artAttrNComponentToolScript.kWrongInput")) );
	}

	return $tool;
}
