// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//////////////////////////////////////////////////////////////////////////////
//	This file contains the MEL script to create the Paintable Attribute Menu
//////////////////////////////////////////////////////////////////////////////

proc string paintableAttributes_uiToMel(string $ui)
{
	string $mel = $ui;
	
	if( $ui == (uiRes("m_artFluidAttrProperties.kDensity")) ) {
		$mel = "Density";
	} else if( $ui == (uiRes("m_artFluidAttrProperties.kDensityAndColor")) ) {
		$mel = "Density and color";
	} else if( $ui == (uiRes("m_artFluidAttrProperties.kDensityAndFuel")) ) {
	    $mel = "Density and fuel";
	} else if( $ui == (uiRes("m_artFluidAttrProperties.kVelocity")) ) {
	    $mel = "Velocity";
	} else if( $ui == (uiRes("m_artFluidAttrProperties.kTemperature")) ) {
	    $mel = "Temperature";
	} else if( $ui == (uiRes("m_artFluidAttrProperties.kFuel")) ) {
	    $mel = "Fuel";
	} else if( $ui == (uiRes("m_artFluidAttrProperties.kColor")) ) {
	    $mel = "Color";
	} else if( $ui == (uiRes("m_artFluidAttrProperties.kFalloff")) ) {
	    $mel = "Falloff";
	} else {
		uiToMelMsg( "paintableAttributes_uiToMel", $ui, 1 );
	}
	
	return $mel;
}

global proc artFluidAttrPaintMenu( string $artCommand ) 
//
//	Description:
// 		Creates a menu that shows all the paintable attributes
// 
{
	string $attr;
	int    $velocity = 0;

	if( `optionMenuGrp -exists artAttrListOptionMenu` ) {
		$attr = `optionMenuGrp -q -v artAttrListOptionMenu`;
	} else {
		$attr = eval( $artCommand + " -q -p `currentCtx`; " );
	}

	$attr = substituteAllString( tolower( paintableAttributes_uiToMel($attr) ), " ", "" );
	$velocity = ($attr == "velocity");

	artFluidAttrVerifyGrid( $attr );

	// Setting the property here will issue an error if we're
	// painting on an unpaintable fluid property.
	//
	catch( evalEcho( $artCommand + " -e " + 
					 " -property " + $attr + 
					 " -displayVelocity " + $velocity + 
					 " `currentCtx`; " ) );
}

