// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Alias" m_artisanCallback.kAlias;
displayString -replace -value "Alpha" m_artisanCallback.kAlpha;
displayString -replace -value "Blue" m_artisanCallback.kBlue;
displayString -replace -value "Both" m_artisanCallback.kBoth;
displayString -replace -value "The maximum set color range value was below the minimum set color range value. The maximum color range value is now equal to the minimum color range value." m_artisanCallback.kColorRangeMaxBelowColorRangeMin;
displayString -replace -value "The minimum set color range value exceeded the maximum set color range value. The minimum color range value is now equal to the maximum color range value." m_artisanCallback.kColorRangeMinExceedsColorRangeMax;
displayString -replace -value "EPS" m_artisanCallback.kEPS;
displayString -replace -value "Export" m_artisanCallback.kExport;
displayString -replace -value "GIF" m_artisanCallback.kGIF;
displayString -replace -value "Green" m_artisanCallback.kGreen;
displayString -replace -value "IFF" m_artisanCallback.kIFF;
displayString -replace -value "Import" m_artisanCallback.kImport;
displayString -replace -value "JPEG" m_artisanCallback.kJPEG;
displayString -replace -value "Luminance" m_artisanCallback.kLuminance;
displayString -replace -value "MacPaint" m_artisanCallback.kMacPaint;
displayString -replace -value "Opacity" m_artisanCallback.kOpacity;
displayString -replace -value "Open" m_artisanCallback.kOpen;
displayString -replace -value "PNG" m_artisanCallback.kPNG;
displayString -replace -value "Photoshop" m_artisanCallback.kPhotoshop;
displayString -replace -value "QuickDraw" m_artisanCallback.kQuickDraw;
displayString -replace -value "QuickTime Image" m_artisanCallback.kQuickTimeImage;
displayString -replace -value "RGB" m_artisanCallback.kRGB;
displayString -replace -value "RGBA" m_artisanCallback.kRGBA;
displayString -replace -value "RLA" m_artisanCallback.kRLA;
displayString -replace -value "Radius" m_artisanCallback.kRadius;
displayString -replace -value "Red" m_artisanCallback.kRed;
displayString -replace -value "SGI" m_artisanCallback.kSGI;
displayString -replace -value "SoftImage" m_artisanCallback.kSoftImage;
displayString -replace -value "TIFF" m_artisanCallback.kTIFF;
displayString -replace -value "Targa" m_artisanCallback.kTarga;
displayString -replace -value "WindowsBitmap" m_artisanCallback.kWindowsBitmap;
