// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  May 2003
//
//  
//  Description:
//      Has functions which give configuration information for various Artisan tools
//
//  Procedures :
//			isExportPanelUsed
//
//  Input Arguments:
//		None
//
//  Return Value:
//      True if export attribute panel is to be added to the UI
//

global proc int isExportPanelUsed()
{
	string  $currentContext = `currentCtx`;
	string  $currTool = `contextInfo -c $currentContext`;

	if ( ( $currTool == "artSelect" ) 
	||	 ( $currTool == "artAttr" )
	||	 ( $currTool == "artClothPaint" )
	||	 ( $currTool == "artClothCollPaint" )
	||	 ( $currTool == "artAttrColorPerVertex" )
	||	 ( $currTool == "artFluidAttr" )
	||	 ( $currTool == "artAttrBlendShape" )
	||	 ( $currTool == "artUserPaint" )
	)
	{
		return 1 ;
	}

	return 0 ;
}

global proc int isOpacityAccumulationRequired()
{
	string  $currentContext = `currentCtx`;
	string  $currTool = `contextInfo -c $currentContext`;

	// if the tool is using TartAttrCmd::update function then opacity built up is
	// handled there otherwise the cmd object needs to handle this.
	if ( ( $currTool == "artAttr" ) 
	||	 ( $currTool == "artClothPaint" )
	||	 ( $currTool == "artClothCollPaint" )
	||	 ( $currTool == "artAttrColorPerVertex" )
	||	 ( $currTool == "artAttrBlendShape" )
	||	 ( $currTool == "artUserPaint" )
	||	 ( $currTool == "artPutty" )
	)
	{
		return 1 ;		
	}

	return 0 ;
}

global proc int isSurfaceConformedBrushAvailable()
//
// Description:
//
//	Returns true if the current tool supports a surface-fitted
//	brush.
//
{
	int $retVal = 0;
	string $currentContext = `currentCtx`;
	string $currentTool = `contextInfo -c $currentContext`;

	if( $currentTool == "artPutty" )
	{
		$retVal = 1;
	}
	return $retVal;
}
