// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  04 January 1999
//
//		Remove string items from a string array.  A new string array with the
//		items removed is returned.  Note that all occurrences of the given 
//		string items will be removed from the string array.
//
//	flags:
//		string[] $items	A list of string values to remove from the string array
//		string[] $list	A list of string values
//
//	returns:
//		string[] : Original list with all occurrences of the string items
//		removed.  If none of the string items are in the string array then
//		the returned string array is identical to the argument string array.
//
//	examples:
//  string $list[] = { a, b, c, d, e, f, g };
//  string $items[] = { a, c, e, g };
//  string $diff[] = AWRemoveStringsFromStringArray($items, $list);
//  // Result : { b, d, f } //
//
//  Note: Use stringArrayRemove instead.
//

global proc string [] AWRemoveStringsFromStringArray(
	string $items[], 
	string $list[])
{
	return stringArrayRemove($items, $list);
}

