// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//	Creation Date:	July 3, 2003
//
//<doc>
//<name basenameEx>
//
//<synopsis>
//		string basenameEx(string $path)
//
//<returns>
//		string : the path's basename
//
//<description>
//		An extension of basename(), this convenience procedure returns the
//		base name of $path, without the directory or the file extension.
//		See also basename() and fileExtension().
//
//<examples>
//		basenameEx("/usr/people/gamera/gamera.mel");
//		// Result: gamera //
//
//		basenameEx("C:/aw/godzilla/hello.c");
//		// Result: hello //
//
//</doc>

global proc string basenameEx(string $path)
{
	string $extension = fileExtension($path);
	if ("" != $extension)
	{
		$extension = "." + $extension;
	}

	return basename($path, $extension);
}

//	=== END OF FILE basenameEx.mel ===========================================
