// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

// Description:  This procedure is called to check if a bin name exists
//      in the hyper shade bin list.  
//      Return true if the given bin name exists in the hyper shade bin
//      list.  Otherwise, return false. 
//
global proc int binNameExistsInHyperShadeBinList(string $binName)
{
    // Check if the bin name is a valid bin name.
    //
    if (!isValidBinName($binName))
    {
        return false;
    }

    string $binList = `getAttr defaultRenderGlobals.hyperShadeBinList`;

    // It is assumed that the bin names are separated by ";".  For
    // example "wood;metal;outdoors".
    //

    // Check if the bin name is the only item in the bin list.
    // 
    if ($binName == $binList)
    {
        return true;
    }

    // Check if the bin name occurred at the beginning of the bin list.
    //
    if (`substitute ("^"+$binName+";") $binList ""` != $binList)
    {
        return true;
    }

    // Check if the bin name occurred at the end of the bin list.
    //
    if (`substitute (";"+$binName+"$") $binList ""` != $binList)
    {
        return true;
    }

    // Check if the bin name occurred at the middle of the bin list.
    //
    if (`substitute (";"+$binName+";") $binList ""` != $binList)
    {
        return true;
    }

    return false;
}
