// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Birail 1 Tool" m_birailToolScript.kBirailTool1;
displayString -replace -value "Birail 2 Tool" m_birailToolScript.kBirailTool2;
displayString -replace -value "Birail 3+ Tool" m_birailToolScript.kBirailTool3;
displayString -replace -value "Profile and rail curves selected.  Press ENTER to compute birail." m_birailToolScript.kComputeBirail;
displayString -replace -value "Profile and rail curves selected.  Press ENTER to compute birail." m_birailToolScript.kComputeBirailTool2;
displayString -replace -value "Profile and rail curves selected.  Press ENTER to compute birail." m_birailToolScript.kComputeBirailTool3;
displayString -replace -value "Select additional profiles or press ENTER to start rail curves selection." m_birailToolScript.kSelectAdditionalProfiles;
displayString -replace -value "Select any number of profile curves." m_birailToolScript.kSelectManyProfileCurves;
displayString -replace -value "Select the profile curve." m_birailToolScript.kSelectProfileCurve;
displayString -replace -value "Profile curve selected. Select two rails curves." m_birailToolScript.kSelectRailCurves;
displayString -replace -value "Select the second profile curve." m_birailToolScript.kSelectSecondProfileCurve;
displayString -replace -value "Select the second rail curve." m_birailToolScript.kSelectSecondRailCurve;
displayString -replace -value "Select the second rail curve." m_birailToolScript.kSelectSecondRailCurveTool2;
displayString -replace -value "Select the second rail curve." m_birailToolScript.kSelectSecondRailCurveTool3;
displayString -replace -value "Select two profile curves." m_birailToolScript.kSelectTwoProfileCurves;
displayString -replace -value "Select two rail curves." m_birailToolScript.kSelectTwoRailCurves;
displayString -replace -value "Select two rail curves." m_birailToolScript.kSelectTwoRailCurvesTool3;
displayString -replace -value "Profile curve selected.  Press ENTER to start rail selection." m_birailToolScript.kStartRailSelection;
displayString -replace -value "Two profile curves selected.  Press ENTER to start rail selection." m_birailToolScript.kStartRailSelectionTool2;
