// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Camera Set" m_buildPanelPopupMenu.kCameraSet;
displayString -replace -value "a menu button added via addPanelCategory references a non-existant menu button to insert after (^1s)" m_buildPanelPopupMenu.kCategoryNotFound;
displayString -replace -value "Change layout of panels" m_buildPanelPopupMenu.kChangeLayoutAnnot;
displayString -replace -value "Edit Layouts..." m_buildPanelPopupMenu.kEditLayouts;
displayString -replace -value "Edit the panel layouts" m_buildPanelPopupMenu.kEditLayoutsAnnot;
displayString -replace -value "Hypergraph Panel" m_buildPanelPopupMenu.kHypergraphPanel;
displayString -replace -value "Layouts" m_buildPanelPopupMenu.kLayouts;
displayString -replace -value "Look through selected camera option box" m_buildPanelPopupMenu.kLookThroughAnnot;
displayString -replace -value "Look Through Selected" m_buildPanelPopupMenu.kLookThroughSelected;
displayString -replace -value "Next Arrangement" m_buildPanelPopupMenu.kNextArrangement;
displayString -replace -value "Orthographic" m_buildPanelPopupMenu.kOrthographic;
displayString -replace -value "Panel" m_buildPanelPopupMenu.kPanel;
displayString -replace -value "Panel Editor..." m_buildPanelPopupMenu.kPanelEditor;
displayString -replace -value "Panels" m_buildPanelPopupMenu.kPanels;
displayString -replace -value "Perspective" m_buildPanelPopupMenu.kPerspective;
displayString -replace -value "Previous Arrangement" m_buildPanelPopupMenu.kPreviousArrangement;
displayString -replace -value "Saved Layouts" m_buildPanelPopupMenu.kSavedLayouts;
displayString -replace -value "Stereo" m_buildPanelPopupMenu.kStereo;
displayString -replace -value "Tear Off..." m_buildPanelPopupMenu.kTearOff;
displayString -replace -value "Tear Off Copy..." m_buildPanelPopupMenu.kTearOffCopy;
