// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
// Creation Date:  October, 1999
//
//
//  Procedure Name:
//      clipPropertiesWindow
//
//  Description:
//    Selects the clips related to the current clips selected
//    and opens the attribute editor.
//
//  Input Arguments:
//      None.
//
//  Return Value:
//      None.
//
global proc clipPropertiesWindow(string $clipEditor)
{
	string $selClips[] = `clipEditor -q -sc $clipEditor`;
	int $nclips = size($selClips);
	if (0 == $nclips) {
		error((uiRes("m_clipPropertiesWindow.kNoClipsSelected")));
		return;
	}

	// find the selected clip names
	//
	int $ii;
	int $count = 0;
	string $names[];
	for ($ii = 0; $ii < $nclips; $ii += 2) {
		string $sch = $selClips[$ii];
		int $clipIndex = $selClips[$ii+1];
		$names[$count] = `clipSchedule -ci $clipIndex -q -n $sch`;
		$count++;
	}
	select -add $names;

	// open the attribute editor
	//
	openAEWindow();
}
