// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Add" m_colorSetEditor.kAdd;
displayString -replace -value "All" m_colorSetEditor.kAll;
displayString -replace -value "Apply Color" m_colorSetEditor.kApplyColor;
displayString -replace -value "Bilinear" m_colorSetEditor.kBilinear;
displayString -replace -value "Blend" m_colorSetEditor.kBlend;
displayString -replace -value "Channels" m_colorSetEditor.kChannels;
displayString -replace -value "Close" m_colorSetEditor.kClose;
displayString -replace -value "Color" m_colorSetEditor.kColor;
displayString -replace -value "Color in Shaded Display Off" m_colorSetEditor.kColorInShadedDisplayOff;
displayString -replace -value "Color in Shaded Display On" m_colorSetEditor.kColorInShadedDisplayOn;
displayString -replace -value "Color Material Channel Ambient + Diffuse" m_colorSetEditor.kColorMaterialChannel;
displayString -replace -value "Color Material Channel Ambient" m_colorSetEditor.kColorMaterialChannelAmbient;
displayString -replace -value "Color Material Channel Diffuse" m_colorSetEditor.kColorMaterialChannelDiffuse;
displayString -replace -value "Color Material Channel Emission" m_colorSetEditor.kColorMaterialChannelEmission;
displayString -replace -value "Color Material Channel None" m_colorSetEditor.kColorMaterialChannelNone;
displayString -replace -value "Color Material Channel Specular" m_colorSetEditor.kColorMaterialChannelSpecular;
displayString -replace -value "Color Set Editor" m_colorSetEditor.kColorSetEditor;
displayString -replace -value "Move color set: nothing selected to move" m_colorSetEditor.kColorSetMoveWarning;
displayString -replace -value "Combine two selected Color Sets into a new Color Set" m_colorSetEditor.kCombineTwoSelectedColorSets2Annot;
displayString -replace -value "Combine two selected Color Sets into one Color Set" m_colorSetEditor.kCombineTwoSelectedColorSetsAnnot;
displayString -replace -value "Copy" m_colorSetEditor.kCopy;
displayString -replace -value "Copy the current Color Set to a new Color Set" m_colorSetEditor.kCopyTheCurrentColorSetToANewAnnot;
displayString -replace -value "Create a new Color Set" m_colorSetEditor.kCreateANewColorSetAnnot;
displayString -replace -value "Delete" m_colorSetEditor.kDelete;
displayString -replace -value "Delete the current Color Set" m_colorSetEditor.kDeleteTheCurrentColorSetAnnot;
displayString -replace -value "Display" m_colorSetEditor.kDisplay;
displayString -replace -value "Help on Color Set Editor" m_colorSetEditor.kHelpOnColorSetEditor;
displayString -replace -value "Linear" m_colorSetEditor.kLinear;
displayString -replace -value "Material Blend Setting Add" m_colorSetEditor.kMaterialBlendSettingAdd;
displayString -replace -value "Material Blend Setting Average" m_colorSetEditor.kMaterialBlendSettingAverage;
displayString -replace -value "Material Blend Setting Divide" m_colorSetEditor.kMaterialBlendSettingDivide;
displayString -replace -value "Material Blend Setting Modulate 2X" m_colorSetEditor.kMaterialBlendSettingModulate2;
displayString -replace -value "Material Blend Setting Multiply" m_colorSetEditor.kMaterialBlendSettingMultiply;
displayString -replace -value "Material Blend Setting Overwrite" m_colorSetEditor.kMaterialBlendSettingOverwrite;
displayString -replace -value "Material Blend Setting Subtract" m_colorSetEditor.kMaterialBlendSettingSubtract;
displayString -replace -value "Merge" m_colorSetEditor.kMerge;
displayString -replace -value "Modify" m_colorSetEditor.kModify;
displayString -replace -value "Move Down" m_colorSetEditor.kMoveDown;
displayString -replace -value "Move the selected Color Set down one position" m_colorSetEditor.kMoveTheSelectedColorSetDownAnnot;
displayString -replace -value "Move the selected Color Set up one position" m_colorSetEditor.kMoveTheSelectedColorSetUpOneAnnot;
displayString -replace -value "Move Up" m_colorSetEditor.kMoveUp;
displayString -replace -value "Multiply" m_colorSetEditor.kMultiply;
displayString -replace -value "MultiplyRGBA" m_colorSetEditor.kMultiplyRGBA;
displayString -replace -value "New" m_colorSetEditor.kNew;
displayString -replace -value "Option box for prelighting polygon using the Maya software renderer" m_colorSetEditor.kOptionBoxPrelightMayaSoftwareAnnot;
displayString -replace -value "Over" m_colorSetEditor.kOver;
displayString -replace -value "Paint Vertex Color Tool" m_colorSetEditor.kPaintVertexColorTool;
displayString -replace -value "Prelight" m_colorSetEditor.kPrelight;
displayString -replace -value "Prelight (Maya Software)" m_colorSetEditor.kPrelightMayaSoftware;
displayString -replace -value "Prelight polygon using the Maya software renderer" m_colorSetEditor.kPrelightMayaSoftwareAnnot;
displayString -replace -value "Rename" m_colorSetEditor.kRename;
displayString -replace -value "Rename the current Color Set" m_colorSetEditor.kRenameTheCurrentColorSetAnnot;
displayString -replace -value "Selected" m_colorSetEditor.kSelected;
displayString -replace -value "Subtract" m_colorSetEditor.kSubtract;
displayString -replace -value "Update" m_colorSetEditor.kUpdate;
