// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// Global Maya compatibility file, version 7.0ff07
////////////////////////////////////////////////////////////////////////////
//
// This version becomes effective as of the April 25, 2005 release.
//
////////////////////////////////////////////////////////////////////////////

attrCompatibility -v "7.0ff07";

attrCompatibility -removeAttr renderGlobals "renderGlobalPassEnable" ;
attrCompatibility -removeAttr renderGlobals "rgpn" ;

attrCompatibility -removeAttr renderGlobals "renderLayerPassEnable" ;
attrCompatibility -removeAttr renderGlobals "rlpn" ;

attrCompatibility -removeAttr renderGlobals "renderLayerSubdirs" ;
attrCompatibility -removeAttr renderGlobals "rlsd" ;

// TODO: Can only remove after Mental Ray and Maya Fur have been dealt with
//attrCompatibility -removeAttr renderGlobals "renderLayerEnable" ;
//attrCompatibility -removeAttr renderGlobals "rlen" ;

////////////////////////////////////////////////////////////////////////////
//
// The following attrCompatibility commands are the duplicated commands
// from compat_maya_7.0ff01 thru compat_maya_7.0ff06 (inclusive). This is
// to ensure that the compatibility split between the mainline and custom
// EA cuts is resolved. Duplicating these commands has been tested to have
// no effect. Tests involved files from 7.0ff05 (mainline) and 7.0ff06 (EA).
// No error messages are generated and the move is seamless to the user.
//
// [lli]
//
////////////////////////////////////////////////////////////////////////////

// 7.0ff01
//
attrCompatibility -removeAttr polyModifier cachedPolyMesh ;
attrCompatibility -removeAttr polyModifier icp ;

attrCompatibility -renameAttr scaleMode polyAutoProj scale ;

// 7.0ff02
//
attrCompatibility -removeAttr nonExtendedLightShapeNode useDmapAutoBias ;
attrCompatibility -removeAttr nonExtendedLightShapeNode da ;

// 7.0ff03
//

// 7.0ff04
//

// 7.0ff05
//
attrCompatibility -rm hikEffector pull;
attrCompatibility -rm hikEffector pl;

attrCompatibility -rm hikEffector stiffness;
attrCompatibility -rm hikEffector st;

attrCompatibility -removeAttr hardwareRenderGlobals "enableRenderLayers" ;
attrCompatibility -removeAttr hardwareRenderGlobals "el" ;

attrCompatibility -removeAttr hardwareRenderGlobals "filename" ;
attrCompatibility -removeAttr hardwareRenderGlobals "fn" ;

attrCompatibility -removeAttr hardwareRenderGlobals "startFrame" ;
attrCompatibility -removeAttr hardwareRenderGlobals "sf" ;

attrCompatibility -removeAttr hardwareRenderGlobals "endFrame" ;
attrCompatibility -removeAttr hardwareRenderGlobals "ef" ;

attrCompatibility -removeAttr hardwareRenderGlobals "byFrame" ;
attrCompatibility -removeAttr hardwareRenderGlobals "bf" ;

attrCompatibility -removeAttr hardwareRenderGlobals "imageFormat" ;
attrCompatibility -removeAttr hardwareRenderGlobals "if" ;

attrCompatibility -removeAttr hardwareRenderGlobals "imfPluginKey" ;
attrCompatibility -removeAttr hardwareRenderGlobals "imfkey" ;

attrCompatibility -removeAttr hardwareRenderGlobals "enableDefaultLight" ;
attrCompatibility -removeAttr hardwareRenderGlobals "edl" ;

attrCompatibility -removeAttr hardwareRenderGlobals "resolutionX" ;
attrCompatibility -removeAttr hardwareRenderGlobals "resx" ;

attrCompatibility -removeAttr hardwareRenderGlobals "resolutionY" ;
attrCompatibility -removeAttr hardwareRenderGlobals "resy" ;

attrCompatibility -removeAttr hardwareRenderGlobals "pixelAspectRatio" ;
attrCompatibility -removeAttr hardwareRenderGlobals "par" ;

attrCompatibility -removeAttr hardwareRenderGlobals "preRenderMel" ;
attrCompatibility -removeAttr hardwareRenderGlobals "pre" ;

attrCompatibility -removeAttr hardwareRenderGlobals "postRenderMel" ;
attrCompatibility -removeAttr hardwareRenderGlobals "pst" ;

attrCompatibility -removeAttr hardwareRenderGlobals "modifyExtension" ;
attrCompatibility -removeAttr hardwareRenderGlobals "me" ;

attrCompatibility -removeAttr hardwareRenderGlobals "startExtension" ;
attrCompatibility -removeAttr hardwareRenderGlobals "se" ;

attrCompatibility -removeAttr hardwareRenderGlobals "byExtension" ;
attrCompatibility -removeAttr hardwareRenderGlobals "be" ;

attrCompatibility -removeAttr hardwareRenderGlobals "useCustomExtension" ;
attrCompatibility -removeAttr hardwareRenderGlobals "uce" ;

attrCompatibility -removeAttr hardwareRenderGlobals "customExtension" ;
attrCompatibility -removeAttr hardwareRenderGlobals "ce" ;

// 7.0ff06
//
attrCompatibility -removeAttr renderGlobals "renderLayerPreview" ;
attrCompatibility -removeAttr renderGlobals "rlpv" ;

