// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// Global Maya compatibility file, version 8.0ff03
////////////////////////////////////////////////////////////////////////////
//
// This version becomes effective as of the Feb 07, 2006 release.
//
////////////////////////////////////////////////////////////////////////////

attrCompatibility -v "8.0ff03";

// Shorting the short name to be less then 3 letter to be compatible with 
// polymod command automatic pick up
//

attrCompatibility -renameAttr hue  polyColorMod huev ;
attrCompatibility -renameAttr sat  polyColorMod satv ;
attrCompatibility -renameAttr lum  polyColorMod value ;
attrCompatibility -renameAttr bcn  polyColorMod base ;
attrCompatibility -renameAttr r  polyColorMod rsc ;
attrCompatibility -renameAttr g  polyColorMod gsc ;
attrCompatibility -renameAttr b  polyColorMod bsc ;
attrCompatibility -renameAttr a  polyColorMod asc ;
attrCompatibility -renameAttr l  polyColorMod isc ;
 
attrCompatibility -renameAttr bcn blendColorSets base ; 
attrCompatibility -renameAttr dst blendColorSets dstc ;
attrCompatibility -renameAttr bfn blendColorSets blfn ;
attrCompatibility -renameAttr bwa blendColorSets blwa ;
attrCompatibility -renameAttr bwb blendColorSets blwb ;
attrCompatibility -renameAttr bwc blendColorSets blwc ;
attrCompatibility -renameAttr bwd blendColorSets blwd ;

attrCompatibility -removeAttr polyTransfer triangles ;
attrCompatibility -removeAttr polyTransfer t;
