// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// Global Maya compatibility file, version 2013ff01
////////////////////////////////////////////////////////////////////////////
//
// This version becomes effective as of the April 14, 2011 release.
//
////////////////////////////////////////////////////////////////////////////

attrCompatibility -v "2013ff01";

attrCompatibility -removeAttr pairBlend "quaternionLegacyMode" ;
attrCompatibility -removeAttr pairBlend "qlm" ;
attrCompatibility -removeAttr animBlendInOut "rotateBlend" ;
attrCompatibility -removeAttr animBlendInOut "rb" ;

attrCompatibility -pluginNode HIKPinning2State ;

attrCompatibility -removeAttr HIKPinning2State "manipActive" ;

attrCompatibility -removeAttr HIKPinning2State "HipsEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftAnkleEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightAnkleEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftWristEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightWristEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftKneeEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightKneeEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftElbowEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightElbowEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "ChestOriginEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "ChestEndEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftShoulderEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightShoulderEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "HeadEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHipEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHipEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandThumbEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandIndexEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandMiddleEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandRingEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandPinkyEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandExtraFingerEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandThumbEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandIndexEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandMiddleEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandRingEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandPinkyEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandExtraFingerEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootThumbEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootIndexEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootMiddleEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootRingEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootPinkyEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootExtraFingerEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootThumbEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootIndexEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootMiddleEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootRingEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootPinkyEffectorPullOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootExtraFingerEffectorPullOverride" ;

attrCompatibility -removeAttr HIKPinning2State "HipsEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftAnkleEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightAnkleEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftWristEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightWristEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftKneeEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightKneeEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftElbowEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightElbowEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "ChestOriginEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "ChestEndEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftShoulderEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightShoulderEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "HeadEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHipEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHipEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandThumbEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandIndexEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandMiddleEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandRingEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandPinkyEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftHandExtraFingerEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandThumbEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandIndexEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandMiddleEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandRingEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandPinkyEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightHandExtraFingerEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootThumbEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootIndexEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootMiddleEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootRingEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootPinkyEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "LeftFootExtraFingerEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootThumbEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootIndexEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootMiddleEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootRingEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootPinkyEffectorResistOverride" ;
attrCompatibility -removeAttr HIKPinning2State "RightFootExtraFingerEffectorResistOverride" ;




attrCompatibility -renameAttr imageCenter   imagePlane  center ;
attrCompatibility -renameAttr imageCenterX  imagePlane  centerX ;
attrCompatibility -renameAttr imageCenterY  imagePlane  centerY ;
attrCompatibility -renameAttr imageCenterZ  imagePlane  centerZ ;
attrCompatibility -renameAttr ic imagePlane c ;
attrCompatibility -renameAttr icx imagePlane cx ;
attrCompatibility -renameAttr icy imagePlane cy ;
attrCompatibility -renameAttr icz imagePlane cz ;
