// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

// THIS SCRIPT IS TO CONVERT an NCLOTH InputAttract value so that the effect matches Maya2014 and earlier releases. 
// This is due to a bug that was fixed, where inputAttract had not been correctly normalized for nucleus substeps.
// This is automatically invoked when old files are loaded, however one may still wish to invoke this by hand if one has
// a custom cloth attribute preset that uses input attract.

global proc convertPost2014ClothInputAttract( string $nObj )
{
	string $type = nodeType( $nObj );
	if( $type != "nCloth" ){
		return;
	}
	float $ia = getAttr($nObj + ".inputMeshAttract");
	if( $ia == 0.0 ){
		return;
	}
	// find the nucleus node for the cloth:
	string $con[] = `listConnections -type nucleus ($nObj+".startState")`;
	if( size( $con ) == 0 ){
		return;
	}
	string $nucleus = $con[0];

	float $sub = getAttr( $nucleus+".subSteps");
	float $pf = 5.0;
	float $fac = 1.0/2.0;
	if( getAttr( $nObj+".inputAttractMethod" ) != 0 ){
		$pf = 3.0;
		$fac = 1.5/2.0;
	}
	float $pf2 = 3.0;
	float $iaNew = $fac * pow((pow($ia,$pf) * $sub * $sub), 1.0/$pf2);
	setAttr ($nObj + ".inputMeshAttract")  $iaNew;
}
