// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Unable to bake lighting for ^1s, there is no shading group connected" m_copyConvertSolidTx.kCannotBake;
displayString -replace -value "Unable to bake lighting for ^1s, there are ^2s shading groups connected" m_copyConvertSolidTx.kCannotBake2;
displayString -replace -value "Cannot convert a texture connected to ^1s" m_copyConvertSolidTx.kCannotConvertText;
displayString -replace -value "Only one shading node can be converted, there is more than one selected" m_copyConvertSolidTx.kManyShaderSelected;
displayString -replace -value "^1s is connected to more than one shading group" m_copyConvertSolidTx.kMultiShadingGroup;
displayString -replace -value "^1s is connected to more than one shading group" m_copyConvertSolidTx.kMultiTexture;
displayString -replace -value "Select or highlight a shading node, unable to continue" m_copyConvertSolidTx.kNoSelected;
displayString -replace -value "No surfaces selected, unable to continue" m_copyConvertSolidTx.kNoSurface;
displayString -replace -value "^1s does not have a surface shader" m_copyConvertSolidTx.kNoSurfaceShader;
displayString -replace -value "^1s is not a shading group, convert with baked lighting can only be done on a shading group" m_copyConvertSolidTx.kNotShading;
displayString -replace -value "^1s is not a shading node" m_copyConvertSolidTx.kNotShadingNode;
displayString -replace -value "^1s is not a shading node, unable to continue" m_copyConvertSolidTx.kNotShadingNode2;
displayString -replace -value "Unable to convert ^1s, re-organize your network to use a layered texture instead of a layered shader or use the baked lighting option" m_copyConvertSolidTx.kReogNetwork;
