// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Active view" m_createNurbsTorusProperties.kActiveView;
displayString -replace -value "After Creation Settings" m_createNurbsTorusProperties.kAdjustmentAfterCreateSettings;
displayString -replace -value "Axis:" m_createNurbsTorusProperties.kAxis;
displayString -replace -value "Axis definition:" m_createNurbsTorusProperties.kAxisDefinition;
displayString -replace -value "X" m_createNurbsTorusProperties.kAxisX;
displayString -replace -value "Y" m_createNurbsTorusProperties.kAxisY;
displayString -replace -value "Z" m_createNurbsTorusProperties.kAxisZ;
displayString -replace -value "Drag or single-click on the grid." m_createNurbsTorusProperties.kCreateNurbsTorusToolDescApp;
displayString -replace -value "Create Settings" m_createNurbsTorusProperties.kCreateSettingsFrame;
displayString -replace -value "Cubic" m_createNurbsTorusProperties.kCubic;
displayString -replace -value "Description" m_createNurbsTorusProperties.kDescriptionFrame;
displayString -replace -value "Adjust sections and spans" m_createNurbsTorusProperties.kDoDragEditLine;
displayString -replace -value "End sweep:" m_createNurbsTorusProperties.kEndSweep;
displayString -replace -value "Free" m_createNurbsTorusProperties.kFree;
displayString -replace -value "Global" m_createNurbsTorusProperties.kGlobal;
displayString -replace -value "Linear" m_createNurbsTorusProperties.kLinear;
displayString -replace -value "Local" m_createNurbsTorusProperties.kLocal;
displayString -replace -value "Minor radius:" m_createNurbsTorusProperties.kMinorRadius;
displayString -replace -value "Minor sweep:" m_createNurbsTorusProperties.kMinorSweep;
displayString -replace -value "None" m_createNurbsTorusProperties.kNone;
displayString -replace -value "Positional tolerance:" m_createNurbsTorusProperties.kPositionalTolerance;
displayString -replace -value "Radius:" m_createNurbsTorusProperties.kRadius;
displayString -replace -value "Sections:" m_createNurbsTorusProperties.kSections;
displayString -replace -value "Single-click Settings" m_createNurbsTorusProperties.kSettingsFrame;
displayString -replace -value "Spans:" m_createNurbsTorusProperties.kSpans;
displayString -replace -value "Start sweep:" m_createNurbsTorusProperties.kStartSweep;
displayString -replace -value "Surface degree:" m_createNurbsTorusProperties.kSurfaceDegree;
displayString -replace -value "Use tolerance:" m_createNurbsTorusProperties.kUseTolerance;
