// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Alphabetical Within Type" m_createOutlinerPanelMenu.kAlphabeticalWithinType;
displayString -replace -value "Attribute Order" m_createOutlinerPanelMenu.kAttrAlphaOrder;
displayString -replace -value "Default" m_createOutlinerPanelMenu.kAttrAlphaOrderDefault;
displayString -replace -value "Alphabetical, ascend" m_createOutlinerPanelMenu.kAttrAlphabeticalAscend;
displayString -replace -value "Alphabetical, descend" m_createOutlinerPanelMenu.kAttrAlphabeticalDescend;
displayString -replace -value "Attributes (Channels)" m_createOutlinerPanelMenu.kAttributesChannels;
displayString -replace -value "Both" m_createOutlinerPanelMenu.kBoth;
displayString -replace -value "Channel Names" m_createOutlinerPanelMenu.kChannelNames;
displayString -replace -value "Connected" m_createOutlinerPanelMenu.kConnected;
displayString -replace -value "Advanced Asset Contents" m_createOutlinerPanelMenu.kContainerContents;
displayString -replace -value "DAG Objects Only" m_createOutlinerPanelMenu.kDAGObjectsOnly;
displayString -replace -value "Display" m_createOutlinerPanelMenu.kDisplay;
displayString -replace -value "Help on Outliner" m_createOutlinerPanelMenu.kHelpOnOutliner;
displayString -replace -value "Hide In Outliner" m_createOutlinerPanelMenu.kHideInOutliner;
displayString -replace -value "Hide" m_createOutlinerPanelMenu.kHideInOutlinerHide;
displayString -replace -value "Unhide" m_createOutlinerPanelMenu.kHideInOutlinerHideUnhide;
displayString -replace -value "Ignore 'Hidden In Outliner'" m_createOutlinerPanelMenu.kIgnoreHiddenAttribute;
displayString -replace -value "Ignore 'Use Outliner Color'" m_createOutlinerPanelMenu.kIgnoreUseOutlinerColor;
displayString -replace -value "Long" m_createOutlinerPanelMenu.kLong;
displayString -replace -value "Nice" m_createOutlinerPanelMenu.kNice;
displayString -replace -value "None" m_createOutlinerPanelMenu.kNone;
displayString -replace -value "Reference Members" m_createOutlinerPanelMenu.kReferenceMembers;
displayString -replace -value "Reference Nodes" m_createOutlinerPanelMenu.kReferenceNodes;
displayString -replace -value "Reveal Selected" m_createOutlinerPanelMenu.kRevealSelected;
displayString -replace -value "Scene Hierarchy" m_createOutlinerPanelMenu.kSceneHierarchy;
displayString -replace -value "Select Set Members" m_createOutlinerPanelMenu.kSelectSetMembers;
displayString -replace -value "Set Members" m_createOutlinerPanelMenu.kSetMembers;
displayString -replace -value "Shapes" m_createOutlinerPanelMenu.kShapes;
displayString -replace -value "Short" m_createOutlinerPanelMenu.kShort;
displayString -replace -value "Show Namespace" m_createOutlinerPanelMenu.kShowNamespace;
displayString -replace -value "Sort Order" m_createOutlinerPanelMenu.kSortOrder;
displayString -replace -value "Under Asset" m_createOutlinerPanelMenu.kUnderContainer;
displayString -replace -value "Under Parent" m_createOutlinerPanelMenu.kUnderParent;
