// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "After Creation Settings" m_createPolyPyramidProperties.kAdjustmentAfterCreateSettings;
displayString -replace -value "Axis:" m_createPolyPyramidProperties.kAxis;
displayString -replace -value "Cap divisions:" m_createPolyPyramidProperties.kCapDivisions;
displayString -replace -value "Drag or single-click on the grid." m_createPolyPyramidProperties.kCreatePolyPyramidToolDescApp;
displayString -replace -value "Create Poly Pyramid Tool Settings" m_createPolyPyramidProperties.kCreatePolyPyramidToolSettings;
displayString -replace -value "Create Settings" m_createPolyPyramidProperties.kCreateSettingsFrame;
displayString -replace -value "Create UVs" m_createPolyPyramidProperties.kCreateUVs;
displayString -replace -value "Description" m_createPolyPyramidProperties.kDescriptionFrame;
displayString -replace -value "Adjust cap subdivisions" m_createPolyPyramidProperties.kDoDragEditCapsLine;
displayString -replace -value "Adjust subdivisions" m_createPolyPyramidProperties.kDoDragEditLine;
displayString -replace -value "Height divisions:" m_createPolyPyramidProperties.kHeightDivisions;
displayString -replace -value "Normalize" m_createPolyPyramidProperties.kNormalize;
displayString -replace -value "Number of sides in base:" m_createPolyPyramidProperties.kNumberOfSidesInBase;
displayString -replace -value "Preserve Aspect Ratio" m_createPolyPyramidProperties.kPreserveAR;
displayString -replace -value "Single-click Settings" m_createPolyPyramidProperties.kSettingsFrame;
displayString -replace -value "Side length:" m_createPolyPyramidProperties.kSideLength;
displayString -replace -value "Texture mapping:" m_createPolyPyramidProperties.kTextureMapping;
displayString -replace -value "X" m_createPolyPyramidProperties.kXAxis;
displayString -replace -value "Y" m_createPolyPyramidProperties.kYAxis;
displayString -replace -value "Z" m_createPolyPyramidProperties.kZAxis;
