// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "After Creation Settings" m_createPolyCylinderProperties.kAdjustmentAfterCreateSettings;
displayString -replace -value "Axis:" m_createPolyCylinderProperties.kAxis;
displayString -replace -value "Axis divisions:" m_createPolyCylinderProperties.kAxisDivisions;
displayString -replace -value "Cap divisions:" m_createPolyCylinderProperties.kCapDivisions;
displayString -replace -value "Drag the base on the grid, then pull up for height or single-click on the grid." m_createPolyCylinderProperties.kCreatePolyCylinderToolDescApp;
displayString -replace -value "Create Poly Cylinder Tool Settings" m_createPolyCylinderProperties.kCreatePolyCylinderToolSettings;
displayString -replace -value "Create Settings" m_createPolyCylinderProperties.kCreateSettingsFrame;
displayString -replace -value "Create UVs" m_createPolyCylinderProperties.kCreateUVs;
displayString -replace -value "Description" m_createPolyCylinderProperties.kDescriptionPolyCylFrame;
displayString -replace -value "Adjust cap subdivisions" m_createPolyCylinderProperties.kDoDragEditCapsLine;
displayString -replace -value "Adjust subdivisions" m_createPolyCylinderProperties.kDoDragEditLine;
displayString -replace -value "Height:" m_createPolyCylinderProperties.kHeight;
displayString -replace -value "Height divisions:" m_createPolyCylinderProperties.kHeightDivisions;
displayString -replace -value "Normalize" m_createPolyCylinderProperties.kNormalize;
displayString -replace -value "Preserve Aspect Ratio" m_createPolyCylinderProperties.kPreserveAR;
displayString -replace -value "Radius:" m_createPolyCylinderProperties.kRadius;
displayString -replace -value "Round cap" m_createPolyCylinderProperties.kRoundCap;
displayString -replace -value "Single-click Settings" m_createPolyCylinderProperties.kSettingsFrame;
displayString -replace -value "Texture mapping:" m_createPolyCylinderProperties.kTextureMapping;
displayString -replace -value "X" m_createPolyCylinderProperties.kXAxis;
displayString -replace -value "Y" m_createPolyCylinderProperties.kYAxis;
displayString -replace -value "Z" m_createPolyCylinderProperties.kZAxis;
