// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Active view" m_createNurbsSquareProperties.kActiveView;
displayString -replace -value "After Creation Settings" m_createNurbsSquareProperties.kAdjustmentAfterCreateSettings;
displayString -replace -value "Axis:" m_createNurbsSquareProperties.kAxis;
displayString -replace -value "Axis definition:" m_createNurbsSquareProperties.kAxisDefinition;
displayString -replace -value "X" m_createNurbsSquareProperties.kAxisX;
displayString -replace -value "Y" m_createNurbsSquareProperties.kAxisY;
displayString -replace -value "Z" m_createNurbsSquareProperties.kAxisZ;
displayString -replace -value "Drag or single-click on the grid." m_createNurbsSquareProperties.kCreateNurbsSquareToolDescApp;
displayString -replace -value "Create Settings" m_createNurbsSquareProperties.kCreateSettingsFrame;
displayString -replace -value "3 Cubic" m_createNurbsSquareProperties.kCubic;
displayString -replace -value "Description" m_createNurbsSquareProperties.kDescriptionFrame;
displayString -replace -value "Adjust spans per side" m_createNurbsSquareProperties.kDoDragEditLine;
displayString -replace -value "Free" m_createNurbsSquareProperties.kFree;
displayString -replace -value "Length of side 1:" m_createNurbsSquareProperties.kLen1;
displayString -replace -value "Length of side 2:" m_createNurbsSquareProperties.kLen2;
displayString -replace -value "1 Linear" m_createNurbsSquareProperties.kLinear;
displayString -replace -value "Single-click Settings" m_createNurbsSquareProperties.kSettingsFrame;
displayString -replace -value "Spans per side:" m_createNurbsSquareProperties.kSpans;
displayString -replace -value "Surface degree:" m_createNurbsSquareProperties.kSurfaceDegree;
