// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Failed to convert texture!" m_createTextureToGeom.kFailedToConvert;
displayString -replace -value "Failed to create texture to geometry converter" m_createTextureToGeom.kFailedToCreate;
displayString -replace -value "Specified file ^1s does not exist" m_createTextureToGeom.kFileDoesNotExist;
displayString -replace -value "Please select one mesh." m_createTextureToGeom.kNoMesh;
displayString -replace -value "A shape was found without a parent. All shapes must have a parent." m_createTextureToGeom.kNoParent;
displayString -replace -value "Selection is not a mesh!" m_createTextureToGeom.kNotAMesh;
displayString -replace -value "Selection is not a mesh!" m_createTextureToGeom.kNotAMesh2;
displayString -replace -value "Too many selections. Please select only one mesh." m_createTextureToGeom.kTooManyMeshes;
displayString -replace -value "Too many selections. Please select only one mesh." m_createTextureToGeom.kTooManyMeshes2;
