// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  August 14, 1996
//
//  Description:
//      Make a popup for all the fonts available
//
//  Input Arguments:
//      $popupArgs - extra arguments/flags to pass to the font dialog
//
//      $command   - command to execute. Is passed $extraArg, $tabLayout
//      			 and the font returned by the dialog.
//
//		$extraArg  - first argument passed to $command. If set to "NULL"
//					 then this argument is not passed.
//
//		$layout    - second argument passed to $command (or the first,
//					 if $extraArg was "NULL"). Traditionally this was the
//					 layout to be updated by the command.
//
//  Return Value:
//      None.
//


global proc createFontPopup( string $popupArgs, string $command,
							 string $extraArg, string $layout )
{

	if ( $extraArg == "NULL" ) $extraArg = "";
	string $dowhat = ( $command + " " + $extraArg + " " +
					   "\"" + $layout + "\" " );

	string $fName = eval("fontDialog " + $popupArgs);
	if ($fName == "") return;
	eval ($dowhat + "\"" + $fName + "\";");	

}

