// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// Description: This procedure will return true if the specified render
//              layer is connected to the render layer manager. This
//              will be used as a filter script in the render globals
//              editor.
//
global proc int layerOnRenderManager(string $findRenderLayer)
{
    int $isFound = false;
    string $managerLayers[] = `listConnections renderLayerManager.renderLayerId`;
    for ($layer in $managerLayers) {
        if ($layer == $findRenderLayer && `nodeType $layer` == "renderLayer" ) {
            $isFound = true;
            break;
        }
    }
    return $isFound;
}

// Description: This procedure is used to update the controls in
//      frame Render Layer/Pass.
//
global proc createRenderLayerFilters()
{
    //  Create render layers filters if they have not been created already.
	//	Item filters are no longer deleted on file new/open, so they only
	// 	need to be created once per session of Maya.
    if( !`itemFilter -exists defaultRenderLayerFilter` ) 
    {
        itemFilter -bn defaultRenderLayer -classification "builtIn" defaultRenderLayerFilter;
    }

    if( !`itemFilter -exists renderLayerFilter` ) 
    {
        itemFilter -byScript layerOnRenderManager -classification "builtIn" renderLayerFilter;
    }
}
