// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//  Description:
//      Cycles the background color of viewports, and then to gradient display
//
//  Return Value:
//      None.
//
global proc cycleBackgroundColor(){

	// query bg color
	float $rgb[3] = `displayRGBColor -query background`;

	int $gradOn = `displayPref -q -displayGradient`;
	if ($gradOn)
	{
		displayRGBColor background 0 0 0;
		displayPref -displayGradient 0;
	}
	else
	{
		if ($rgb[0] == 0)
		{	
			displayRGBColor background 0.36 0.36 0.36;//default color
		}
		else if ($rgb[0] < 0.5)
		{
			displayRGBColor background 0.631 0.631 0.631;
		}
		else
		{
			displayPref -displayGradient 1;
		}
	}

	optionVar -intValue "displayViewportGradient" `displayPref -query -displayGradient`;
}
