// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Custom naming chosen, but no custom name was set." m_doPublishAttribute.kCustomNameProblem;
displayString -replace -value "No attributes were selected in the channel box." m_doPublishAttribute.kNoChannelBoxAttrs;
displayString -replace -value "No input connections found." m_doPublishAttribute.kNoIncomingConns;
displayString -replace -value "No keyable attributes found." m_doPublishAttribute.kNoKeyableAttrs;
displayString -replace -value "No selected attributes found." m_doPublishAttribute.kNoSelectedAttrs;
displayString -replace -value "Nothing was selected for publishing." m_doPublishAttribute.kNothingSelected;
displayString -replace -value "// Published ^1s to ^2s.\n" m_doPublishAttribute.kPublishedAttrMsg;
displayString -replace -value "Skipping ^1s. It is already published." m_doPublishAttribute.kPublishedAttrSkip;
displayString -replace -value "Selected objects are not in an asset." m_doPublishAttribute.kSelectedNotInContainer;
displayString -replace -value "// Skipping '^1s'. It is not in a container." m_doPublishAttribute.kSkippingNode;
