// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.


//
//
//  Creation Date:  May, 1997
//
//  Description:
//      dynExecuteGoalCommand executes the goal command 
//
//  Input Arguments():
//		string $goalCmd -- the goal command string (except for the selection)
//
//  Return Value:
//      None.
//
//
//  ============== dynExecuteGoalCommand ==============
//
//  SYNOPSIS
//		Execute the goal command.
//		The last item in the selection list is the goal, and all
//		other items are attracted to it.
//
global proc	dynExecuteGoalCommand(string $goalCmd)
{
	string $fullCmd;
	int $numParticleObjs;
	int $i;

	string $selected[] = `ls -sl`;

	$numParticleObjs = size($selected) - 1;

	$fullCmd = $goalCmd + " -g " +$selected[$numParticleObjs] + " ";

	for ($i = 0; $i < $numParticleObjs; $i++)
		$fullCmd = $fullCmd + " " + $selected[$i];

	evalEcho($fullCmd);
}

