// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "All Files" m_fileDialogFilterTypes.kAllFiles;
displayString -replace -value "XML Files" m_fileDialogFilterTypes.kEDLExportFiles;
displayString -replace -value "XML and AAF Files" m_fileDialogFilterTypes.kEDLFiles;
displayString -replace -value "From Tool Settings" m_fileDialogFilterTypes.kFromToolSettings;
displayString -replace -value "Image Files" m_fileDialogFilterTypes.kImageFiles;
displayString -replace -value "Light Profile" m_fileDialogFilterTypes.kLightProfile;
displayString -replace -value "Maya ASCII" m_fileDialogFilterTypes.kMayaAscii;
displayString -replace -value "Maya Binary" m_fileDialogFilterTypes.kMayaBinary;
displayString -replace -value "Maya Scenes" m_fileDialogFilterTypes.kMayaScenes;
displayString -replace -value "Maya Mel Files" m_fileDialogFilterTypes.kMelFiles;
displayString -replace -value "Movie Files" m_fileDialogFilterTypes.kMovieFiles;
displayString -replace -value "Offline Edit Ascii" m_fileDialogFilterTypes.kOfflineEditAscii;
displayString -replace -value "Offline Edit Binary" m_fileDialogFilterTypes.kOfflineEditBinary;
displayString -replace -value "Photoshop Files" m_fileDialogFilterTypes.kPhotoshopFiles;
displayString -replace -value "Image Files" m_fileDialogFilterTypes.kPixmapFiles;
displayString -replace -value "Plug-in Files" m_fileDialogFilterTypes.kPluginFiles;
displayString -replace -value "Render Proxy" m_fileDialogFilterTypes.kRenderProxy;
displayString -replace -value "Template Files" m_fileDialogFilterTypes.kTemplateFiles;
displayString -replace -value "Weight Map" m_fileDialogFilterTypes.kWeightMap;
displayString -replace -value "XML Cache Files" m_fileDialogFilterTypes.kXMLCacheFiles;
