// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  15 September 1996
//<doc>
//<name floatEq>
//
//<synopsis>
//		int	floatEq(float $f1, float $f2)
//
//<description>
//      This script checks two float to determine they are
//      equal within 0.01.
//
//<flags>
//      float	$f1	First float value to be compared
//      float	$f2	Second float value to be compared
//
//<returns>
//      int : 1 if values are within 0.01, else 0
//
//<examples>
//
//	floatEq(5.0, 5.001);
//	// Result: 1 //
//
//	floatEq(5.0, 5.1);
//	// Result: 0 //
//
//</doc>
//
global proc int floatEq( float $vLhs, float $vRhs )
{
	return abs( $vLhs - $vRhs ) < 0.01;

} // floatEq //
