// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Save State As: failed to create cache file: ^1s" m_fluidSaveStateAs.kCacheCreateFailure;
displayString -replace -value "Cancel" m_fluidSaveStateAs.kCancel;
displayString -replace -value "**** debug : ^1s\tresult: ^2s\n" m_fluidSaveStateAs.kDebugInfo;
displayString -replace -value "Save State As: failed to create data directory ^1s" m_fluidSaveStateAs.kDirectoryCreationFailureWarn;
displayString -replace -value "File Exists. Overwrite?" m_fluidSaveStateAs.kFileExists;
displayString -replace -value "No fluid selected." m_fluidSaveStateAs.kNoFluidSelectedError;
displayString -replace -value "Save State" m_fluidSaveStateAs.kSaveState;
displayString -replace -value "Save State As" m_fluidSaveStateAs.kSaveStateAs;
displayString -replace -value "Save State As... is only valid on one fluid at a time." m_fluidSaveStateAs.kSaveStateAsError;
displayString -replace -value "Save State As: cannot save Initial State.  Check write permissions and disk space." m_fluidSaveStateAs.kSaveStateAsWarn;
displayString -replace -value "Yes" m_fluidSaveStateAs.kYes;
