// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "As Action" m_getOptionBox.kCreateAsAction;
displayString -replace -value "As Tool" m_getOptionBox.kCreateAsTool;
displayString -replace -value "Edit" m_getOptionBox.kCreateEditMenu;
displayString -replace -value "Help" m_getOptionBox.kCreateHelpMenu;
displayString -replace -value "No Help Currently Available" m_getOptionBox.kCreateNoHelpCurrentlyAvailable;
displayString -replace -value "Options" m_getOptionBox.kCreateOptions;
displayString -replace -value "Reset Settings" m_getOptionBox.kCreateResetSettings;
displayString -replace -value "Save Settings" m_getOptionBox.kCreateSaveSettings;
displayString -replace -value "Apply" m_getOptionBox.kGetApply;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kGetApplyCloseWindowDoesNotExist;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kGetApplyWindowDoesNotExist;
displayString -replace -value "Close" m_getOptionBox.kGetClose;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kGetCloseWindowDoesNotExist;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kGetHelpWindowDoesNotExist;
displayString -replace -value "Reset" m_getOptionBox.kGetReset;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kGetResetWindowDoesNotExist;
displayString -replace -value "Save" m_getOptionBox.kGetSave;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kGetSaveWindowDoesNotExist;
displayString -replace -value "Help on ^1s" m_getOptionBox.kHelpOn;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kNoOptionBoxWin;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kSetHelpWindowDoesNotExist;
displayString -replace -value "Help with " m_getOptionBox.kSetHelpWith;
displayString -replace -value "No Help Currently Available" m_getOptionBox.kSetNoHelp;
displayString -replace -value "Option Box window does not exist." m_getOptionBox.kSetTitleWindowDoesNotExist;
displayString -replace -value "Apply" m_getOptionBox.kShowApply;
displayString -replace -value "Apply and Close" m_getOptionBox.kShowApplyAndClose;
