// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// Helper for forming the nodePreset command when saving presets for the render
// settings.
//
// Because both the Common Tab and Maya Software Tab share the node
// defaultRenderGlobals and defaultRenderResolution, we should only save
// the settings in Common Tab when the current render is not Maya Software.
//
global proc string[] getRenderSettingPresetArgs(string $renderer)
{
	string $globalsNodes[] = `renderer -q -globalsNodes $renderer`;
    string $savingArgs[] = {};
    string $attrInCommonTabRenderGlobals = "renderAll imageFilePrefix imageFormat imfPluginKey " +
                                           "animation extensionPadding outFormatControl outFormatExt useMayaFileName " +
                                           "useFrameExt putFrameBeforeExt periodInExt renderVersion animationRange " +
                                           "startFrame endFrame byFrameStep modifyExtension startExtension byExtension " +
                                           "enableDefaultLight preMel postMel preRenderLayerMel postRenderLayerMel " +
                                           "preRenderMel postRenderMel renderLayerEnable multiCamNamingMode bufferName";
    string $attrInCommonTabResolution = "aspectLock lockDeviceAspectRatio width height imageSizeUnits dotsPerInch " +
                                        "pixelDensityUnits deviceAspectRatio pixelAspect";

    if ($renderer == "mayaSoftware") {
        for ($globalsNode in $globalsNodes) {
            $savingArgs[size($savingArgs)] = "";
        }
    }
    else {
        for ($globalsNode in $globalsNodes) {
        	if (`objExists $globalsNode`) {
				if (`nodeType $globalsNode` == "renderGlobals")
					$savingArgs[size($savingArgs)] = "-attributes \"" + $attrInCommonTabRenderGlobals + "\"";
				else if(`nodeType $globalsNode` == "resolution")
					$savingArgs[size($savingArgs)] = "-attributes \"" + $attrInCommonTabResolution + "\"";
				else
					$savingArgs[size($savingArgs)] = "";
			}
        }
    }

    return $savingArgs;
}