// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  October 1998
//
//  Description:
//      Global function to ensure the options for bevel are set.
//
//  Input Arguments:
//      Force the factory setting or not.
//
//  Return Value:
//      None.
//

global proc globalStitchSetOptionVars( 
	int $forceFactorySettings )
//
//
//
{
	if ($forceFactorySettings || !`optionVar -exists globalStitchKeepOriginal`) {
        optionVar -intValue globalStitchKeepOriginal 0 ;
    }
	if ($forceFactorySettings || !`optionVar -exists globalStitchCorners`) {
        optionVar -intValue globalStitchCorners 1 ;
    }
	if ($forceFactorySettings || !`optionVar -exists globalStitchEdges`) {
        optionVar -intValue globalStitchEdges 1 ;
    }
	if ($forceFactorySettings || !`optionVar -exists globalStitchSmoothness`) {
        optionVar -intValue globalStitchSmoothness 0 ;
    }
	if ($forceFactorySettings || !`optionVar -exists globalStitchCheckInteriors`) {
        optionVar -intValue globalStitchCheckInteriors 0 ;
    }
	if ($forceFactorySettings || !`optionVar -exists globalStitchMaxSeparation`) {
        optionVar -floatValue globalStitchMaxSeparation 0.1 ;
    }
	if ($forceFactorySettings || !`optionVar -exists globalStitchModificationResistance`) {
        optionVar -floatValue globalStitchModificationResistance 0.01 ;
    }
	if ($forceFactorySettings || !`optionVar -exists globalStitchSampling`) {
        optionVar -intValue globalStitchSampling 1 ;
    }

}

