// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Feet appear to be located below the ground. Foot Bottom To Ankle value may be wrong." m_hikDefinitionOperations.kCharacterizationBadFootHeight;
displayString -replace -value "Referenced character cannot be deleted." m_hikDefinitionOperations.kDeleteReferencedCharacterWarning;
displayString -replace -value "Enter Name:" m_hikDefinitionOperations.kEnterName;
displayString -replace -value " character definition is locked. Un-lock it?" m_hikDefinitionOperations.kExistingDefinitionMessageDialog;
displayString -replace -value "No" m_hikDefinitionOperations.kExistingDefinitionNoDialog;
displayString -replace -value "Existing Definition" m_hikDefinitionOperations.kExistingDefinitionTitleDialog;
displayString -replace -value "Yes" m_hikDefinitionOperations.kExistingDefinitionYesDialog;
displayString -replace -value "The Skeleton Definition is invalid and cannot be locked." m_hikDefinitionOperations.kLockMessageDialog;
displayString -replace -value "OK" m_hikDefinitionOperations.kLockNoDialog;
displayString -replace -value "Referenced character cannot be locked or un-locked." m_hikDefinitionOperations.kLockReferencedCharacterWarning;
displayString -replace -value "Lock Characterization" m_hikDefinitionOperations.kLockTitleDialog;
displayString -replace -value "Un-locking the character definition will delete the control rig.\n Do you want to continue?" m_hikDefinitionOperations.kMessageDialog;
displayString -replace -value "No" m_hikDefinitionOperations.kNoDialog;
displayString -replace -value "Referenced rig cannot be deleted." m_hikDefinitionOperations.kReferencedRigDeleteWarning;
displayString -replace -value "Rename Character" m_hikDefinitionOperations.kRename;
displayString -replace -value "Delete Rig: " m_hikDefinitionOperations.kTitleDialog;
displayString -replace -value "Yes" m_hikDefinitionOperations.kYesDialog;
