// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Bake Control Rig" m_hikGlobalUtils.kBakeControlRig;
displayString -replace -value "Bake Custom Rig" m_hikGlobalUtils.kBakeCustomRig;
displayString -replace -value "Bake Live To Custom Rig" m_hikGlobalUtils.kBakeLiveToCustomRig;
displayString -replace -value "Bake Live To Skeleton" m_hikGlobalUtils.kBakeLiveToSkeleton;
displayString -replace -value "Bake Rig Body Part" m_hikGlobalUtils.kBakeRigBodyPart;
displayString -replace -value "Bake Skeleton" m_hikGlobalUtils.kBakeSkeleton;
displayString -replace -value "Bake To Control Rig" m_hikGlobalUtils.kBakeToControlRig;
displayString -replace -value "Bake To Custom Rig" m_hikGlobalUtils.kBakeToCustomRig;
displayString -replace -value "Bake To Skeleton" m_hikGlobalUtils.kBakeToSkeleton;
displayString -replace -value "Box" m_hikGlobalUtils.kBox;
displayString -replace -value "Cancel" m_hikGlobalUtils.kCancel;
displayString -replace -value "// New character '^1s' was created.\n" m_hikGlobalUtils.kCharacterCreated2;
displayString -replace -value "Configure Mirror Matching" m_hikGlobalUtils.kConfigureMirrorMatching;
displayString -replace -value "Control Rig" m_hikGlobalUtils.kControlRig;
displayString -replace -value "Controls" m_hikGlobalUtils.kControls;
displayString -replace -value "Create" m_hikGlobalUtils.kCreate;
displayString -replace -value "Custom Rig" m_hikGlobalUtils.kCustomRig;
displayString -replace -value "Define" m_hikGlobalUtils.kDefine;
displayString -replace -value "Definition" m_hikGlobalUtils.kDefinition;
displayString -replace -value "Delete" m_hikGlobalUtils.kDelete;
displayString -replace -value "Delete Control Rig" m_hikGlobalUtils.kDeleteControlRig;
displayString -replace -value "Edit Properties" m_hikGlobalUtils.kEditProperties;
displayString -replace -value "Export Mapping" m_hikGlobalUtils.kExportMapping;
displayString -replace -value "FK" m_hikGlobalUtils.kFK;
displayString -replace -value "HIK Definition" m_hikGlobalUtils.kHIKDefinition;
displayString -replace -value "IK" m_hikGlobalUtils.kIK;
displayString -replace -value "Import Mapping" m_hikGlobalUtils.kImportMapping;
displayString -replace -value "Live Connection" m_hikGlobalUtils.kLiveConnection;
displayString -replace -value "Load Skeleton Definition..." m_hikGlobalUtils.kLoadDefinition;
displayString -replace -value "Lock Definition" m_hikGlobalUtils.kLockDefinition;
displayString -replace -value "Map Rotation" m_hikGlobalUtils.kMapRotation;
displayString -replace -value "Map Translation" m_hikGlobalUtils.kMapTranslation;
displayString -replace -value "Mirror Matching" m_hikGlobalUtils.kMirrorMatching;
displayString -replace -value "None" m_hikGlobalUtils.kNone;
displayString -replace -value "OK" m_hikGlobalUtils.kOK;
displayString -replace -value "Rename" m_hikGlobalUtils.kRename;
displayString -replace -value "Reset" m_hikGlobalUtils.kReset;
displayString -replace -value "Reset Properties" m_hikGlobalUtils.kResetProperties;
displayString -replace -value "Align Control Rig" m_hikGlobalUtils.kRigAlign;
displayString -replace -value "Rig Look" m_hikGlobalUtils.kRigLook;
displayString -replace -value "Save Skeleton Definition..." m_hikGlobalUtils.kSaveDefinition;
displayString -replace -value "Skeleton" m_hikGlobalUtils.kSkeleton;
displayString -replace -value "Stance" m_hikGlobalUtils.kStance;
displayString -replace -value "Stance Pose" m_hikGlobalUtils.kStancePose;
displayString -replace -value "Stick" m_hikGlobalUtils.kStick;
displayString -replace -value "Unknown" m_hikGlobalUtils.kUnknown;
displayString -replace -value "Wire" m_hikGlobalUtils.kWire;
