// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Big Toe" m_hikSkeletonUI.kBigToe;
displayString -replace -value "Character Scale" m_hikSkeletonUI.kCharacterScale;
displayString -replace -value "Create Skeleton" m_hikSkeletonUI.kCreateSkeleton;
displayString -replace -value "Extra Finger" m_hikSkeletonUI.kExtraFinger;
displayString -replace -value "Extras" m_hikSkeletonUI.kExtras;
displayString -replace -value "Finger-Base" m_hikSkeletonUI.kFingerBase;
displayString -replace -value "Finger Joint Count" m_hikSkeletonUI.kFingerJointsCount;
displayString -replace -value "Fingers" m_hikSkeletonUI.kFingers;
displayString -replace -value "Foot Thumb" m_hikSkeletonUI.kFootThumb;
displayString -replace -value "Lock Skeleton Definition" m_hikSkeletonUI.kHIKCharacterizationLock;
displayString -replace -value "Delete Skeleton and Definition" m_hikSkeletonUI.kHIKDeleteSkeleton;
displayString -replace -value "Hips Translation" m_hikSkeletonUI.kHipTranslation;
displayString -replace -value "In-Foot Joints" m_hikSkeletonUI.kInFootJts;
displayString -replace -value "In-Hand Joints" m_hikSkeletonUI.kInHandJts;
displayString -replace -value "Index" m_hikSkeletonUI.kIndex;
displayString -replace -value "Index" m_hikSkeletonUI.kIndexToe;
displayString -replace -value "Lower-Arms" m_hikSkeletonUI.kLowArms;
displayString -replace -value "Lower-Legs" m_hikSkeletonUI.kLowLegs;
displayString -replace -value "Middle" m_hikSkeletonUI.kMiddleFinger;
displayString -replace -value "Middle" m_hikSkeletonUI.kMiddleToe;
displayString -replace -value "Mirror Left -> Right" m_hikSkeletonUI.kMirrorSkeleton;
displayString -replace -value "Neck Count" m_hikSkeletonUI.kNectCount;
displayString -replace -value "Pinky" m_hikSkeletonUI.kPinkyFinger;
displayString -replace -value "Pinky" m_hikSkeletonUI.kPinkyToe;
displayString -replace -value "Ring" m_hikSkeletonUI.kRing;
displayString -replace -value "Ring" m_hikSkeletonUI.kRingToe;
displayString -replace -value "Roll-Bones" m_hikSkeletonUI.kRollBones;
displayString -replace -value "Shoulder Count" m_hikSkeletonUI.kShoulderCount;
displayString -replace -value "Referenced skeleton cannot be edited." m_hikSkeletonUI.kSkeletonGeneratorToolReferencedEditWarning;
displayString -replace -value "Spine Count" m_hikSkeletonUI.kSpineCount;
displayString -replace -value "Thumb" m_hikSkeletonUI.kThumb;
displayString -replace -value "Toe-Base" m_hikSkeletonUI.kToeBase;
displayString -replace -value "Toes" m_hikSkeletonUI.kToes;
displayString -replace -value "Toe Joint Count" m_hikSkeletonUI.kToesJoints;
displayString -replace -value "Upper-Arms" m_hikSkeletonUI.kUpArms;
displayString -replace -value "Upper-Legs" m_hikSkeletonUI.kUpLegs;
