// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Add selected to asset" m_HyperGraphEdMenu.kAddToAsset;
displayString -replace -value "Add selected nodes to asset" m_HyperGraphEdMenu.kAddToAssetAnnot;
displayString -replace -value "Adjust Image" m_HyperGraphEdMenu.kAdjustImage;
displayString -replace -value "Advanced Assets" m_HyperGraphEdMenu.kAdvancedAssets;
displayString -replace -value "AnimateTransitions" m_HyperGraphEdMenu.kAnimateTransitions;
displayString -replace -value "Asset" m_HyperGraphEdMenu.kAsset;
displayString -replace -value "Attributes..." m_HyperGraphEdMenu.kAttributes;
displayString -replace -value "Automatic Layout" m_HyperGraphEdMenu.kAutomaticLayout;
displayString -replace -value "Bookmarks" m_HyperGraphEdMenu.kBookmarks;
displayString -replace -value "Bookmarks" m_HyperGraphEdMenu.kBookmarksHyperGraph;
displayString -replace -value "Callback" m_HyperGraphEdMenu.kCallback;
displayString -replace -value "Toggle global timing on and off" m_HyperGraphEdMenu.kChangeCommandAnnot;
displayString -replace -value "Circular Layout" m_HyperGraphEdMenu.kCircularLayout;
displayString -replace -value "Clear View" m_HyperGraphEdMenu.kClearView;
displayString -replace -value "Close" m_HyperGraphEdMenu.kClose;
displayString -replace -value "Collapse" m_HyperGraphEdMenu.kCollapse;
displayString -replace -value "Collapse Asset" m_HyperGraphEdMenu.kCollapseAsset;
displayString -replace -value "Collapse selected asset(s)" m_HyperGraphEdMenu.kCollapseAssetAnnot;
displayString -replace -value "Collapse" m_HyperGraphEdMenu.kCollapseMenuItem;
displayString -replace -value "Compute" m_HyperGraphEdMenu.kCompute;
displayString -replace -value "Confirm" m_HyperGraphEdMenu.kConfirm;
displayString -replace -value "Confirm" m_HyperGraphEdMenu.kConfirmClear;
displayString -replace -value "Do you really want to clear your graph view ?" m_HyperGraphEdMenu.kConfirmClearMsg;
displayString -replace -value "Do you really want to reset the freeform layout?" m_HyperGraphEdMenu.kConfirmResetMsg;
displayString -replace -value "Constraint Connections" m_HyperGraphEdMenu.kConstraintConn;
displayString -replace -value "Constraint Connections" m_HyperGraphEdMenu.kConstraintConnections;
displayString -replace -value "Count" m_HyperGraphEdMenu.kCount;
displayString -replace -value "Create" m_HyperGraphEdMenu.kCreate;
displayString -replace -value "Create Asset with Transform" m_HyperGraphEdMenu.kCreateAssetWithTransform;
displayString -replace -value "Create asset from selected" m_HyperGraphEdMenu.kCreateNewAsset;
displayString -replace -value "Create an asset for the selected object(s)" m_HyperGraphEdMenu.kCreateNewAssetAnnot;
displayString -replace -value "Create Render Node..." m_HyperGraphEdMenu.kCreateRenderNode;
displayString -replace -value "Selection cutoff:" m_HyperGraphEdMenu.kCutoff;
displayString -replace -value "When selecting hottest nodes, specifies the cutoff above which nodes are selected, relative to threshold (if enabled)" m_HyperGraphEdMenu.kCutoffAnnot;
displayString -replace -value "Decrease Depth Traversal" m_HyperGraphEdMenu.kDecreaseDepthTraversal;
displayString -replace -value "Deformer Connections" m_HyperGraphEdMenu.kDeformerConn;
displayString -replace -value "Deformer Connections" m_HyperGraphEdMenu.kDeformerConnections;
displayString -replace -value "Dirty" m_HyperGraphEdMenu.kDirty;
displayString -replace -value "Display" m_HyperGraphEdMenu.kDisplay;
displayString -replace -value "Display settings" m_HyperGraphEdMenu.kDisplayTimingValues;
displayString -replace -value "Draw" m_HyperGraphEdMenu.kDraw;
displayString -replace -value "Edit" m_HyperGraphEdMenu.kEdit;
displayString -replace -value "Edit" m_HyperGraphEdMenu.kEditMenu;
displayString -replace -value "Expand" m_HyperGraphEdMenu.kExpand;
displayString -replace -value "Expand All" m_HyperGraphEdMenu.kExpandAll;
displayString -replace -value "Expand All" m_HyperGraphEdMenu.kExpandAllMenuItem;
displayString -replace -value "Expand Asset" m_HyperGraphEdMenu.kExpandAsset;
displayString -replace -value "Expand selected asset(s)" m_HyperGraphEdMenu.kExpandAssetAnnot;
displayString -replace -value "Expand" m_HyperGraphEdMenu.kExpandMenuItem;
displayString -replace -value "Expression Connections" m_HyperGraphEdMenu.kExpressionConn;
displayString -replace -value "Expression Connections" m_HyperGraphEdMenu.kExpressionConnections;
displayString -replace -value "Filter Connections" m_HyperGraphEdMenu.kFilterConnect;
displayString -replace -value "Show Connections from Selected" m_HyperGraphEdMenu.kFilterFrom;
displayString -replace -value "Show All Connections" m_HyperGraphEdMenu.kFilterShowAll;
displayString -replace -value "Show Connections to Selected" m_HyperGraphEdMenu.kFilterTo;
displayString -replace -value "Show Connections to/from Selected" m_HyperGraphEdMenu.kFilterToFrom;
displayString -replace -value "Fit to Height" m_HyperGraphEdMenu.kFitToHeight;
displayString -replace -value "Fit to Width" m_HyperGraphEdMenu.kFitToWidth;
displayString -replace -value "Frame All" m_HyperGraphEdMenu.kFrameAll;
displayString -replace -value "Frame Branch" m_HyperGraphEdMenu.kFrameBranch;
displayString -replace -value "Frame Branch" m_HyperGraphEdMenu.kFrameBranchMenuItem;
displayString -replace -value "Frame Hierarchy" m_HyperGraphEdMenu.kFrameHierarchy;
displayString -replace -value "Frame Hierarchy" m_HyperGraphEdMenu.kFrameHierarchyMenuItem;
displayString -replace -value "Frame Selection" m_HyperGraphEdMenu.kFrameSelection;
displayString -replace -value "10 Frames" m_HyperGraphEdMenu.kFrames10;
displayString -replace -value "15 Frames" m_HyperGraphEdMenu.kFrames15;
displayString -replace -value "20 Frames" m_HyperGraphEdMenu.kFrames20;
displayString -replace -value " 5 Frames" m_HyperGraphEdMenu.kFrames5;
displayString -replace -value "Freeform Layout" m_HyperGraphEdMenu.kFreeformLayout;
displayString -replace -value "Global timing" m_HyperGraphEdMenu.kGlobalTiming;
displayString -replace -value "Graph" m_HyperGraphEdMenu.kGraph;
displayString -replace -value "Graph" m_HyperGraphEdMenu.kGraphHyperGraph;
displayString -replace -value "Graph Layout Style" m_HyperGraphEdMenu.kGraphLayoutStyle;
displayString -replace -value "Heat Map Controls" m_HyperGraphEdMenu.kHeatMapControls;
displayString -replace -value "Heat Map Display" m_HyperGraphEdMenu.kHeatMapDisplay;
displayString -replace -value "Hidden Nodes" m_HyperGraphEdMenu.kHiddenNodes;
displayString -replace -value "Hide" m_HyperGraphEdMenu.kHideMenuItem;
displayString -replace -value "Hierarchical Layout" m_HyperGraphEdMenu.kHierarchicalLayout;
displayString -replace -value "Horizontal" m_HyperGraphEdMenu.kHorizontal;
displayString -replace -value "Horizontal Position" m_HyperGraphEdMenu.kHorizontalPosition;
displayString -replace -value "Hypergraph" m_HyperGraphEdMenu.kHypergraph;
displayString -replace -value "Image Name" m_HyperGraphEdMenu.kImageName;
displayString -replace -value "Inclusive" m_HyperGraphEdMenu.kInclusive;
displayString -replace -value "Increase Depth Traversal" m_HyperGraphEdMenu.kIncreaseDepthTraversal;
displayString -replace -value "Input and Output Connections" m_HyperGraphEdMenu.kInputAndOutputConnections;
displayString -replace -value "Input Connections" m_HyperGraphEdMenu.kInputConnections;
displayString -replace -value "Layout" m_HyperGraphEdMenu.kLayout;
displayString -replace -value "Layout Asset" m_HyperGraphEdMenu.kLayoutAsset;
displayString -replace -value "Perform an automatic layout on the asset contents" m_HyperGraphEdMenu.kLayoutAssetAnnot;
displayString -replace -value "Layout" m_HyperGraphEdMenu.kLayoutOptionMenu;
displayString -replace -value "Load..." m_HyperGraphEdMenu.kLoad;
displayString -replace -value "Load Image" m_HyperGraphEdMenu.kLoadImage;
displayString -replace -value "Load" m_HyperGraphEdMenu.kLoadNoDots;
displayString -replace -value "Merge Connections" m_HyperGraphEdMenu.kMergeConnections;
displayString -replace -value "Metric:" m_HyperGraphEdMenu.kMetric;
displayString -replace -value "Select which timing metric is used for heat map display" m_HyperGraphEdMenu.kMetricAnnot;
displayString -replace -value "Next View" m_HyperGraphEdMenu.kNextView;
displayString -replace -value "No" m_HyperGraphEdMenu.kNoClear;
displayString -replace -value "No" m_HyperGraphEdMenu.kNoReset;
displayString -replace -value "Node Display Override Color" m_HyperGraphEdMenu.kNodeDisplayOverrideColor;
displayString -replace -value "On Nodes Creation" m_HyperGraphEdMenu.kOnNodesCreation;
displayString -replace -value "On Selection" m_HyperGraphEdMenu.kOnSelection;
displayString -replace -value "Opaque Assets" m_HyperGraphEdMenu.kOpaqueAssets;
displayString -replace -value "Toggles asset opacity" m_HyperGraphEdMenu.kOpaqueContainersAnnot;
displayString -replace -value "Options" m_HyperGraphEdMenu.kOptions;
displayString -replace -value "Options" m_HyperGraphEdMenu.kOptionsHyperGraph;
displayString -replace -value "Orientation" m_HyperGraphEdMenu.kOrientation;
displayString -replace -value "Orthogonal Layout" m_HyperGraphEdMenu.kOrthogonalLayout;
displayString -replace -value "Output Connections" m_HyperGraphEdMenu.kOutputConnections;
displayString -replace -value "Previous View" m_HyperGraphEdMenu.kPreviousView;
displayString -replace -value "Publish Child Anchor" m_HyperGraphEdMenu.kPublishChildAnchor;
displayString -replace -value "Publish Connections" m_HyperGraphEdMenu.kPublishConnections;
displayString -replace -value "Publish Parent Anchor" m_HyperGraphEdMenu.kPublishParentAnchor;
displayString -replace -value "Rebuild" m_HyperGraphEdMenu.kRebuild;
displayString -replace -value "Remove Asset" m_HyperGraphEdMenu.kRemoveAsset;
displayString -replace -value "Remove selected asset(s)" m_HyperGraphEdMenu.kRemoveAssetAnnot;
displayString -replace -value "Remove from asset" m_HyperGraphEdMenu.kRemoveFromAsset;
displayString -replace -value "Remove selected from asset" m_HyperGraphEdMenu.kRemoveFromAssetAnnot;
displayString -replace -value "Rename" m_HyperGraphEdMenu.kRename;
displayString -replace -value "Rename" m_HyperGraphEdMenu.kRenameMenuItem;
displayString -replace -value "Rendering" m_HyperGraphEdMenu.kRendering;
displayString -replace -value "Rendering" m_HyperGraphEdMenu.kRenderingHyperGraph;
displayString -replace -value "Reset Freeform Layout" m_HyperGraphEdMenu.kResetFreeformLayout;
displayString -replace -value "Reset timers" m_HyperGraphEdMenu.kResetTimers;
displayString -replace -value "Reset all timers to zero" m_HyperGraphEdMenu.kResetTimersAnnot;
displayString -replace -value "Scale" m_HyperGraphEdMenu.kScale;
displayString -replace -value "Scene Hierarchy" m_HyperGraphEdMenu.kSceneHierarchy;
displayString -replace -value "Schematic" m_HyperGraphEdMenu.kSchematic;
displayString -replace -value "Select" m_HyperGraphEdMenu.kSelect;
displayString -replace -value "Set the selection list to contain the hottest nodes based on the cutoff parameter" m_HyperGraphEdMenu.kSelectAnnot;
displayString -replace -value "Select Asset Contents" m_HyperGraphEdMenu.kSelectAssetContent;
displayString -replace -value "Selection tool" m_HyperGraphEdMenu.kSelectionTool;
displayString -replace -value "Self" m_HyperGraphEdMenu.kSelf;
displayString -replace -value "Set Asset as Current" m_HyperGraphEdMenu.kSetAssetCurrent;
displayString -replace -value "Set the asset as the current asset" m_HyperGraphEdMenu.kSetAssetCurrentAnnot;
displayString -replace -value "Set Background Image..." m_HyperGraphEdMenu.kSetBackgroundImage;
displayString -replace -value "Set Current Asset" m_HyperGraphEdMenu.kSetCurrentAsset;
displayString -replace -value "Set current asset. New nodes will be placed into the current asset." m_HyperGraphEdMenu.kSetCurrentAssetAnnot;
displayString -replace -value "Shape Nodes" m_HyperGraphEdMenu.kShapeNodes;
displayString -replace -value "Show to Selected" m_HyperGraphEdMenu.kShowAToConn;
displayString -replace -value "Show all Connections" m_HyperGraphEdMenu.kShowAllConn;
displayString -replace -value "Show Background Image" m_HyperGraphEdMenu.kShowBackgroundImage;
displayString -replace -value "Show Cached Connections" m_HyperGraphEdMenu.kShowCachedConnections;
displayString -replace -value "Show Cached Connections" m_HyperGraphEdMenu.kShowCachedConnectionsOption;
displayString -replace -value "Show from Selected" m_HyperGraphEdMenu.kShowFromConn;
displayString -replace -value "Show to/from Selected" m_HyperGraphEdMenu.kShowFromToConn;
displayString -replace -value "Show Lights" m_HyperGraphEdMenu.kShowLights;
displayString -replace -value "Show Materials" m_HyperGraphEdMenu.kShowMaterials;
displayString -replace -value "Show" m_HyperGraphEdMenu.kShowMenuItem;
displayString -replace -value "Show Relationship Connections" m_HyperGraphEdMenu.kShowRelationshipConnections;
displayString -replace -value "Show Selected" m_HyperGraphEdMenu.kShowSelected;
displayString -replace -value "Show ShadingGroups" m_HyperGraphEdMenu.kShowShadingGroups;
displayString -replace -value "Show Textures" m_HyperGraphEdMenu.kShowTextures;
displayString -replace -value "Symmetric Layout" m_HyperGraphEdMenu.kSymetricLayout;
displayString -replace -value "Threshold:" m_HyperGraphEdMenu.kThreshold;
displayString -replace -value "Remap colors" m_HyperGraphEdMenu.kThreshold1;
displayString -replace -value "Hide nodes" m_HyperGraphEdMenu.kThreshold2;
displayString -replace -value "Specify node display based on the threshold limits" m_HyperGraphEdMenu.kThresholdAnnot;
displayString -replace -value "Lower threshold" m_HyperGraphEdMenu.kThresholdLower;
displayString -replace -value "Only display nodes above the lower threshold limit" m_HyperGraphEdMenu.kThresholdLowerAnnot;
displayString -replace -value "Upper threshold" m_HyperGraphEdMenu.kThresholdUpper;
displayString -replace -value "Only display nodes below the upper threshold limit" m_HyperGraphEdMenu.kThresholdUpperAnnot;
displayString -replace -value "Timing:" m_HyperGraphEdMenu.kTiming;
displayString -replace -value "on/off" m_HyperGraphEdMenu.kTiming1;
displayString -replace -value "Toggle Connection Label" m_HyperGraphEdMenu.kToggleConstLabel;
displayString -replace -value "Toggle the display node override color in the Hypergraph on and off" m_HyperGraphEdMenu.kToggleDisplayNodeAnnot;
displayString -replace -value "Toggle the colour coding of nodes based on performance" m_HyperGraphEdMenu.kToggleHeatMapDisplayAnnot;
displayString -replace -value "Toggles the display of cached connections" m_HyperGraphEdMenu.kTogglesDisplayAnnot;
displayString -replace -value "Toggles the display of relationship connections" m_HyperGraphEdMenu.kTogglesDisplayRelationshipAnnot;
displayString -replace -value "Toggles merging of connections" m_HyperGraphEdMenu.kTogglesMergeConnectionsAnnot;
displayString -replace -value "Transfer Attribute Values" m_HyperGraphEdMenu.kTransferAttrValues;
displayString -replace -value "Transitions" m_HyperGraphEdMenu.kTransitions;
displayString -replace -value "Tree Layout" m_HyperGraphEdMenu.kTreeLayout;
displayString -replace -value "Type:" m_HyperGraphEdMenu.kType;
displayString -replace -value "Select which timing type is used for heat map display" m_HyperGraphEdMenu.kTypeAnnot;
displayString -replace -value "Underworld Nodes" m_HyperGraphEdMenu.kUnderworldNodes;
displayString -replace -value "Unpublish Child Anchor" m_HyperGraphEdMenu.kUnpublishChild;
displayString -replace -value "Unpublish Parent Anchor" m_HyperGraphEdMenu.kUnpublishParent;
displayString -replace -value "Update" m_HyperGraphEdMenu.kUpdate;
displayString -replace -value "Redraw HyperGraph(s)" m_HyperGraphEdMenu.kUpdateDisplay;
displayString -replace -value "Redraw HyperGraph windows" m_HyperGraphEdMenu.kUpdateDisplayAnnot;
displayString -replace -value "Vertical" m_HyperGraphEdMenu.kVertical;
displayString -replace -value "Vertical Position" m_HyperGraphEdMenu.kVerticalPosition;
displayString -replace -value "View" m_HyperGraphEdMenu.kView;
displayString -replace -value "View" m_HyperGraphEdMenu.kViewMenu;
displayString -replace -value "Yes" m_HyperGraphEdMenu.kYesClear;
displayString -replace -value "Yes" m_HyperGraphEdMenu.kYesReset;
