// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Object, \"^1s\", does not have the attribute, \"^2s\"." m_includeEffectsGlobals.kAttrInexistant;
displayString -replace -value "Breaking execution at ^1s\n" m_includeEffectsGlobals.kBreakingExecution;
displayString -replace -value "Can't create decomposeMatrix node." m_includeEffectsGlobals.kCantCreateNode;
displayString -replace -value "Can't load plugin node matrixNodes." m_includeEffectsGlobals.kCantLoadPlugin;
displayString -replace -value "Object, \"^1s\", does not exist and cannot be marked." m_includeEffectsGlobals.kCantMark;
displayString -replace -value "Object, \"^1s\", does not exist and cannot be used to mark ^2s." m_includeEffectsGlobals.kCantUse;
displayString -replace -value "^1s is an underworld object.  This procedure does not work for underworld objects." m_includeEffectsGlobals.kCurveUnderworld;
displayString -replace -value "Cannot find a curve shape from the object \"^1s\"." m_includeEffectsGlobals.kNoCurve;
displayString -replace -value "The object \"^1s\" does not exist." m_includeEffectsGlobals.kNoObject;
displayString -replace -value "Cannot find the shape for the object \"^1s\"." m_includeEffectsGlobals.kNoShape;
displayString -replace -value "Object, \"^1s\", does not exist." m_includeEffectsGlobals.kObjInexistant;
displayString -replace -value "The object, \"^1s\", does not exist to add an attribute to." m_includeEffectsGlobals.kObjectInexistant;
displayString -replace -value "Saving scene to file ^1s\n" m_includeEffectsGlobals.kSavingScene;
