// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//<doc>
//<name intArrayInsertAtIndex>
//
//<synopsis>
//		int intArrayInsertAtIndex(int $index, int[] $list, int $item)
//
//<description>
//		Insert $item at $index in the integer array $list. If $index is
//		greater than the last index of $list, $item will be placed at the
//		end of the list.
//
//<flags>
//		int   $index  The index into $list to add $item at
//		int[] $list   A list of int values.
//		int   $item   The new item to add to $list at $index
//
//<returns>
//		int : Returns false if $index was negative and true on
//			  success.
//
//<examples>
//  // Initialize the list
//  int $list[] = {1, 3};
//  // Result: 1 3 //
//  // Insert in the middle of the sequence
//  intArrayInsertAtIndex(1, $list, 2 );
//  // Result: 1 //
//  print $list;
//  // Result: 1 2 3 //
//  // Insert before the first element
//  intArrayInsertAtIndex(-1, $list, 4 );
//  // Result: 0 //
//  // Insert at ( or after ) the last element
//  intArrayInsertAtIndex(10, $list, 4 );
//  // Result: 1 //
//  print $list;
//  // Result: 1 2 3 4 //
//  // Insert at the beginning of the sequence
//  intArrayInsertAtIndex( 0, $list, 0 );
//  // Result: 1 //
//  print $list;
//  // Result: 0 1 2 3 4 //
//
//</doc>
//

global proc int intArrayInsertAtIndex( int $index, int $list[], int $item )
{
	int $len = size( $list );

	// Check for a invalid indeces ...
	//
	if ( $index < 0 )
		return false;

	// ... or for the simple case of appending to the 
	//     end of the array
	//
	if ( $index >= $len )
	{
		$list[$len] = $item;
		return true;
	}

	// If either of these tests fail, we are inserting 
	// somewhere into the middle of the list
	
	// First do an in-place copy of all entries after $index
	//
	int $i;
	for ($i = $len-1; $i >= $index; $i--)
		$list[$i+1] = $list[$i];

	// Lastly copy entry at $index
	//
	$list[$index] = $item;

	return true;
}
