// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  November 20, 1996
//
//
//<doc>
//<name isAnimCurve>
//
//<synopsis>
//		isAnimCurve (string $object)
//
//<returns>
//		int : true if the object is an animCurve, false if not
//
//<description>
//		Determines whether or not the specified object is an animCurve 
//		(i.e. its nodeType is one
//		of animCurveTL, animCurveTA, animCurveTU, animCurveTT,
//		animCurveUL, animCurveUA, animCurveUU or animCurveUT)
//
//<flags>
//		string $object : The name of the object
//
//<examples>
//  polySphere;
//  string $sel[] = `ls -sl`;
//  isAnimCurve($sel[0]);
//
//</doc>

global proc int isAnimCurve (string $object)
{
	if ($object == "") {
		return (false);
	}
	string $nodeType = `nodeType $object`;
	if (substring ($nodeType, 1, 9) != "animCurve") {
		return (false);
	}
	return (true);
}
