// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//	Creation Date:	May 22, 2003
//
//<doc>
//<name isParentOf>
//
//<synopsis>
//		int isParentOf(string $parent, string $child)
//
//<returns>
//		int : True if $parent is a DAG parent of the specified DAG object.
//
//<description>
//		This procedure returns true if $parent is a DAG parent of the
//		specified DAG object, and false otherwise.
//
//		See also firstParentOf().
//
//<examples>
//		//	Create a NURBS sphere.
//		//
//		string $createdNodes[] = `sphere -constructionHistory false`;
//		string $sphere = $createdNodes[0];
//
//		//	Create a group containing a group containing the sphere.
//		//
//		string $group1 = `group`;
//		string $group2 = `group`;
//
//		isParentOf($sphere, $sphere);
//		//	Result: 0 //
//
//		isParentOf($group1, $sphere);
//		//	Result: 1 //
//
//		isParentOf($group2, $sphere);
//		//	Result: 1 //
//
//		isParentOf("", $group2);
//		//	Result: 0 //
//
//</doc>

global proc int isParentOf(string $parent, string $child)
{

	string $parentFullName = longNameOf( $parent );
	string $childFullName = longNameOf( $child );
	
	int $parentNameLen = size( $parentFullName );
	int $isParent = false;
	
	// Check that parent is not empty but still shorted than the child full name
	if( ($parentNameLen > 0) && ($parentNameLen < size( $childFullName )) )
	{
		// ensure that parent name s a prefix to the child full name
		$childFullName = substring( $childFullName, 1, $parentNameLen+1 ); 
		if( $childFullName ==  ($parentFullName+"|") )
		{
			$isParent = 1;
		}
	}
	return $isParent;
}

//	=== END OF FILE isParentOf.mel ===========================================
