// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.


//
//<doc>
//<name makeCurvesDynamicHairs>
//<owner "Autodesk">
//
//<synopsis>
//		makeCurvesDynamicHairs(int $surfaceAttach, int $snapToSurface, int $matchPosition)
//
//<returns>
//		None.	
//
//<description>
//	This is an older version of the command makeCurvesDynamic and is provided for backward compatibility.
//
//<flags>
//  int $surfaceAttach	If true then connect the hairs to a surface(also selected) basing the uv on the nearest point to the first curve cv
//  int $snapToSurface  If true and attaching to a surface then also snap the curve to the surface.
//  int $matchPosition	If true then make the input curve a degree one so resulting output curve exactly matches the position.
//
//<examples>
//  makeCurvesDynamicHairs false false false;
//</doc>


// This routine is an old routine for backward compatibility.
global proc makeCurvesDynamicHairs(int $surfaceAttach, int $snapToSurface, int $matchPosition)
{
	string $s1 = $surfaceAttach;
	string $s2 = $snapToSurface;
	string $s3 = $matchPosition;
	makeCurvesDynamic 1 { $s1, $s2, $s3 };
}
