// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Absolute" m_manipMoveProperties.kAbsolute;
displayString -replace -value "Along Live Object Axis" m_manipMoveProperties.kAlongLiveObjectAxis;
displayString -replace -value "Along Rotation Axis" m_manipMoveProperties.kAlongRotationAxis;
displayString -replace -value "Component" m_manipMoveProperties.kAutoAlign;
displayString -replace -value "Set a custom axis orientation" m_manipMoveProperties.kCustomAxisOrientFieldsAnn;
displayString -replace -value "Custom" m_manipMoveProperties.kCustomAxisOrientation;
displayString -replace -value "Set the orientation of the tool's axis" m_manipMoveProperties.kCustomAxisOrientationAnn;
displayString -replace -value "Edit Pivot" m_manipMoveProperties.kEditPivot;
displayString -replace -value "Activate pivot editing mode. Set the pivot position and axis orientation by selecting objects and components in the scene (D)" m_manipMoveProperties.kEditPivotAnn;
displayString -replace -value "Automatically Orient Joints" m_manipMoveProperties.kEnableJointOrient;
displayString -replace -value "Face center" m_manipMoveProperties.kFaceCenter;
displayString -replace -value "Joint Orient Settings" m_manipMoveProperties.kJointOrientSnapSettings;
displayString -replace -value "Parent" m_manipMoveProperties.kLocal;
displayString -replace -value "Transform Constraint:" m_manipMoveProperties.kManipMoveXformConstraint;
displayString -replace -value "Constrain moving components" m_manipMoveProperties.kManipMoveXformConstraintAnn;
displayString -replace -value "Edge" m_manipMoveProperties.kManipMoveXformConstraintEdge;
displayString -replace -value "Off" m_manipMoveProperties.kManipMoveXformConstraintNone;
displayString -replace -value "Surface" m_manipMoveProperties.kManipMoveXformConstraintSurf;
displayString -replace -value "Axis Orientation:" m_manipMoveProperties.kMove;
displayString -replace -value "Reset" m_manipMoveProperties.kMoveResetOri;
displayString -replace -value "Set To Component" m_manipMoveProperties.kMoveSetOriToComponent;
displayString -replace -value "Set To Edge" m_manipMoveProperties.kMoveSetOriToEdge;
displayString -replace -value "Set To Face" m_manipMoveProperties.kMoveSetOriToFace;
displayString -replace -value "Set To Point" m_manipMoveProperties.kMoveSetOriToVertex;
displayString -replace -value "Move Settings" m_manipMoveProperties.kMoveSettings;
displayString -replace -value "Move Snap Settings" m_manipMoveProperties.kMoveSnapSettings;
displayString -replace -value "Normal" m_manipMoveProperties.kNormal;
displayString -replace -value "Object" m_manipMoveProperties.kObject;
displayString -replace -value "Off" m_manipMoveProperties.kOff;
displayString -replace -value "Pin Component Pivot" m_manipMoveProperties.kPinComponentPivot;
displayString -replace -value "Lock the component pivot to prevent it from resetting on selection changes" m_manipMoveProperties.kPinComponentPivotAnn;
displayString -replace -value "Pivot:" m_manipMoveProperties.kPivotLabel;
displayString -replace -value "Preserve Children:" m_manipMoveProperties.kPreserveChildPos;
displayString -replace -value "Offset child objects to preserve their position while moving the parent object" m_manipMoveProperties.kPreserveChildPosAnn;
displayString -replace -value "Preserve UVs:" m_manipMoveProperties.kPreserveUVMove;
displayString -replace -value "Offset UVs to prevent texture warping when moving components" m_manipMoveProperties.kPreserveUVMoveAnn;
displayString -replace -value "Relative" m_manipMoveProperties.kRelative;
displayString -replace -value "Reset" m_manipMoveProperties.kResetPivot;
displayString -replace -value "Reset the pivot position and axis orientation" m_manipMoveProperties.kResetPivotAnn;
displayString -replace -value "Retain component spacing" m_manipMoveProperties.kRetainComponentSpacing;
displayString -replace -value "Orientation" m_manipMoveProperties.kSnapPivotOri;
displayString -replace -value "Snap the pivot orientation to the selected component" m_manipMoveProperties.kSnapPivotOriAnn;
displayString -replace -value "Position" m_manipMoveProperties.kSnapPivotPos;
displayString -replace -value "Snap the pivot position to the selected component" m_manipMoveProperties.kSnapPivotPosAnn;
displayString -replace -value "Snap to live polygon:" m_manipMoveProperties.kSnaptoLivePolygon;
displayString -replace -value "Step Snap:" m_manipMoveProperties.kStepSnap;
displayString -replace -value "Transform an object or component in increments (J)" m_manipMoveProperties.kStepSnapAnn;
displayString -replace -value "Tweak Mode:" m_manipMoveProperties.kTweakMode;
displayString -replace -value "Click and drag mode for adjusting components (`)" m_manipMoveProperties.kTweakModeAnn;
displayString -replace -value "Update [UVN] triad:" m_manipMoveProperties.kUpdateTriad;
displayString -replace -value "Vertex" m_manipMoveProperties.kVertex;
displayString -replace -value "World" m_manipMoveProperties.kWorld;
