// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Pick CV" m_menu_PA_Style_LMB.kPickCV;
displayString -replace -value "Pick Curve On Surface" m_menu_PA_Style_LMB.kPickCurveOnSurface;
displayString -replace -value "Pick Iso/Trim Edge/Curve Points" m_menu_PA_Style_LMB.kPickIso;
displayString -replace -value "Pick Nothing" m_menu_PA_Style_LMB.kPickNothing;
displayString -replace -value "Pick Obj Comp" m_menu_PA_Style_LMB.kPickObjComp;
displayString -replace -value "Pick Obj Root" m_menu_PA_Style_LMB.kPickObjRoot;
displayString -replace -value "Pick Pivot Point" m_menu_PA_Style_LMB.kPickPivotPoint;
displayString -replace -value "Pick Template" m_menu_PA_Style_LMB.kPickTemplate;
displayString -replace -value "Show HotBox" m_menu_PA_Style_LMB.kShowHotBox;
