// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Procedure Name:
//      nodePresetConfirmDeleteDialog
//
//      jdc (September 13, 2000)
//      cdt (March 2005)
//
// Description:
//      This procedure is called when the user has asked to delete a
//      preset. A dialog is displayed prompting the user to confirm that
//      they want to delete the settings. If the user chooses "Yes", the
//      preset is deleted. If the user chooses "No", this dialog closes
//      and the preset is not deleted.
//
//  Input Arguments:
//      $argv - a variable list of node names followed by the preset name.
//
//  Return Value:
//      None
//

global proc nodePresetConfirmDeleteDialog(
    string $argv[] )
{
    string $presetName = $argv[size($argv)-1];

	string $message = (uiRes("m_nodePresetConfirmDeleteDialog.kDeletePresetMsg"));
	string $dispMsg = `format -s $presetName $message`;
    string $delete = (uiRes("m_nodePresetConfirmDeleteDialog.kDelete"));
    string $cancel = (uiRes("m_nodePresetConfirmDeleteDialog.kCancel"));

	$confirmResponse = `confirmDialog
		-title (uiRes("m_nodePresetConfirmDeleteDialog.kDeletePreset"))
		-button $delete -button $cancel
		-cancelButton $cancel -defaultButton $delete
		-message $dispMsg`;

	int $isOverwritten = false;

	if ($delete == $confirmResponse)
	{
        int $i;
        for ($i = 0; $i < size($argv)-1; $i++)
        {
			if (`nodePreset -exists $argv[$i] $presetName`)
			{
				evalEcho(("nodePreset -delete " + $argv[$i] + " " + $presetName));
			}
        }
	}
}
