// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Create a new ^1s node" m_OutlinerEdRepMenu.kAnnAssemblyCreateLabel;
displayString -replace -value "Add a ^1s representation to the selected assembly definition node." m_OutlinerEdRepMenu.kAnnAssemblyCreateRep;
displayString -replace -value "Select a scene assembly reference or definition node for scene assembly options." m_OutlinerEdRepMenu.kAnnNoSceneAssemblySelected;
displayString -replace -value "Switch to the selected representation" m_OutlinerEdRepMenu.kAnnNoneRepLabel;
displayString -replace -value "Switch to the selected representation" m_OutlinerEdRepMenu.kAnnSceneAssemblyRep;
displayString -replace -value "Unload the active representation from the scene " m_OutlinerEdRepMenu.kAnnUnloadActiveRepLabel;
displayString -replace -value "Create ^1s..." m_OutlinerEdRepMenu.kAssemblyCreateLabel;
displayString -replace -value "Add ^1s representation" m_OutlinerEdRepMenu.kAssemblyCreateRep;
displayString -replace -value "Delete Representation" m_OutlinerEdRepMenu.kDeleteRepresentation;
displayString -replace -value "List Edits..." m_OutlinerEdRepMenu.kListAssemblyEdits;
displayString -replace -value "List edits to the contents of the selected assembly reference" m_OutlinerEdRepMenu.kListAssemblyEditsAnnot;
displayString -replace -value "No scene assembly node is selected." m_OutlinerEdRepMenu.kNoSceneAssemblySelected;
displayString -replace -value "No representations" m_OutlinerEdRepMenu.kNoneRepLabel;
displayString -replace -value "..." m_OutlinerEdRepMenu.kOpenAssemblyWindow;
displayString -replace -value "Unload Active Representation" m_OutlinerEdRepMenu.kUnloadActiveRepLabel;
