// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Auto completion" m_performBirail.kAutoCompletion;
displayString -replace -value "Bezier" m_performBirail.kBezier;
displayString -replace -value "Birail" m_performBirail.kBirail;
displayString -replace -value "Birail ^1s Options" m_performBirail.kBirailOptions;
displayString -replace -value "Birail ^1s Tool" m_performBirail.kBirailTool;
displayString -replace -value "Continuity:" m_performBirail.kContinuity;
displayString -replace -value "Exit on completion" m_performBirail.kExitOnCompletion;
displayString -replace -value "First profile" m_performBirail.kFirstProfile;
displayString -replace -value "First rail" m_performBirail.kFirstRail;
displayString -replace -value "Last Profile" m_performBirail.kLastProfile;
displayString -replace -value "Non proportional" m_performBirail.kNonProportional;
displayString -replace -value "NURBS" m_performBirail.kNurbs;
displayString -replace -value "Output geometry:" m_performBirail.kOutputGeometry;
displayString -replace -value "Polygons" m_performBirail.kPolygons;
displayString -replace -value "Profile" m_performBirail.kProfile;
displayString -replace -value "Profile blend value:" m_performBirail.kProfileBlendValue;
displayString -replace -value "Proportional" m_performBirail.kProportional;
displayString -replace -value "Rebuild:" m_performBirail.kRebuild;
displayString -replace -value "Second profile" m_performBirail.kSecondProfile;
displayString -replace -value "Second rail" m_performBirail.kSecondRail;
displayString -replace -value "Subdiv" m_performBirail.kSubdiv;
displayString -replace -value "Tool behavior:" m_performBirail.kToolBehavior;
displayString -replace -value "Transform control:" m_performBirail.kTransformControl;
