// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Smooth" m_performSmoothSkinWeights.kSmooth;
displayString -replace -value "Smoothing Iterations:" m_performSmoothSkinWeights.kSmoothIterations;
displayString -replace -value "Controls the maximum number of iterations the smoothing algorithm uses." m_performSmoothSkinWeights.kSmoothIterationsAnnotation;
displayString -replace -value "Obey Max Influences" m_performSmoothSkinWeights.kSmoothObeyMaxInfluences;
displayString -replace -value "Do not exceed max influences when smoothing" m_performSmoothSkinWeights.kSmoothObeyMaxInfluencesAnnotation;
displayString -replace -value "Preview" m_performSmoothSkinWeights.kSmoothPreview;
displayString -replace -value "Select vertices which will be smoothed" m_performSmoothSkinWeights.kSmoothPreviewAnnotation;
displayString -replace -value "Smooth Skin Weights Options" m_performSmoothSkinWeights.kSmoothSkinWeightsOptions;
displayString -replace -value "Required Weight Difference:" m_performSmoothSkinWeights.kSmoothTolerance;
displayString -replace -value "Specifies the required weight difference between components to be smoothed. The smaller the number the larger the set of components that will be smoothed." m_performSmoothSkinWeights.kSmoothToleranceAnnotation;
