// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Area tolerance:" m_performPolyCleanup.kAreaTol;
displayString -replace -value "Area tolerance:" m_performPolyCleanup.kAreaTol2;
displayString -replace -value "Cleanup" m_performPolyCleanup.kCleanupButton;
displayString -replace -value "Cleanup Options" m_performPolyCleanup.kCleanupOptions;
displayString -replace -value "Concave faces" m_performPolyCleanup.kConcaveFaces;
displayString -replace -value "Keep construction history" m_performPolyCleanup.kConstructHist;
displayString -replace -value "Edges with zero length" m_performPolyCleanup.kEdgesZeroLength;
displayString -replace -value "Faces with holes" m_performPolyCleanup.kFacesWithHoles;
displayString -replace -value "Faces with zero geometry area" m_performPolyCleanup.kFacesZeroGeomArea;
displayString -replace -value "Faces with zero map area" m_performPolyCleanup.kFacesZeroMapArea;
displayString -replace -value "4-sided faces" m_performPolyCleanup.kFourSidedFaces;
displayString -replace -value "Cleanup Effect" m_performPolyCleanup.kGeneralFrame;
displayString -replace -value "Geometry only" m_performPolyCleanup.kGeomOnly;
displayString -replace -value "Lamina faces (faces sharing all edges)" m_performPolyCleanup.kLaminaFaces;
displayString -replace -value "Length tolerance:" m_performPolyCleanup.kLengthTol;
displayString -replace -value "Faces with more than 4 sides" m_performPolyCleanup.kMoreFaces;
displayString -replace -value "Nonmanifold geometry" m_performPolyCleanup.kNomanifold;
displayString -replace -value "Non-planar faces" m_performPolyCleanup.kNonPlanarFaces;
displayString -replace -value "Normals and geometry" m_performPolyCleanup.kNormalsAndGeom;
displayString -replace -value "Operation:" m_performPolyCleanup.kOperation;
displayString -replace -value "Cleanup matching polygons" m_performPolyCleanup.kOperation1;
displayString -replace -value "Select matching polygons" m_performPolyCleanup.kOperation2;
displayString -replace -value "Remove Geometry" m_performPolyCleanup.kRemoveGeomFrame;
displayString -replace -value "Scope:" m_performPolyCleanup.kScope;
displayString -replace -value "Apply to selected objects" m_performPolyCleanup.kScope1;
displayString -replace -value "Apply to all polygonal objects" m_performPolyCleanup.kScope2;
displayString -replace -value "Fix by Tesselation" m_performPolyCleanup.kTesselationFrame;
