// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Auto completion" m_performIntersect.kAuto;
displayString -replace -value "Both surfaces" m_performIntersect.kBothSurfaces;
displayString -replace -value "Create curves for:" m_performIntersect.kCreateCurves;
displayString -replace -value "Curve on surface" m_performIntersect.kCurveOnSurface;
displayString -replace -value "Curve type:" m_performIntersect.kCurveType;
displayString -replace -value "Exit on completion" m_performIntersect.kExit;
displayString -replace -value "First surface" m_performIntersect.kFirstSurface;
displayString -replace -value "Global" m_performIntersect.kGlobal;
displayString -replace -value "Intersect" m_performIntersect.kIntersect;
displayString -replace -value "Intersect Tool" m_performIntersect.kIntersectTool;
displayString -replace -value "Local" m_performIntersect.kLocal;
displayString -replace -value "Intersect Surfaces Options" m_performIntersect.kSurfacesTitle;
displayString -replace -value "Intersect Surfaces Tool Options" m_performIntersect.kSurfacesToolTitle;
displayString -replace -value "Tolerance:" m_performIntersect.kTolerance;
displayString -replace -value "Tool behavior:" m_performIntersect.kToolBehavior;
displayString -replace -value "Use tolerance:" m_performIntersect.kUseTolerance;
displayString -replace -value "3D world" m_performIntersect.kWorld;
