// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Cone" m_performSubdPrimitive.kCone;
displayString -replace -value "Create" m_performSubdPrimitive.kCreate;
displayString -replace -value "Cube" m_performSubdPrimitive.kCube;
displayString -replace -value "Cylinder" m_performSubdPrimitive.kCylinder;
displayString -replace -value "NURBS" m_performSubdPrimitive.kNurbs;
displayString -replace -value "  Command: subdPrimitive - create a subd primitive with history.\n" m_performSubdPrimitive.kNurbsSquareHelp;
displayString -replace -value "Plane" m_performSubdPrimitive.kPlane;
displayString -replace -value "Polygon" m_performSubdPrimitive.kPolygon;
displayString -replace -value "Primitive: " m_performSubdPrimitive.kPrimitive;
displayString -replace -value "Primitive Style: " m_performSubdPrimitive.kPrimitiveStyle;
displayString -replace -value "Sphere" m_performSubdPrimitive.kSphere;
displayString -replace -value "Subdiv Primitive with History Options" m_performSubdPrimitive.kSubdivPrimitiveWithHistoryOptions;
displayString -replace -value "Torus" m_performSubdPrimitive.kTorus;
