// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Add color" m_performApplyColor.kAddColor;
displayString -replace -value "All channels" m_performApplyColor.kAllChannels;
displayString -replace -value "Alpha:" m_performApplyColor.kAlpha;
displayString -replace -value "Alpha:" m_performApplyColor.kAlphaIndiv;
displayString -replace -value "Apply Color" m_performApplyColor.kApplyColorButton;
displayString -replace -value "Apply Color Options" m_performApplyColor.kApplyColorOptions;
displayString -replace -value "Blue:" m_performApplyColor.kBlue;
displayString -replace -value "Color:" m_performApplyColor.kColor;
displayString -replace -value "Color Channel Values" m_performApplyColor.kColorChannelValuesFrame;
displayString -replace -value "Color Value" m_performApplyColor.kColorValueFrame;
displayString -replace -value "Color with alpha:" m_performApplyColor.kColorWithAlpha;
displayString -replace -value "Effect:" m_performApplyColor.kEffect;
displayString -replace -value "Grab color:" m_performApplyColor.kGrabColor;
displayString -replace -value "Green:" m_performApplyColor.kGreen;
displayString -replace -value "Individual channels" m_performApplyColor.kIndividualChannels;
displayString -replace -value "No color channels set to apply. No command to execute" m_performApplyColor.kNoColorChannels;
displayString -replace -value "Operation:" m_performApplyColor.kOperation;
displayString -replace -value "Red:" m_performApplyColor.kRed;
displayString -replace -value "Remove color" m_performApplyColor.kRemoveColor;
displayString -replace -value "Replace color" m_performApplyColor.kReplaceColor;
displayString -replace -value "Selected Vertex Color" m_performApplyColor.kSelectedVertexColor;
displayString -replace -value "Set alpha" m_performApplyColor.kSetAlpha;
displayString -replace -value "Set blue" m_performApplyColor.kSetBlue;
displayString -replace -value "Set green" m_performApplyColor.kSetGreen;
displayString -replace -value "Set red" m_performApplyColor.kSetRed;
displayString -replace -value "Settings" m_performApplyColor.kSettingsFrame;
displayString -replace -value "Subtract color" m_performApplyColor.kSubtractColor;
