// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Advanced" m_performTwist.kAdvanced;
displayString -replace -value "After" m_performTwist.kAfter;
displayString -replace -value "Basic" m_performTwist.kBasic;
displayString -replace -value "Before" m_performTwist.kBefore;
displayString -replace -value "Create" m_performTwist.kCreate;
displayString -replace -value "Create new partition" m_performTwist.kCreateNewPartition;
displayString -replace -value "Create Twist Deformer Options" m_performTwist.kCreateTwistDeformerOptions;
displayString -replace -value "Default" m_performTwist.kDefault;
displayString -replace -value "Deformation order:" m_performTwist.kDeformationOrder;
displayString -replace -value "End angle:" m_performTwist.kEndAngle;
displayString -replace -value "Exclusive" m_performTwist.kExclusive;
displayString -replace -value "High bound:" m_performTwist.kHighBound;
displayString -replace -value "Low bound:" m_performTwist.kLowBound;
displayString -replace -value "New partition name:" m_performTwist.kNewPartitionName;
displayString -replace -value "Parallel" m_performTwist.kParallel;
displayString -replace -value "Partition to use:" m_performTwist.kPartitiontoUse;
displayString -replace -value "Split" m_performTwist.kSplit;
displayString -replace -value "Start angle:" m_performTwist.kStartAngle;
