// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Apply" m_performComposite.kApply;
displayString -replace -value "Auto load range in image viewer" m_performComposite.kAutoLoadRangeInImageViewer;
displayString -replace -value "bmp" m_performComposite.kBmp;
displayString -replace -value "By frame:" m_performComposite.kByFrame;
displayString -replace -value "cin" m_performComposite.kCin;
displayString -replace -value "End frame:" m_performComposite.kEndFrame;
displayString -replace -value "eps" m_performComposite.kEps;
displayString -replace -value "File format:" m_performComposite.kFileFmt;
displayString -replace -value "gif" m_performComposite.kGif;
displayString -replace -value "iff" m_performComposite.kIff;
displayString -replace -value "Image" m_performComposite.kImage;
displayString -replace -value "Image name:" m_performComposite.kImageName;
displayString -replace -value "jpg" m_performComposite.kJpg;
displayString -replace -value "Padding:" m_performComposite.kPadding;
displayString -replace -value "pix" m_performComposite.kPix;
displayString -replace -value "Range" m_performComposite.kRange;
displayString -replace -value "Render Texture Range" m_performComposite.kRenderTextureRange;
displayString -replace -value "Render Texture Range Options" m_performComposite.kRenderTextureRangeOptions;
displayString -replace -value "rla" m_performComposite.kRla;
displayString -replace -value "sgi" m_performComposite.kSgi;
displayString -replace -value "si" m_performComposite.kSi;
displayString -replace -value "Start frame:" m_performComposite.kStartFrame;
displayString -replace -value "tga" m_performComposite.kTga;
displayString -replace -value "tif" m_performComposite.kTif;
displayString -replace -value "X resolution:" m_performComposite.kXResolution;
displayString -replace -value "Y resolution:" m_performComposite.kYResolution;
displayString -replace -value "yuv" m_performComposite.kYuv;
