// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Active" m_performDisplaySmoothnessCustom.kActive;
displayString -replace -value "All" m_performDisplaySmoothnessCustom.kAll;
displayString -replace -value "Curve div per span:" m_performDisplaySmoothnessCustom.kCurveDivPerSpan;
displayString -replace -value "Display render tessellation geometry" m_performDisplaySmoothnessCustom.kDisplayRenderTessellation;
displayString -replace -value "Full" m_performDisplaySmoothnessCustom.kFull;
displayString -replace -value "Geometry:" m_performDisplaySmoothnessCustom.kGeometry;
displayString -replace -value "Hull" m_performDisplaySmoothnessCustom.kHull;
displayString -replace -value "Hull" m_performDisplaySmoothnessCustom.kHullLayout;
displayString -replace -value "Hull simplification U:" m_performDisplaySmoothnessCustom.kHullSimplificationU;
displayString -replace -value "Hull simplification V:" m_performDisplaySmoothnessCustom.kHullSimplificationV;
displayString -replace -value "NURBS Smoothness (Custom) Options" m_performDisplaySmoothnessCustom.kNURBSSmoothnessCustomOptions;
displayString -replace -value "Objects affected:" m_performDisplaySmoothnessCustom.kObjectsAffected;
displayString -replace -value "Shaded" m_performDisplaySmoothnessCustom.kShaded;
displayString -replace -value "Surface div per span:" m_performDisplaySmoothnessCustom.kSurfaceDivPerSpan;
displayString -replace -value "Surface div per span U:" m_performDisplaySmoothnessCustom.kSurfaceDivSpanU;
displayString -replace -value "Surface div per span V:" m_performDisplaySmoothnessCustom.kSurfaceDivSpanV;
displayString -replace -value "Wireframe" m_performDisplaySmoothnessCustom.kWireframe;
