// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Camera Properties" m_performCamera.kCameraProperties;
displayString -replace -value "Camera scale:" m_performCamera.kCameraScale;
displayString -replace -value "Center of interest:" m_performCamera.kCenterOfInterest;
displayString -replace -value "Clipping Planes" m_performCamera.kClippingPlanes;
displayString -replace -value "Create" m_performCamera.kCreate;
displayString -replace -value "Create Camera, Aim, and Up Options" m_performCamera.kCreateCameraAimandUpOptions;
displayString -replace -value "Create Camera Options" m_performCamera.kCreateCameraOptions;
displayString -replace -value "Create Camera and Aim Options" m_performCamera.kCreateCameraandAimOptions;
displayString -replace -value "Far clip plane:" m_performCamera.kFarClipPlane;
displayString -replace -value "Fill" m_performCamera.kFill;
displayString -replace -value "Film Back Properties" m_performCamera.kFilmBackProperties;
displayString -replace -value "Film fit:" m_performCamera.kFilmFit;
displayString -replace -value "Film fit offset:" m_performCamera.kFilmFitOffset;
displayString -replace -value "Focal length:" m_performCamera.kFocalLength;
displayString -replace -value "Horizontal" m_performCamera.kHorizontal;
displayString -replace -value "Horizontal film aperture:" m_performCamera.kHorizontalFilmAperture;
displayString -replace -value "Horizontal film offset:" m_performCamera.kHorizontalFilmOffset;
displayString -replace -value "Horizontal pan:" m_performCamera.kHorizontalPan;
displayString -replace -value "Lens Properties" m_performCamera.kLensProperties;
displayString -replace -value "Lens squeeze ratio:" m_performCamera.kLensSqueezeRatio;
displayString -replace -value "Motion Blur" m_performCamera.kMotionBlur;
displayString -replace -value "Near clip plane:" m_performCamera.kNearClipPlane;
displayString -replace -value "Orthographic" m_performCamera.kOrthographic;
displayString -replace -value "Orthographic Views" m_performCamera.kOrthographicViews;
displayString -replace -value "Orthographic width:" m_performCamera.kOrthographicWidth;
displayString -replace -value "Overscan" m_performCamera.kOverscan;
displayString -replace -value "Overscan:" m_performCamera.kOverscanLabel;
displayString -replace -value "2D Pan/Zoom" m_performCamera.kPanZoom;
displayString -replace -value "Pan/Zoom enabled" m_performCamera.kPanZoomEnabled;
displayString -replace -value "Shutter angle:" m_performCamera.kShutterAngle;
displayString -replace -value "Vertical" m_performCamera.kVertical;
displayString -replace -value "Vertical film aperture:" m_performCamera.kVerticalFilmAperture;
displayString -replace -value "Vertical film offset:" m_performCamera.kVerticalFilmOffset;
displayString -replace -value "Vertical pan:" m_performCamera.kVerticalPan;
displayString -replace -value "Zoom:" m_performCamera.kZoom;
