// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Delete nCache Frames Options" m_performDeleteFluidCacheFrames.kDeleteOptions;
displayString -replace -value "Current Time" m_performDeleteFluidCacheFrames.kFluidCurrentTime;
displayString -replace -value "Custom renaming of removed frames" m_performDeleteFluidCacheFrames.kFluidCustomRename;
displayString -replace -value "Default renaming of removed frames" m_performDeleteFluidCacheFrames.kFluidDefaultNaming;
displayString -replace -value "Delete" m_performDeleteFluidCacheFrames.kFluidDelete;
displayString -replace -value "Delete backup files" m_performDeleteFluidCacheFrames.kFluidDeleteBackups;
displayString -replace -value "End Delete Frame" m_performDeleteFluidCacheFrames.kFluidDeleteEnd;
displayString -replace -value "Start Delete Frame" m_performDeleteFluidCacheFrames.kFluidDeleteStart;
displayString -replace -value "Start/End" m_performDeleteFluidCacheFrames.kFluidStartEnd;
