// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  18 April 1997
//
//  Description:
//      pointLight default options box.  The content for each tab 
//		is not created until it is accessed for the first time.
//
//////////////////////////////////////////////////////////////////////
//
//  Procedure Name:
//      setOptionVars
//
//  Description:
//		Initialize the option values.
//
//  Input Arguments:
//		Whether to set the options to default values.
//
//  Return Value:
//      None.
//
proc setOptionVars(int $forceFactorySettings)
{
	//	Intensity.
	//
	if ($forceFactorySettings || !`optionVar -exists pointLightIntensity`) {
		optionVar -floatValue pointLightIntensity 1;
	}

	//	Color.
	//
	if ($forceFactorySettings || !`optionVar -exists pointLightColor`) {
		optionVar -floatValue pointLightColor 1
			-floatValueAppend pointLightColor 1
			-floatValueAppend pointLightColor 1;
	}

	//	Decay Rate.
	//
	if ($forceFactorySettings || !`optionVar -exists pointLightDecay`) {
		optionVar -intValue pointLightDecay 0;
	}

	//	Shadows.
	//
	if ($forceFactorySettings || !`optionVar -exists pointLightShadows`) {
		optionVar -intValue pointLightShadows false;
	}

	//	Shadow Color.
	//
	if ($forceFactorySettings || !`optionVar -exists pointLightShadowColor`) {
		optionVar -floatValue pointLightShadowColor 0
			-floatValueAppend pointLightShadowColor 0
			-floatValueAppend pointLightShadowColor 0;
	}
}

//
//  Procedure Name:
//      pointLightSetup
//
//  Description:
//		Update the state of the option box UI to reflect the option values.
//
//  Input Arguments:
//      parent               - Top level parent layout of the option box UI.
//                             Required so that UI object names can be 
//                             successfully resolved.
//
//		forceFactorySettings - Whether the option values should be set to
//                             default values.
//
//  Return Value:
//      None.
//
global proc pointLightSetup(string $parent, int $forceFactorySettings)
{
	//	Retrieve the option settings
	//
	setOptionVars($forceFactorySettings);

	setParent $parent;
	float $rgb[3];
	
	//	Query the optionVar's and set the values into the controls.

	//	Intensity.
	//
	if (`floatSliderGrp -exists pointLightIntensity`) {
		floatSliderGrp -edit 
			-value `optionVar -query pointLightIntensity`
			pointLightIntensity;
	}

	//	Color.
	//
	if (`colorSliderGrp -exists pointLightColor`) {
		float $rgb[3] = `optionVar -query pointLightColor`;
		colorSliderGrp -edit 
			-rgb $rgb[0] $rgb[1] $rgb[2]
			pointLightColor;
	}
	
	//	Decay Rate.
	//
	if (`optionMenuGrp -exists pointLightDecay`) {
		optionMenuGrp -edit -sl (1+`optionVar -query pointLightDecay`)
			pointLightDecay;
	}

	//	Shadows.
	//
	if (`checkBoxGrp -exists pointLightShadows`) {
		checkBoxGrp -edit
			-value1 `optionVar -query pointLightShadows` 
			pointLightShadows;
	}

	//	Shadow Color.
	//
	if (`colorSliderGrp -exists pointLightShadowColor`) {
		$rgb = `optionVar -query pointLightShadowColor`;
		colorSliderGrp -edit 
			-rgb $rgb[0] $rgb[1] $rgb[2]
			pointLightShadowColor;
	}
}

//
//  Procedure Name:
//      pointLightCallback
//
//  Description:
//		Update the option values with the current state of the option box UI.
//
//  Input Arguments:
//      parent - Top level parent layout of the option box UI.  Required so
//               that UI object names can be successfully resolved.
//
//		doIt   - Whether the command should execute.
//
//  Return Value:
//      None.
//
global proc pointLightCallback(string $parent, int $doIt)
{
    setParent $parent;
	float $rgb[3];
	
	//	Set the optionVar's from the control values, and then
	//	perform the command.

	//	Intensity.
	//
	if (`floatSliderGrp -exists pointLightIntensity`) {
		optionVar -floatValue pointLightIntensity		
			`floatSliderGrp -query -value pointLightIntensity`;
	}

	//	Color.
	//
	if (`colorSliderGrp -exists pointLightColor`) {
		$rgb = `colorSliderGrp -query -rgb pointLightColor`;
		optionVar -floatValue pointLightColor $rgb[0];
		optionVar -floatValueAppend pointLightColor $rgb[1];
		optionVar -floatValueAppend pointLightColor $rgb[2];
	}

	//	Decay Rate.
	//
	if (`optionMenuGrp -exists pointLightDecay`) {
		optionVar -intValue pointLightDecay
			(`optionMenuGrp -query -sl pointLightDecay`-1);
	}

	//	Shadow.
	//
	if (`checkBoxGrp -exists pointLightShadows`) {
		optionVar -intValue pointLightShadows
			`checkBoxGrp -query -value1 pointLightShadows`;
	}

	//	Shadow Color.
	//
	if (`colorSliderGrp -exists pointLightShadowColor`) {
		$rgb = `colorSliderGrp -query -rgb pointLightShadowColor`;
		optionVar -floatValue pointLightShadowColor $rgb[0];
		optionVar -floatValueAppend pointLightShadowColor $rgb[1];
		optionVar -floatValueAppend pointLightShadowColor $rgb[2];
	}

	if ($doIt) {
		performPointLight 0; 
		addToRecentCommandQueue "performPointLight 0" "PointLight";
	}
}

//
//  Procedure Name:
//      createPointLightTabUI
//
//  Description:
//		Create the tab UI.  The contents of each tab are created only 
//		when it is required, ie. if the tab is initially visible or 
//		if the tab is selected by the user.
//
//  Input Arguments:
//      The name of the tab layout.
//
//  Return Value:
//      None.
//
global proc createPointLightTabUI(string $tabLayout)
{
	string $tab[] = `tabLayout -query -childArray $tabLayout`;
	int $currentTabIndex = `tabLayout -query -selectTabIndex $tabLayout`;

	//	Determine if the UI for this tab has been created yet.
	//	This is accomplished by querying the number of children
	//	in the current tab.  If the tab has no children then the UI
	//	must be created.
	//
	if (0 == `columnLayout -query -numberOfChildren $tab[$currentTabIndex-1]`) {

		setParent $tab[$currentTabIndex-1];

		string $label;
		int $index;

		//	Activate the default UI template so that the layout of this 
		//	option box is consistent with the layout of the rest of the 
		//	application.
		//
		setUITemplate -pushTemplate DefaultTemplate;

		//	Turn on the wait cursor.
		//
		waitCursor -state 1;

		//	The current tab has no children.  Determine which tab is
		//	active and create its UI.
		//
		//	RECOMMENDATION:  Use the 'Grp' commands where possible because
		//	they obey the formatting specified in the default template.
		//	This will result in a more consistent look throughout the
		//	application.
		//	
		if (1 == $currentTabIndex) {
			
    		//	Create UI for the first tab.
    		//
    		floatSliderGrp -label (uiRes("m_performPointLight.kIntensity"))  -fieldMaxValue 100
    			pointLightIntensity;
	    
    		colorSliderGrp -label (uiRes("m_performPointLight.kColor")) 
    			pointLightColor;

   			//	Create UI for the second tab.
   			//
			optionMenuGrp -label (uiRes("m_performPointLight.kDecayRate"))  pointLightDecay;
			menuItem -label (uiRes("m_performPointLight.kNone")) ;
			menuItem -label (uiRes("m_performPointLight.kLinear")) ;
			menuItem -label (uiRes("m_performPointLight.kQuadratic")) ;
			menuItem -label (uiRes("m_performPointLight.kCubic")) ;
			setParent -menu ..;

			separator;

   			//	Create UI for the third tab.
   			//
  			checkBoxGrp -ncb 1 -label1 (uiRes("m_performPointLight.kCastShadows")) 
				pointLightShadows;
    
			colorSliderGrp -label (uiRes("m_performPointLight.kShadowColor")) 
				pointLightShadowColor;

			setParent ..;
		}

		//	Update the control values to match the options.
		//
		eval (("pointLightSetup " + $tabLayout + " " + 0));	
	
		//	Turn off the wait cursor.
		//
		waitCursor -state 0;
		
		//	Deactivate the default UI template.
		//
		setUITemplate -popTemplate;
	}
}

//
//  Procedure Name:
//      pointLightOptions
//
//  Description:
//		Construct the option box UI.  Involves accessing the standard option
//		box and customizing the UI accordingly.
//
//  Input Arguments:
//      None.
//
//  Return Value:
//      None.
//
// ********* Change 'pointLight' in this proc to be the name of your command
proc pointLightOptions()
{
	//	Name of the command for this option box.
	//
	string $commandName = "pointLight";

	//	Build the option box actions.
	//
	string $callback = ($commandName + "Callback");
	string $setup = ($commandName + "Setup");

	//	STEP 1:  Get the option box.
	//	============================
	//
	//  The value returned is the name of the layout to be used as
	//	the parent for the option box UI.
	//
	string $layout = getOptionBox();
	setParent $layout;
	
	//	STEP 2:  Pass the command name to the option box.
	//	=================================================
	//
	//	Any default option box behaviour based on the command name is set 
	//	up with this call.  For example, updating the 'Help' menu item with
	//	the name of the command.
	//
	setOptionBoxCommandName($commandName);

	//	STEP 3:  Activate the default UI template.
	//	==========================================
	//
	//	Activate the default UI template so that the layout of this 
	//	option box is consistent with the layout of the rest of the 
	//	application.
	//
	//	Note: this option box example delays the creation of the UI
	//	until it's required.  Therefore this step is moved to the
	//	procedure where the UI is actually created. 
	//
	//setUITemplate -pushTemplate DefaultTemplate;

	//	STEP 4: Create option box contents.
	//	===================================
	//	
	//	This, of course, will vary from option box to option box.	
	
	//	Demonstrate the delaying of UI creation via tab layouts.
	//	Instead of creating all of the option box UI initially, only
	//	create that which is initially visible.  Wait, until the 
	//	other tabs are selected to create the remaining UI.
	//
	string $tabLayout = `tabLayout -scrollable 1`;

	//	Attach an action that will be invoked before a tab is selected.
	//	
	tabLayout -edit 
		-tabsVisible false
		-preSelectCommand ("createPointLightTabUI " + $tabLayout)
		$tabLayout;

	//	Create just the immediate children of the tab layout so that
	//	the tabs appear.
	//
	columnLayout -adj true;
		setParent ..;
	
	//	Set the tab labels.
	//
	tabLayout -edit
		$tabLayout;

	//	Create the UI for the tab that is initially visible.
	//
	createPointLightTabUI($tabLayout);

	//	Step 5: Deactivate the default UI template.
	//  ===========================================
	//
	//	Note: this option box example delays the creation of the UI
	//	until it's required.  Therefore this step is moved to the
	//	procedure where the UI is actually created.
	//
	//	See also Step 2. 
	//
	//setUITemplate -popTemplate;

	//	Step 6: Customize the buttons.  
	//	==============================
	//
	//	Provide more descriptive labels for the buttons.  This is not 
	//	necessary, but in some cases, for example, a button labelled 
	//	'Create' may be more meaningful to the user than one labelled
	//	'Apply'.
	//
	//  Disable those buttons that are not applicable to the option box.
	//
	//	Attach actions to those buttons that are applicable to the option
	//	box.  Note that the 'Close' button has a default action attached 
	//	to it that will hide the window.  If a a custom action is
	//	attached to the 'Close' button then be sure to call the 'hide the
	//	option box' procedure within the custom action so that the option
	//	box is hidden properly.

	//	'Apply' button.
	//
	string $applyBtn = getOptionBoxApplyBtn();
	button -edit
		-label (uiRes("m_performPointLight.kCreate")) 
		-command ($callback + " " + $tabLayout + " " + 1)
		$applyBtn;

	//	'Save' button.
	//
	string $saveBtn = getOptionBoxSaveBtn();
	button -edit 
		-command ($callback + " " + $tabLayout + " " + 0 + "; hideOptionBox")
		$saveBtn;

	//	'Reset' button.
	//
	string $resetBtn = getOptionBoxResetBtn();
	button -edit 
		-command ($setup + " " + $tabLayout + " " + 1)
		$resetBtn;

	//	Step 7: Set the option box title.
	//	=================================
	//
	setOptionBoxTitle (uiRes("m_performPointLight.kCreatePointLightOptions"));

	//	Step 8: Customize the 'Help' menu item text.
	//	============================================
	//
	setOptionBoxHelpTag( "PointLight" );

	//	Step 9: Set the current values of the option box.
	//	=================================================
	//
	//	NOTE:  Can not do this here since we do not know what UI is
	//	currently visible.  This is moved to where the UI is created.
	//
	//eval (($setup + " " + $tabLayout + " " + 0));	
	
	//	Step 10: Show the option box.
	//	=============================
	//
	showOptionBox();
}

//
//  Procedure Name:
//      optionBoxExample1Help
//
//  Description:
//		Return a short description about this command.
//
//  Input Arguments:
//      None.
//
//  Return Value:
//      string.
//
proc string pointLightHelp()
{
	return 
	"  Command: pointLight - creates a pointLight\n" +
	"Selection: None.";	
}

proc string getCmd()
{
	string $cmd = "defaultPointLight(";

	$cmd = $cmd + `optionVar -query pointLightIntensity`;
	float $rgb[3] = `optionVar -query pointLightColor`;
	$cmd = $cmd + ", " + $rgb[0] + "," + $rgb[1] + "," + $rgb[2];
	$cmd = $cmd + ", " + `optionVar -query pointLightDecay`;
	$cmd = $cmd + ", " + `optionVar -query pointLightShadows`;
	$rgb = `optionVar -query pointLightShadowColor`;
	$cmd = $cmd + ", " + $rgb[0] + "," + $rgb[1] + "," + $rgb[2];
	$cmd = $cmd + ", 1";
	$cmd = $cmd + ");";

	return $cmd;
}

//
//  Procedure Name:
//      performPointLight
//
//  Description:
//		Perform the pointLight command using the corresponding 
//		option values.  This procedure will also show the option box
//		window if necessary as well as construct the command string
//		that will invoke the pointLight command with the current
//		option box values.
//
//  Input Arguments:
//      0 - Execute the command.
//      1 - Show the option box dialog.
//      2 - Return the command.
//
//  Return Value:
//      None.
//
global proc string performPointLight(int $action)
{
	string $cmd = "";

	switch ($action) {

		//	Execute the command.
		//
		case 0:
			//	Retrieve the option settings
			//
			setOptionVars(false);

			//	Get the command.
			//
			$cmd = getCmd();

			//	Execute the command with the option settings.
			//
			evalEcho($cmd);

			break;

		//	Show the option box.
		//
		case 1:
			pointLightOptions;
			break;

		//	Return the command string.
		//
		case 2:
			//	Retrieve the option settings.
			//
			setOptionVars (false);

			//	Get the command.
			//
			$cmd = getCmd();
			break;
	}
	return $cmd;
}

