// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Along U" m_performPolyAutoProj.kAlongU;
displayString -replace -value "Polygon Automatic Mapping Options" m_performPolyAutoProj.kAutomaticMappingOptions;
displayString -replace -value "Bounding box" m_performPolyAutoProj.kBoundingBox;
displayString -replace -value "Could not create a new set to hold the faces." m_performPolyAutoProj.kCreateNewSetWarn;
displayString -replace -value "Create new UV set" m_performPolyAutoProj.kCreateNewUVSet;
displayString -replace -value " Custom" m_performPolyAutoProj.kCustom;
displayString -replace -value "Could not create the default polygons shader" m_performPolyAutoProj.kDefaultPolygonsShaderWarn;
displayString -replace -value "8" m_performPolyAutoProj.kEight;
displayString -replace -value "Fewer pieces" m_performPolyAutoProj.kFewerPieces;
displayString -replace -value "5" m_performPolyAutoProj.kFive;
displayString -replace -value "4" m_performPolyAutoProj.kFour;
displayString -replace -value "Insert projection before deformers" m_performPolyAutoProj.kInsertBeforeDeformers;
displayString -replace -value "Into square" m_performPolyAutoProj.kIntoSquare;
displayString -replace -value "Shell layout:" m_performPolyAutoProj.kLayout;
displayString -replace -value "Layout" m_performPolyAutoProj.kLayoutFrame;
displayString -replace -value "Less distortion" m_performPolyAutoProj.kLessDistortion;
displayString -replace -value "Load projection" m_performPolyAutoProj.kLoadProjection;
displayString -replace -value "Load Selected" m_performPolyAutoProj.kLoadSelected;
displayString -replace -value "1024 Map" m_performPolyAutoProj.kMap1024;
displayString -replace -value " 128 Map" m_performPolyAutoProj.kMap128;
displayString -replace -value " 256 Map" m_performPolyAutoProj.kMap256;
displayString -replace -value "  32 Map" m_performPolyAutoProj.kMap32;
displayString -replace -value " 512 Map" m_performPolyAutoProj.kMap512;
displayString -replace -value "  64 Map" m_performPolyAutoProj.kMap64;
displayString -replace -value "Mapping Settings" m_performPolyAutoProj.kMappingFrame;
displayString -replace -value "None" m_performPolyAutoProj.kNone;
displayString -replace -value "Optimize for:" m_performPolyAutoProj.kOptimize;
displayString -replace -value "Overlap" m_performPolyAutoProj.kOverlap;
displayString -replace -value "Planes:" m_performPolyAutoProj.kPalnes;
displayString -replace -value "Percentage space:" m_performPolyAutoProj.kPercentageSpace;
displayString -replace -value "Project" m_performPolyAutoProj.kProject;
displayString -replace -value "Project both directions" m_performPolyAutoProj.kProjectBothDirections;
displayString -replace -value "Projection" m_performPolyAutoProj.kProjectionFrame;
displayString -replace -value "Projection object: " m_performPolyAutoProj.kProjectionObject;
displayString -replace -value "Scale mode:" m_performPolyAutoProj.kScaleMode;
displayString -replace -value "Shape" m_performPolyAutoProj.kShape;
displayString -replace -value "Shell Spacing" m_performPolyAutoProj.kShellSpacingFrame;
displayString -replace -value "Shell stacking:" m_performPolyAutoProj.kShellStacking;
displayString -replace -value "6" m_performPolyAutoProj.kSix;
displayString -replace -value "Spacing presets:" m_performPolyAutoProj.kSpacingPresets;
displayString -replace -value "Stretch to square" m_performPolyAutoProj.kStretchToSquare;
displayString -replace -value "3" m_performPolyAutoProj.kThree;
displayString -replace -value "Tile" m_performPolyAutoProj.kTile;
displayString -replace -value "12" m_performPolyAutoProj.kTwelve;
displayString -replace -value "UV Set" m_performPolyAutoProj.kUVSetFrame;
displayString -replace -value "UV set name: " m_performPolyAutoProj.kUVSetName;
displayString -replace -value "Uniform" m_performPolyAutoProj.kUniform;
