// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Active view" m_performNurbsCube.kActiveView;
displayString -replace -value "Axis:" m_performNurbsCube.kAxis;
displayString -replace -value "Axis definition:" m_performNurbsCube.kAxisDefinition;
displayString -replace -value "Create" m_performNurbsCube.kCreateButton;
displayString -replace -value "Free" m_performNurbsCube.kFree;
displayString -replace -value "Height:" m_performNurbsCube.kHeight;
displayString -replace -value "Length:" m_performNurbsCube.kLength;
displayString -replace -value "NURBS Cube Options" m_performNurbsCube.kNURBSCubeOptions;
displayString -replace -value "Object" m_performNurbsCube.kObject;
displayString -replace -value "1 Linear" m_performNurbsCube.kOption1Linear;
displayString -replace -value "2" m_performNurbsCube.kOption2;
displayString -replace -value "3 Cubic" m_performNurbsCube.kOption3Cubic;
displayString -replace -value "5" m_performNurbsCube.kOption5;
displayString -replace -value "7" m_performNurbsCube.kOption7;
displayString -replace -value "Pivot:" m_performNurbsCube.kPivot;
displayString -replace -value "Pivot point:" m_performNurbsCube.kPivotPoint;
displayString -replace -value "Surface degree:" m_performNurbsCube.kSurfaceDegree;
displayString -replace -value "U patches:" m_performNurbsCube.kUPatches;
displayString -replace -value "User defined" m_performNurbsCube.kUserDefined;
displayString -replace -value "V patches:" m_performNurbsCube.kVPatches;
displayString -replace -value "Width:" m_performNurbsCube.kWidth;
displayString -replace -value "X" m_performNurbsCube.kX;
displayString -replace -value "Y" m_performNurbsCube.kY;
displayString -replace -value "Z" m_performNurbsCube.kZ;
