// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Transfer" m_performTransferShadingSets.kApplyandClose;
displayString -replace -value "Attribute Settings" m_performTransferShadingSets.kAttributeSettingsFrame;
displayString -replace -value "Apply" m_performTransferShadingSets.kBake;
displayString -replace -value "Closest along normal" m_performTransferShadingSets.kClosestAlongNormal;
displayString -replace -value "Closest to point" m_performTransferShadingSets.kClosestToPoint;
displayString -replace -value "Please select at least one surface" m_performTransferShadingSets.kErrorSelectAtLeastOneSurface;
displayString -replace -value "Local" m_performTransferShadingSets.kObjectSpace;
displayString -replace -value "Sample space:" m_performTransferShadingSets.kSampleSpace;
displayString -replace -value "Search method:" m_performTransferShadingSets.kSearchMethod;
displayString -replace -value "Transfer Shading Sets Options" m_performTransferShadingSets.kTransferShadingSetsOptions;
displayString -replace -value "World" m_performTransferShadingSets.kWorldSpace;
