// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Attach" m_performAttachSrf.kAttach;
displayString -replace -value "Attach method:" m_performAttachSrf.kAttachMethod;
displayString -replace -value "Attach Tool" m_performAttachSrf.kAttachTool;
displayString -replace -value "Auto completion" m_performAttachSrf.kAuto;
displayString -replace -value "Blend" m_performAttachSrf.kBlend;
displayString -replace -value "Blend bias:" m_performAttachSrf.kBlendBias;
displayString -replace -value "Connect" m_performAttachSrf.kConnect;
displayString -replace -value "Exit on completion" m_performAttachSrf.kExit;
displayString -replace -value "Insert knot" m_performAttachSrf.kInsertKnot;
displayString -replace -value "Insert parameter:" m_performAttachSrf.kInsertParameter;
displayString -replace -value "Keep" m_performAttachSrf.kKeep;
displayString -replace -value "Keep originals" m_performAttachSrf.kKeepOriginals;
displayString -replace -value "Multiple knots:" m_performAttachSrf.kMultipleKnots;
displayString -replace -value "Remove" m_performAttachSrf.kRemove;
displayString -replace -value "Attach Surfaces Options" m_performAttachSrf.kSurfacesTitle;
displayString -replace -value "Attach Surfaces Tool Options" m_performAttachSrf.kSurfacesToolTitle;
displayString -replace -value "Tool behavior:" m_performAttachSrf.kToolBehavior;
