// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Average Normals" m_performPolyAverageNormal.kAverageNormalsButton;
displayString -replace -value "Average Normals Options" m_performPolyAverageNormal.kAverageNormalsOptions;
displayString -replace -value "Grouping threshold:" m_performPolyAverageNormal.kGroupingThreshold;
displayString -replace -value "Normal lengths:" m_performPolyAverageNormal.kNormalLengths;
displayString -replace -value "Normalize before averaging" m_performPolyAverageNormal.kNormalLengths1;
displayString -replace -value "Normalize after averaging" m_performPolyAverageNormal.kNormalLengths2;
displayString -replace -value "Do not normalize" m_performPolyAverageNormal.kNormalLengths3;
displayString -replace -value "Settings" m_performPolyAverageNormal.kSettingsFrame;
displayString -replace -value "Zero length handling:" m_performPolyAverageNormal.kZeroLengthHandle;
displayString -replace -value "Allow zero normals" m_performPolyAverageNormal.kZeroLengthHandle1;
displayString -replace -value "Replace zero normals by:" m_performPolyAverageNormal.kZeroLengthHandle2;
