// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Edges either side:" m_performSelContiguousEdges.kEdgesEitherSide;
displayString -replace -value "Limit number of edges selected" m_performSelContiguousEdges.kLimitNumberEdgesSelected;
displayString -replace -value "Maximum 2D angle:" m_performSelContiguousEdges.kMax2D;
displayString -replace -value "Maximum 3D angle:" m_performSelContiguousEdges.kMax3D;
displayString -replace -value "Select" m_performSelContiguousEdges.kSelectButton;
displayString -replace -value "Select Contiguous Edges Options" m_performSelContiguousEdges.kSelectContiguousEdgesOptions;
displayString -replace -value "Stopping Conditions" m_performSelContiguousEdges.kStoppingConditionsFrame;
