// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Edge weights:" m_performPolyOptimizeUV.kEdgeWeights;
displayString -replace -value "Iterations:" m_performPolyOptimizeUV.kIterations;
displayString -replace -value "Legacy (relax)" m_performPolyOptimizeUV.kLegacyLabel;
displayString -replace -value "Map size (Pixels):" m_performPolyOptimizeUV.kMapSize;
displayString -replace -value "Maximum iterations:" m_performPolyOptimizeUV.kMaxIterations;
displayString -replace -value "Method" m_performPolyOptimizeUV.kMethodLabel;
displayString -replace -value "Optimize Options" m_performPolyOptimizeUV.kOptimizeOptionsFrame;
displayString -replace -value "Optimize UVs Options" m_performPolyOptimizeUV.kOptimizeUVsOptions;
displayString -replace -value "Other Settings" m_performPolyOptimizeUV.kOtherSettingsFrame;
displayString -replace -value "Pack" m_performPolyOptimizeUV.kPack;
displayString -replace -value "Pin UV border" m_performPolyOptimizeUV.kPinUVBorder;
displayString -replace -value "Pin UVs:" m_performPolyOptimizeUV.kPinUVs;
displayString -replace -value "Pinning" m_performPolyOptimizeUV.kPinningFrame;
displayString -replace -value "Pin selected UVs" m_performPolyOptimizeUV.kPolyRelaxPinSel;
displayString -replace -value "Pin unselected UVs" m_performPolyOptimizeUV.kPolyRelaxPinUnsel;
displayString -replace -value "Uniform" m_performPolyOptimizeUV.kPolyRelaxUform;
displayString -replace -value "World space" m_performPolyOptimizeUV.kPolyRelaxWorldSpace;
displayString -replace -value "Power:" m_performPolyOptimizeUV.kPower;
displayString -replace -value "Prevent self border intersections" m_performPolyOptimizeUV.kPreventSI;
displayString -replace -value "Prevent triangle flips" m_performPolyOptimizeUV.kPreventTF;
displayString -replace -value "Room Space Options" m_performPolyOptimizeUV.kRoomSpace;
displayString -replace -value "Room space (Pixels):" m_performPolyOptimizeUV.kRoomSpaceSize;
displayString -replace -value "Surfangle:" m_performPolyOptimizeUV.kSurfangle;
displayString -replace -value "Unfold3D" m_performPolyOptimizeUV.kUnfoldLabel;
