// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Bind skins and flexors:" m_performanceSettingsWin.kBindSkinsAndFlexors;
displayString -replace -value "Blend shapes:" m_performanceSettingsWin.kBlendShapes;
displayString -replace -value "Close" m_performanceSettingsWin.kClose;
displayString -replace -value "Cluster resolution:" m_performanceSettingsWin.kClusterResolution;
displayString -replace -value "Clusters:" m_performanceSettingsWin.kClusters;
displayString -replace -value "Deformers" m_performanceSettingsWin.kDeformers;
displayString -replace -value "Demand" m_performanceSettingsWin.kDemand;
displayString -replace -value "Dependency Graph Evaluation" m_performanceSettingsWin.kDependencyGraphEvaluation;
displayString -replace -value "Drag" m_performanceSettingsWin.kDrag;
displayString -replace -value "Flexors:" m_performanceSettingsWin.kFlexors;
displayString -replace -value "Full" m_performanceSettingsWin.kFull;
displayString -replace -value "Global" m_performanceSettingsWin.kGlobal;
displayString -replace -value "Global cluster resolution:" m_performanceSettingsWin.kGlobalClusterResolution;
displayString -replace -value "Global lattice resolution:" m_performanceSettingsWin.kGlobalLatticeResolution;
displayString -replace -value "Help" m_performanceSettingsWin.kHelp;
displayString -replace -value "Help on Performance Settings" m_performanceSettingsWin.kHelpOnPerformanceSettings;
displayString -replace -value "High" m_performanceSettingsWin.kHigh;
displayString -replace -value "Interactive" m_performanceSettingsWin.kInteractive;
displayString -replace -value "Lattice resolution:" m_performanceSettingsWin.kLatticeResolution;
displayString -replace -value "Lattices:" m_performanceSettingsWin.kLattices;
displayString -replace -value "Low" m_performanceSettingsWin.kLow;
displayString -replace -value "Medium" m_performanceSettingsWin.kMedium;
displayString -replace -value "Off" m_performanceSettingsWin.kOff;
displayString -replace -value "On" m_performanceSettingsWin.kOn;
displayString -replace -value "Paint Effects:" m_performanceSettingsWin.kPaintEffects;
displayString -replace -value "Paint Effects" m_performanceSettingsWin.kPaintEffectsTitle;
displayString -replace -value "Per node" m_performanceSettingsWin.kPerNode;
displayString -replace -value "Performance" m_performanceSettingsWin.kPerformance;
displayString -replace -value "Performance Settings" m_performanceSettingsWin.kPerformanceSettings;
displayString -replace -value "Refresh on:" m_performanceSettingsWin.kRefreshOn;
displayString -replace -value "Release" m_performanceSettingsWin.kRelease;
displayString -replace -value "Sculpts:" m_performanceSettingsWin.kSculpts;
displayString -replace -value "Stitch surfaces:" m_performanceSettingsWin.kStitchSurfaces;
displayString -replace -value "Surfaces" m_performanceSettingsWin.kSurfaces;
displayString -replace -value "Trim display:" m_performanceSettingsWin.kTrimDisplay;
displayString -replace -value "Wires:" m_performanceSettingsWin.kWires;
