// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Attach" m_performPathAnimation.kAttach;
displayString -replace -value "Bank" m_performPathAnimation.kBank;
displayString -replace -value "Bank limit:" m_performPathAnimation.kBankLimit;
displayString -replace -value "Bank scale:" m_performPathAnimation.kBankScale;
displayString -replace -value "End time:" m_performPathAnimation.kEndTime;
displayString -replace -value "Follow:" m_performPathAnimation.kFollow;
displayString -replace -value "Front axis:" m_performPathAnimation.kFrontAxis;
displayString -replace -value "Inverse front" m_performPathAnimation.kInverseFront;
displayString -replace -value "Inverse up" m_performPathAnimation.kInverseUp;
displayString -replace -value "Attach to Motion Path Options" m_performPathAnimation.kMotionPathOptions;
displayString -replace -value "Normal" m_performPathAnimation.kNormal;
displayString -replace -value "Object rotation up" m_performPathAnimation.kObjRotUp;
displayString -replace -value "Object up" m_performPathAnimation.kObjUp;
displayString -replace -value "Parametric length:" m_performPathAnimation.kParamLength;
displayString -replace -value "Scene up" m_performPathAnimation.kSceneUp;
displayString -replace -value "Start" m_performPathAnimation.kStart;
displayString -replace -value "Start/End" m_performPathAnimation.kStartEnd;
displayString -replace -value "Start time:" m_performPathAnimation.kStartTime;
displayString -replace -value "Time range:" m_performPathAnimation.kTimeRange;
displayString -replace -value "Up axis:" m_performPathAnimation.kUpAxis;
displayString -replace -value "Vector" m_performPathAnimation.kVector;
displayString -replace -value "World up type:" m_performPathAnimation.kWorldUp;
displayString -replace -value "World up object:" m_performPathAnimation.kWorldUpObj;
displayString -replace -value "World up vector:" m_performPathAnimation.kWorldUpVector;
displayString -replace -value "X" m_performPathAnimation.kX;
displayString -replace -value "Y" m_performPathAnimation.kY;
displayString -replace -value "Z" m_performPathAnimation.kZ;
