// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Convert NURBS/Polygons to Subdiv Options" m_performSubdivCreate.kConvertNURBS;
displayString -replace -value "Create" m_performSubdivCreate.kCreate;
displayString -replace -value "Keep original" m_performSubdivCreate.kKeepOriginal;
displayString -replace -value "Maximum base mesh faces:" m_performSubdivCreate.kMaximumBase;
displayString -replace -value "Maximum edges per vertex:" m_performSubdivCreate.kMaximumEdges;
displayString -replace -value "Proxy object" m_performSubdivCreate.kProxyObjec;
displayString -replace -value "Standard (no history)" m_performSubdivCreate.kStandard;
displayString -replace -value "Subdivision surface mode:" m_performSubdivCreate.kSubdivisionSurface;
