// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "All keyable" m_performCreateCharacter.kAllKeyable;
displayString -replace -value "All keyable except:" m_performCreateCharacter.kAllKeyableExcept;
displayString -replace -value "Attributes" m_performCreateCharacter.kAttributes;
displayString -replace -value "Character" m_performCreateCharacter.kCharacter;
displayString -replace -value "Create Character Set" m_performCreateCharacter.kCreateCharacterSet;
displayString -replace -value "Create Character Set Options" m_performCreateCharacter.kCreateCharacterSetOptions;
displayString -replace -value "Dynamic" m_performCreateCharacter.kDynamic;
displayString -replace -value "From Channel Box" m_performCreateCharacter.kFromChannelBox;
displayString -replace -value "Hierarchy below selected node" m_performCreateCharacter.kHierarchyBelow;
displayString -replace -value "Include:" m_performCreateCharacter.kInclude;
displayString -replace -value "Include:" m_performCreateCharacter.kIncludeOptions;
displayString -replace -value "Name:" m_performCreateCharacter.kName;
displayString -replace -value "Redirect character" m_performCreateCharacter.kRedirectCharacter;
displayString -replace -value "Redirection" m_performCreateCharacter.kRedirection;
displayString -replace -value "Rotate" m_performCreateCharacter.kRotate;
displayString -replace -value "Rotation only" m_performCreateCharacter.kRotation;
displayString -replace -value "Rotation and translation" m_performCreateCharacter.kRotationTranslation;
displayString -replace -value "Scale" m_performCreateCharacter.kScale;
displayString -replace -value "Translate" m_performCreateCharacter.kTranslate;
displayString -replace -value "Translation only" m_performCreateCharacter.kTranslation;
displayString -replace -value "Visibility" m_performCreateCharacter.kVisibility;
