// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Auto completion" m_performExtendCosCurve.kAutoCompletion;
displayString -replace -value "Both" m_performExtendCosCurve.kBoth;
displayString -replace -value "Circular" m_performExtendCosCurve.kCircular;
displayString -replace -value "End" m_performExtendCosCurve.kEnd;
displayString -replace -value "Exit on completion" m_performExtendCosCurve.kExitOnCompletion;
displayString -replace -value "Extend CoS" m_performExtendCosCurve.kExtendCoS;
displayString -replace -value "Extend CoS Tool" m_performExtendCosCurve.kExtendCoSTool;
displayString -replace -value "Extend curve at:" m_performExtendCosCurve.kExtendCurveAt;
displayString -replace -value "Extend Curve on Surface Options" m_performExtendCosCurve.kExtendCurveSurfaceOptions;
displayString -replace -value "Extend Curve on Surface Tool Options" m_performExtendCosCurve.kExtendCurveSurfaceToolOptions;
displayString -replace -value "Extend method" m_performExtendCosCurve.kExtendMethod;
displayString -replace -value "Extension type:" m_performExtendCosCurve.kExtensionType;
displayString -replace -value "Extrapolate" m_performExtendCosCurve.kExtrapolate;
displayString -replace -value "Join to original" m_performExtendCosCurve.kJoinToOriginal;
displayString -replace -value "Keep original" m_performExtendCosCurve.kKeepOriginal;
displayString -replace -value "Linear" m_performExtendCosCurve.kLinear;
displayString -replace -value "Parametric distance" m_performExtendCosCurve.kParametric;
displayString -replace -value "Parametric distance:" m_performExtendCosCurve.kParametricDistance;
displayString -replace -value "Remove multiple knots" m_performExtendCosCurve.kRemoveMultipleKnots;
displayString -replace -value "Start" m_performExtendCosCurve.kStart;
displayString -replace -value "Tool behavior:" m_performExtendCosCurve.kToolBehavior;
displayString -replace -value "UV point" m_performExtendCosCurve.kUVPoint;
displayString -replace -value "UV point to extend to:" m_performExtendCosCurve.kUVPointToExtendTo;
