// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "All keyable" m_performSetBreakdown.kAllKeyable;
displayString -replace -value "All keyable attributes" m_performSetBreakdown.kAllKeyableAttrs;
displayString -replace -value "All manipulator handles" m_performSetBreakdown.kAllManipHandles;
displayString -replace -value "Below" m_performSetBreakdown.kBelow;
displayString -replace -value "Channels:" m_performSetBreakdown.kChannels;
displayString -replace -value "Control points:" m_performSetBreakdown.kControlPoints;
displayString -replace -value "Current manipulator handle" m_performSetBreakdown.kCurrentManipHandle;
displayString -replace -value "Current time" m_performSetBreakdown.kCurrentTime;
displayString -replace -value "From Channel Box" m_performSetBreakdown.kFromChannelBox;
displayString -replace -value "Hierarchy:" m_performSetBreakdown.kHierarchy;
displayString -replace -value "Prompt" m_performSetBreakdown.kPrompt;
displayString -replace -value "Selected" m_performSetBreakdown.kSelected;
displayString -replace -value "Set Breakdown" m_performSetBreakdown.kSetBreakdown;
displayString -replace -value "Set Breakdown Options" m_performSetBreakdown.kSetBreakdownOptions;
displayString -replace -value "Set breakdowns at:" m_performSetBreakdown.kSetBreakdownsAt;
displayString -replace -value "Set breakdowns on:" m_performSetBreakdown.kSetBreakdownson;
displayString -replace -value "Shapes:" m_performSetBreakdown.kShapes;
