// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "At path" m_performExtrude.kAtPath;
displayString -replace -value "At profile" m_performExtrude.kAtProfile;
displayString -replace -value "Auto completion" m_performExtrude.kAutoCompletion;
displayString -replace -value "Bezier" m_performExtrude.kBezier;
displayString -replace -value "Closest end point" m_performExtrude.kClosestEndPoint;
displayString -replace -value "Complete" m_performExtrude.kComplete;
displayString -replace -value "Component" m_performExtrude.kComponent;
displayString -replace -value "Cubic" m_performExtrude.kCubic;
displayString -replace -value "Curve range:" m_performExtrude.kCurveRange;
displayString -replace -value "Direction:" m_performExtrude.kDirection;
displayString -replace -value "Direction vector:" m_performExtrude.kDirectionVector;
displayString -replace -value "Distance" m_performExtrude.kDistance;
displayString -replace -value "Exit on completion" m_performExtrude.kExitOnCompletion;
displayString -replace -value "Extrude" m_performExtrude.kExtrude;
displayString -replace -value "Extrude length:" m_performExtrude.kExtrudeLength;
displayString -replace -value "Extrude Options" m_performExtrude.kExtrudeOptions;
displayString -replace -value "Extrude Tool" m_performExtrude.kExtrudeTool;
displayString -replace -value "Extrude Tool Options" m_performExtrude.kExtrudeToolOptions;
displayString -replace -value "Flat" m_performExtrude.kFlat;
displayString -replace -value "Free" m_performExtrude.kFree;
displayString -replace -value "Linear" m_performExtrude.kLinear;
displayString -replace -value "NURBS" m_performExtrude.kNurbs;
displayString -replace -value "Orientation:" m_performExtrude.kOrientation;
displayString -replace -value "Profile normal" m_performExtrude.kOrientationProfile;
displayString -replace -value "Output geometry:" m_performExtrude.kOutputGeometry;
displayString -replace -value "Partial" m_performExtrude.kPartial;
displayString -replace -value "Path direction" m_performExtrude.kPathDirection;
displayString -replace -value "Pivot:" m_performExtrude.kPivot;
displayString -replace -value "Polygons" m_performExtrude.kPolygons;
displayString -replace -value "Profile normal" m_performExtrude.kProfileNormal;
displayString -replace -value "Result position:" m_performExtrude.kResultPosition;
displayString -replace -value "Rotation:" m_performExtrude.kRotation;
displayString -replace -value "Scale:" m_performExtrude.kScale;
displayString -replace -value "Specify" m_performExtrude.kSpecify;
displayString -replace -value "Style:" m_performExtrude.kStyle;
displayString -replace -value "Subdiv" m_performExtrude.kSubdiv;
displayString -replace -value "Surface degree:" m_performExtrude.kSurfaceDegree;
displayString -replace -value "Tool behavior:" m_performExtrude.kToolBehavior;
displayString -replace -value "Tube" m_performExtrude.kTube;
displayString -replace -value "X axis" m_performExtrude.kXAxis;
displayString -replace -value "Y axis" m_performExtrude.kYAxis;
displayString -replace -value "Z axis" m_performExtrude.kZAxis;
