// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "File clean-up:" m_performReplaceNclothCacheFrames.kCleanup;
displayString -replace -value "Current time" m_performReplaceNclothCacheFrames.kCurrentTime;
displayString -replace -value "Delete backup files" m_performReplaceNclothCacheFrames.kDeleteBackups;
displayString -replace -value "In tangent:" m_performReplaceNclothCacheFrames.kInTangent;
displayString -replace -value "End interpolation frame" m_performReplaceNclothCacheFrames.kInterpEnd;
displayString -replace -value "Start interpolation frame" m_performReplaceNclothCacheFrames.kInterpStart;
displayString -replace -value "Interpolate frames" m_performReplaceNclothCacheFrames.kInterpolateFrames;
displayString -replace -value "Linear" m_performReplaceNclothCacheFrames.kLinear;
displayString -replace -value "Note: When using multiple caches on a single surface\nthat overlap" m_performReplaceNclothCacheFrames.kMultiCacheWarning1;
displayString -replace -value " in time, it is best to merge these caches into\none and replace frames" m_performReplaceNclothCacheFrames.kMultiCacheWarning2;
displayString -replace -value " in the new merged cache." m_performReplaceNclothCacheFrames.kMultiCacheWarning3;
displayString -replace -value "No interpolation" m_performReplaceNclothCacheFrames.kNoInterpolation;
displayString -replace -value "Out tangent:" m_performReplaceNclothCacheFrames.kOutTangent;
displayString -replace -value "Rename interpolated frames" m_performReplaceNclothCacheFrames.kRenameInterpolateFrames;
displayString -replace -value "Replace" m_performReplaceNclothCacheFrames.kReplace;
displayString -replace -value "End replace frame" m_performReplaceNclothCacheFrames.kReplaceEnd;
displayString -replace -value "Replace nCache Frame(s) Options" m_performReplaceNclothCacheFrames.kReplaceOptions;
displayString -replace -value "Start replace frame" m_performReplaceNclothCacheFrames.kReplaceStart;
displayString -replace -value "Replace time range:" m_performReplaceNclothCacheFrames.kReplaceTimeRange;
displayString -replace -value "Save every" m_performReplaceNclothCacheFrames.kSampleMultiplier;
displayString -replace -value "evaluation(s)" m_performReplaceNclothCacheFrames.kSampleMultiplierEnd;
displayString -replace -value "Evaluate every" m_performReplaceNclothCacheFrames.kSimulationRate;
displayString -replace -value "frame(s)" m_performReplaceNclothCacheFrames.kSimulationRateEnd;
displayString -replace -value "Smooth" m_performReplaceNclothCacheFrames.kSmooth;
displayString -replace -value "Start/End" m_performReplaceNclothCacheFrames.kStartEnd;
displayString -replace -value "Step" m_performReplaceNclothCacheFrames.kStep;
displayString -replace -value "Replace with simulation data" m_performReplaceNclothCacheFrames.kWithSimulation;
