// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Anti-alias lines" m_photoshopEditTexture.kAntialiasLines;
displayString -replace -value "Apply" m_photoshopEditTexture.kApply;
displayString -replace -value "Attributes" m_photoshopEditTexture.kAttributes;
displayString -replace -value "Connected attribute list has been modified. Do you wish to save changes?\n" m_photoshopEditTexture.kAttrubeListModifiedMsg;
displayString -replace -value "Bottom" m_photoshopEditTexture.kBottom;
displayString -replace -value "Close" m_photoshopEditTexture.kClose;
displayString -replace -value "Color value:" m_photoshopEditTexture.kColorValue;
displayString -replace -value "Convert To File Texture Options" m_photoshopEditTexture.kConvertToFileTextureOptions;
displayString -replace -value "Detailed attribute list" m_photoshopEditTexture.kDetailedAttributeList;
displayString -replace -value "Edit" m_photoshopEditTexture.kEdit;
displayString -replace -value "Edit" m_photoshopEditTexture.kEditButton;
displayString -replace -value "Edit PSD Network Options" m_photoshopEditTexture.kEditPSDNetworkOptions;
displayString -replace -value "Help on Edit PSD Network Options" m_photoshopEditTexture.kHelpOnEditPSDNetworkOptions;
displayString -replace -value "Image Details" m_photoshopEditTexture.kImageDetails;
displayString -replace -value "Image name:" m_photoshopEditTexture.kImageName;
displayString -replace -value "Include UV snapshot" m_photoshopEditTexture.kIncludeUVSnapshot;
displayString -replace -value "More than one object has been selected." m_photoshopEditTexture.kManyObjectsSelectedError;
displayString -replace -value "More than one connection exists between ^1s and ^2s" m_photoshopEditTexture.kMoreConnectionsWarn;
displayString -replace -value "No" m_photoshopEditTexture.kNo;
displayString -replace -value "Channels are not selected. Select Channels" m_photoshopEditTexture.kNoChannelSelected;
displayString -replace -value "No object has been selected" m_photoshopEditTexture.kNoObjectSelectedError;
displayString -replace -value "Selected shape does not have any PSD connections. Select proper shape" m_photoshopEditTexture.kNoPsdConnections;
displayString -replace -value "Selected object is neither a NURBS nor a POLY nor a SUBD. Select the proper surface" m_photoshopEditTexture.kObjectSelectionError;
displayString -replace -value "Open Adobe(R) Photoshop(R)" m_photoshopEditTexture.kOpenAdobeRPhotoshopR;
displayString -replace -value "Position:" m_photoshopEditTexture.kPosition;
displayString -replace -value "Position of the UV snapshot layer in the PSD file" m_photoshopEditTexture.kPositionOfTheUVSnapshotLayerAnnot;
displayString -replace -value "Reset Settings" m_photoshopEditTexture.kResetSettings;
displayString -replace -value "Save Settings" m_photoshopEditTexture.kSaveSettings;
displayString -replace -value "Selected Attributes" m_photoshopEditTexture.kSelectedAttributes;
displayString -replace -value "Selected shape is not connected to any of the PSD textures" m_photoshopEditTexture.kShapeSelectionError;
displayString -replace -value "Size X:" m_photoshopEditTexture.kSizeX;
displayString -replace -value "Size Y:" m_photoshopEditTexture.kSizeY;
displayString -replace -value "Top" m_photoshopEditTexture.kTop;
displayString -replace -value "UV Details" m_photoshopEditTexture.kUVDetails;
displayString -replace -value "UV set:" m_photoshopEditTexture.kUVSet;
displayString -replace -value "Warning" m_photoshopEditTexture.kWarning;
displayString -replace -value "Yes" m_photoshopEditTexture.kYes;
