// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  March 11, 2003
//
//<doc>
//<name plugAttr>
//
//<synopsis>
//      string plugAttr(string $plug)
//
//<returns>
//      string : Attribute name portion of the specified plug
//
//<description>
//      This procedure returns the attribute name portion of the specified
//      plug. Note that some attribute names may contain multiple, 
//		"."-separated tokens. For example, the attribute name portion of the 
//		plug "ramp1.colorEntryList[0].color" would be "colorEntryList[0].color".
//
//<flags>
//      string $plug The plug name from which to extract the attribute name
//      portion.
//
//<examples>
//  	// Find the attribute name portion of checker1.color1
//		plugAttr "checker1.color1";
//		// Result: color1 //
//
//</doc>


global proc string plugAttr(string $plug)
{
	//
	// Description:
	//	This procedure returns the attribute name portion of the specified
	//	plug.
	//	Note that some attribute names may still have multiple, "."-separated
	//	tokens. For example, the attribute name portion of the plug
	//	"ramp1.colorEntryList[0].color" would be "colorEntryList[0].color".
	//

	string $buffer[];
	tokenize($plug, ".", $buffer);

	string $attr;
	int $i;

	$attr = $buffer[1];

	for ($i = 2; $i < size($buffer); $i++)
	{
		$attr += ("." + $buffer[$i]);
	}

	return $attr;
}
