// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// This script helps to re-adjust the sharing of color sets on instances for
// per-instance color sets.
//
// Given a selected set of instances, it finds the current color set for the
// first selected instance and it moves the subsequently selected instances
// into that set.
//
//
global proc polyColorShareInstances()
{
	string $sel[] = `ls -sl`;
	if (size($sel) == 0) {
		error( (uiRes("m_polyColorShareInstances.kColorShareNothingSelected")));
	} else {
		int $foundIt = 0;
		for ($ii = 0; $ii < size($sel); $ii++) {
			string $currSet[] = `polyColorSet -q -currentPerInstanceSet $sel[$ii]`;
			if (size($currSet) > 0) {
				polyColorSet -colorSet $currSet[0] -shareInstances;
				
				// redo the selection to trigger the color set editor to update
				// its display
				//
				select -r $sel;
				$foundIt = true;
				break;
			}
		}
		if (! $foundIt) {
			warning( (uiRes("m_polyColorShareInstances.kNoPerInstance")));
		}
	}
}
