// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Description" m_polyMergeProperties.kDescriptionFrame;
displayString -replace -value "Merge Edge Settings" m_polyMergeProperties.kMergeEdgeSettings;
displayString -replace -value "Make Hole Settings" m_polyMergeProperties.kMergeHoleSettings;
displayString -replace -value "Merge mode:" m_polyMergeProperties.kMergeMode;
displayString -replace -value "New edge:" m_polyMergeProperties.kPolyMergeEdgeModeL;
displayString -replace -value "Created between first and second edge" m_polyMergeProperties.kPolyMergeEdgeModeL1;
displayString -replace -value "First edge selected becomes new edge" m_polyMergeProperties.kPolyMergeEdgeModeL2;
displayString -replace -value "Second edge selected becomes new edge" m_polyMergeProperties.kPolyMergeEdgeModeL3;
displayString -replace -value "To merge boundary edges to make one common edge, click two \nboundary edges from the same mesh." m_polyMergeProperties.kPolyMergeEdgeToolDescApp;
displayString -replace -value "First" m_polyMergeProperties.kPolyMergeFaceModeFir;
displayString -replace -value "Middle" m_polyMergeProperties.kPolyMergeFaceModeMid;
displayString -replace -value "None" m_polyMergeProperties.kPolyMergeFaceModeNone;
displayString -replace -value "Second" m_polyMergeProperties.kPolyMergeFaceModeSec;
displayString -replace -value "Project First" m_polyMergeProperties.kPolyMergeFaceModepFir;
displayString -replace -value "Project Middle" m_polyMergeProperties.kPolyMergeFaceModepMid;
displayString -replace -value "Project Second" m_polyMergeProperties.kPolyMergeFaceModepSec;
displayString -replace -value "Punch a hole in a selected face in the shape of a second face. \nBoth faces should be in the same object." m_polyMergeProperties.kPolyMergeFaceToolDescApp;
displayString -replace -value "Settings" m_polyMergeProperties.kSettingsFrame;
