// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Append to Polygon Settings" m_polyEditFacetProperties.kAppendSettings;
displayString -replace -value "Create Polygon Settings" m_polyEditFacetProperties.kCreateSettings;
displayString -replace -value "Description" m_polyEditFacetProperties.kDescriptionFrame;
displayString -replace -value "Number of points:" m_polyEditFacetProperties.kNumberOfPoints;
displayString -replace -value "Click a boundary edge. Click to place vertices, or click on edges in\nthe direction of the arrows." m_polyEditFacetProperties.kPolyCreatePolyToolDescApp;
displayString -replace -value "To create a polygon, click to place each vertex and then press Enter." m_polyEditFacetProperties.kPolyCreatePolyToolDescCreate;
displayString -replace -value "Draw a line across a face to split it into two more new faces.\nThe line must start and end on an edge.\nEach time it touches an edge a new face will be created." m_polyEditFacetProperties.kPolyCreatePolyToolDescSplit;
displayString -replace -value "Divisions:" m_polyEditFacetProperties.kPolyCreatePolyToolDivisions;
displayString -replace -value "Limit the number of points" m_polyEditFacetProperties.kPolyCreatePolyToolLimit;
displayString -replace -value "Limit points to:" m_polyEditFacetProperties.kPolyCreatePolyToolLimitTo;
displayString -replace -value "Keep new faces planar" m_polyEditFacetProperties.kPolyCreatePolyToolPlanar;
displayString -replace -value "Rotation angle:" m_polyEditFacetProperties.kPolyCreatePolyToolRotAngle;
displayString -replace -value "Smoothing angle:" m_polyEditFacetProperties.kPolyCreatePolyToolSmooAngle;
displayString -replace -value "Snapping tolerance:" m_polyEditFacetProperties.kPolyCreatePolyToolSnapTol;
displayString -replace -value "(vertices added per edge)" m_polyEditFacetProperties.kPolyCreatePolyToolSubdExtra;
displayString -replace -value "Settings" m_polyEditFacetProperties.kSettingsFrame;
displayString -replace -value "(1 = snap to midpoint)" m_polyEditFacetProperties.kSnapToMidpoint;
displayString -replace -value "Split only from edges" m_polyEditFacetProperties.kSplitOnlyFromEdges;
displayString -replace -value "Split Polygon Settings" m_polyEditFacetProperties.kSplitSettings;
displayString -replace -value "Texture space:" m_polyEditFacetProperties.kTextureSpace;
displayString -replace -value "None" m_polyEditFacetProperties.kTextureSpaceNone;
displayString -replace -value "Normalize (scale to fit)" m_polyEditFacetProperties.kTextureSpaceNormalize;
displayString -replace -value "Unitize (use corners and boundary)" m_polyEditFacetProperties.kTextureSpaceUnitize;
displayString -replace -value "Use snapping points along edge" m_polyEditFacetProperties.kUseSnappingPointsAlongEdge;
