// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// Script:    polySelConstraintPanel.mel
//
// SYNOPSIS
//			Creates the mel components around the polySelConstraintEditor
//

global proc polySelectionConstraintPanel(string $panelName) 
{
	global string $gMainPane;
	if (!`scriptedPanelType -exists polySelectionConstraintPanel`) {
		scriptedPanelType
			-unique true
			-addCallback 	"addPolySelConstraintWindow" 
			-removeCallback "removePolySelConstraintWindow" 
			-label (uiRes("m_polySelConstraintPanel.kPolySelectionConstraintPanel"))
			polySelectionConstraintPanel;	
		
		setParent $gMainPane;
		scriptedPanel -unParent -type "polySelectionConstraintPanel"
			$panelName;
	}
}


global proc buildPolyConstraintContextHelpItems(string $nameRoot, string $menuParent)
//
//  Description:
//		Build context sensitive menu items
//		
//  Input Arguments:
//		$nameRoot - name to use as the root of all item names
//		$menuParent - the name of the parent of this menu
//
//  Return Value:
//      None
//
{
	menuItem -label (uiRes("m_polySelConstraintPanel.kPolySelectionConstraintPanelHelp"))
		-enableCommandRepeat false
		-command "showHelp SelectionConstraints";
}

global proc addPolySelConstraintWindow(string $whichPanel)
{
	int $menusOkayInPanels = `optionVar -q allowMenusInPanels`;
	panel -e -mbv $menusOkayInPanels $whichPanel;

	//  Build Menubar.
	menu -label (uiRes("m_polySelConstraintPanel.kPolySelectionConstraintPanelReset"))
		($whichPanel+"resetMenu");
	menuItem -label (uiRes("m_polySelConstraintPanel.kPolySelectionConstraintPanelDisableAll"))
		-c ("resetPolySelectConstraint; polygonConstraintUpdate(\"" + $whichPanel + "\");")
		($whichPanel+"resetMenuDisable");

	//	Add support for the Context Sensitive Help Menu.
	//
	addContextHelpProc $whichPanel "buildPolyConstraintContextHelpItems";

	// create Monitor
	polySelectConstraintMonitor -create;
	// fill panel
	polygonConstraint($whichPanel);
}

global proc removePolySelConstraintWindow(string $whichPanel)
{
	// delete Monitor
	polySelectConstraintMonitor -delete;
}
