// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

// Description:  This procedure is called when you have a string S
//      which has quotation mark (") in it, and you want to put this
//      string inside of two quotation marks "....." in order to
//      pass it into a function, then you need
//      to put a backslash (\) in front of the quotation mark in S.
//
//      For example, S is
//              print("foo")
//      and you want to end up with
//              "print(\"foo\")"
//
global proc string portableString( string $str )
{
    string $res = "";

    int $i;
    for( $i = 1; $i <= size($str); $i++ )
    {
        string $src = `substring $str $i $i`;

        if( $src == "\"" )
        {
            $res += "\\\"";
        }
        else if ( $src == "\\" )
        {
            $res += "\\\\";
        }
        else
        {
            $res += $src;
        }
    }

    return ("\"" + $res + "\"");
}
