// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Prepare For Stitch: Failed in creating stitch node" m_prepareSurfacesToStitch.kErrorFailedCreatingStitchNode;
displayString -replace -value "Prepare For Stitch: Failed to make a connection to stitch input" m_prepareSurfacesToStitch.kErrorFailedToConnectToStitchInput;
displayString -replace -value "Prepare For Stitch: Failed to make a connection to stitch output" m_prepareSurfacesToStitch.kErrorFailedToConnectToStitchOutput;
displayString -replace -value "Prepare For Stitch: select NURBS surface(s) to be stitched together." m_prepareSurfacesToStitch.kErrorSelectSurfaces;
displayString -replace -value "Prepare For Stitch: ^1s already prepared" m_prepareSurfacesToStitch.kWarningAlreadyPrepared;
displayString -replace -value "Prepare For Stitch: Cannot prepare ^1s" m_prepareSurfacesToStitch.kWarningCannotPrepare;
displayString -replace -value "Prepare For Stitch: Failed to connect to the shading group." m_prepareSurfacesToStitch.kWarningFailedToConnectToShadingGroup;
