// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc addProfilerPanel(string $panelName) {
//
//  Description:  This proc is called every time a profilerPanel is made.
// It creates the profilerTool and then parent a new popupMenu to the draw region of the tool
// The draw region layout is ProfilerToolLayout (defined in the TprofilerTool.ui file)
//  
	addContextHelpProc $panelName "buildProfilerHelpItems";

	profilerTool -mk;
	popupMenu -p "ProfilerToolLayout" -pmc ("updateProfilerPopupMenu()") profilerToolLayoutPopupMenu;
}

global proc buildProfilerHelpItems(string $nameRoot, string $menuParent)
{
	menuItem -label (uiRes("m_profilerPanel.kProfilerHelp"))
		-annotation (uiRes("m_profilerPanel.kProfilerHelpAnnot"))
		-enableCommandRepeat false
		-command "showHelp Profiler";
}

global proc updateProfilerPopupMenu() {
// This procedure updates the menuItems in the pop up menu

	popupMenu -e -deleteAllItems profilerToolLayoutPopupMenu;

		menuItem -label (uiRes("m_profilerPanel.kProfilerToolHideSel"))
				 -annotation (uiRes("m_profilerPanel.kProfilerToolHideSelAnnot"))
				 -command "profilerTool -e -showSelectedEvents false"
				 -parent profilerToolLayoutPopupMenu;

		menuItem -label (uiRes("m_profilerPanel.kProfilerToolHideSelRep"))
				 -annotation (uiRes("m_profilerPanel.kProfilerToolHideSelRepAnnot"))
				 -command "profilerTool -e -showSelectedEventsRepetition false"
				 -parent profilerToolLayoutPopupMenu;

		menuItem -label (uiRes("m_profilerPanel.kProfilerToolShowSel"))
				 -annotation (uiRes("m_profilerPanel.kProfilerToolShowSelAnnot"))
				 -command "profilerTool -e -showSelectedEvents true"
				 -parent profilerToolLayoutPopupMenu;
				 	
		menuItem -label (uiRes("m_profilerPanel.kProfilerToolShowSelRep"))
				 -annotation (uiRes("m_profilerPanel.kProfilerToolShowSelRepAnnot"))
				 -command "profilerTool -e -showSelectedEventsRepetition true"
				 -parent profilerToolLayoutPopupMenu;

		menuItem -label (uiRes("m_profilerPanel.kProfilerToolShowAll"))
				 -annotation (uiRes("m_profilerPanel.kProfilerToolShowAllAnnot"))
				 -command "profilerTool -e -showAllEvent true"
				 -parent profilerToolLayoutPopupMenu;
}
