// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Help on Profiler" m_profilerPanel.kProfilerHelp;
displayString -replace -value "Get help on Profiler" m_profilerPanel.kProfilerHelpAnnot;
displayString -replace -value "Hide selected events" m_profilerPanel.kProfilerToolHideSel;
displayString -replace -value "Hide the selected events" m_profilerPanel.kProfilerToolHideSelAnnot;
displayString -replace -value "Hide selected events repetition" m_profilerPanel.kProfilerToolHideSelRep;
displayString -replace -value "Hide every event(s) with the same type as the selected event(s)" m_profilerPanel.kProfilerToolHideSelRepAnnot;
displayString -replace -value "Unhide all" m_profilerPanel.kProfilerToolShowAll;
displayString -replace -value "Show all events" m_profilerPanel.kProfilerToolShowAllAnnot;
displayString -replace -value "Show only selected events" m_profilerPanel.kProfilerToolShowSel;
displayString -replace -value "Show only the events selected" m_profilerPanel.kProfilerToolShowSelAnnot;
displayString -replace -value "Show only selected events repetition" m_profilerPanel.kProfilerToolShowSelRep;
displayString -replace -value "Show only every event(s) with the same type as the selected event(s)" m_profilerPanel.kProfilerToolShowSelRepAnnot;
