// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Anim. curve:" m_propModProperties.kAnimCurve;
displayString -replace -value "Create new" m_propModProperties.kCreateNew;
displayString -replace -value "Create new" m_propModProperties.kCreateNewParam;
displayString -replace -value "Curve" m_propModProperties.kCurve;
displayString -replace -value "Degree:" m_propModProperties.kDegree;
displayString -replace -value "Distance based on:" m_propModProperties.kDistanceBasedOn;
displayString -replace -value "Distance cutoff:" m_propModProperties.kDistanceCutoff;
displayString -replace -value "Distance cutoff U:" m_propModProperties.kDistanceCutoffU;
displayString -replace -value "Distance cutoff V:" m_propModProperties.kDistanceCutoffV;
displayString -replace -value "Linear" m_propModProperties.kLinear;
displayString -replace -value "Modification falloff:" m_propModProperties.kModificationFalloff;
displayString -replace -value "Modification type:" m_propModProperties.kModificationType;
displayString -replace -value "NURBS curve:" m_propModProperties.kNURBSCurve;
displayString -replace -value "NURBS curve" m_propModProperties.kNURBSCurveOption;
displayString -replace -value "No anim curves with prefix ^1s" m_propModProperties.kNoAnimCurveParam;
displayString -replace -value "No anim curves with prefix ^1s" m_propModProperties.kNoAnimCurves;
displayString -replace -value "No NURBS curves." m_propModProperties.kNoNURBSCurves;
displayString -replace -value "Parametric(NURBS)" m_propModProperties.kParametric;
displayString -replace -value "Power" m_propModProperties.kPower;
displayString -replace -value "Scale U:" m_propModProperties.kScaleU;
displayString -replace -value "Scale V:" m_propModProperties.kScaleV;
displayString -replace -value "Script" m_propModProperties.kScript;
displayString -replace -value "User defined script:" m_propModProperties.kUserDefinedScript;
displayString -replace -value "World" m_propModProperties.kWorld;
displayString -replace -value "X" m_propModProperties.kXaxis;
displayString -replace -value "Y" m_propModProperties.kYaxis;
displayString -replace -value "Z" m_propModProperties.kZaxis;
