// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Anti-alias" m_psdConvertSolidTxPanel.kAntialias;
displayString -replace -value "Apply" m_psdConvertSolidTxPanel.kApply;
displayString -replace -value "Background Color" m_psdConvertSolidTxPanel.kBackgroundColor;
displayString -replace -value "Background Mode" m_psdConvertSolidTxPanel.kBackgroundMode;
displayString -replace -value "Bake Transparency" m_psdConvertSolidTxPanel.kBakeTransparency;
displayString -replace -value "Bake Using Virtual Plane" m_psdConvertSolidTxPanel.kBakeUsingVirtualPlane;
displayString -replace -value "Close" m_psdConvertSolidTxPanel.kClose;
displayString -replace -value "Connected Attributes" m_psdConvertSolidTxPanel.kConnectedAttributes;
displayString -replace -value "Custom color" m_psdConvertSolidTxPanel.kCustomColor;
displayString -replace -value "Edit" m_psdConvertSolidTxPanel.kEdit;
displayString -replace -value "Extend Edge Color" m_psdConvertSolidTxPanel.kExtendEdgeColor;
displayString -replace -value "Fill Texture Seams" m_psdConvertSolidTxPanel.kFillTextureSeams;
displayString -replace -value "PSD Convert Solid Textures Options" m_psdConvertSolidTxPanel.kPSDConvertSolidTextures;
displayString -replace -value "Reset Settings" m_psdConvertSolidTxPanel.kResetSettings;
displayString -replace -value "Save Settings" m_psdConvertSolidTxPanel.kSaveSettings;
displayString -replace -value "Shader default" m_psdConvertSolidTxPanel.kShaderDefault;
displayString -replace -value "Texture Sample" m_psdConvertSolidTxPanel.kTextureSample;
