// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc string pv_basename(string $fileName)
//
//	Description:
//		Given a file name, return the basename.
//
{
	string $fName = $fileName;
	if (`about -nt`) {
		$fName = convert($fName);
	}

	string $buffer[];
	int $nTokens;
	$nTokens = `tokenize $fName "/" $buffer`;

	if ($nTokens > 0) {
		$fName = $buffer[$nTokens-1];
	}

	$nTokens = `tokenize $fName "." $buffer`;
	
	// baseName's can have a "." in them too. So
	// make sure we concatenate everything but the
	// last token, which will be the extension.
	//
	int $i = 0;
	$fName = "";
	for( $i = 0; $i < ($nTokens-1); $i++) {
		if( $i > 0 ) {
			$fName += ".";
		}
		$fName = $fName + $buffer[$i];
	}
	
	return $fName;
}
