// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
// Creation Date:  14 January 1999
//
//
//  Procedure Name:
//      rebuildCurveToolScript
//
//  Description:
//	create wrapper around the rebuildCurve command
//
//  Input Arguments:
//		0 ==> do the command.
//		1 ==> show the tool/action option box
//		2 ==> return the command
//		3 ==> show tool/action option box
//		4 ==> enter the tool
//
//  Return Value:
//      None.
//

global proc rebuildCurveToolSetup( int $forceFactorySettings, string $goToTool )
{
	if( $forceFactorySettings || !`optionVar -ex rebuildCurveEuc` ) {
		optionVar -iv rebuildCurveEuc 0;
	}
	if( $forceFactorySettings || !`optionVar -ex rebuildCurveLac` ) {
		optionVar -iv rebuildCurveLac 1;
	}
	if( "" != $goToTool ) {
		scriptCtx -e -euc `optionVar -q rebuildCurveEuc` $goToTool;
		scriptCtx -e -lac `optionVar -q rebuildCurveLac` $goToTool;
	}
}

global proc rebuildCurveValues ( string $toolName ) 
{
	performRebuildCurve 3 $toolName;
	scriptCtxCommonValues( $toolName );
}

global proc rebuildCurveProperties()
{
	scriptCtxCommonProperties;
}

proc createRebuildCurveContext( string $tool )
{
	if( ! `scriptCtx -exists $tool` ) {
		rebuildCurveToolSetup( 0, "" );
		scriptCtx -i1 "rebuildCurve.png"
		  -title (uiRes("m_rebuildCurveToolScript.kRebuildCurveDirectionTool"))
		  -bcn "rebuildCurve"

		  -exitUponCompletion `optionVar -q rebuildCurveEuc`
		  -totalSelectionSets 1
		  -expandSelectionList true
		  -fcs ("rebuildCurveToolScript 0")

		  -setNoSelectionPrompt (uiRes("m_rebuildCurveToolScript.kSelectCurves"))
		  -setSelectionPrompt (uiRes("m_rebuildCurveToolScript.kSelectAdditionalCurves"))
		  -setDoneSelectionPrompt (uiRes("m_rebuildCurveToolScript.kRebuildCurve"))

		  -setAutoToggleSelection true
		  -setAutoComplete `optionVar -q rebuildCurveLac`
		  -setAllowExcessCount true
		  -showManipulators true

		  -setSelectionCount 0
		  -nurbsCurve true
		  -curveOnSurface true
		$tool;
	}
}

global proc string rebuildCurveToolScript( int $setToTool )
//
//	Description :
//		0 ==> do the command.
//		1 ==> show the action option box
//		2 ==> return the command
//		3 ==> show tool/action option box
//		4 ==> enter the tool/do the command
{
	string $tool = "";
	if( $setToTool > 2 ) {
		if( !`optionVar -q modelWithToolRebuildCurve` ) {
			$setToTool = 4 - $setToTool;
		}
		else {
			$tool = "rebuildCurveContext";
			createRebuildCurveContext $tool;
		}
	}
	return scriptToolScript( "performRebuildCurve", $setToTool, $tool );
}
