// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Filter" m_referenceEditsWindow.kFilter;
displayString -replace -value "Must select a referenced file in the reference editor window." m_referenceEditsWindow.kMustSelectReferencedFile;
displayString -replace -value "Offline edits cannot be removed. Import the offline file to remove the edit." m_referenceEditsWindow.kOfflineEditsNotRemovable;
displayString -replace -value "Reference Edits: ^1s" m_referenceEditsWindow.kRefEditsTitle;
displayString -replace -value "Reference Edit: " m_referenceEditsWindow.kReferenceEdit;
displayString -replace -value "Refresh Edits List" m_referenceEditsWindow.kRefreshEdit;
displayString -replace -value "Remove Selected Edits" m_referenceEditsWindow.kRemoveEdit;
displayString -replace -value "Show Dag Path" m_referenceEditsWindow.kShowDagPath;
displayString -replace -value "Show Namespaces" m_referenceEditsWindow.kShowNamespaces;
