// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Cameras" m_renderFlagsWindow.kCameras;
displayString -replace -value "Close" m_renderFlagsWindow.kClose;
displayString -replace -value "Dynamics" m_renderFlagsWindow.kDynamics;
displayString -replace -value "General" m_renderFlagsWindow.kGeneral;
displayString -replace -value "Help on Render Flags" m_renderFlagsWindow.kHelpOnRenderFlags;
displayString -replace -value "Lights" m_renderFlagsWindow.kLights;
displayString -replace -value "Materials" m_renderFlagsWindow.kMaterials;
displayString -replace -value "Objects" m_renderFlagsWindow.kObjects;
displayString -replace -value "Render Flags" m_renderFlagsWindow.kRenderFlags;
displayString -replace -value "Rendering Flags" m_renderFlagsWindow.kRenderingFlags;
displayString -replace -value "Show:" m_renderFlagsWindow.kShow;
displayString -replace -value "Textures" m_renderFlagsWindow.kTextures;
