// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Free Rotate" m_rotateMarkingMenuImpl.kCenterTrackballLabel;
displayString -replace -value "Discrete Rotate" m_rotateMarkingMenuImpl.kDiscreteRotate;
displayString -replace -value "Gimbal" m_rotateMarkingMenuImpl.kGimbalLabel;
displayString -replace -value "Object" m_rotateMarkingMenuImpl.kLocalLabel;
displayString -replace -value "Component" m_rotateMarkingMenuImpl.kNormalAverageRotate;
displayString -replace -value "Preserve UVs" m_rotateMarkingMenuImpl.kPreserveUVs;
displayString -replace -value "When true, the uvs are edited to project to new values to stop texture swimming as vertices are moved" m_rotateMarkingMenuImpl.kPreserveUVsAnnot;
displayString -replace -value "Relative" m_rotateMarkingMenuImpl.kRelativeLabel;
displayString -replace -value "Rotate Options" m_rotateMarkingMenuImpl.kRotateOptions;
displayString -replace -value "Rotate tool options" m_rotateMarkingMenuImpl.kRotateToolOptionsAnnot;
displayString -replace -value "Rotate Object Center" m_rotateMarkingMenuImpl.kUseObjectPivotLabel;
displayString -replace -value "World" m_rotateMarkingMenuImpl.kWorldLabel;
