// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//
//  Creation Date:  Nov 24, 1998
//
//  Description:
//  This proc fills the free form surface fillet tool property sheet 
//	with values.
//  See also roundProperties.mel
//
//  Input Arguments:
//      $toolName        - this is the name of the instance of the tool
//                        that the property sheet is modifying.
//
//  Return Value:
//      None.
//


global proc roundCRValues ( string $toolName ) 
//
//  Description:
//		Sets the state of the property sheet based on the values
//		in the tool context.
//
{
	// set my top layout to be the current $parent
	//
	string $parent = (`toolPropertyWindow -q -location` + "|roundCR");
	setParent $parent;

	// Set the slider for radius value based on the context's values
	//
	float $radiusToDisplay = eval("roundCRCtx -q -radiusToUse " + $toolName );
	floatSliderGrp -e -v $radiusToDisplay radiusSlider;

	// Set the tolerance values
	//
	int $useLocalTolerance = (`roundCRCtx -q -ugt $toolName` == 1)? 1 : 2;
	radioButtonGrp -e -sl $useLocalTolerance commonToleranceOptions;
	if( $useLocalTolerance == 1 ) {
		floatSliderGrp -e -enable false commonPositionalTolerance;
	}
	else if( $useLocalTolerance == 2 ) {
		floatSliderGrp -e -enable true commonPositionalTolerance;
	}

	float $tolerance = `roundCRCtx -q -tol $toolName`;
    floatSliderGrp -e -value $tolerance commonPositionalTolerance;

	// set property sheet label and icon
	//
	string $icon = "roundSrf.png";
	string $helpTag = "RoundTool";

	toolPropertySetCommon $toolName $icon $helpTag;
	toolPropertySelect roundCR;
}
