// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Averaged Normal" m_sculptMeshCacheProperties.kAvgNormal;
displayString -replace -value "Brush" m_sculptMeshCacheProperties.kBrushSection;
displayString -replace -value "Buildup:" m_sculptMeshCacheProperties.kBuildUpRate;
displayString -replace -value "Set the rate at which the brush deformation grows to reach the strength value" m_sculptMeshCacheProperties.kBuildUpRateAnnotation;
displayString -replace -value "Camera" m_sculptMeshCacheProperties.kCamera;
displayString -replace -value "Clear stamp" m_sculptMeshCacheProperties.kClearStamp;
displayString -replace -value "Constrain to Surface" m_sculptMeshCacheProperties.kConstrainToSurface;
displayString -replace -value "Direction:" m_sculptMeshCacheProperties.kDirection;
displayString -replace -value "Display" m_sculptMeshCacheProperties.kDisplaySection;
displayString -replace -value "" m_sculptMeshCacheProperties.kDummy;
displayString -replace -value "Curve:" m_sculptMeshCacheProperties.kFalloffCurve;
displayString -replace -value "Custom Curve:" m_sculptMeshCacheProperties.kFalloffCurveCustom;
displayString -replace -value "Preset Curve:" m_sculptMeshCacheProperties.kFalloffCurvePreset;
displayString -replace -value "Surface/Volume" m_sculptMeshCacheProperties.kFalloffHybrid;
displayString -replace -value "Falloff" m_sculptMeshCacheProperties.kFalloffSection;
displayString -replace -value "Size:" m_sculptMeshCacheProperties.kFalloffSize;
displayString -replace -value "Adjust brush size (b + drag left/right or MMB-drag left/right)" m_sculptMeshCacheProperties.kFalloffSizeAnnotation;
displayString -replace -value "Size Units:" m_sculptMeshCacheProperties.kFalloffSizeUnits;
displayString -replace -value "Strength:" m_sculptMeshCacheProperties.kFalloffStrength;
displayString -replace -value "Adjust brush strength (m + drag up/down or MMB-drag up/down)" m_sculptMeshCacheProperties.kFalloffStrengthAnnotation;
displayString -replace -value "Surface" m_sculptMeshCacheProperties.kFalloffSurface;
displayString -replace -value "Type:" m_sculptMeshCacheProperties.kFalloffType;
displayString -replace -value "Volume" m_sculptMeshCacheProperties.kFalloffVolume;
displayString -replace -value "Flip horizontally" m_sculptMeshCacheProperties.kFlipHorizonatlly;
displayString -replace -value "Flip vertically" m_sculptMeshCacheProperties.kFlipVertically;
displayString -replace -value "Follow Path" m_sculptMeshCacheProperties.kFollowPath;
displayString -replace -value "Forward" m_sculptMeshCacheProperties.kForward;
displayString -replace -value "Averaged Normal" m_sculptMeshCacheProperties.kGrabAvgNormal;
displayString -replace -value "Direction:" m_sculptMeshCacheProperties.kGrabDirection;
displayString -replace -value "Center Normal" m_sculptMeshCacheProperties.kGrabNormal;
displayString -replace -value "Screen" m_sculptMeshCacheProperties.kGrabScreen;
displayString -replace -value "Grab Silhouette" m_sculptMeshCacheProperties.kGrabSilhouette;
displayString -replace -value "Import" m_sculptMeshCacheProperties.kImport;
displayString -replace -value " Import... " m_sculptMeshCacheProperties.kImportButton;
displayString -replace -value "Import stamp" m_sculptMeshCacheProperties.kImportStamp;
displayString -replace -value "Invert" m_sculptMeshCacheProperties.kInvert;
displayString -replace -value "Invert the tool function (Ctrl)" m_sculptMeshCacheProperties.kInvertAnnotation;
displayString -replace -value "Invert Frozen" m_sculptMeshCacheProperties.kInvertFrozenButton;
displayString -replace -value "Reverse frozen and unfrozen parts of the active mesh (Ctrl + Shift + I)" m_sculptMeshCacheProperties.kInvertFrozenButtonAnnotation;
displayString -replace -value "Lock Shell Border" m_sculptMeshCacheProperties.kLockShellBorder;
displayString -replace -value "Min Brush Size:" m_sculptMeshCacheProperties.kMinSize;
displayString -replace -value "Min Brush Strength:" m_sculptMeshCacheProperties.kMinStrength;
displayString -replace -value "Object X" m_sculptMeshCacheProperties.kMirrorLX;
displayString -replace -value "Object Y" m_sculptMeshCacheProperties.kMirrorLY;
displayString -replace -value "Object Z" m_sculptMeshCacheProperties.kMirrorLZ;
displayString -replace -value "Mirror:" m_sculptMeshCacheProperties.kMirrorMode;
displayString -replace -value "Off" m_sculptMeshCacheProperties.kMirrorOff;
displayString -replace -value "World X" m_sculptMeshCacheProperties.kMirrorX;
displayString -replace -value "World Y" m_sculptMeshCacheProperties.kMirrorY;
displayString -replace -value "World Z" m_sculptMeshCacheProperties.kMirrorZ;
displayString -replace -value "Center Normal" m_sculptMeshCacheProperties.kNormal;
displayString -replace -value "Orient brush to surface" m_sculptMeshCacheProperties.kOrientBrush;
displayString -replace -value "Paint" m_sculptMeshCacheProperties.kPMPaint;
displayString -replace -value "Paint & Smooth" m_sculptMeshCacheProperties.kPMPaintSmooth;
displayString -replace -value "Smooth" m_sculptMeshCacheProperties.kPMSmooth;
displayString -replace -value "Paint Method:" m_sculptMeshCacheProperties.kPaintMethod;
displayString -replace -value "Set how freeze values are applied or edited on a mesh" m_sculptMeshCacheProperties.kPaintMethodAnnotation;
displayString -replace -value "Pick Stamp..." m_sculptMeshCacheProperties.kPickButton;
displayString -replace -value "Pick stamp" m_sculptMeshCacheProperties.kPickStamp;
displayString -replace -value "Scale image from center" m_sculptMeshCacheProperties.kPlacementCenter;
displayString -replace -value "Continuous" m_sculptMeshCacheProperties.kPlacementPath;
displayString -replace -value "Scale image from side" m_sculptMeshCacheProperties.kPlacementSide;
displayString -replace -value "Refresh image" m_sculptMeshCacheProperties.kRefreshImage;
displayString -replace -value "Reset Curve" m_sculptMeshCacheProperties.kResetCurveButton;
displayString -replace -value "Right" m_sculptMeshCacheProperties.kRight;
displayString -replace -value "Rotate" m_sculptMeshCacheProperties.kRotateStampButton;
displayString -replace -value "Save Custom Curve" m_sculptMeshCacheProperties.kSaveCurveButton;
displayString -replace -value "Screen Pixels" m_sculptMeshCacheProperties.kScreenSpace;
displayString -replace -value "Show frozen" m_sculptMeshCacheProperties.kShowFrozen;
displayString -replace -value "Show wireframe" m_sculptMeshCacheProperties.kShowWireframe;
displayString -replace -value "Snap to grid" m_sculptMeshCacheProperties.kSnapToGrid;
displayString -replace -value "Image: " m_sculptMeshCacheProperties.kStampImage;
displayString -replace -value "Orient to stroke" m_sculptMeshCacheProperties.kStampOrientToStroke;
displayString -replace -value "Draw Method:" m_sculptMeshCacheProperties.kStampPlacement;
displayString -replace -value "Randomize" m_sculptMeshCacheProperties.kStampRandomization;
displayString -replace -value "Horizontal Flip" m_sculptMeshCacheProperties.kStampRandomizeFlipX;
displayString -replace -value "Vertical Flip" m_sculptMeshCacheProperties.kStampRandomizeFlipY;
displayString -replace -value "X Position:" m_sculptMeshCacheProperties.kStampRandomizePosX;
displayString -replace -value "Y Position:" m_sculptMeshCacheProperties.kStampRandomizePosY;
displayString -replace -value "Rotation:" m_sculptMeshCacheProperties.kStampRandomizeRotation;
displayString -replace -value "Scale:" m_sculptMeshCacheProperties.kStampRandomizeScale;
displayString -replace -value "Strength:" m_sculptMeshCacheProperties.kStampRandomizeStrength;
displayString -replace -value "Stamp" m_sculptMeshCacheProperties.kStampSection;
displayString -replace -value "Steady Stroke" m_sculptMeshCacheProperties.kSteadyStroke;
displayString -replace -value "Enable finer control over the brush stroke" m_sculptMeshCacheProperties.kSteadyStrokeAnnotation;
displayString -replace -value "Distance:" m_sculptMeshCacheProperties.kSteadyStrokeDistance;
displayString -replace -value "Stylus" m_sculptMeshCacheProperties.kStylusSection;
displayString -replace -value "Twist" m_sculptMeshCacheProperties.kTwist;
displayString -replace -value "Rotate vertices clockwise or counterclockwise (Ctrl)" m_sculptMeshCacheProperties.kTwistAnnotation;
displayString -replace -value "Unfreeze All" m_sculptMeshCacheProperties.kUnfreezeAllButton;
displayString -replace -value "Unfreeze all frozen parts of the active mesh (Shift + U)" m_sculptMeshCacheProperties.kUnfreezeAllButtonAnnotation;
displayString -replace -value "Update Plane" m_sculptMeshCacheProperties.kUpdatePlane;
displayString -replace -value "Recalculate the underlying tool plane for each stamp update in a stroke" m_sculptMeshCacheProperties.kUpdatePlaneAnnotation;
displayString -replace -value "Save the brush size for this tool" m_sculptMeshCacheProperties.kUseGlobalSizeAnnotation;
displayString -replace -value "Insert gaps between individual stamps along the stroke" m_sculptMeshCacheProperties.kUseSpacingAnnotation;
displayString -replace -value "Use Stamp" m_sculptMeshCacheProperties.kUseStamp;
displayString -replace -value "Spacing" m_sculptMeshCacheProperties.kUseStampDist;
displayString -replace -value "Vertex Normal" m_sculptMeshCacheProperties.kVNormal;
displayString -replace -value "View image" m_sculptMeshCacheProperties.kViewImage;
displayString -replace -value "Whole Stroke" m_sculptMeshCacheProperties.kWholeStroke;
displayString -replace -value "Continuously recalculate the underlying tool plane for each vertex affected during a stroke" m_sculptMeshCacheProperties.kWholeStrokeAnnotation;
displayString -replace -value "World" m_sculptMeshCacheProperties.kWorldSpace;
displayString -replace -value "X" m_sculptMeshCacheProperties.kX;
displayString -replace -value "XY" m_sculptMeshCacheProperties.kXY;
displayString -replace -value "XZ" m_sculptMeshCacheProperties.kXZ;
displayString -replace -value "Y" m_sculptMeshCacheProperties.kY;
displayString -replace -value "YZ" m_sculptMeshCacheProperties.kYZ;
displayString -replace -value "Z" m_sculptMeshCacheProperties.kZ;
