// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc sculptMeshCacheConvertMM()
{
	menuItem -rp "N" -l (uiRes("m_sculptMeshCacheConvertMM.kSetGrab"))
 		-c ("setMeshSculptTool(  \"Grab\" ); ");
	menuItem -rp "NE" -l (uiRes("m_sculptMeshCacheConvertMM.kSetWax"))
 		-c ("setMeshSculptTool(  \"Wax\" ); ");
 	menuItem -rp "E" -l (uiRes("m_sculptMeshCacheConvertMM.kSetFlatten"))
 		-c ("setMeshSculptTool(  \"Flatten\" ); ");
	menuItem -rp "SE" -l (uiRes("m_sculptMeshCacheConvertMM.kSetSmooth"))
 		-c ("setMeshSculptTool(  \"Smooth\" ); ");
	menuItem -rp "S" -l (uiRes("m_sculptMeshCacheConvertMM.kSetSculpt"))
 		-c ("setMeshSculptTool(  \"Sculpt\" ); ");
	menuItem -rp "SW" -l (uiRes("m_sculptMeshCacheConvertMM.kSetPinch"))
 		-c ("setMeshSculptTool(  \"Pinch\" ); ");
	menuItem -rp "W" -l (uiRes("m_sculptMeshCacheConvertMM.kSetBulge"))
 		-c ("setMeshSculptTool(  \"Bulge\" ); ");
	menuItem -rp "NW" -l (uiRes("m_sculptMeshCacheConvertMM.kSetFreeze"))
 		-c ("setMeshSculptTool(  \"Freeze\" ); ");

	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetRelax"))
 		-c ("setMeshSculptTool(  \"Relax\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetFoamy"))
 		-c ("setMeshSculptTool(  \"Foamy\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetSpray"))
 		-c ("setMeshSculptTool(  \"Spray\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetRepeat"))
 		-c ("setMeshSculptTool(  \"Repeat\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetImprint"))
 		-c ("setMeshSculptTool(  \"Imprint\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetScrape"))
 		-c ("setMeshSculptTool(  \"Scrape\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetFill"))
 		-c ("setMeshSculptTool(  \"Fill\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetKnife"))
 		-c ("setMeshSculptTool(  \"Knife\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetSmear"))
 		-c ("setMeshSculptTool(  \"Smear\" ); ");
	menuItem -l (uiRes("m_sculptMeshCacheConvertMM.kSetAmplify"))
 		-c ("setMeshSculptTool(  \"Amplify\" ); ");
}
