// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//	setNClothMapType
//
//	Description:
//		This method sets the nCloth/nRigid map type for either the selected
//	meshes, or for the specified mesh, by setting the appropriate MapType
//	attribute corresponding to the specified attribute, to the given mapType
//	value.
//
global proc setNClothMapType(string $attr, string $meshParam, int $mapType)
{
	string $objs[];
	// The 0 to getNMeshToPaint means we do not accept component
	// selections, the user must select an nCloth
	//
	string $meshAndCloth[] = `getNMeshToPaint $meshParam 0`;
	if( size($meshAndCloth) > 0 ){
		$objs[0] = $meshAndCloth[1];	// We want the nBase
	}
	string $mapTypeAttr = ($attr+"MapType");
	for ($obj in $objs) {
		string $cmd = ("setAttr "+$obj+"."+$mapTypeAttr+" "+$mapType);
		eval $cmd;
	}
}
