// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  Oct 31 2014
//
//  Description:
//      This script provides a way to set the target for sculpting/tweaks on a blendshape node.
//
//

global proc setSculptTargetIndex( string $blendShape, int $idx, int $ivm )
{
    string $attr = $blendShape;
	$attr += ".inputTarget";

	int $nbInputs = `getAttr -size $attr`;
	int $indices[] = `getAttr -multiIndices $attr`;

	for( $i = 0; $i < $nbInputs; $i++ )
	{
		int $index = $indices[$i];
		$attr = $blendShape + ".inputTarget[" + $index + "].sculptTargetIndex";

		int $oldIdx = `getAttr $attr`;

		if( $oldIdx == $idx )
			$idx = -1;

		setAttr $attr $idx;
	}

	if( $ivm == 1 )
	{
		if( $idx > -1 )
		{
			string $weightName = $blendShape + ".weight[" + $idx + "]";
			$weightName = `aliasAttr -q $weightName`;

			string $msg = (uiRes("m_setSculptTargetIndex.kEnabledBlendSculptTarget"));
			$msg += $weightName;

			inViewMessage -smg $msg -pos "botCenter" -fade;
		}
		else
		{
			inViewMessage -clear "botCenter";

			string $msg = (uiRes("m_setSculptTargetIndex.kDisabledBlendSculptTarget"));
			$msg += $blendShape;

			inViewMessage -smg $msg -pos "botCenter" -fade;
		}
    }
}
