// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc setTRSOrientJoint( string $parent, int $what[], string $tool )
{
    setParent $parent;

    // Update UI according to what has been selected.
    if ( size( $what ) )
    {
        switch( $what[0] )
        {
            case  0: manipMoveOrientJointPrefs    $parent; break;
            case  1: jointOrientWorldSelected     $parent; break;
            case  2: jointOrientPrimarySelected   $parent; break;
            case  3: jointOrientSecondarySelected $parent; break;
            default: break;
        }
    }
    
    // Determine if joint orientation is enabled
    int $state = `checkBoxGrp -q -v1 orientJointCheckBox`;
    
    // Get the string representation of the oj and sao params
    string $axes[] = {};
    jointOrientGetOrientAxes( $parent, $axes );

    // Update the oj manip params
    manipMoveContext -e -oje $state   $tool;
    manipMoveContext -e -oj  $axes[0] $tool;
    manipMoveContext -e -sao $axes[1] $tool;
}
