// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Cancel" m_shellWnd.kCancel;
displayString -replace -value "Cancel" m_shellWnd.kCancelButton;
displayString -replace -value "Change History Length..." m_shellWnd.kChangeHistoryLength;
displayString -replace -value "Change History Length" m_shellWnd.kChangeHistoryLengthTitle;
displayString -replace -value "Change Prompt..." m_shellWnd.kChangePrompt;
displayString -replace -value "Change Prompt" m_shellWnd.kChangePromptTitle;
displayString -replace -value "Clear" m_shellWnd.kClear;
displayString -replace -value "Command Shell" m_shellWnd.kCommandShell;
displayString -replace -value "Enter new history length:" m_shellWnd.kEnterNewHistoryLength;
displayString -replace -value "Enter new prompt string:" m_shellWnd.kEnterNewPromptString;
displayString -replace -value "\"^1s\" is not valid, please enter an integer between 0 and 1000." m_shellWnd.kInvalidEntry;
displayString -replace -value "OK" m_shellWnd.kOK;
displayString -replace -value "OK" m_shellWnd.kOKButton;
displayString -replace -value "Options" m_shellWnd.kOptions;
displayString -replace -value "Shell" m_shellWnd.kShell;
