// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "^1s does not exist." m_spriteSmoke.kEmitterNotExist;
displayString -replace -value "You are not licensed to use the Sprite Smoke Effect." m_spriteSmoke.kNoSpriteLicense;
displayString -replace -value "An object that cannot own an emitter was in the active list, so the smoke effect was not created.\nDeselect all objects or select an object than can own an emitter and try again." m_spriteSmoke.kObjectCannotOwnEmitter;
displayString -replace -value "A sprite file must be specified as the Sprite Image Name in the options box. A default set of images and Readme.txt file of instructions are on the Maya documentation, lessons, extras CD in the directory Gifts/smoke." m_spriteSmoke.kSpriteFileMissing;
displayString -replace -value "For spriteSmoke only one object may be selected to add an emitter to;  sprite smoke effect was not created." m_spriteSmoke.kSpriteSomkeOnlyOne;
displayString -replace -value "^1s does not exist." m_spriteSmoke.kTurbNotExist;
