// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc stitchSrfHistoryLink( string $parent, string $node )
{
	setParent $parent;


	string $pcattr = $node + ".pc" ;
    string $tcattr = $node + ".tc" ;
    string $scattr = $node + ".sc" ;

    int $npc = `getAttr -size $pcattr` ;
    int $ntc = `getAttr -size $tcattr` ;
    int $nsc = `getAttr -size $scattr` ;

	if( $npc == $nsc && $npc == $nsc && $npc > 0 ) {

		string $ptpcName_CheckBoxGrp = "blendPtsPosition" ;	
    	connectControl -index 2  $ptpcName_CheckBoxGrp ($node+".tpp") ;
		string $pttcName_CheckBoxGrp = "blendPtsTangent" ;	
		connectControl -index 2  $pttcName_CheckBoxGrp ($node +".tpn") ;

        float $scount[] = `getAttr $scattr`;
       	float $pc[] = `getAttr $pcattr`;
       	float $tc[] = `getAttr $tcattr`;
		int $i ;
        for( $i = 0 ; $i < $npc ; $i++ ) {
            string $pcName_checkBoxGrp = "PositionalContinuity"+$i ;
           	string $tcName_checkBoxGrp = "TangentContinuity"+$i ;
           	string $scName_intSliderGrp = "samples"+$i ;

           	connectControl $scName_intSliderGrp ($node+".sc["+$i+"]") ;
           	connectControl -index 2 $pcName_checkBoxGrp ($node+".pc["+$i+"]") ;
           	connectControl -index 2 $tcName_checkBoxGrp ($node+".tc["+$i+"]") ;
       	}
	}
}

