// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:  29 March 2005
//
//<doc>
//<name stripPrefixFromName>
//
//<synopsis>
//		string stripPrefixFromName(string $prefix, string $nodeName)
//
//<description>
//		Strips $prefix from the beginning of $nodeName. This script will
//		handle DAG paths by stripping the $prefix from the beginning of
//		every node name in the DAG path.
//
//		NOTE: This script will not actually rename $nodeName, it just
//		generates a string.
//
//<flags>
//		string $prefix		The string to strip.
//		string $nodeName	The node name to be stripped.
//
//<returns>
//		string : The stripped node name.
//
//<examples>
//	stripPrefixFromName( "shaders:", "shaders:blinn1SG" );
//	// Result: blinn1SG
//  stripPrefixFromName( "skel:", "skel:joint1|skel:joint2|skel:joint3" );
//	// Result: joint1|joint2|joint3
//	stripPrefixFromName( "two:", "one:two:myNode" );
//	// Result: one:two:myNode
//
//</doc>
//

global proc string stripPrefixFromName(string $prefix, string $nodeName)
{
	string $result;
	
	if ( "" == $nodeName )
	{
		return "";
	}

	int $prefixLength = `size( $prefix )`;
	int $hasLeadingBar = ("|" == `substring $nodeName 1 1`);
	
	string $path[];
	int $pathLength = `tokenize $nodeName "|" $path`;
	if ( $pathLength > 0 )
	{
	
		// Strip $prefix from all names in path.
		//
		int $i = 0;
		for ( $i = 0; $i < $pathLength; $i++ )
		{
			if ( startsWith( $path[$i], $prefix ) )
			{
				int $elementLength = `size $path[$i]`;
				$path[$i] = substring( $path[$i], $prefixLength + 1, $elementLength );
			}	
		}
		
		// Build $result from the, now stripped, elements of $nodeName
		//
		$result = "";
		if ( $hasLeadingBar )
		{
			$result = "|";
		}
		$result += $path[0];
		for ( $i = 1; $i < $pathLength; $i++ )
		{
			$result += "|" + $path[$i];	
		}
	}
	
	return $result;
}
