// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Description:
//		This script sets the values for the specified smooth
//	context within the tool property sheet. 
//
//  Input Arguments:
//      None.
//
//  Return Value:
//      None.
//

global proc textureSmoothValues( string $context ) 
{
	string $parent = `toolPropertyWindow -query -location`;
	setParent $parent;

	// pinning
	int $hasPinBorder  = `texSmoothContext -q -pb $context`;
	checkBoxGrp -e -v1 $hasPinBorder texSmoothPinBorderCheck;
	
	checkBoxGrp -e 
		-cc1 ("texSmoothContext -e -pb #1 " + $context)
		texSmoothPinBorderCheck;


	int $space = `texSmoothContext -q -space $context`;
	switch ($space)
	{
		case 0:
			 radioButtonGrp -e -sl 1 texSmoothSpaceRadio;
			 $space = 1;
		break;
		case 1:
			radioButtonGrp -e -sl 2  texSmoothSpaceRadio;
			 $space = 2;
		break;
	}

	radioButtonGrp -e
		-nrb 2
		-on1 ("texSmoothContext -e -space 0 " + $context)
		-on2 ("texSmoothContext -e -space 1 " + $context)
		-select $space
		texSmoothSpaceRadio;

	// Update soft select values
	// softSelectValues( $parent );

	string $helpTag = "textureSmoothTool";
	toolPropertySetCommon $context "texSmoothLarge.png" $helpTag; 
	toolPropertySelect "textureSmooth";
}
