// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc textureSmudgeUVOptionsPopup()
{
	string $effectLabel = (uiRes("m_textureSmudgeUVOptionsPopup.kEffectType"));
	string $fixedLabel = (uiRes("m_textureSmudgeUVOptionsPopup.kFixed"));
	string $smudgeLabel = (uiRes("m_textureSmudgeUVOptionsPopup.kSmudge"));

	string $fallofLabel = (uiRes("m_textureSmudgeUVOptionsPopup.kFalloffType"));
	string $expLabel = (uiRes("m_textureSmudgeUVOptionsPopup.kExponential"));
	string $linLabel = (uiRes("m_textureSmudgeUVOptionsPopup.kLinear"));
	string $constLabel = (uiRes("m_textureSmudgeUVOptionsPopup.kConstant"));

	string $MMInitiatesLabel = (uiRes("m_textureSmudgeUVOptionsPopup.kMiddleMouseInitiates"));

	string $effectValue = `texSmudgeUVContext -q -effectType texSmudgeUVCtx`;
	string $falloffValue = `texSmudgeUVContext -q -functionType texSmudgeUVCtx`;
	int $MMValue = `texSmudgeUVContext -q -smudgeIsMiddle texSmudgeUVCtx`;

	menuItem
		-checkBox $MMValue
		-label $MMInitiatesLabel
		-command ("texSmudgeUVContext -e -smudgeIsMiddle #1 texSmudgeUVCtx")
		-radialPosition "N";

	menuItem
		-label $effectLabel
		-radialPosition "W"
		-subMenu 1;

		menuItem
			-label $fixedLabel
			-checkBox ("fixed" == $effectValue)
			-command ("texSmudgeUVContext -e -effectType fixed texSmudgeUVCtx")
			-radialPosition "W";

		menuItem
			-label $smudgeLabel
			-checkBox ("smudge" == $effectValue)
			-command ("texSmudgeUVContext -e -effectType smudge texSmudgeUVCtx")
			-radialPosition "E";

	setParent -m ..;

	menuItem
		-label $fallofLabel
		-radialPosition "E"
		-subMenu 1;

		menuItem
			-label $expLabel
			-checkBox ("exponential" == $falloffValue)
			-command ("texSmudgeUVContext -e -functionType exponential texSmudgeUVCtx")
			-radialPosition "E";

		menuItem
			-label $linLabel
			-checkBox ("linear" == $falloffValue)
			-command ("texSmudgeUVContext -e -functionType linear texSmudgeUVCtx")
			-radialPosition "N";

		menuItem
			-label $constLabel
			-checkBox ("constant" == $falloffValue)
			-command ("texSmudgeUVContext -e -functionType constant texSmudgeUVCtx")
			-radialPosition "W";

	setParent -m ..;
}
