// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Active" m_TimeSliderMenu.kActive;
displayString -replace -value "Display keys for all active objects in the timeline" m_TimeSliderMenu.kActiveAnnot;
displayString -replace -value "Add Inbetween" m_TimeSliderMenu.kAddInbetween;
displayString -replace -value "Insert inbetween at current time" m_TimeSliderMenu.kAddInbetweenAnnot;
displayString -replace -value "Cannot copy grease frames when viewing all cameras" m_TimeSliderMenu.kAllCamerasCopyWarn;
displayString -replace -value "Cannot cut grease frames when viewing all cameras" m_TimeSliderMenu.kAllCamerasCutWarn;
displayString -replace -value "Cannot paste grease frames when viewing all cameras" m_TimeSliderMenu.kAllCamerasPasteWarn;
displayString -replace -value "Auto" m_TimeSliderMenu.kAuto;
displayString -replace -value "Set in and out tangents to auto" m_TimeSliderMenu.kAutoAnnot;
displayString -replace -value "Clamped" m_TimeSliderMenu.kClamped;
displayString -replace -value "Set in and out tangents to clamped" m_TimeSliderMenu.kClampedAnnot;
displayString -replace -value "Continuous" m_TimeSliderMenu.kContinuous;
displayString -replace -value "Set playback looping to continuous" m_TimeSliderMenu.kContinuousAnnot;
displayString -replace -value "Convert to Breakdown" m_TimeSliderMenu.kConvertToBreakdown;
displayString -replace -value "Change existing keys into breakdowns" m_TimeSliderMenu.kConvertToBreakdownAnnot;
displayString -replace -value "Convert to Key" m_TimeSliderMenu.kConvertToKey;
displayString -replace -value "Change existing breakdowns into keys" m_TimeSliderMenu.kConvertToKeyAnnot;
displayString -replace -value "Copy" m_TimeSliderMenu.kCopy;
displayString -replace -value "Copy keys and place on animation clipboard" m_TimeSliderMenu.kCopyAnnot;
displayString -replace -value "Cut" m_TimeSliderMenu.kCut;
displayString -replace -value "Remove keys and place on animation clipboard" m_TimeSliderMenu.kCutAnnot;
displayString -replace -value "Delete" m_TimeSliderMenu.kDelete;
displayString -replace -value "Delete All FBIK Keys" m_TimeSliderMenu.kDeleteAllFBIKKeys;
displayString -replace -value "Delete FBIK keys on all body parts" m_TimeSliderMenu.kDeleteAllFBIKKeysAnnot;
displayString -replace -value "Delete keys but do not place on animation clipboard" m_TimeSliderMenu.kDeleteAnnot;
displayString -replace -value "Delete Body Part Keys" m_TimeSliderMenu.kDeleteBodyPartKeys;
displayString -replace -value "Delete FBIK keys on the selected body parts" m_TimeSliderMenu.kDeleteBodyPartKeysAnnot;
displayString -replace -value "Delete FBIK Keys" m_TimeSliderMenu.kDeleteFBIKKeys;
displayString -replace -value "Delete Selected FBIK Keys" m_TimeSliderMenu.kDeleteSelectedFBIKKeys;
displayString -replace -value "Delete FBIK keys on the selected object and its associated FK control joint" m_TimeSliderMenu.kDeleteSelectedFBIKKeysAnnot;
displayString -replace -value "Display Key Ticks" m_TimeSliderMenu.kDisplayTicks;
displayString -replace -value "Enabled Clips" m_TimeSliderMenu.kEnabledClips;
displayString -replace -value "Set playback range to times of the enabled clips." m_TimeSliderMenu.kEnabledClipsAnnot;
displayString -replace -value "Flat" m_TimeSliderMenu.kFlat;
displayString -replace -value "Set in and out tangents to flat" m_TimeSliderMenu.kFlatAnnot;
displayString -replace -value "Play Every Frame, Free" m_TimeSliderMenu.kFree;
displayString -replace -value "Set playback speed to play every frame as quickly as possible." m_TimeSliderMenu.kFreeAnnot;
displayString -replace -value "From Channel Box" m_TimeSliderMenu.kFromChannelBox;
displayString -replace -value "Display keys for channels selected in the Channel Box" m_TimeSliderMenu.kFromChannelBoxAnnot;
displayString -replace -value "Active Camera" m_TimeSliderMenu.kGreasePencilActiveCamera;
displayString -replace -value "Set to view the grease frames of the active camera" m_TimeSliderMenu.kGreasePencilActiveCameraAnnot;
displayString -replace -value "All Cameras" m_TimeSliderMenu.kGreasePencilAllCameras;
displayString -replace -value "Set to view the grease frames of all cameras" m_TimeSliderMenu.kGreasePencilAllCamerasAnnot;
displayString -replace -value "All" m_TimeSliderMenu.kGreasePencilDeleteFramesAll;
displayString -replace -value "Delete Frames" m_TimeSliderMenu.kGreasePencilDeleteFramesSubMenu;
displayString -replace -value "Grease Pencil" m_TimeSliderMenu.kGreasePencilMenu;
displayString -replace -value "None" m_TimeSliderMenu.kGreasePencilNone;
displayString -replace -value "Do not display grease pencil frames" m_TimeSliderMenu.kGreasePencilNoneAnnot;
displayString -replace -value "Keys" m_TimeSliderMenu.kKeysMenu;
displayString -replace -value "Linear" m_TimeSliderMenu.kLinear;
displayString -replace -value "Set in and out tangents to linear" m_TimeSliderMenu.kLinearAnnot;
displayString -replace -value "Min/Max" m_TimeSliderMenu.kMinMax;
displayString -replace -value "Set playback range to times of first and last keys" m_TimeSliderMenu.kMinMaxAnnot;
displayString -replace -value "No clips found; cannot determine clip animation range." m_TimeSliderMenu.kNoClipsError;
displayString -replace -value "No enabled clips found; cannot determine clip animation range." m_TimeSliderMenu.kNoEnabledClipsError;
displayString -replace -value "No keys found; cannot determine min/max of animation range." m_TimeSliderMenu.kNoKeysError;
displayString -replace -value "No objects selected to copy keys" m_TimeSliderMenu.kNoObjectsCopyWarn;
displayString -replace -value "No objects selected to cut keys" m_TimeSliderMenu.kNoObjectsCutWarn;
displayString -replace -value "No objects selected to delete keys" m_TimeSliderMenu.kNoObjectsDeleteWarn;
displayString -replace -value "No objects selected to edit keys" m_TimeSliderMenu.kNoObjectsEditWarn;
displayString -replace -value "No objects selected to paste keys" m_TimeSliderMenu.kNoObjectsPasteWarn;
displayString -replace -value "No objects selected to snap keys" m_TimeSliderMenu.kNoObjectsSnapWarn;
displayString -replace -value "No objects selected to set tangents" m_TimeSliderMenu.kNoObjectsTangetsWarn;
displayString -replace -value "No range selected; use Shift-LMB to select a range." m_TimeSliderMenu.kNoRangeError;
displayString -replace -value "No sound displayed; import a sound file, then use the Sound menu to display it in the Time Slider" m_TimeSliderMenu.kNoSound;
displayString -replace -value "None" m_TimeSliderMenu.kNone;
displayString -replace -value "Do not display keys in the timeline" m_TimeSliderMenu.kNoneAnnot;
displayString -replace -value "Once" m_TimeSliderMenu.kOnce;
displayString -replace -value "Set playback looping to once" m_TimeSliderMenu.kOnceAnnot;
displayString -replace -value "Oscillate" m_TimeSliderMenu.kOscillate;
displayString -replace -value "Set playback looping to oscillate" m_TimeSliderMenu.kOscillateAnnot;
displayString -replace -value "Paste" m_TimeSliderMenu.kPaste;
displayString -replace -value "Paste keys from animation clipboard" m_TimeSliderMenu.kPasteAnnot;
displayString -replace -value "Paste Connect" m_TimeSliderMenu.kPasteConnect;
displayString -replace -value "Paste and connect keys from animation clipboard" m_TimeSliderMenu.kPasteConnectAnnot;
displayString -replace -value "Paste" m_TimeSliderMenu.kPasteMenu;
displayString -replace -value "Plateau" m_TimeSliderMenu.kPlateau;
displayString -replace -value "Set in and out tangents to plateau" m_TimeSliderMenu.kPlateauAnnot;
displayString -replace -value "Play Every Frame, Max Real-time" m_TimeSliderMenu.kPlayEveryFrameRealtime;
displayString -replace -value "Set playback speed to play every frame with a maximum speed of real-time." m_TimeSliderMenu.kPlayEveryFrameRealtimeAnnot;
displayString -replace -value "Playback Looping" m_TimeSliderMenu.kPlaybackLooping;
displayString -replace -value "Playback Speed" m_TimeSliderMenu.kPlaybackSpeed;
displayString -replace -value "Playblast..." m_TimeSliderMenu.kPlayblast;
displayString -replace -value "Preview animation by screen-capturing frames" m_TimeSliderMenu.kPlayblastAnnot;
displayString -replace -value "Playblast options" m_TimeSliderMenu.kPlayblastOptionsAnnot;
displayString -replace -value "Preferences" m_TimeSliderMenu.kPrefs;
displayString -replace -value "Set playback range to values in animation preferences" m_TimeSliderMenu.kPrefsAnnot;
displayString -replace -value "Real-time" m_TimeSliderMenu.kRealtime;
displayString -replace -value "Set playback speed to real-time. Frames will be dropped if necessary to maintain speed." m_TimeSliderMenu.kRealtimeAnnot;
displayString -replace -value "Remove Inbetween" m_TimeSliderMenu.kRemoveInbetween;
displayString -replace -value "Remove inbetween at current time" m_TimeSliderMenu.kRemoveInbetweenAnnot;
displayString -replace -value "Selected" m_TimeSliderMenu.kSelected;
displayString -replace -value "Set playback range to currently selected range in Time Slider" m_TimeSliderMenu.kSelectedAnnot;
displayString -replace -value "Set Range to" m_TimeSliderMenu.kSetRange;
displayString -replace -value "Snap" m_TimeSliderMenu.kSnap;
displayString -replace -value "Snap keys to integer times" m_TimeSliderMenu.kSnapAnnot;
displayString -replace -value "Sound Length" m_TimeSliderMenu.kSound;
displayString -replace -value "Set playback range to length of currently displayed sound" m_TimeSliderMenu.kSoundAnnot;
displayString -replace -value "Sound" m_TimeSliderMenu.kSoundMenu;
displayString -replace -value "Spline" m_TimeSliderMenu.kSpline;
displayString -replace -value "Set in and out tangents to spline" m_TimeSliderMenu.kSplineAnnot;
displayString -replace -value "Start/End" m_TimeSliderMenu.kStartEnd;
displayString -replace -value "Set playback range to times stored with current scene" m_TimeSliderMenu.kStartEndAnnot;
displayString -replace -value "No start/end found in this scene.  Use File->save to set the current Animation Range as the start/end for this scene." m_TimeSliderMenu.kStartEndError;
displayString -replace -value "Stepped" m_TimeSliderMenu.kStepped;
displayString -replace -value "Set out tangent to stepped" m_TimeSliderMenu.kSteppedAnnot;
displayString -replace -value "Enable Stepped Preview" m_TimeSliderMenu.kSteppedPreview;
displayString -replace -value "When enabled, all animCurve tangents play back as if they were stepped -- their original values are preserved." m_TimeSliderMenu.kSteppedPreviewAnnot;
displayString -replace -value "Active" m_TimeSliderMenu.kTLAnimLayerFilterActive;
displayString -replace -value "Active and Selected" m_TimeSliderMenu.kTLAnimLayerFilterActiveAndSelected;
displayString -replace -value "All Affecting" m_TimeSliderMenu.kTLAnimLayerFilterAllAffecting;
displayString -replace -value "From Layer Editor Show Options" m_TimeSliderMenu.kTLAnimLayerFilterFromLayerEditor;
displayString -replace -value "Selected" m_TimeSliderMenu.kTLAnimLayerFilterSelected;
displayString -replace -value "Show Layer Weight" m_TimeSliderMenu.kTLShowAnimLayerWeight;
displayString -replace -value "Tangents" m_TimeSliderMenu.kTangentsMenu;
