// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.


global proc toggleAEFilter( string $nodeType, int $allTypes, int $action )
//
//	Description:
//		A callback to toggle the AE filter for the given node type
//		$nodeType : node type to toggle; "" implies "other" type
//		$allTypes:	if true, action applies to all types
//		$action:	0 - turn off
//					1 - turn on
//					2 - toggle
//				
//
{
	string $filterTypes[] = `optionVar -query activeAEShowFilterTypes`;
	int $numFilterTypes = size($filterTypes);
	if( $numFilterTypes == 0 ){
		return;	// No filtering, we're done
	}

	int $filterStates[];
	if( `optionVar -exists activeAEShowFilterStates` ){
		$filterStates = `optionVar -query activeAEShowFilterStates`;
	}
	int $numFilterStates = size($filterStates);

	// Remove old filter states
	//
	optionVar -remove activeAEShowFilterStates;

	// Do "other" first, since it's entry 0, and it's a special case
	//
	int $show = 1;	// Default value is 1 (i.e., on)
	if( $numFilterStates > 0 ){
		$show = $filterStates[0];
	}
	if( $allTypes || ($nodeType == "") ){
		if( $show != $action ){
			$show = !$show;
			string $itemName = "OtherOnOff";
			// Update UI
			if( `menuItem -exists $itemName` ) {
				menuItem -e -cb $show $itemName;
			}
		}
	}
	optionVar -iva activeAEShowFilterStates $show;

	// Now do the rest of the filters
	//
	int $filterIndex = 1;
	while( $filterIndex < $numFilterTypes ){
		int $show = 1;	// Default value is 1 (i.e., on)
		if( $filterIndex < $numFilterStates ){
			$show = $filterStates[$filterIndex];
			if( $allTypes || ( $filterTypes[$filterIndex] == $nodeType ) ){
				if( $show != $action ){
					$show = !$show;
					string $itemName = ($filterTypes[$filterIndex] + "OnOff");
					// Update UI
					if( `menuItem -exists $itemName` ) {
						menuItem -e -cb $show $itemName;
					}
				}
			}
		}
		optionVar -iva activeAEShowFilterStates $show;
		$filterIndex++;
	}
	updateAEshowAllButton();
	global string $gAEFocusNode;
	if( $gAEFocusNode != "" ){
		updateAE $gAEFocusNode;
	}
}
