// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Set To Edge" m_translateMarkingMenuImpl.kAlignAxisWithEdge;
displayString -replace -value "Set To Face" m_translateMarkingMenuImpl.kAlignAxisWithFace;
displayString -replace -value "Axis" m_translateMarkingMenuImpl.kAxis;
displayString -replace -value "Axes alignment options" m_translateMarkingMenuImpl.kAxisAnnot;
displayString -replace -value "Custom" m_translateMarkingMenuImpl.kCustomAxis;
displayString -replace -value "Discrete Move" m_translateMarkingMenuImpl.kDiscreteMoveLabel;
displayString -replace -value "Face Center" m_translateMarkingMenuImpl.kFaceCenterLabel;
displayString -replace -value "Keep Spacing" m_translateMarkingMenuImpl.kKeepSpacing;
displayString -replace -value "Live Object Axis" m_translateMarkingMenuImpl.kLiveObjectAxis;
displayString -replace -value "Parent" m_translateMarkingMenuImpl.kLocal;
displayString -replace -value "Maintain component spacing when snapping" m_translateMarkingMenuImpl.kMaintainComponentAnnot;
displayString -replace -value "Move Options" m_translateMarkingMenuImpl.kMoveOptions;
displayString -replace -value "Normal" m_translateMarkingMenuImpl.kNormal;
displayString -replace -value "Component" m_translateMarkingMenuImpl.kNormalAverage;
displayString -replace -value "Object" m_translateMarkingMenuImpl.kObject;
displayString -replace -value "Reset" m_translateMarkingMenuImpl.kOrientAxisReset;
displayString -replace -value "Set to Component" m_translateMarkingMenuImpl.kOrientAxisToComponent;
displayString -replace -value "Set To Point" m_translateMarkingMenuImpl.kOrientAxisTowardsPoint;
displayString -replace -value "Preserve Children" m_translateMarkingMenuImpl.kPreserveChild;
displayString -replace -value "Preserve the world space position of the child when the parent is moved" m_translateMarkingMenuImpl.kPreserveChildAnnot;
displayString -replace -value "Preserve UVs" m_translateMarkingMenuImpl.kPreserveUVs;
displayString -replace -value "When true, the uvs are edited to project to new values to stop texture swimming as vertices are moved" m_translateMarkingMenuImpl.kPreserveUVsAnnot;
displayString -replace -value "Relative Mode" m_translateMarkingMenuImpl.kRelativeMode;
displayString -replace -value "Relative move mode snapping toggle" m_translateMarkingMenuImpl.kRelativeMoveModeSnappingAnnot;
displayString -replace -value "Along Rotation Axis" m_translateMarkingMenuImpl.kRotationAxis;
displayString -replace -value "Set move manipulator to align along live object axis" m_translateMarkingMenuImpl.kSetMoveManipulatorObjectAnnot;
displayString -replace -value "Set move manipulator to align along rotation axis" m_translateMarkingMenuImpl.kSetMoveManipulatorRotationAnnot;
displayString -replace -value "Set move to local mode" m_translateMarkingMenuImpl.kSetMoveToLocalModeAnnot;
displayString -replace -value "Set move to component mode" m_translateMarkingMenuImpl.kSetMoveToNormalAverageModeAnnot;
displayString -replace -value "Set move to normal mode" m_translateMarkingMenuImpl.kSetMoveToNormalModeAnnot;
displayString -replace -value "Set move to object mode" m_translateMarkingMenuImpl.kSetMoveToObjectModeAnnot;
displayString -replace -value "Snap" m_translateMarkingMenuImpl.kSnapLabel;
displayString -replace -value "Tweak Mode" m_translateMarkingMenuImpl.kTweakMode;
displayString -replace -value "Update manip triad when in normal mode" m_translateMarkingMenuImpl.kUpdateManipTriadAnnot;
displayString -replace -value "Update Triad" m_translateMarkingMenuImpl.kUpdateTriad;
displayString -replace -value "Vertex" m_translateMarkingMenuImpl.kVertexLabel;
displayString -replace -value "World" m_translateMarkingMenuImpl.kWorld;
displayString -replace -value "Set move to world mode" m_translateMarkingMenuImpl.kWorldSetMoveAnnot;
