// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date: Aug 6, 1996
//
//  Description:
//      These procs create the controls for a trim tool property sheet.
//      See also trimValues.mel for procs that set the state of the
//      property sheet.
//
//  Input Arguments:
//      None.
//
//  Return Value:
//      None.
//


global proc trimHistoryLink( string $parent, string $node )
{
	setParent $parent;

	// selectedState:
	connectControl trimSelectedState ($node + ".sl");

	// trimOptions:
	connectControl -index 2 trimOptions ($node + ".sh");

	// slider for fitting tolerance:
	//
	connectControl fitTolerance($node + ".tol") ;
}

global proc trimProperties()
//
//  Description:
//      This procedure builds the property sheet and assigns callbacks to
//      its controls.  The state of the controls are set in trimValues().
//
//
{
	int $hasNodes = 0;

	string $parent = `toolPropertyWindow -q -location`;
	string $curctx = `currentCtx`;
	string $node = `trimCtx -q -tnq $curctx`;
	string $ext_defaultToolID = "trimDefaultProperties";

	setUITemplate -pushTemplate OptionsTemplate;

	setParent $parent;
	columnLayout -adj true trim;
		separator -st "none";
		$parent = `setParent -query`;

 		frameLayout -label (uiRes("m_trimProperties.kTrimSettings"))  -collapse false trimHistory_Frame;	
			columnLayout trimHistory_Column;
				radioButtonGrp -nrb 2 -sl 1 
					-label (uiRes("m_trimProperties.kCSelectedState")) 
					-label1 (uiRes("m_trimProperties.kKeep"))  -da1 0
					-label2 (uiRes("m_trimProperties.kDiscard"))  -da2 1
					trimSelectedState;

				checkBoxGrp -ncb 1 
					-label " "   
					-label1 (uiRes("m_trimProperties.kShrinkSurface")) 
					trimOptions;

				floatSliderGrp -field true -label (uiRes("m_trimProperties.kFittingTolerance"))  fitTolerance;
			setParent ..;
		setParent ..;

		trimHistoryLink( $parent, $node );
		commonModellingProperties( $parent, "trimCtx" );
		optionalCommonModellingSetCallbacks($parent, 
				"trimCtx", 
				"dontShowOutputStyle", 
				"showKeepOriginals",
				"dontShowCurveRange",
				"dontShowRebuild");

	setParent ..; // columnLayout

	setUITemplate -popTemplate;
}

