// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Brush pressure" m_Unfold3DBrushProperties.kBrushPressure;
displayString -replace -value "Brush Size" m_Unfold3DBrushProperties.kBrushSize;
displayString -replace -value "Iterations" m_Unfold3DBrushProperties.kIterations;
displayString -replace -value "Mode" m_Unfold3DBrushProperties.kMode;
displayString -replace -value "Optimize" m_Unfold3DBrushProperties.kOptimizeMode;
displayString -replace -value "Prevent self border intersections" m_Unfold3DBrushProperties.kSelfBorder;
displayString -replace -value "Surface Angle" m_Unfold3DBrushProperties.kSrfAngle;
displayString -replace -value "Prevent triangle flips" m_Unfold3DBrushProperties.kTriFlips;
displayString -replace -value "Unfold3DBrush Options" m_Unfold3DBrushProperties.kU3DBrushOpotions;
displayString -replace -value "UV Scale" m_Unfold3DBrushProperties.kUVScale;
displayString -replace -value "Unfold" m_Unfold3DBrushProperties.kUnfoldMode;
