// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "After" m_wireProperties.kAfter;
displayString -replace -value "Before" m_wireProperties.kBefore;
displayString -replace -value "Crossing effect:" m_wireProperties.kCrossingEffect;
displayString -replace -value "The crossing effect specifies the amplitude of the deformation in areas where two wires cross" m_wireProperties.kCrossingEffectAnnot;
displayString -replace -value "Default" m_wireProperties.kDefault;
displayString -replace -value "Deformation order:" m_wireProperties.kDeformationOrder;
displayString -replace -value "The deformation order is used to control how the wire is added to the history of the shape" m_wireProperties.kDeformationOrderAnnot;
displayString -replace -value "Dropoff distance:" m_wireProperties.kDropoffDistance;
displayString -replace -value "The dropoff distance specifies the region of influence of the wire" m_wireProperties.kDropoffDistanceAnnot;
displayString -replace -value "Envelope:" m_wireProperties.kEnvelope;
displayString -replace -value "The envelope is a scale on the deformation" m_wireProperties.kEnvelopeAnnot;
displayString -replace -value "Exclusive" m_wireProperties.kExclusive;
displayString -replace -value "The exclusive option is used to put the wire in a partition so its membership will not overlap with other deformers in the partition" m_wireProperties.kExclusiveOptionAnnot;
displayString -replace -value "Exclusive partition:" m_wireProperties.kExclusivePartition;
displayString -replace -value "Existing partitions:" m_wireProperties.kExistingPartitions;
displayString -replace -value "Group wire(s) and base wire(s)" m_wireProperties.kGroupWire;
displayString -replace -value "Grouping:" m_wireProperties.kGrouping;
displayString -replace -value "The grouping option groups the wire with the base wire so that they can easily be moved together to create a ripple effect" m_wireProperties.kGroupingOptionAnnot;
displayString -replace -value "Holders" m_wireProperties.kHolders;
displayString -replace -value "Holders are curves that you can use to limit the wire's deformation region" m_wireProperties.kHoldersAnnot;
displayString -replace -value "Local influence:" m_wireProperties.kLocalInfluence;
displayString -replace -value "The local influence specifies the localization of the deformation effect of two or more wires" m_wireProperties.kLocalInfluenceAnnot;
displayString -replace -value "Parallel" m_wireProperties.kParallel;
displayString -replace -value "Split" m_wireProperties.kSplit;
displayString -replace -value "Wire Settings" m_wireProperties.kWireSettings;
