// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.


//<doc>
//<name xbmLangPathList>

//
//<synopsis>
//		xbmLangPathList
//
//<returns>
//		string [] Array of directory names
//
//<description>
//		Returns the directories in the 
//		XBMLANGPATH environment variable.
//
//<flags>
//		None.
//
//<examples>
//  xbmLangPathList;
//
//</doc>

global proc string [] xbmLangPathList()
{
	global string $gXBMLANGPATH[];

	if (size($gXBMLANGPATH) == 0) {
		string $xbmPath = `getenv "XBMLANGPATH"`;
		string $paths[];
		string $buff, $buff2;
		int $i, $j, $ndx, $nArr;
		int $isOkay = true;

		if (`about -win`) {
			tokenize $xbmPath ";" $paths;
		}
		else {
			tokenize $xbmPath ":" $paths;
		}
		$nArr = size($paths);
		for ($i = 0, $ndx = 0; $i < $nArr; $i++) {
			$isOkay = true;
			$buff2 = $paths[$i];

			$buff = `substitute "/%L" $buff2 ""`;	
			$buff2 = `substitute "/%T" $buff ""`;	
			$buff = `substitute "/%N" $buff2 ""`;
			$buff2 = `substitute "/%S" $buff ""`;
			$buff = `substitute "/%C" $buff2 ""`;
			$buff2 = `substitute "%B" $buff ""`;

			if ($buff2 == "") {
				$buff = `system "pwd"`;			// GG: need command for pwd
				$buff2 = `substitute "\n" $buff "/"`;
			}

			//  check for duplicates
			//
			for ($j = 0; $j < $ndx; $j++) {
				if ($gXBMLANGPATH[$j] == $buff2) {
					$isOkay = false;
					break;
				}
			}

			if (`about -win`)
			{
				if ($isOkay) {
					$gXBMLANGPATH[$ndx++] = $buff2;
				}
			}
			else
			{		
				if ($isOkay && ("1\n" == system("test -d " + $buff2 + " && echo 1 || echo 0"))) // GG: Irix Only
				{
					$gXBMLANGPATH[$ndx++] = $buff2;
				}
			}
		}
	}
	
	return $gXBMLANGPATH;
}

