import maya

maya.stringTable['y_igExport.kTextureNode'] = u'Texture Node'
maya.stringTable['y_igExport.kThereIsNothingToExport'] = u'There is nothing to export.'
maya.stringTable['y_igExport.kFolderPathUVExport'] = u'Folder Path'
maya.stringTable['y_igExport.kFullPathAnn'] = u'Specify the folder in which to save the maps'
maya.stringTable['y_igExport.kCancel'] = u'Cancel'
maya.stringTable['y_igExport.kBrowseForAFolder2'] = u'Browse for a folder'
maya.stringTable['y_igExport.kFolderPathPtexExport'] = u'Folder Path'
maya.stringTable['y_igExport.kRegionMap'] = u'Region Map'
maya.stringTable['y_igExport.kBrowseForAFolder3'] = u'Browse for a folder'
maya.stringTable['y_igExport.k2dTexture'] = u'2D Texture'
maya.stringTable['y_igExport.kFullPathUVExportAnn'] = u'Specify the folder in which to save the maps'
maya.stringTable['y_igExport.kIgExportUIAttrMapsFrom'] = u'Attribute maps for description <%s> exported to: %s'
maya.stringTable['y_igExport.kExport'] = u'Export'
maya.stringTable['y_igExport.kCancelAnn'] = u'Finish exporting files.'
maya.stringTable['y_igExport.kBrowseForAFolder'] = u'Browse for a folder'
maya.stringTable['y_igExport.kUvset'] = u'UVSet'
maya.stringTable['y_igExport.kTextureNodeAnn'] = u'Texture node name to export'
maya.stringTable['y_igExport.kAttributeMaps'] = u'Attribute Maps'
maya.stringTable['y_igExport.kColorSetAnn'] = u'ColorSet name to export'
maya.stringTable['y_igExport.kMethodTypeAnn'] = u'When baking the grooming information into maps, specify\nhow each texel is calculated.\n\n"Nearest (faster)" uses the closest sample value for each point,\nwhich is fast and okay for items with a high count.\n\n"Interpolate (better)" is slower but gives better results between samples.'
maya.stringTable['y_igExport.kIgExportUIRegionMapsFrom'] = u'Region maps for description <%s> exported to: %s'
maya.stringTable['y_igExport.kColorset'] = u'ColorSet'
maya.stringTable['y_igExport.kIgroomExport'] = u'Export Grooming'
maya.stringTable['y_igExport.kCopyNearest'] = u'Nearest (faster)'
maya.stringTable['y_igExport.kInstanceMethod'] = u'Sampling'
maya.stringTable['y_igExport.kMask'] = u'Mask'
maya.stringTable['y_igExport.kUvSetAnn'] = u'UV set name to export'
maya.stringTable['y_igExport.kTexelsPerUnitAnn'] = u'Number of texels per unit in world space.\nLarger values result in higher resolution (and more memory).'
maya.stringTable['y_igExport.kUvs'] = u'UVs'
maya.stringTable['y_igExport.kInterpolate'] = u'Interpolate (better)'
maya.stringTable['y_igExport.kIgExportUIMaskMapsFrom'] = u'Mask maps for description <%s> exported to: %s'
maya.stringTable['y_igExport.kColors'] = u'Colors'
maya.stringTable['y_igExport.kTexelsPerUnit'] = u'Texels Per Unit'
maya.stringTable['y_igExport.kFolderPathColorExport'] = u'Folder Path'
maya.stringTable['y_igExport.kFilePathColorExportAnn'] = u'Specify the folder in which to save the maps'

