import maya

maya.stringTable['y_xgCopyMoveDescription.kMove'] = u'Move'
maya.stringTable['y_xgCopyMoveDescription.kNewNameAnn'] = u'Specify the name of the duplicated Description'
maya.stringTable['y_xgCopyMoveDescription.kThereAreNoDescriptionsToCopy'] = u'There are no descriptions to copy.'
maya.stringTable['y_xgCopyMoveDescription.kCopyDescriptionOnlyAvailableInMaya'] = u'Copy description only available in Maya.'
maya.stringTable['y_xgCopyMoveDescription.kCancel'] = u'Cancel'
maya.stringTable['y_xgCopyMoveDescription.kMoveFrom'] = u'Move From'
maya.stringTable['y_xgCopyMoveDescription.kCancelAnn'] = u'Cancel the Move.'
maya.stringTable['y_xgCopyMoveDescription.kMoveDescriptionOnlyAvailableInMaya'] = u'Move description only available in Maya.'
maya.stringTable['y_xgCopyMoveDescription.kDuplicateDescription'] = u'Duplicate Description'
maya.stringTable['y_xgCopyMoveDescription.kDescriptionOnly'] = u'Include Patch Bindings'
maya.stringTable['y_xgCopyMoveDescription.kMoveDescription'] = u'Move Description to Collection'
maya.stringTable['y_xgCopyMoveDescription.kDuplicate'] = u'Duplicate'
maya.stringTable['y_xgCopyMoveDescription.kTo'] = u'To'
maya.stringTable['y_xgCopyMoveDescription.kIncludePatchBindingsAnn'] = u'Binds the new Description to the same faces as the original. If this is turned off, the new Description will not be bound to any faces.'
maya.stringTable['y_xgCopyMoveDescription.kFrom'] = u'From'
maya.stringTable['y_xgCopyMoveDescription.kCancelDuplicationAnn'] = u'Cancel the Duplication.'
maya.stringTable['y_xgCopyMoveDescription.kNameGivenForDescriptionAlreadyExitsInTheScene'] = u'Name given for description already exits in the scene.'
maya.stringTable['y_xgCopyMoveDescription.kYouMustSpecifyADestinationDescriptionName'] = u'You must specify a destination description name.'
maya.stringTable['y_xgCopyMoveDescription.kNewCollectionAnn'] = u'Specify which Collection the new Description should be placed into'
maya.stringTable['y_xgCopyMoveDescription.kThereAreNoDescriptionsThatCanBeMoved'] = u'There are no descriptions that can be moved.'
maya.stringTable['y_xgCopyMoveDescription.kApplyAnn'] = u'%s the Description.'
maya.stringTable['y_xgCopyMoveDescription.kYouMustSpecifyADifferentName'] = u'You must specify a different name in order to copy a  \ndescription within the same Collection.'
maya.stringTable['y_xgCopyMoveDescription.kNewNameMoveAnn'] = u'Specify the name the Description should have after it is moved'

