import maya

maya.stringTable['y_xgCreateDescription.kCreate'] = u'Create'
maya.stringTable['y_xgCreateDescription.kWhatKindOfPrimitivesAreMadeByThisDescription'] = u'What kind of Primitives are made by this Description?'
maya.stringTable['y_xgCreateDescription.kPlacingGuides'] = u'Placing and shaping Guides'
maya.stringTable['y_xgCreateDescription.kGroomThePrimitivesBy'] = u'Control the Primitives by:'
maya.stringTable['y_xgCreateDescription.kUsingGroomingTools'] = u'Using Grooming tools'
maya.stringTable['y_xgCreateDescription.kDescriptionAlreadyExistsOnDisk'] = u'Description <%s> already exists on disk:\n%s'
maya.stringTable['y_xgCreateDescription.kAtPointsYouSpecify'] = u'At points you specify'
maya.stringTable['y_xgCreateDescription.kRandomlyAcrossTheSurface'] = u'Randomly across the surface'
maya.stringTable['y_xgCreateDescription.kCreateXgenDescriptionDescriptionClash'] = u'Create Xgen Description'
maya.stringTable['y_xgCreateDescription.kOverwrite'] = u'Overwrite "%s"'
maya.stringTable['y_xgCreateDescription.kAddDescriptionToExistingCollection'] = u'Add Description to existing Collection:'
maya.stringTable['y_xgCreateDescription.kGroomingTip'] = u'Use the Grooming tools to shape the primitives'
maya.stringTable['y_xgCreateDescription.kCardsDescription'] = u'Cards (use for scales or other flat textures)'
maya.stringTable['y_xgCreateDescription.kGenerateThePrimitives'] = u'Generate the Primitives:'
maya.stringTable['y_xgCreateDescription.kSpheresDescription'] = u'Spheres (use for pebbles, marbles, or other round objects)'
maya.stringTable['y_xgCreateDescription.kNamespaceIssueError'] = u'Cannot create a description when the selected \nobjects are not part of the same namespace.'
maya.stringTable['y_xgCreateDescription.kCancel'] = u'Cancel'
maya.stringTable['y_xgCreateDescription.kCreateXgenDescription'] = u'Create XGen Description'
maya.stringTable['y_xgCreateDescription.kGroomableSplinesDescription'] = u'Groomable splines (use for short hair, fur, grass, etc)'
maya.stringTable['y_xgCreateDescription.kNewDescriptionName'] = u'New Description Name:'
maya.stringTable['y_xgCreateDescription.kSplinesDescription'] = u'Splines (use for long hair, vines, etc)'
maya.stringTable['y_xgCreateDescription.kPleaseSelectAPolygonSurfaceTip'] = u'Please select a polygon surface (or faces)\\nbefore creating a Description'
maya.stringTable['y_xgCreateDescription.kCreateInstead2'] = u'Create "%s" instead'
maya.stringTable['y_xgCreateDescription.kCreateNewCollectionNamed'] = u'Create new Collection named:'
maya.stringTable['y_xgCreateDescription.kEachDescriptionMustBeStoredInACollection'] = u'Each Description must be stored in a Collection'
maya.stringTable['y_xgCreateDescription.kCreateInstead'] = u'Create "%s" instead'
maya.stringTable['y_xgCreateDescription.kCollectionAlreadyExistsOnDisk'] = u'Collection <%s> already exists on disk:\n\n%s'
maya.stringTable['y_xgCreateDescription.kInUniformRowsAndColumns'] = u'In Uniform rows and columns'
maya.stringTable['y_xgCreateDescription.kErrorCreatingDescription'] = u'Cannot create description [%s]'
maya.stringTable['y_xgCreateDescription.kCreateXgenDescriptionOverwrite'] = u'Create Xgen Description'
maya.stringTable['y_xgCreateDescription.kCustomGeometryArchives'] = u'Custom Geometry/Archives (use for any model you have created)'
maya.stringTable['y_xgCreateDescription.kUsingAttributesControlledByExpressions'] = u'Using Attributes controlled by expressions'
maya.stringTable['y_xgCreateDescription.kCreateXgenDescriptionNamespace'] = u'Create Xgen Description'
maya.stringTable['y_xgCreateDescription.kGuideToolTip'] = u'Use the <b>Add/Move Guides</b> Tool to add guides to your surface'

