import maya

maya.stringTable['y_xgExportFile.kDescription1'] = u'Description'
maya.stringTable['y_xgExportFile.kDescription2'] = u'Description'
maya.stringTable['y_xgExportFile.kCollectionAnn2'] = u'Collection holding description to export.'
maya.stringTable['y_xgExportFile.kCollectionAnn1'] = u'Collection holding description to export.'
maya.stringTable['y_xgExportFile.kThereAreNoCollectionsToExport'] = u'There are no Collections to export.'
maya.stringTable['y_xgExportFile.kFileName1'] = u'File Name'
maya.stringTable['y_xgExportFile.kExport'] = u'Export'
maya.stringTable['y_xgExportFile.kExportAllAnn'] = u'Export all checked collections.\nEach collection exports into its own file.'
maya.stringTable['y_xgExportFile.kExportAnn1'] = u'Export the current XGen Collection'
maya.stringTable['y_xgExportFile.kExportAnn2'] = u'Export the specified\nXGen Description'
maya.stringTable['y_xgExportFile.kXgenExport'] = u'Export Collections or Descriptions'
maya.stringTable['y_xgExportFile.kExportPaletteAnn1'] = u'Export the %s Collection.'
maya.stringTable['y_xgExportFile.kYouMustSpecifyAFilename'] = u'You must specify a fileName.'
maya.stringTable['y_xgExportFile.kCollection1'] = u'Collection'
maya.stringTable['y_xgExportFile.kCollection2'] = u'Collection'
maya.stringTable['y_xgExportFile.kFilePathAnn1'] = u'Specify the full path name of the\nexported XGen Description file'
maya.stringTable['y_xgExportFile.kDescriptionAnn1'] = u'Description to export.'
maya.stringTable['y_xgExportFile.kYouMustSpecifyFilename'] = u'You must specify fileName, collection, and description.'
maya.stringTable['y_xgExportFile.kFileNameAnn'] = u'Specify the full path name of the\nexported XGen Collection file'
maya.stringTable['y_xgExportFile.kBrowseForAFileName1'] = u'Browse for a file name'
maya.stringTable['y_xgExportFile.kBrowseForAFileName2'] = u'Browse for a file name'
maya.stringTable['y_xgExportFile.kExportCollectionAnn2'] = u'Export the current\nXgen Collection'
maya.stringTable['y_xgExportFile.kDescriptionToExport'] = u'Description to export.'
maya.stringTable['y_xgExportFile.kCancelAnn'] = u'Close window\nwithout exporting'
maya.stringTable['y_xgExportFile.kCancel'] = u'Cancel'

