import maya

maya.stringTable['y_xgTubeGroom.kGuideMask'] = u'Guide Mask'
maya.stringTable['y_xgTubeGroom.kFloatUIAnn'] = u'Number of CVs per unit length. This can only reduce the CV count for a guide. (float)'
maya.stringTable['y_xgTubeGroom.kSpacingAnn2'] = u'Test the spacing setting.'
maya.stringTable['y_xgTubeGroom.kTubeGroomTestGuides'] = u' {0:d} guides'
maya.stringTable['y_xgTubeGroom.kTexelsPerUnit'] = u'Texels Per Unit'
maya.stringTable['y_xgTubeGroom.kTubesAnn'] = u'List of space separated tube names.'
maya.stringTable['y_xgTubeGroom.kTubes'] = u'Tubes'
maya.stringTable['y_xgTubeGroom.kCancelAnn'] = u'Cancel the tube groom.'
maya.stringTable['y_xgTubeGroom.kSpacingAnnxs'] = u'Amount of spacing between guides.'
maya.stringTable['y_xgTubeGroom.kTexelsPerUnitAnn'] = u'Number of texels per unit in world space. Larger values result in higher resolution (and more memory). (float: [0, 10000])'
maya.stringTable['y_xgTubeGroom.kTubeBasedGrooming'] = u'Tube Based Grooming'
maya.stringTable['y_xgTubeGroom.kCancel'] = u'Cancel'
maya.stringTable['y_xgTubeGroom.kMemorySizeInMb'] = u'Memory size in MB.'
maya.stringTable['y_xgTubeGroom.kGuideMaskAnn'] = u'Mask for damping down creation of guides. (expression: [0,1])'
maya.stringTable['y_xgTubeGroom.kTest1'] = u'Test'
maya.stringTable['y_xgTubeGroom.kCvFrequency'] = u'CV Frequency'
maya.stringTable['y_xgTubeGroom.kCutParamAnn'] = u'Param for how much of each guide to cut off where one results in the same length as the minimum length guide. (expression: [0,1])'
maya.stringTable['y_xgTubeGroom.kGuideSpacing'] = u'Guide Spacing'
maya.stringTable['y_xgTubeGroom.kGenerateAnn'] = u'Generate guides and maps.'
maya.stringTable['y_xgTubeGroom.kTestAnn'] = u'Test the tpu setting.'
maya.stringTable['y_xgTubeGroom.kGuideNumberAnn'] = u'Number of guides to be created.'
maya.stringTable['y_xgTubeGroom.kTest2'] = u'Test'
maya.stringTable['y_xgTubeGroom.kMb'] = u' 0 MB'
maya.stringTable['y_xgTubeGroom.kCutParam'] = u'Cut Param'
maya.stringTable['y_xgTubeGroom.kTubeGroomProgressGeneratingRegionMaps'] = u'Generating region maps for a tube groom.'
maya.stringTable['y_xgTubeGroom.kGenerate'] = u'Generate'
maya.stringTable['y_xgTubeGroom.kUnkownGuides'] = u' ?? guides'

