#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Makes sierpinski pattern from a polyPyramid in Maya
"""

import pymel.core as pm


def main():
	pyPyramid = pm.PyNode("pPyramid1")
	pyPyramidShape = pyPyramid.getShape()
	polyPyra = pyPyramidShape.listConnections()[1]
	polyPyra.setNumberOfSides(3)
	
	pyPyramidPnts = pyPyramidShape.getPoints()
	for pnt in pyPyramidPnts:
		loc = pm.spaceLocator()
		loc.translate.set(pnt + pyPyramid.translate.get())
# end main


if __name__ == "__main__":
	main()