# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/selecaotwo/Dropbox/Private/my_PROJECT/proj_POP2/Pipeline/the_LATEST/sys_PY/py_MODULES/hdrprocess/view/mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

try:
    import PyQt.QtCore as QtCore
    import PyQt.QtGui as QtGui
except ImportError:
    import PySide.QtCore as QtCore
    import PySide.QtGui as QtGui
except:
    raise

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1148, 890)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 8, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.colorBalancing_cb = QtGui.QCheckBox(self.centralwidget)
        self.colorBalancing_cb.setObjectName(_fromUtf8("colorBalancing_cb"))
        self.gridLayout.addWidget(self.colorBalancing_cb, 20, 1, 1, 1)
        self.title_hl = QtGui.QHBoxLayout()
        self.title_hl.setObjectName(_fromUtf8("title_hl"))
        self.title_l = QtGui.QLabel(self.centralwidget)
        self.title_l.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(18)
        self.title_l.setFont(font)
        self.title_l.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.title_l.setObjectName(_fromUtf8("title_l"))
        self.title_hl.addWidget(self.title_l)
        self.version_l = QtGui.QLabel(self.centralwidget)
        self.version_l.setMaximumSize(QtCore.QSize(16777215, 40))
        self.version_l.setStyleSheet(_fromUtf8("margin-bottom: 2px;"))
        self.version_l.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.version_l.setObjectName(_fromUtf8("version_l"))
        self.title_hl.addWidget(self.version_l)
        self.gridLayout.addLayout(self.title_hl, 0, 0, 1, 1)
        self.curveInput_hl = QtGui.QHBoxLayout()
        self.curveInput_hl.setObjectName(_fromUtf8("curveInput_hl"))
        self.curveInput_l = QtGui.QLabel(self.centralwidget)
        self.curveInput_l.setMaximumSize(QtCore.QSize(90, 16777215))
        self.curveInput_l.setObjectName(_fromUtf8("curveInput_l"))
        self.curveInput_hl.addWidget(self.curveInput_l)
        self.curveInput_cb = QtGui.QComboBox(self.centralwidget)
        self.curveInput_cb.setObjectName(_fromUtf8("curveInput_cb"))
        self.curveInput_hl.addWidget(self.curveInput_cb)
        self.curveInput_tb = QtGui.QToolButton(self.centralwidget)
        self.curveInput_tb.setObjectName(_fromUtf8("curveInput_tb"))
        self.curveInput_hl.addWidget(self.curveInput_tb)
        self.gridLayout.addLayout(self.curveInput_hl, 9, 0, 1, 2)
        self.generalSettings_l = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.generalSettings_l.setFont(font)
        self.generalSettings_l.setObjectName(_fromUtf8("generalSettings_l"))
        self.gridLayout.addWidget(self.generalSettings_l, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 23, 0, 1, 2)
        self.ghostRemoval_cb = QtGui.QCheckBox(self.centralwidget)
        self.ghostRemoval_cb.setObjectName(_fromUtf8("ghostRemoval_cb"))
        self.gridLayout.addWidget(self.ghostRemoval_cb, 19, 1, 1, 1)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 18, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.outputType_hl = QtGui.QHBoxLayout()
        self.outputType_hl.setObjectName(_fromUtf8("outputType_hl"))
        self.outputType_l = QtGui.QLabel(self.centralwidget)
        self.outputType_l.setObjectName(_fromUtf8("outputType_l"))
        self.outputType_hl.addWidget(self.outputType_l)
        self.outputType_le = QtGui.QLineEdit(self.centralwidget)
        self.outputType_le.setMaximumSize(QtCore.QSize(70, 16777215))
        self.outputType_le.setObjectName(_fromUtf8("outputType_le"))
        self.outputType_hl.addWidget(self.outputType_le)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.outputType_hl.addItem(spacerItem3)
        self.gridLayout.addLayout(self.outputType_hl, 5, 0, 1, 1)
        self.threads_hl = QtGui.QHBoxLayout()
        self.threads_hl.setObjectName(_fromUtf8("threads_hl"))
        self.threads_l = QtGui.QLabel(self.centralwidget)
        self.threads_l.setObjectName(_fromUtf8("threads_l"))
        self.threads_hl.addWidget(self.threads_l)
        self.threads_sb = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threads_sb.sizePolicy().hasHeightForWidth())
        self.threads_sb.setSizePolicy(sizePolicy)
        self.threads_sb.setMaximumSize(QtCore.QSize(50, 16777215))
        self.threads_sb.setObjectName(_fromUtf8("threads_sb"))
        self.threads_hl.addWidget(self.threads_sb)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.threads_hl.addItem(spacerItem4)
        self.gridLayout.addLayout(self.threads_hl, 4, 0, 1, 1)
        self.seqInterval_hl = QtGui.QHBoxLayout()
        self.seqInterval_hl.setObjectName(_fromUtf8("seqInterval_hl"))
        self.seqInterval_l = QtGui.QLabel(self.centralwidget)
        self.seqInterval_l.setObjectName(_fromUtf8("seqInterval_l"))
        self.seqInterval_hl.addWidget(self.seqInterval_l)
        self.seqInterval_sb = QtGui.QSpinBox(self.centralwidget)
        self.seqInterval_sb.setMaximumSize(QtCore.QSize(60, 16777215))
        self.seqInterval_sb.setProperty("value", 0)
        self.seqInterval_sb.setObjectName(_fromUtf8("seqInterval_sb"))
        self.seqInterval_hl.addWidget(self.seqInterval_sb)
        self.automaticSeq_cb = QtGui.QCheckBox(self.centralwidget)
        self.automaticSeq_cb.setObjectName(_fromUtf8("automaticSeq_cb"))
        self.seqInterval_hl.addWidget(self.automaticSeq_cb)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.seqInterval_hl.addItem(spacerItem5)
        self.gridLayout.addLayout(self.seqInterval_hl, 15, 0, 1, 2)
        self.outputLogger_l = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.outputLogger_l.setFont(font)
        self.outputLogger_l.setObjectName(_fromUtf8("outputLogger_l"))
        self.gridLayout.addWidget(self.outputLogger_l, 0, 5, 1, 1)
        self.outputLogger_pb = QtGui.QProgressBar(self.centralwidget)
        self.outputLogger_pb.setProperty("value", 24)
        self.outputLogger_pb.setObjectName(_fromUtf8("outputLogger_pb"))
        self.gridLayout.addWidget(self.outputLogger_pb, 0, 6, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 16, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 6, 0, 1, 1)
        self.shottingSettings_l = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.shottingSettings_l.setFont(font)
        self.shottingSettings_l.setObjectName(_fromUtf8("shottingSettings_l"))
        self.gridLayout.addWidget(self.shottingSettings_l, 12, 0, 1, 1)
        self.mergeSettings_l = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mergeSettings_l.setFont(font)
        self.mergeSettings_l.setObjectName(_fromUtf8("mergeSettings_l"))
        self.gridLayout.addWidget(self.mergeSettings_l, 17, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 28, 6, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(21, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 29, 0, 1, 7)
        self.curveSettings_l = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.curveSettings_l.setFont(font)
        self.curveSettings_l.setObjectName(_fromUtf8("curveSettings_l"))
        self.gridLayout.addWidget(self.curveSettings_l, 7, 0, 1, 1)
        self.miscSettings_l = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.miscSettings_l.setFont(font)
        self.miscSettings_l.setObjectName(_fromUtf8("miscSettings_l"))
        self.gridLayout.addWidget(self.miscSettings_l, 22, 0, 1, 1)
        self.exposureCorrection_cb = QtGui.QCheckBox(self.centralwidget)
        self.exposureCorrection_cb.setObjectName(_fromUtf8("exposureCorrection_cb"))
        self.gridLayout.addWidget(self.exposureCorrection_cb, 20, 0, 1, 1)
        self.use32bitIEE_cb = QtGui.QCheckBox(self.centralwidget)
        self.use32bitIEE_cb.setChecked(False)
        self.use32bitIEE_cb.setObjectName(_fromUtf8("use32bitIEE_cb"))
        self.gridLayout.addWidget(self.use32bitIEE_cb, 24, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 13, 0, 1, 2)
        self.estimateCurve_cb = QtGui.QCheckBox(self.centralwidget)
        self.estimateCurve_cb.setObjectName(_fromUtf8("estimateCurve_cb"))
        self.gridLayout.addWidget(self.estimateCurve_cb, 10, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 2)
        self.imageAlignment_cb = QtGui.QCheckBox(self.centralwidget)
        self.imageAlignment_cb.setObjectName(_fromUtf8("imageAlignment_cb"))
        self.gridLayout.addWidget(self.imageAlignment_cb, 19, 0, 1, 1)
        self.okCancel_bb = QtGui.QDialogButtonBox(self.centralwidget)
        self.okCancel_bb.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.okCancel_bb.setObjectName(_fromUtf8("okCancel_bb"))
        self.gridLayout.addWidget(self.okCancel_bb, 31, 6, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem10, 30, 6, 1, 1)
        self.autoRenameFiles_cb = QtGui.QCheckBox(self.centralwidget)
        self.autoRenameFiles_cb.setObjectName(_fromUtf8("autoRenameFiles_cb"))
        self.gridLayout.addWidget(self.autoRenameFiles_cb, 5, 1, 1, 1)
        self.defaultCurve_cb = QtGui.QCheckBox(self.centralwidget)
        self.defaultCurve_cb.setObjectName(_fromUtf8("defaultCurve_cb"))
        self.gridLayout.addWidget(self.defaultCurve_cb, 10, 0, 1, 1)
        self.outputLogger_te = QtGui.QTextEdit(self.centralwidget)
        self.outputLogger_te.setMinimumSize(QtCore.QSize(530, 0))
        self.outputLogger_te.setStyleSheet(_fromUtf8("background-color: #cccccc;"))
        self.outputLogger_te.setObjectName(_fromUtf8("outputLogger_te"))
        self.gridLayout.addWidget(self.outputLogger_te, 1, 5, 27, 2)
        self.ignoreMissingExposures_cb = QtGui.QCheckBox(self.centralwidget)
        self.ignoreMissingExposures_cb.setObjectName(_fromUtf8("ignoreMissingExposures_cb"))
        self.gridLayout.addWidget(self.ignoreMissingExposures_cb, 24, 0, 1, 1)
        self.recursiveSearch_cb = QtGui.QCheckBox(self.centralwidget)
        self.recursiveSearch_cb.setObjectName(_fromUtf8("recursiveSearch_cb"))
        self.gridLayout.addWidget(self.recursiveSearch_cb, 4, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem11, 21, 0, 1, 1)
        self.fnum_hl = QtGui.QHBoxLayout()
        self.fnum_hl.setObjectName(_fromUtf8("fnum_hl"))
        self.fnum_l = QtGui.QLabel(self.centralwidget)
        self.fnum_l.setObjectName(_fromUtf8("fnum_l"))
        self.fnum_hl.addWidget(self.fnum_l)
        self.fnum_sw = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fnum_sw.sizePolicy().hasHeightForWidth())
        self.fnum_sw.setSizePolicy(sizePolicy)
        self.fnum_sw.setMaximumSize(QtCore.QSize(80, 16777215))
        self.fnum_sw.setObjectName(_fromUtf8("fnum_sw"))
        self.fnum_cb_p = QtGui.QWidget()
        self.fnum_cb_p.setObjectName(_fromUtf8("fnum_cb_p"))
        self.gridLayout_3 = QtGui.QGridLayout(self.fnum_cb_p)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fnum_cb = QtGui.QComboBox(self.fnum_cb_p)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fnum_cb.sizePolicy().hasHeightForWidth())
        self.fnum_cb.setSizePolicy(sizePolicy)
        self.fnum_cb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fnum_cb.setObjectName(_fromUtf8("fnum_cb"))
        self.gridLayout_3.addWidget(self.fnum_cb, 0, 0, 1, 1)
        self.fnum_sw.addWidget(self.fnum_cb_p)
        self.fnum_le_p = QtGui.QWidget()
        self.fnum_le_p.setObjectName(_fromUtf8("fnum_le_p"))
        self.gridLayout_2 = QtGui.QGridLayout(self.fnum_le_p)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.fnum_le = QtGui.QLineEdit(self.fnum_le_p)
        self.fnum_le.setObjectName(_fromUtf8("fnum_le"))
        self.gridLayout_2.addWidget(self.fnum_le, 0, 0, 1, 1)
        self.fnum_sw.addWidget(self.fnum_le_p)
        self.fnum_hl.addWidget(self.fnum_sw)
        self.manual_fnum_cb = QtGui.QCheckBox(self.centralwidget)
        self.manual_fnum_cb.setObjectName(_fromUtf8("manual_fnum_cb"))
        self.fnum_hl.addWidget(self.manual_fnum_cb)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.fnum_hl.addItem(spacerItem12)
        self.gridLayout.addLayout(self.fnum_hl, 14, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1148, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.fnum_sw.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.colorBalancing_cb.setText(_translate("MainWindow", "Color Balancing", None))
        self.title_l.setText(_translate("MainWindow", "HDR Batch Processor", None))
        self.version_l.setText(_translate("MainWindow", "v 1.2.0", None))
        self.curveInput_l.setText(_translate("MainWindow", "Curve Input", None))
        self.curveInput_tb.setText(_translate("MainWindow", "...", None))
        self.generalSettings_l.setText(_translate("MainWindow", "General", None))
        self.ghostRemoval_cb.setText(_translate("MainWindow", "Ghost Removal", None))
        self.outputType_l.setText(_translate("MainWindow", "Output Type", None))
        self.threads_l.setText(_translate("MainWindow", "Number of Threads", None))
        self.seqInterval_l.setText(_translate("MainWindow", "Sequence Interval", None))
        self.automaticSeq_cb.setText(_translate("MainWindow", "Automatic", None))
        self.outputLogger_l.setText(_translate("MainWindow", "Output Logger", None))
        self.shottingSettings_l.setText(_translate("MainWindow", "Shooting Settings", None))
        self.mergeSettings_l.setText(_translate("MainWindow", "Merge Settings", None))
        self.curveSettings_l.setText(_translate("MainWindow", "Curve Settings", None))
        self.miscSettings_l.setText(_translate("MainWindow", "Misc Settings", None))
        self.exposureCorrection_cb.setText(_translate("MainWindow", "Exposure Correction", None))
        self.use32bitIEE_cb.setText(_translate("MainWindow", "Use 32-bit-float IEEE for TIFFs", None))
        self.estimateCurve_cb.setText(_translate("MainWindow", "Estimate Curve only", None))
        self.imageAlignment_cb.setText(_translate("MainWindow", "Image Alignment", None))
        self.autoRenameFiles_cb.setText(_translate("MainWindow", "auto-rename files", None))
        self.defaultCurve_cb.setText(_translate("MainWindow", "Default Curve", None))
        self.outputLogger_te.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.ignoreMissingExposures_cb.setText(_translate("MainWindow", "Ignore Missing Exposure Values", None))
        self.recursiveSearch_cb.setText(_translate("MainWindow", "recursive search", None))
        self.fnum_l.setText(_translate("MainWindow", "F-Number", None))
        self.manual_fnum_cb.setText(_translate("MainWindow", "Manual", None))

