// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

// Apply this preset to the selected fluid
// 
applyFluidDiskCache( "$MAYA_LOCATION/presets/fluids/.mayaData/cloud3D.mcfi",
	0,		// createFluidShape
	60,		// x resolution
	30,		// y resolution
	30,		// z resolution
	0,		// is fluid 2d?
	1,		// has density
	0,		// has velocity
	0,		// has temperature
	0,		// has fuel
	0,		// has color
	0,		// has texture coordinates
	0 );	// has falloff
string $selectedCacheNodes[] = `ls -sl -type diskCache`;
if(size ($selectedCacheNodes) == 1) {
	// if this apply worked, a cache node will be selected
	// and we can apply notes to that node
	string $cacheNode = $selectedCacheNodes[0];
	string $objAttr = ($cacheNode + ".notes");
	if(!objExists( $objAttr )) {
		if( catch(`addAttr -dt "string" -ln "notes" -sn "nts"  $cacheNode`)) {
			Warning(" Could not add Notes to the initial state node.");
		}
	}
	if(objExists( $objAttr )) {
		setAttr -type "string" $objAttr "For best results with this cache, use Self Shadowing set to about 0.2, and make the opacity graph rise quickly from the left to the right. This will emphasize the less dense areas and give you a fuller looking cloud.";
	}
}
