import maya

maya.stringTable['y_xgNoiseFXModuleTab.kFrequency'] = u'Frequency'
maya.stringTable['y_xgNoiseFXModuleTab.kCorrelation'] = u'Correlation'
maya.stringTable['y_xgNoiseFXModuleTab.kFrequencyAnn'] = u'Frequency of the noise, i.e. cyles per unit length of primitive. (expression)'
maya.stringTable['y_xgNoiseFXModuleTab.kPreserveLength'] = u'Preserve Length'
maya.stringTable['y_xgNoiseFXModuleTab.kMagnitude'] = u'Magnitude'
maya.stringTable['y_xgNoiseFXModuleTab.kMode'] = u'Mode'
maya.stringTable['y_xgNoiseFXModuleTab.kBaked'] = u'Baked'
maya.stringTable['y_xgNoiseFXModuleTab.kBakeDirAnn'] = u'Directory for the baked noise file.'
maya.stringTable['y_xgNoiseFXModuleTab.kMagnitudeScaleAnn'] = u'The amount to scale the magnitude by at each point along the curve.'
maya.stringTable['y_xgNoiseFXModuleTab.kBakeOptions'] = u'Bake Options'
maya.stringTable['y_xgNoiseFXModuleTab.kBakeNoiseData'] = u'Bake Noise Data'
maya.stringTable['y_xgNoiseFXModuleTab.kCorrelationAnn'] = u'The amount noise should correlate across surface. (expression)'
maya.stringTable['y_xgNoiseFXModuleTab.kMagnitudeScale'] = u'Magnitude Scale'
maya.stringTable['y_xgNoiseFXModuleTab.kBakeDir'] = u'Bake Dir'
maya.stringTable['y_xgNoiseFXModuleTab.kMagnitudeAnn'] = u'Amount of the noise effect to apply to  the primitives. ($t expression: [0, 1])'
maya.stringTable['y_xgNoiseFXModuleTab.kLive'] = u'Live'
maya.stringTable['y_xgNoiseFXModuleTab.kNoiseModifier'] = u'Noise Modifier'
maya.stringTable['y_xgNoiseFXModuleTab.kBakingProgress'] = u'Baking primitive noise offsets into XPD files.'
maya.stringTable['y_xgNoiseFXModuleTab.kModeAnn'] = u'Whether to apply noise to the primitives live or to read the noise data from the bake file.'
maya.stringTable['y_xgNoiseFXModuleTab.kPreserveLengthAnn'] = u'The percentage of the blend of modified length to the original groomed length. (expression: [0, 100])'

