// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Clear Initial State" m_shelf_Fluids.kClearInitialState;
displayString -replace -value "Create Cache" m_shelf_Fluids.kCreateCache;
displayString -replace -value "Delete Cache" m_shelf_Fluids.kDeleteCache;
displayString -replace -value "Edit Fluid Resolution" m_shelf_Fluids.kEditFluidResolution;
displayString -replace -value "Emit Fluid from Object" m_shelf_Fluids.kEmitFluidFromObject;
displayString -replace -value "Extend Fluid Resolution" m_shelf_Fluids.kExtendFluidResolution;
displayString -replace -value "2D Fluid Container" m_shelf_Fluids.kFluidContainer2D;
displayString -replace -value "3D Fluid Container" m_shelf_Fluids.kFluidContainer3D;
displayString -replace -value "2D Fluid Container with Emitter" m_shelf_Fluids.kFluidContainerWithEmitter2D;
displayString -replace -value "3D Fluid Container with Emitter" m_shelf_Fluids.kFluidContainerWithEmitter3D;
displayString -replace -value "Fluid Emitter" m_shelf_Fluids.kFluidEmitter;
displayString -replace -value "Make Collide" m_shelf_Fluids.kMakeCollide;
displayString -replace -value "Ocean Material" m_shelf_Fluids.kOceanMaterial;
displayString -replace -value "Ocean Material: Assign a new ocean material to the active objects" m_shelf_Fluids.kOceanMaterialAnnot;
displayString -replace -value "Paint Fluids Tool" m_shelf_Fluids.kPaintFluidsTool;
displayString -replace -value "Set Initial State" m_shelf_Fluids.kSetInitialState;
