// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc shelf_NCloth () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("nClothCreate"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kCreateNcloth"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothCreate.png" 
        -image1 "nClothCreate.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNCloth 0" 
        -sourceType "mel" 
        -doubleClickCommand "nClothCreateOptions" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("nClothMakeCollide"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kCreatePassive"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothCreatePassive.png" 
        -image1 "nClothCreatePassive.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "makeCollideNCloth" 
        -sourceType "mel" 
        -doubleClickCommand "nClothMakeCollideOptions" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("nClothRemove"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kRemoveNcloth"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothRemove.png" 
        -image1 "nClothRemove.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "removeNCloth \"selected\"" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation  (uiRes("m_shelf_NCloth.kDisplayInputMesh"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kInputMesh"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothDisplayInput.png" 
        -image1 "nClothDisplayInput.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "displayNClothMesh \"input\"" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kDisplayCurrentMesh"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kCurrentMesh"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothDisplayCurrent.png" 
        -image1 "nClothDisplayCurrent.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "displayNClothMesh \"current\"" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("InteractivePlayback")) 
        -align "center" 
        -label  (uiRes("m_shelf_NCloth.kInteractivePlayback"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "interactivePlayback.png" 
        -image1 "interactivePlayback.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "InteractivePlayback" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kThicknessMapAnnot")) 
        -align "center" 
        -label  (uiRes("m_shelf_NCloth.kThicknessMap"))
        -labelOffset 0
        -font "tinyBoldLabelFont"
        -image "nClothPaintMapThickness.png" 
        -image1 "nClothPaintMapThickness.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "setNClothMapType(\"thickness\",\"\",1); artAttrNClothToolScript 3 thickness" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kTransformAnnot"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kTransform"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintTransform.png" 
        -image1 "nConstraintTransform.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNConstraint transform 0" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kComponentToComponentAnnot")) 
        -align "center" 
        -label  (uiRes("m_shelf_NCloth.kComponentToComponent"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintComponent.png" 
        -image1 "nConstraintComponent.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNConstraint pointToPoint 0" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kPointToSurfaceAnnot")) 
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kPointToSurface"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintPointoSurface.png" 
        -image1 "nConstraintPointoSurface.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNConstraint pointToSurface 0" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kSlideOnSurfaceAnnot"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kSlideOnSurface"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintSlideonSurface.png" 
        -image1 "nConstraintSlideonSurface.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNConstraint slideOnSurface 0" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kWeldBordersAnnot"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kWeldBorders")) 
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintWeldBorders.png" 
        -image1 "nConstraintWeldBorders.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNConstraint weldBorders 0" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kTearableSurfaceAnnot"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kTearableSurface"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintTearable.png" 
        -image1 "nConstraintTearable.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNConstraint tearableSurface 0" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kCollisionExclusionAnnot"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kCollisionExclusion"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintExcludeCollision.png" 
        -image1 "nConstraintExcludeCollision.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNConstraint collisionExclusion 0" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kDisableCollisionAnnot"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kDisableCollision"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintDisableCollision.png" 
        -image1 "nConstraintDisableCollision.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNConstraint disableCollision 0" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("dynamicConstraintRemove"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kRemoveDynamicConstraint"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nConstraintRemove.png" 
        -image1 "nConstraintRemove.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "removeDynamicConstraint \"selected\"" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (uiRes("m_shelf_NCloth.kStrengthMapAnnot"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kStrengthMap"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothPaintMapStrength.png" 
        -image1 "nClothPaintMapStrength.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "setNComponentMapType(\"strength\",1); artAttrNComponentToolScript 3 strength"
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("nClothCache"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kCreateCache"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothCacheCreate.png" 
        -image1 "nClothCacheCreate.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNclothCache 4 { \"2\", \"1\", \"10\", \"OneFilePerFrame\", \"1\", \"\",\"1\",\"\",\"0\", \"0\", \"0\", \"1\", \"1\",\"0\",\"1\" } " 
        -sourceType "mel" 
    ;
   shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("deleteNclothCache"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kDeleteCache"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothCacheDelete.png" 
        -image1 "nClothCacheDelete.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "deleteNclothCache" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kDisableAllCache"))
	-annotation (uiRes("m_shelf_NCloth.kDisableAllCacheAnnot"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothCacheDisable.png" 
        -image1 "nClothCacheDisable.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "setCacheEnable 0 0 {}" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kEnableAllCache"))
	-annotation (uiRes("m_shelf_NCloth.kEnableAllCacheAnnot"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothCacheEnable.png" 
        -image1 "nClothCacheEnable.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "setCacheEnable 1 0 {}" 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("nClothMergeCache"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kMergeCache"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothCacheMerge.png" 
        -image1 "nClothCacheMerge.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doCreateNclothCache 4 { \"2\", \"1\", \"10\", \"OneFilePerFrame\", \"1\", \"\",\"1\",\"\",\"0\", \"merge\", \"0\", \"1\", \"1\",\"0\",\"1\" } " 
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("nClothReplaceFrames"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kReplaceCacheFrames"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "nClothCacheReplaceFrames.png" 
        -image1 "nClothCacheReplaceFrames.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "doReplaceNclothCacheFrames 1 1 10 0 1 0 0 \"linear\" \"linear\" \"\" 1 1 0"
        -sourceType "mel" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation (getRunTimeCommandAnnotation("PaintCacheTool"))
        -align "center" 
        -label (uiRes("m_shelf_NCloth.kPaintCache"))
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -image "paintCacheWeights.png" 
        -image1 "paintCacheWeights.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "PaintCacheToolOptions" 
        -sourceType "mel" 
    ;

} 
