// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc string shelf_Sculpting() 
{
    string $label;
    string $annot;

    $label = (uiRes("m_shelf_Sculpting.kSculptTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshSculptTool")`
		-image1     "Sculpt.png"
		-command    ("SetMeshSculptTool")
		-doubleClickCommand ("ShowMeshSculptToolOptions")
		meshSculptBtn ;

    $label = (uiRes("m_shelf_Sculpting.kSmoothTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshSmoothTool")`
		-image1     "Smooth.png"
		-command    ("SetMeshSmoothTool")
		-doubleClickCommand ("ShowMeshSmoothToolOptions")
		meshSmoothBtn ;

    $label = (uiRes("m_shelf_Sculpting.kRelaxTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshRelaxTool")`
		-image1     "Relax.png"
		-command    ("SetMeshRelaxTool")
		-doubleClickCommand ("ShowMeshRelaxToolOptions")
		meshRelaxBtn ;

    $label = (uiRes("m_shelf_Sculpting.kGrabTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshGrabTool")`
		-image1     "Grab.png"
		-command    ("SetMeshGrabTool")
		-doubleClickCommand ("ShowMeshGrabToolOptions")
		meshGrabBtn ;

    $label = (uiRes("m_shelf_Sculpting.kPinchTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshPinchTool")`
		-image1     "Pinch.png"
		-command    ("SetMeshPinchTool")
		-doubleClickCommand ("ShowMeshPinchToolOptions")
		meshPinchBtn ;

    $label = (uiRes("m_shelf_Sculpting.kFlattenTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshFlattenTool")`
		-image1     "Flatten.png"
		-command    ("SetMeshFlattenTool")
		-doubleClickCommand ("ShowMeshFlattenToolOptions")
		meshFlattenBtn ;

	$label = (uiRes("m_shelf_Sculpting.kFoamyTool"));
	shelfButton
        -label      $label
        -annotation `getRunTimeCommandAnnotation("SetMeshFoamyTool")`
        -image1     "Foamy.png"
        -command    ("SetMeshFoamyTool")
		-doubleClickCommand ("ShowMeshFoamyToolOptions")
		meshFoamyBtn ;

	$label = (uiRes("m_shelf_Sculpting.kSprayTool"));
	shelfButton
        -label      $label
        -annotation `getRunTimeCommandAnnotation("SetMeshSprayTool")`
        -image1     "Spray.png"
       -command    ("SetMeshSprayTool")
		-doubleClickCommand ("ShowMeshSprayToolOptions")
		meshSprayBtn ;

	$label = (uiRes("m_shelf_Sculpting.kRepeatTool"));
	shelfButton
        -label      $label
        -annotation `getRunTimeCommandAnnotation("SetMeshRepeatTool")`
        -image1     "Repeat.png"
        -command    ("SetMeshRepeatTool")
		-doubleClickCommand ("ShowMeshRepeatToolOptions")
		meshRepeatBtn ;

	$label = (uiRes("m_shelf_Sculpting.kImprintTool"));
	shelfButton
        -label      $label
        -annotation `getRunTimeCommandAnnotation("SetMeshImprintTool")`
        -image1     "Imprint.png"
        -command    ("SetMeshImprintTool")
		-doubleClickCommand ("ShowMeshImprintToolOptions")
		meshImprintBtn ;

    $label = (uiRes("m_shelf_Sculpting.kWaxTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshWaxTool")`
		-image1     "Wax.png"
		-command    ("SetMeshWaxTool")
		-doubleClickCommand ("ShowMeshWaxToolOptions")
		meshWaxBtn ;

    $label = (uiRes("m_shelf_Sculpting.kScrapeTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshScrapeTool")`
		-image1     "Scrape.png"
		-command    ("SetMeshScrapeTool")
		-doubleClickCommand ("ShowMeshScrapeToolOptions")
		meshScrapeBtn ;

    $label = (uiRes("m_shelf_Sculpting.kFillTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshFillTool")`
		-image1     "Fill.png"
		-command    ("SetMeshFillTool")
		-doubleClickCommand ("ShowMeshFillToolOptions")
		meshFillBtn ;

	$label = (uiRes("m_shelf_Sculpting.kKnifeTool"));
	shelfButton
        -label      $label
        -annotation `getRunTimeCommandAnnotation("SetMeshKnifeTool")`
        -image1     "Knife.png"
        -command    ("SetMeshKnifeTool")
		-doubleClickCommand ("ShowMeshKnifeToolOptions")
		meshKnifeBtn ;

    $label = (uiRes("m_shelf_Sculpting.kSmearTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshSmearTool")`
		-image1     "Smear.png"
		-command    ("SetMeshSmearTool")
		-doubleClickCommand ("ShowMeshSmearToolOptions")
		meshSmearBtn ;

    $label = (uiRes("m_shelf_Sculpting.kBulgeTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshBulgeTool")`
		-image1     "Bulge.png"
		-command    ("SetMeshBulgeTool")
		-doubleClickCommand ("ShowMeshBulgeToolOptions")
		meshBulgeBtn ;

    $label = (uiRes("m_shelf_Sculpting.kAmplifyTool"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("SetMeshAmplifyTool")`
		-image1     "Amplify.png"
		-command    ("SetMeshAmplifyTool")
		-doubleClickCommand ("ShowMeshAmplifyToolOptions")
		meshAmplifyBtn ;

    $label = (uiRes("m_shelf_Sculpting.kFreezeTool"));
	shelfButton
        -label      $label
        -annotation `getRunTimeCommandAnnotation("SetMeshFreezeTool")`
        -image1     "Freeze.png"
        -command    ("SetMeshFreezeTool")
		-doubleClickCommand ("ShowMeshFreezeToolOptions")
		meshFreezeBtn ;

    addShelfSeparator();

    $label = (uiRes("m_shelf_Sculpting.kConvertToFrozen"));
	$annot = (uiRes("m_shelf_Sculpting.kConvertToFrozenAnnot"));
	shelfButton
		-label				$label
		-annotation			$annot
		-image1				"freezeSelected.png"
		-command			("ConvertToFrozen");

    $label = (uiRes("m_shelf_Sculpting.kOpenVisorForMeshes"));
	shelfButton
		-label      $label
		-annotation `getRunTimeCommandAnnotation("OpenVisorForMeshes")`
		-image1     "Objects.png"
		-command    ("OpenVisorForMeshes");

    $label = (uiRes("m_shelf_Sculpting.kCreateBlendShape"));
	$annot = (uiRes("m_shelf_Sculpting.kCreateBlendShapeAnnot"));
	shelfButton
		-label      $label
		-annotation $annot
		-image1     "blendShape.png"
		-command    ("CreateBlendShape");

    $label = (uiRes("m_shelf_Sculpting.kOpenBlendShapeEditor"));
	$annot = (uiRes("m_shelf_Sculpting.kOpenBlendShapeEditorAnnot"));
	shelfButton
		-label				$label
		-annotation			$annot
		-image1				"blendShapeEditor.png"
		-command			("BlendShapeEditor")
		-doubleClickCommand ("CreateBlendShapeOptions");

	// This shelf was introduced in Maya 2016
	return "2016";
} 
