// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Amplify Tool" m_shelf_Sculpting.kAmplifyTool;
displayString -replace -value "Bulge Tool" m_shelf_Sculpting.kBulgeTool;
displayString -replace -value "Convert To Frozen" m_shelf_Sculpting.kConvertToFrozen;
displayString -replace -value "Convert To Frozen" m_shelf_Sculpting.kConvertToFrozenAnnot;
displayString -replace -value "Blend Shape" m_shelf_Sculpting.kCreateBlendShape;
displayString -replace -value "Blend Shape: Create a blend shape node for the selected object(s)." m_shelf_Sculpting.kCreateBlendShapeAnnot;
displayString -replace -value "Fill Tool" m_shelf_Sculpting.kFillTool;
displayString -replace -value "Flatten Tool" m_shelf_Sculpting.kFlattenTool;
displayString -replace -value "Foamy Tool" m_shelf_Sculpting.kFoamyTool;
displayString -replace -value "Freeze Tool" m_shelf_Sculpting.kFreezeTool;
displayString -replace -value "Grab Tool" m_shelf_Sculpting.kGrabTool;
displayString -replace -value "Imprint Tool" m_shelf_Sculpting.kImprintTool;
displayString -replace -value "Knife Tool" m_shelf_Sculpting.kKnifeTool;
displayString -replace -value "Blend Shape Editor" m_shelf_Sculpting.kOpenBlendShapeEditor;
displayString -replace -value "Blend Shape Editor: Adjust Blend Shape weights" m_shelf_Sculpting.kOpenBlendShapeEditorAnnot;
displayString -replace -value "Base Meshes" m_shelf_Sculpting.kOpenVisorForMeshes;
displayString -replace -value "Pinch Tool" m_shelf_Sculpting.kPinchTool;
displayString -replace -value "Relax Tool" m_shelf_Sculpting.kRelaxTool;
displayString -replace -value "Repeat Tool" m_shelf_Sculpting.kRepeatTool;
displayString -replace -value "Scrape Tool" m_shelf_Sculpting.kScrapeTool;
displayString -replace -value "Sculpt Tool" m_shelf_Sculpting.kSculptTool;
displayString -replace -value "Smear Tool" m_shelf_Sculpting.kSmearTool;
displayString -replace -value "Smooth Tool" m_shelf_Sculpting.kSmoothTool;
displayString -replace -value "Spray Tool" m_shelf_Sculpting.kSprayTool;
displayString -replace -value "Wax Tool" m_shelf_Sculpting.kWaxTool;
