// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc string shelf_Rigging() {

	string $label;
	string $annot;
	string $format = "^1s: ^2s";
	string $runtimeCommand;
	string $image;

	$label = (uiRes("m_shelf_Rigging.kLocator"));
	$runtimeCommand = "CreateLocator";
	$annot = getRunTimeCommandAnnotation($runtimeCommand);
	$image = "locator.png";
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand;

	$label = (uiRes("m_shelf_Rigging.kJointTool")) ;
	$runtimeCommand = "JointTool" ;
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "kinJoint.png";
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand
		-doubleClickCommand ($runtimeCommand + "Options");

	$label = (uiRes("m_shelf_Rigging.kIKHandleTool")) ;
	$runtimeCommand = "IKHandleTool";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "kinHandle.png" ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand
		-doubleClickCommand ($runtimeCommand + "Options");

	$label = (uiRes("m_shelf_Rigging.kBindSkin")) ;
	$runtimeCommand = "SmoothBindSkin";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "smoothSkin.png" ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand
		-doubleClickCommand ($runtimeCommand + "Options");

	$label = (uiRes("m_shelf_Rigging.kHumanIK")) ;
	$runtimeCommand = "HIKCharacterControlsTool";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "humanIK_CharCtrl.png" ;
	shelfButton
		-version	2016
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand
		-doubleClickCommand ($runtimeCommand + "Options");

	addShelfSeparator();

	$label = (uiRes("m_shelf_Rigging.kPaintSkinWeights")) ;
	$runtimeCommand = "ArtPaintSkinWeightsTool";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "paintSkinWeights.png" ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand 
		-doubleClickCommand ($runtimeCommand + "Options");

	$label = (uiRes("m_shelf_Rigging.kBlendShapes")) ;
	$runtimeCommand = "CreateBlendShape";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "blendShape.png";
	shelfButton
		-version	2016
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand 
		-doubleClickCommand ($runtimeCommand + "Options");

	$label = (uiRes("m_shelf_Rigging.kLattice")) ;
	$runtimeCommand = "CreateLattice";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "lattice.png";
	shelfButton
		-version	2016
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand 
		-doubleClickCommand ($runtimeCommand + "Options");

	$label = (uiRes("m_shelf_Rigging.kCluster"));
	$runtimeCommand = "CreateCluster";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "cluster.png" ;
	shelfButton
		-version	2016
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand
		-doubleClickCommand ($runtimeCommand + "Options");

	addShelfSeparator();

	$label = (uiRes("m_shelf_Rigging.kParentConstraint")) ;
	$annot = getRunTimeCommandAnnotation("ParentConstraint") ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     "parentConstraint.png"
		-command    ("ParentConstraint")
		-doubleClickCommand ("ParentConstraintOptions");

	$label = (uiRes("m_shelf_Rigging.kPointConstraint")) ;
	$annot = getRunTimeCommandAnnotation("PointConstraint") ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     "posConstraint.png"
		-command    ("PointConstraint")
		-doubleClickCommand ("PointConstraintOptions");

	$label = (uiRes("m_shelf_Rigging.kOrientConstraint")) ;
	$annot = getRunTimeCommandAnnotation("OrientConstraint") ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     "orientConstraint.png"
		-command    ("OrientConstraint")
		-doubleClickCommand ("OrientConstraintOptions");

	$label = (uiRes("m_shelf_Rigging.kScaleConstraint")) ;
	$annot = getRunTimeCommandAnnotation("ScaleConstraint") ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     "scaleConstraint.png"
		-command    ("ScaleConstraint")
		-doubleClickCommand ("ScaleConstraintOptions");

	$label = (uiRes("m_shelf_Rigging.kAimConstraint")) ;
	$annot = getRunTimeCommandAnnotation("AimConstraint") ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     "aimConstraint.png"
		-command    ("AimConstraint")
		-doubleClickCommand ("AimConstraintOptions");

	$label = (uiRes("m_shelf_Rigging.kPoleVectorConstraint")) ;
	$runtimeCommand = "PoleVectorConstraint";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "poleVectorConstraint.png";
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand
		-doubleClickCommand ($runtimeCommand + "Options");

	addShelfSeparator();

	$label = (uiRes("m_shelf_Rigging.kSetKey"));
	$runtimeCommand = "SetKey";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "setKeyframe.png" ;
	shelfButton
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand
		-doubleClickCommand ($runtimeCommand + "Options");

	$label = (uiRes("m_shelf_Rigging.kSetDrivenKey"));
	$runtimeCommand = "SetDrivenKeyOptions";
	$annot = getRunTimeCommandAnnotation($runtimeCommand) ;
	$image = "setDrivenKeyframe.png" ;
	shelfButton
		-version	2016
		-label      $label
		-annotation `format -s $label -s $annot $format`
		-image1     $image
		-command    $runtimeCommand
		-doubleClickCommand $runtimeCommand;
	
	// This shelf was introduced in Maya 2016 using buttons from the old
	// animation shelf.
	return "2016";
}
