// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// provided at the time of installation or download, or which otherwise accompanies 

//
// Procedures specifying the UI layout for ilrRaySampler shader
// in Maya's Attribute Editor
//

global proc AEilrUpdateRaySampler(string $node)
{
	int $dim = (`getAttr ($node + ".normalSpace")` != 0);
	editorTemplate -dimControl $node "faceTangents" $dim;
	editorTemplate -dimControl $node "flipNormalChannel" $dim;
}

global proc AEilrRaySamplerTemplate(string $node)
{
	editorTemplate -beginScrollLayout;

		editorTemplate -beginLayout "Ray Sampling Attributes" -collapse false;
			editorTemplate -l "Front Range" -ac "frontRange";
			editorTemplate -l "Back Range" -ac "backRange";
			editorTemplate -l "Front Bias" -ac "frontBias";
			editorTemplate -l "Back Bias" -ac "backBias";
			editorTemplate -l "Selection Mode" -ac "selectionMode";
			editorTemplate -s "envelopeMode";

		editorTemplate -endLayout;

		editorTemplate -beginLayout "Color Output Attributes" -collapse false;
			editorTemplate -l "Color Mode" -ac "colorMode";
			editorTemplate -l "Background Color" -ac "colorBackground";
		editorTemplate -endLayout;

		editorTemplate -beginLayout "Normal Output Attributes" -collapse false;
			editorTemplate -l "Coordinate System" -ac "normalSpace" "AEilrUpdateRaySampler";
			editorTemplate -l "Modify Channels" -ac "flipNormalChannel" "AEilrUpdateRaySampler";
			editorTemplate -beginNoOptimize;
			editorTemplate -l "Use Face Tangents" -ac "faceTangents";
			editorTemplate -l "Include Bump Maps" -ac "useBumpMaps";
			editorTemplate -endNoOptimize;
			editorTemplate -l "Background Color" -ac "normalBackground";
		editorTemplate -endLayout;

		editorTemplate -beginLayout "Displacement Output Attributes" -collapse false;
			editorTemplate -l "Displacement Scale" -ac "displacementScale";
			editorTemplate -l "Displacement Offset" -ac "displacementOffset";
			editorTemplate -l "Background Value" -ac "displacementBackground";
		editorTemplate -endLayout;

		// include/call base class/node attributes
		AEdependNodeTemplate $node;

		// suppressed attributes
		editorTemplate -s "version";

		editorTemplate -addExtraControls;

	editorTemplate -endScrollLayout;
}
