// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// provided at the time of installation or download, or which otherwise accompanies 

//
// Procedures specifying the UI layout for ilrBakeLayer
// in Maya's Attribute Editor
//

global proc AEilrUpdateBakeLayerMembersList(string $layer)
{
	string $members[] = `sets -query $layer`;
	textScrollList -edit -removeAll AEilrBakeLayerMembersList;
	for ($m in $members) {
		textScrollList -edit -append $m AEilrBakeLayerMembersList;
	}
}

global proc AEilrBakeLayerMembersReplace(string $attr)
{
	string	$layer;
	string	$buffer[];
	tokenize($attr, ".", $buffer);
	$layer = $buffer[0];

	AEilrUpdateBakeLayerMembersList($layer);
}

global proc AEilrBakeLayerMembersNew(string $attr)
{
	setUITemplate -pushTemplate attributeEditorTemplate;

	columnLayout -columnAttach "both" 5 -rowSpacing 10 -columnWidth 280;

		textScrollList
			//-numberOfRows 6
			-allowMultiSelection false
			AEilrBakeLayerMembersList;

 	setParent ..;

	setUITemplate -popTemplate;

	AEilrBakeLayerMembersReplace $attr;
}

global proc AEilrBakeLayerTemplate(string $node)
{
	editorTemplate -beginScrollLayout;

		editorTemplate -beginLayout "Layer Members" -collapse false;
				editorTemplate -callCustom "AEilrBakeLayerMembersNew" "AEilrBakeLayerMembersReplace" "dagSetMembers";
		editorTemplate -endLayout;

		editorTemplate -beginLayout "Layer Options" -collapse false;
			editorTemplate -l "Renderable" -ac "renderable";
		editorTemplate -endLayout;

		// include/call base class/node attributes
		AEobjectSetNoScroll $node;

		// suppressed attributes
		editorTemplate -s "version";
		editorTemplate -s "index";
		editorTemplate -s "renderOptions";
		editorTemplate -s "textureBakeOptions";
		editorTemplate -s "vertexBakeOptions";
		editorTemplate -s "surfaceTransferOptions";
		editorTemplate -s "sourceLinks";
		editorTemplate -s "envelopeLinks";

		editorTemplate -addExtraControls;

	editorTemplate -endScrollLayout;
}
