// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
// provided at the time of installation or download, or which otherwise accompanies 

//
// Procedures specifying the UI layout for ilrOrenNayarShader
// in Maya's Attribute Editor
//

global proc AEilrOrenNayarShaderTemplate(string $node)
{
	editorTemplate -beginScrollLayout;
 		AElambertCommon $node;

		editorTemplate -beginLayout "Oren Nayar Attributes" -collapse true;

		editorTemplate -label "Material" -addControl "materialIndex" "ilrMaterialIndexChanged";
		editorTemplate -label "Roughness" -addControl "sigma" "ilrSigmaChanged";

		editorTemplate -endLayout;

		editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;

	// suppressed attributes
 	editorTemplate -suppress "caching";
	editorTemplate -suppress "nodeState";
	editorTemplate -suppress "normalCamera";
	editorTemplate -suppress "version";
}

global proc ilrMaterialIndexChanged(string $node)
{
	int $materialIndex = `getAttr ($node+".materialIndex")`;

 	switch ($materialIndex) {
		case 1:   // Felt
			setAttr ($node+".sigma") 0.414686;
			break;
		case 2:   // Polyester
			setAttr ($node+".sigma") 0.576862;
			break;
		case 3:   // Terrycloth
			setAttr ($node+".sigma") 0.458514;
			break;
		case 4:   // Rough Plastic
			setAttr ($node+".sigma") 0.278057;
			break;
		case 5:   // Leather
			setAttr ($node+".sigma") 0.179776;
			break;
		case 6:   // Sandpaper
			setAttr ($node+".sigma") 0.513084;
			break;
		case 7:   // Velvet
			setAttr ($node+".sigma") 0.751002;
			break;
		case 8:   // Pebbles
			setAttr ($node+".sigma") 0.443289;
			break;
		case 9:   // Frosted Glass
			setAttr ($node+".sigma") 0.416384;
			break;
		case 10:   // Plaster A
			setAttr ($node+".sigma") 0.362825;
			break;
		case 11:   // Plaster B
			setAttr ($node+".sigma") 0.543788;
			break;
		case 12:   // Rough Paper
			setAttr ($node+".sigma") 0.311376;
			break;
		case 13:   // Artificial Grass
			setAttr ($node+".sigma") 1.378872;
			break;
		case 14:   // Roof Shingle
			setAttr ($node+".sigma") 0.819147;
			break;
		case 15:   // Foil
			setAttr ($node+".sigma") 0.252702;
			break;
		case 16:   // Cork
			setAttr ($node+".sigma") 0.659956;
			break;
		case 17:   // Rough Tile
			setAttr ($node+".sigma") 0.204088;
			break;
		case 18:   // Rug A
			setAttr ($node+".sigma") 0.566478;
			break;
		case 19:   // Rug B
			setAttr ($node+".sigma") 0.613889;
			break;
		case 20:   // Styrofoam
			setAttr ($node+".sigma") 0.509725;
			break;
		case 21:   // Sponge
			setAttr ($node+".sigma") 0.872413;
			break;
		case 22:   // Lambswool
			setAttr ($node+".sigma") 0.978133;
			break;
		case 23:   // Lettuce Leaf
			setAttr ($node+".sigma") 0.241785;
			break;
		case 24:   // Rabbit Fur
			setAttr ($node+".sigma") 0.933632;
			break;
		case 25:   // Quarry Tile
			setAttr ($node+".sigma") 0.360574;
			break;
		case 26:   // Loofa
			setAttr ($node+".sigma") 0.300436;
			break;
		case 27:   // Insulation
			setAttr ($node+".sigma") 0.136013;
			break;
		case 28:   // Crumpled Paper
			setAttr ($node+".sigma") 0.274957;
			break;
		case 29:   // Polyester Zoomed
			setAttr ($node+".sigma") 0.522950;
			break;
		case 30:   // Plaster B Zoomed
			setAttr ($node+".sigma") 0.520868;
			break;
		case 31:   // Rough Paper Zoomed
			setAttr ($node+".sigma") 0.318498;
			break;
		case 32:   // Roof Shingle Zoomed
			setAttr ($node+".sigma") 0.950521;
			break;
		case 33:   // Slate A
			setAttr ($node+".sigma") 0.356822;
			break;
		case 34:   // Slate B
			setAttr ($node+".sigma") 0.309590;
			break;
		case 35:   // Spheres
			setAttr ($node+".sigma") 1.211948;
			break;
		case 36:   // Limestone
			setAttr ($node+".sigma") 0.413544;
			break;
		case 37:   // Brick A
			setAttr ($node+".sigma") 0.893379;
			break;
		case 38:   // Ribbed Paper
			setAttr ($node+".sigma") 0.215297;
			break;
		case 39:   // Human Skin
			setAttr ($node+".sigma") 0.579386;
			break;
		case 40:   // Straw
			setAttr ($node+".sigma") 0.717587;
			break;
		case 41:   // Brick B
			setAttr ($node+".sigma") 0.275990;
			break;
		case 42:   // Corduroy
			setAttr ($node+".sigma") 0.699112;
			break;
		case 43:   // Salt Crystals
			setAttr ($node+".sigma") 0.481594;
			break;
		case 44:   // Linen
			setAttr ($node+".sigma") 0.514593;
			break;
		case 45:   // Concrete A
			setAttr ($node+".sigma") 0.600672;
			break;
		case 46:   // Cotton
			setAttr ($node+".sigma") 0.482679;
			break;
		case 47:   // Stones
			setAttr ($node+".sigma") 1.107168;
			break;
		case 48:   // Brown Bread
			setAttr ($node+".sigma") 0.784827;
			break;
		case 49:   // Concrete B
			setAttr ($node+".sigma") 0.308956;
			break;
		case 50:   // Concrete C
			setAttr ($node+".sigma") 0.461930;
			break;
		case 51:   // Corn Husk
			setAttr ($node+".sigma") 0.387725;
			break;
		case 52:   // White Bread
			setAttr ($node+".sigma") 0.507820;
			break;
		case 53:   // Plant
			setAttr ($node+".sigma") 0.758465;
			break;
		case 54:   // Wood A
			setAttr ($node+".sigma") 0.598438;
			break;
		case 55:   // Orange Peel
			setAttr ($node+".sigma") 0.235808;
			break;
		case 56:   // Wood B
			setAttr ($node+".sigma") 0.351271;
			break;
		case 57:   // Peacock Feather
			setAttr ($node+".sigma") 0.308792;
			break;
		case 58:   // Tree Bark
			setAttr ($node+".sigma") 0.293226;
			break;
		case 59:   // Cracker A
			setAttr ($node+".sigma") 0.505978;
			break;
		case 60:   // Cracker B
			setAttr ($node+".sigma") 0.722678;
			break;
		case 61:   // Moss
			setAttr ($node+".sigma") 0.542447;
			break;
	}
}

global proc ilrSigmaChanged(string $node)
{
	int $materialIndex = `getAttr ($node+".materialIndex")`;
	
	float $sigma = `getAttr ($node+".sigma")`;
	int $sigmaScaled = (int) 1000000.0 * $sigma;

 	switch ($sigmaScaled) {
		case 414685:
			if ($materialIndex != 1) {
				setAttr ($node+".materialIndex") 1;
			}
			break;
		case 576861:
			if ($materialIndex != 2) {
				setAttr ($node+".materialIndex") 2;
			}
			break;
		case 458514:
			if ($materialIndex != 3) {
				setAttr ($node+".materialIndex") 3;
			}
			break;
		case 278057:
			if ($materialIndex != 4) {
				setAttr ($node+".materialIndex") 4;
			}
			break;
		case 179775:
			if ($materialIndex != 5) {
				setAttr ($node+".materialIndex") 5;
			}
			break;
		case 513083:
			if ($materialIndex != 6) {
				setAttr ($node+".materialIndex") 6;
			}
			break;
		case 751002:
			if ($materialIndex != 7) {
				setAttr ($node+".materialIndex") 7;
			}
			break;
		case 443289:
			if ($materialIndex != 8) {
				setAttr ($node+".materialIndex") 8;
			}
			break;
		case 416384:
			if ($materialIndex != 9) {
				setAttr ($node+".materialIndex") 9;
			}
			break;
		case 362825:
			if ($materialIndex != 10) {
				setAttr ($node+".materialIndex") 10;
			}
			break;
		case 543788:
			if ($materialIndex != 11) {
				setAttr ($node+".materialIndex") 11;
			}
			break;
		case 311376:
			if ($materialIndex != 12) {
				setAttr ($node+".materialIndex") 12;
			}
			break;
		case 1378872:
			if ($materialIndex != 13) {
				setAttr ($node+".materialIndex") 13;
			}
			break;
		case 819146:
			if ($materialIndex != 14) {
				setAttr ($node+".materialIndex") 14;
			}
			break;
		case 252701:
			if ($materialIndex != 15) {
				setAttr ($node+".materialIndex") 15;
			}
			break;
		case 659955:
			if ($materialIndex != 16) {
				setAttr ($node+".materialIndex") 16;
			}
			break;
		case 204088:
			if ($materialIndex != 17) {
				setAttr ($node+".materialIndex") 17;
			}
			break;
		case 566478:
			if ($materialIndex != 18) {
				setAttr ($node+".materialIndex") 18;
			}
			break;
		case 613888:
			if ($materialIndex != 19) {
				setAttr ($node+".materialIndex") 19;
			}
			break;
		case 509724:
			if ($materialIndex != 20) {
				setAttr ($node+".materialIndex") 20;
			}
			break;
		case 872412:
			if ($materialIndex != 21) {
				setAttr ($node+".materialIndex") 21;
			}
			break;
		case 978133:
			if ($materialIndex != 22) {
				setAttr ($node+".materialIndex") 22;
			}
			break;
		case 241785:
			if ($materialIndex != 23) {
				setAttr ($node+".materialIndex") 23;
			}
			break;
		case 933632:
			if ($materialIndex != 24) {
				setAttr ($node+".materialIndex") 24;
			}
			break;
		case 360574:
			if ($materialIndex != 25) {
				setAttr ($node+".materialIndex") 25;
			}
			break;
		case 300435:
			if ($materialIndex != 26) {
				setAttr ($node+".materialIndex") 26;
			}
			break;
		case 136013:
			if ($materialIndex != 27) {
				setAttr ($node+".materialIndex") 27;
			}
			break;
		case 274957:
			if ($materialIndex != 28) {
				setAttr ($node+".materialIndex") 28;
			}
			break;
		case 522949:
			if ($materialIndex != 29) {
				setAttr ($node+".materialIndex") 29;
			}
			break;
		case 520868:
			if ($materialIndex != 30) {
				setAttr ($node+".materialIndex") 30;
			}
			break;
		case 318497:
			if ($materialIndex != 31) {
				setAttr ($node+".materialIndex") 31;
			}
			break;
		case 950520:
			if ($materialIndex != 32) {
				setAttr ($node+".materialIndex") 32;
			}
			break;
		case 356822:
			if ($materialIndex != 33) {
				setAttr ($node+".materialIndex") 33;
			}
			break;
		case 309590:
			if ($materialIndex != 34) {
				setAttr ($node+".materialIndex") 34;
			}
			break;
		case 1211948:
			if ($materialIndex != 35) {
				setAttr ($node+".materialIndex") 35;
			}
			break;
		case 413543:
			if ($materialIndex != 36) {
				setAttr ($node+".materialIndex") 36;
			}
			break;
		case 893378:
			if ($materialIndex != 37) {
				setAttr ($node+".materialIndex") 37;
			}
			break;
		case 215296:
			if ($materialIndex != 38) {
				setAttr ($node+".materialIndex") 38;
			}
			break;
		case 579385:
			if ($materialIndex != 39) {
				setAttr ($node+".materialIndex") 39;
			}
			break;
		case 717586:
			if ($materialIndex != 40) {
				setAttr ($node+".materialIndex") 40;
			}
			break;
		case 275990:
			if ($materialIndex != 41) {
				setAttr ($node+".materialIndex") 41;
			}
			break;
		case 699111:
			if ($materialIndex != 42) {
				setAttr ($node+".materialIndex") 42;
			}
			break;
		case 481593:
			if ($materialIndex != 43) {
				setAttr ($node+".materialIndex") 43;
			}
			break;
		case 514593:
			if ($materialIndex != 44) {
				setAttr ($node+".materialIndex") 44;
			}
			break;
		case 600672:
			if ($materialIndex != 45) {
				setAttr ($node+".materialIndex") 45;
			}
			break;
		case 482679:
			if ($materialIndex != 46) {
				setAttr ($node+".materialIndex") 46;
			}
			break;
		case 1107167:
			if ($materialIndex != 47) {
				setAttr ($node+".materialIndex") 47;
			}
			break;
		case 784826:
			if ($materialIndex != 48) {
				setAttr ($node+".materialIndex") 48;
			}
			break;
		case 308955:
			if ($materialIndex != 49) {
				setAttr ($node+".materialIndex") 49;
			}
			break;
		case 461930:
			if ($materialIndex != 50) {
				setAttr ($node+".materialIndex") 50;
			}
			break;
		case 387724:
			if ($materialIndex != 51) {
				setAttr ($node+".materialIndex") 51;
			}
			break;
		case 507820:
			if ($materialIndex != 52) {
				setAttr ($node+".materialIndex") 52;
			}
			break;
		case 758464:
			if ($materialIndex != 53) {
				setAttr ($node+".materialIndex") 53;
			}
			break;
		case 598438:
			if ($materialIndex != 54) {
				setAttr ($node+".materialIndex") 54;
			}
			break;
		case 235807:
			if ($materialIndex != 55) {
				setAttr ($node+".materialIndex") 55;
			}
			break;
		case 351271:
			if ($materialIndex != 56) {
				setAttr ($node+".materialIndex") 56;
			}
			break;
		case 308791:
			if ($materialIndex != 57) {
				setAttr ($node+".materialIndex") 57;
			}
			break;
		case 293226:
			if ($materialIndex != 58) {
				setAttr ($node+".materialIndex") 58;
			}
			break;
		case 505977:
			if ($materialIndex != 59) {
				setAttr ($node+".materialIndex") 59;
			}
			break;
		case 722678:
			if ($materialIndex != 60) {
				setAttr ($node+".materialIndex") 60;
			}
			break;
		case 542446:
			if ($materialIndex != 61) {
				setAttr ($node+".materialIndex") 61;
			}
			break;
		default:
			if ($materialIndex != 0) {
				setAttr ($node+".materialIndex") 0;
			}
			break;
	}
}
