// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "In Scale" m_AEaddRampControl.kInScale;
displayString -replace -value "Input" m_AEaddRampControl.kInput;
displayString -replace -value "Input source for ramp" m_AEaddRampControl.kInputAnnot;
displayString -replace -value "Input Bias" m_AEaddRampControl.kInputBias;
displayString -replace -value "^1s Input" m_AEaddRampControl.kInputFmt;
displayString -replace -value "Input Max" m_AEaddRampControl.kInputMax;
displayString -replace -value "Input Offset" m_AEaddRampControl.kInputOffset;
displayString -replace -value "Input Scale" m_AEaddRampControl.kInputScale;
displayString -replace -value "Input" m_AEaddRampControl.kInputShort;
displayString -replace -value "input source for ramp" m_AEaddRampControl.kInputVarAnnot;
displayString -replace -value "Interpolation" m_AEaddRampControl.kInterp;
displayString -replace -value "Interpolation method" m_AEaddRampControl.kInterpMethod;
displayString -replace -value "Multiplier for input value" m_AEaddRampControl.kMultiplierAnnot;
displayString -replace -value "Selected Color" m_AEaddRampControl.kSelClr;
displayString -replace -value "Selected Position" m_AEaddRampControl.kSelPos;
displayString -replace -value "Selected Value" m_AEaddRampControl.kSelVal;
