// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Abs." m_AEanimClipTemplate.kAbsolute;
displayString -replace -value "All Absolute" m_AEanimClipTemplate.kAllAbsolute;
displayString -replace -value "All Relative" m_AEanimClipTemplate.kAllRelative;
displayString -replace -value "Anim Clip Attributes" m_AEanimClipTemplate.kAnimClipAttributes;
displayString -replace -value "Channel Offsets" m_AEanimClipTemplate.kChannelOffsets;
displayString -replace -value "Rel." m_AEanimClipTemplate.kRelative;
displayString -replace -value "Relative Root(s) Only" m_AEanimClipTemplate.kRelativeRoots;
displayString -replace -value "Set non-rotation root channels to relative." m_AEanimClipTemplate.kSetRelativeRootsAnnot;
displayString -replace -value "Set all the channels to absolute." m_AEanimClipTemplate.kSetallthechannelstoabsoluteAnnot;
displayString -replace -value "Set all the channels to relative." m_AEanimClipTemplate.kSetallthechannelstorelativeAnnot;
displayString -replace -value "Source Clip Attributes" m_AEanimClipTemplate.kSourceClipAttributes;
