// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Alpha Weight" m_AEblendColorSetsTemplate.kAlphaWeight;
displayString -replace -value "Base Color Set" m_AEblendColorSetsTemplate.kBaseColorSet;
displayString -replace -value "Blend Color Set" m_AEblendColorSetsTemplate.kBlendColorSet;
displayString -replace -value "Blend Style" m_AEblendColorSetsTemplate.kBlendStyle;
displayString -replace -value "Blending Controls" m_AEblendColorSetsTemplate.kBlendingControls;
displayString -replace -value "Blue Weight" m_AEblendColorSetsTemplate.kBlueWeight;
displayString -replace -value "Destination Color Set" m_AEblendColorSetsTemplate.kDestinationColorSet;
displayString -replace -value "Primary (Red) Weight " m_AEblendColorSetsTemplate.kPrimaryWeight;
displayString -replace -value "Secondary (Green) Weight" m_AEblendColorSetsTemplate.kSecondaryWeight;
displayString -replace -value "Swap Base and Blend Sets" m_AEblendColorSetsTemplate.kSwapBaseBlendSets;
