// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//	Creation Date:	Oct 22, 1998
//
//	Procedure Name:
//	    AEcharacterRelated
//
//	Description Name;
//	    Return all of the nodes related to the given character
//
//	Input Value:
//	    node name
//
//	Output Value:
//	    None
//


//
//  Procedure Name:
//      getAllCharacters
//
//  Description:
//		Helper function to recursively find all of the sub characters in a 
//      character
//
//  Input Arguments:
//      $character - the name of the character to expand
//
//  Return Value:
//      string[] (list of related nodes, with the node whose
//		tab you want to be opened duplicated at the
//		end of the array)
//
proc string[] getAllCharacters( string $character, int $includeSelf )
{
	string $retval[];

	if ( $includeSelf ) {
		$retval[size($retval)] = $character;
	}

	string $setMembers[] = `sets -query $character`;
	for ( $item in $setMembers ) {
		if ( `nodeType $item` == "character" ) {
			$result = getAllCharacters( $item, true );
			for ( $subCharacter in $result ) {
				$retval[size($retval)] = $subCharacter;
			}
		}
	}

	return $retval;
}

global proc string[] AEcharacterRelated( string $node )
{
	string $relatedNodes[] = getAllCharacters( $node, false );
	$relatedNodes[size($relatedNodes)] = $node;
	return $relatedNodes;
}

