// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//  Procedure Name:
//	AEclusterCommon
//
//  Description Name;
//	Creates the attribute editor controls for the cluster Node
//
//  Input Value:
//	nodeName 
//
//  Output Value:
//	None
// 


global proc checkClusterPartialResolution ( string $nodeName )
{
	string $nodeAttr = $nodeName + ".usePartialResolution";
	int $value = `getAttr $nodeAttr`;
	if ($value == 0) {
		editorTemplate -dimControl $nodeName "percentResolution" true;
	} else {
		editorTemplate -dimControl $nodeName "percentResolution" false;
	}
}

global proc AEusePartialResolutionNew( string $attrName )
{
	setUITemplate -pst attributeEditorTemplate;	
 	attrEnumOptionMenuGrp -attribute $attrName 
		-label (uiRes("m_AEclusterCommon.kResolution")) 
    	usePartialResolutionEnum;
    setUITemplate -ppt;

	AEusePartialResolutionReplace $attrName;
}

global proc AEusePartialResolutionReplace( string $attrName )
{
	string $tmp[];
	tokenize($attrName, ".", $tmp);
	string $nodeName = $tmp[0];

 	attrEnumOptionMenuGrp -e -attribute $attrName 
		-label (uiRes("m_AEclusterCommon.kResolution"))
    	usePartialResolutionEnum;
	scriptJob -p usePartialResolutionEnum -rp
		-ac $attrName ("checkClusterPartialResolution " + $nodeName );

	// Check the partial resoultion initial state
	//
	evalDeferred ("checkClusterPartialResolution " + $nodeName);
}

global proc AEclusterCommon ( string $nodeName )
{
		editorTemplate -addControl "relative";
		editorTemplate -callCustom "AEusePartialResolutionNew"
			"AEusePartialResolutionReplace" "usePartialResolution";
		editorTemplate -addControl "percentResolution";
		editorTemplate -addControl "angleInterpolation";

	//suppressed attributes
	editorTemplate -suppress "clusterXforms";
	editorTemplate -suppress "matrix";
	editorTemplate -suppress "bindPreMatrix";
	editorTemplate -suppress "bindState";
}
