// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Bounding Box Information" m_AEdagNodeCommon.kBoundingBoxInformation;
displayString -replace -value "Bounding Box Max" m_AEdagNodeCommon.kBoundingBoxMax;
displayString -replace -value "Bounding Box Min" m_AEdagNodeCommon.kBoundingBoxMin;
displayString -replace -value "Custom Frames" m_AEdagNodeCommon.kCustomFrames;
displayString -replace -value "Drawing Overrides" m_AEdagNodeCommon.kDrawingOverrides;
displayString -replace -value "End Frame" m_AEdagNodeCommon.kEndFrame;
displayString -replace -value "Enter the frame numbers separated by commas." m_AEdagNodeCommon.kEntertheframenumbersseparatedAnnot;
displayString -replace -value "Environment Map Texture" m_AEdagNodeCommon.kEnvironmentMapTexture;
displayString -replace -value "Ghost Driver" m_AEdagNodeCommon.kGhostDriver;
displayString -replace -value "Ghosting Information" m_AEdagNodeCommon.kGhostingInformation;
displayString -replace -value "Hardware Fog Multiplier" m_AEdagNodeCommon.kHardwareFogMultiplier;
displayString -replace -value "Hidden In Outliner" m_AEdagNodeCommon.kHiddenInOutliner;
displayString -replace -value "Hide on playback" m_AEdagNodeCommon.kHideOnPlayback;
displayString -replace -value "Ignore Hardware Shader" m_AEdagNodeCommon.kIgnoreHardwareShader;
displayString -replace -value "LOD Visibility" m_AEdagNodeCommon.kLODVisibility;
displayString -replace -value "Outliner Color" m_AEdagNodeCommon.kOutlinerColor;
displayString -replace -value "Post Frame Alpha" m_AEdagNodeCommon.kPostFrameAlpha;
displayString -replace -value "Post Frame Color" m_AEdagNodeCommon.kPostFrameColor;
displayString -replace -value "Post Steps" m_AEdagNodeCommon.kPostSteps;
displayString -replace -value "Pre Frame Alpha" m_AEdagNodeCommon.kPreFrameAlpha;
displayString -replace -value "Pre Frame Color" m_AEdagNodeCommon.kPreFrameColor;
displayString -replace -value "Pre Steps" m_AEdagNodeCommon.kPreSteps;
displayString -replace -value "Selection" m_AEdagNodeCommon.kSelection;
displayString -replace -value "Start Frame" m_AEdagNodeCommon.kStartFrame;
displayString -replace -value "Step Size" m_AEdagNodeCommon.kStepSize;
displayString -replace -value "Use Outliner Color" m_AEdagNodeCommon.kUseOutlinerColor;
