// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Bilinear" m_AEhardwareTextureTemplate.kBilinear;
displayString -replace -value "Bump Map" m_AEhardwareTextureTemplate.kBumpMap;
displayString -replace -value "Combined Textures" m_AEhardwareTextureTemplate.kCombinedTextures;
displayString -replace -value "Default" m_AEhardwareTextureTemplate.kDefault;
displayString -replace -value "High  (128x128)" m_AEhardwareTextureTemplate.kHigh128by128;
displayString -replace -value "Highest  (256x256)" m_AEhardwareTextureTemplate.kHighest256by256;
displayString -replace -value "Low  (32x32)" m_AEhardwareTextureTemplate.kLow32by32;
displayString -replace -value "Medium  (64x64)" m_AEhardwareTextureTemplate.kMedium64by64;
displayString -replace -value "MipMap Trilinear" m_AEhardwareTextureTemplate.kMipMapTrilinear;
displayString -replace -value "Mipmap Bilinear" m_AEhardwareTextureTemplate.kMipmapBilinear;
displayString -replace -value "Mipmap Linear" m_AEhardwareTextureTemplate.kMipmapLinear;
displayString -replace -value "Mipmap Nearest" m_AEhardwareTextureTemplate.kMipmapNearest;
displayString -replace -value "Nearest (Unfiltered)" m_AEhardwareTextureTemplate.kNearestUnfiltered;
displayString -replace -value "None" m_AEhardwareTextureTemplate.kNone;
displayString -replace -value "^1s : ^2s not a valid materialPlug." m_AEhardwareTextureTemplate.kNotValid;
displayString -replace -value "Texture Filter" m_AEhardwareTextureTemplate.kTextureFilter;
displayString -replace -value "Texture resolution" m_AEhardwareTextureTemplate.kTextureResolution;
displayString -replace -value "Textured channel" m_AEhardwareTextureTemplate.kTexturedChannel;
displayString -replace -value "Use Global Settings" m_AEhardwareTextureTemplate.kUseGlobalSettings;
