// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Finger Tip Sizes" m_AEhikHandleTemplate.kFingerTipSizes;
displayString -replace -value "HIK Handle Attributes" m_AEhikHandleTemplate.kHIKHandleAttributes;
displayString -replace -value "Hips Stiffness" m_AEhikHandleTemplate.kHipsStiffness;
displayString -replace -value "Kill Pitch Attributes" m_AEhikHandleTemplate.kKillPitchAttributes;
displayString -replace -value "Left Arm Pull" m_AEhikHandleTemplate.kLeftArmPull;
displayString -replace -value "Left Arm Stiffness" m_AEhikHandleTemplate.kLeftArmStiffness;
displayString -replace -value "Left Leg Pull" m_AEhikHandleTemplate.kLeftLegPull;
displayString -replace -value "Left Leg Stiffness" m_AEhikHandleTemplate.kLeftLegStiffness;
displayString -replace -value "Pull" m_AEhikHandleTemplate.kPull;
displayString -replace -value "Right Arm Pull" m_AEhikHandleTemplate.kRightArmPull;
displayString -replace -value "Right Arm Stiffness" m_AEhikHandleTemplate.kRightArmStiffness;
displayString -replace -value "Right Leg Pull" m_AEhikHandleTemplate.kRightLegPull;
displayString -replace -value "Right Leg Stiffness" m_AEhikHandleTemplate.kRightLegStiffness;
displayString -replace -value "Roll Attributes" m_AEhikHandleTemplate.kRollAttributes;
displayString -replace -value "Stiffness Attributes" m_AEhikHandleTemplate.kStiffnessAttributes;
displayString -replace -value "Toe Tips Size" m_AEhikHandleTemplate.kToeTipsSize;
