// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Alpha" m_AElayeredTextureTemplate.kAlpha;
displayString -replace -value "Add" m_AElayeredTextureTemplate.kBlendAdd;
displayString -replace -value "Darken" m_AElayeredTextureTemplate.kBlendDarken;
displayString -replace -value "Desaturate" m_AElayeredTextureTemplate.kBlendDesaturate;
displayString -replace -value "Difference" m_AElayeredTextureTemplate.kBlendDiff;
displayString -replace -value "Illuminate" m_AElayeredTextureTemplate.kBlendIllum;
displayString -replace -value "In" m_AElayeredTextureTemplate.kBlendIn;
displayString -replace -value "Lighten" m_AElayeredTextureTemplate.kBlendLighten;
displayString -replace -value "Blend Mode:" m_AElayeredTextureTemplate.kBlendMode;
displayString -replace -value "Multiply" m_AElayeredTextureTemplate.kBlendMultiply;
displayString -replace -value "None" m_AElayeredTextureTemplate.kBlendNone;
displayString -replace -value "Out" m_AElayeredTextureTemplate.kBlendOut;
displayString -replace -value "Over" m_AElayeredTextureTemplate.kBlendOver;
displayString -replace -value "Saturate" m_AElayeredTextureTemplate.kBlendSaturate;
displayString -replace -value "Subtract" m_AElayeredTextureTemplate.kBlendSubtract;
displayString -replace -value "Color" m_AElayeredTextureTemplate.kColor;
displayString -replace -value "Layer is Visible" m_AElayeredTextureTemplate.kLayerIsVisible;
displayString -replace -value "Layered Texture Attributes" m_AElayeredTextureTemplate.kLayeredTextureAttr;
