// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc AEmakeIllustratorCurvesTemplate( string $nodeName )
{
    editorTemplate -beginScrollLayout;
	    editorTemplate -beginLayout (uiRes("m_AEmakeIllustratorCurvesTemplate.kFileAttributes"))  -collapse 0;
			editorTemplate -callCustom "AEaiFileNameNew" 
						"AEaiFileNameReplace" 
						"illustratorFilename";
			editorTemplate -callCustom "AEaiFileNameReload"
						"AEaiFileNameReloadReplace"
						"illustratorFilename";
						
			editorTemplate -addControl "scaleFactor";
			editorTemplate -addControl "tolerance";
			editorTemplate -suppress "reload";

	editorTemplate -endLayout;

	AEdependNodeTemplate $nodeName;
}

global proc AEaiFileNameNew (string $fileAttribute)
{
	setUITemplate -pst attributeEditorTemplate;
	rowLayout -nc 3 aiFileNameLayout;
		text -label (uiRes("m_AEmakeIllustratorCurvesTemplate.kFileName")) ;
		textField aiFileNameField;
			symbolButton -image "navButtonBrowse.png" browserBtn;
	setParent ..;
	setUITemplate -ppt;
	
    AEaiFileNameReplace $fileAttribute;
}

global proc  AEaiFileNameReplace(string $fileAttribute)
{
	connectControl -fileName aiFileNameField $fileAttribute;
	string $command = "AEassignAIfilenameCB "+$fileAttribute;
    symbolButton -e -c ("illustratorCurvesFileBrowser \"" + $command + "\"") browserBtn;

}

global proc AEaiFileNameReload(string $fileAttribute)
{
	setUITemplate -pst attributeEditorTemplate;
	rowLayout -nc 3 -cl3  "center" "center" "center" ;
		text -label "";
		button -label (uiRes("m_AEmakeIllustratorCurvesTemplate.kReload"))  reloadFileButton;
		text -label "";
	setParent ..;
	setUITemplate -ppt;
	
	AEaiFileNameReloadReplace $fileAttribute;
}

global proc AEaiFileNameReloadReplace(string $fileAttribute)
{
	// To force reload the same Adobe(R) Illustrator(R) file...
	//
    string $forceReloadCmd = "setAttr " + `plugNode $fileAttribute` + ".reload 1";
	button -e -c ($forceReloadCmd) reloadFileButton;
}

global proc illustratorCurvesFileBrowser(string $command)
{
	string $open = (uiRes("m_AEmakeIllustratorCurvesTemplate.kOpen"));
	fileBrowser($command, $open, "Adobe(R) Illustrator(R)", 0);
}


global proc AEassignAIfilenameCB( string $fileAttribute,
                                 string $filename,
                                 string $fileType )
{
	setAttr $fileAttribute -type "string" $filename;

	string $currentDir = `workspace -q -dir`;
    retainWorkingDirectory ($currentDir);
}
