// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//	Creation Date:	15 April 1997
//
//	Description:
//		This procedure adds property sheet controls for
//		a new enumerated attribute.  This is for internal
//		use only.
//
//	Input Arguments:
//		The name of the plug for the attribute
//		The name of the attribute
//		The list of enumerated items (strings)
//
//	Return Value:
//		The name of the newly-created control.
//

global proc string AEnewEnum(	string $plugName,
								string $attrName,
								string $changedCommand,
								string $enumItems[])
{
	string	$createdControl;

	string $cmd = ("attrEnumOptionMenuGrp -at \"" + $plugName + "\"");
	int $i;
	for ($i = 0; $i < size($enumItems); $i+=2) {
		$cmd += (" -enumeratedItem " + $enumItems[$i] + " \"" + $enumItems[$i+1]) + "\"";
	}
	$createdControl = `eval $cmd`;
	attrEnumOptionMenuGrp -e -l $attrName $createdControl;
	if ( $changedCommand != "" ) {
		string $buffer[];
		tokenize($plugName,".",$buffer);
		string $cmd = $changedCommand + " \"" + $buffer[0] + "\"";
		scriptJob -p $createdControl -rp -ac $plugName $cmd;
	}

	return $createdControl;
}
