// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.


// PLUGIN NAME: nearestPointOnMesh v1.0
// FILE: AEnearestPointOnMeshTemplate.mel
// DESCRIPTION: -Defines the attribute template for the "nearestPointOnMesh" node.
//              -Please see readme.txt for full details.
// REFERENCES: -This plugin is based off of the "nearestPointOnSurface" node.
//             -The MEL script AEnearestPointOnSurfaceTemplate.mel was referred to for this script.

global proc AEnearestPointOnMeshTemplate(string $nodeName)
{
   editorTemplate -beginScrollLayout;
   string $inputMesh = (uiRes("m_AEnearestPointOnMeshTemplate.kInputMesh"));
      editorTemplate -beginLayout (uiRes("m_AEnearestPointOnMeshTemplate.kNPOMAttributes")) -collapse 0;

         editorTemplate -callCustom ("AEinputNew \""+$inputMesh+"\"")
                                        ("AEinputReplace \""+$inputMesh+"\"")
                                        "inMesh";

         editorTemplate -addControl "inPosition";

         editorTemplate -beginLayout (uiRes("m_AEnearestPointOnMeshTemplate.kResult"));

            editorTemplate -addControl "position";
            editorTemplate -addControl "normal";
            editorTemplate -addControl "parameterU";
            editorTemplate -addControl "parameterV";
            editorTemplate -addControl "nearestFaceIndex";

         editorTemplate -endLayout;

      editorTemplate -endLayout;

      AEabstractBaseCreateTemplate $nodeName;

      editorTemplate -addExtraControls;

   editorTemplate -endScrollLayout;

}

