// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.


global proc polyCBoolOpControl ( string $nodeName )
{
	string	$attr = $nodeName + ".useThresholds";
	int $threshold = `getAttr $attr`;
	if($threshold == 1) {
		editorTemplate -dimControl $nodeName "faceAreaThreshold" false;
		editorTemplate -dimControl $nodeName "vertexDistanceThreshold" false;
	} else {
		editorTemplate -dimControl $nodeName "faceAreaThreshold" true;
		editorTemplate -dimControl $nodeName "vertexDistanceThreshold" true;
	}
}

global proc AEpolyCBoolOpTemplate ( string $nodeName )
{
	editorTemplate -beginScrollLayout;
		editorTemplate -beginLayout (uiRes("m_AEpolyCBoolOpTemplate.kPolyBooleanHistory")) -collapse 0;
		editorTemplate -addControl "operation";
		editorTemplate -label (uiRes("m_AEpolyCBoolOpTemplate.kIntersectionLabel")) -addControl "classification";
		editorTemplate -addControl "useThresholds" "polyCBoolOpControl";
		editorTemplate -addControl "vertexDistanceThreshold";
		editorTemplate -addControl "faceAreaThreshold";
		editorTemplate -endLayout;
		//supressed attributes
		editorTemplate -suppress "inputPoly";
		editorTemplate -suppress "inputMat";
		editorTemplate -suppress "mergeUVSets";
		editorTemplate -suppress "useCarveBooleans";
		editorTemplate -suppress "preserveColor";
		editorTemplate -suppress "mergeGroups";

		// include/call base class/node attributes		
		AEpolyCreatorTemplate $nodeName;

	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
}
