// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
//  Creation Date:	June 5, 1997
//
//  Procedure Name:
//	AEpolySubdFaceTemplate
//
//  Description Name;
//	Creates the attribute editor controls for the polySubdFace Node
//
//  Input Value:
//	nodeName 
//
//  Output Value:
//	None
// 

global proc checkSubdTemplateEnable( string $nodeName )
{
	string $nodeAttr = $nodeName + ".subdMethod";
	int $subm = `getAttr $nodeAttr`;
		
	if($subm == 0)
	{
		editorTemplate -dimControl $nodeName "divisionsU" true;
		editorTemplate -dimControl $nodeName "divisionsV" true;
		editorTemplate -dimControl $nodeName "divisions" false;
		editorTemplate -dimControl $nodeName "mode" false;
	}
	else
	{
		editorTemplate -dimControl $nodeName "divisions" true;
		editorTemplate -dimControl $nodeName "mode" true;
		editorTemplate -dimControl $nodeName "divisionsU" false;
		editorTemplate -dimControl $nodeName "divisionsV" false;
	}
}


global proc AEpolySubdFaceTemplate ( string $nodeName )
{
	editorTemplate -beginScrollLayout;
	editorTemplate -beginLayout (uiRes("m_AEpolySubdFaceTemplate.kPolySubdivideFaceHistory")) -collapse 0;

		editorTemplate -label (uiRes("m_AEpolySubdFaceTemplate.kSubdivisionMethod")) -addControl "subdMethod" "checkSubdTemplateEnable";
		
		editorTemplate -label (uiRes("m_AEpolySubdFaceTemplate.kSubdivisionLevels")) -addControl "divisions";
		editorTemplate -addControl "mode";

		editorTemplate -addControl "divisionsU";
		editorTemplate -addControl "divisionsV";

	editorTemplate -endLayout;
		// include/call base class/node attributes		
		AEpolyModifierInclude $nodeName;

	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
}
