// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Advanced Options" m_AEpolyReduceTemplate.kAdvancedOptions;
displayString -replace -value "Cache reduction (for speed)" m_AEpolyReduceTemplate.kCacheReduction;
displayString -replace -value "Feature Preservation" m_AEpolyReduceTemplate.kFeaturePreservation;
displayString -replace -value "Invert weights" m_AEpolyReduceTemplate.kInvertVertexWeights;
displayString -replace -value "Legacy Attributes" m_AEpolyReduceTemplate.kLegacyAttributes;
displayString -replace -value "Border" m_AEpolyReduceTemplate.kLegacyBorder;
displayString -replace -value "Detail" m_AEpolyReduceTemplate.kLegacyDetail;
displayString -replace -value "Line" m_AEpolyReduceTemplate.kLegacyLine;
displayString -replace -value "Percentage" m_AEpolyReduceTemplate.kPercentage;
displayString -replace -value "Poly Reduce History" m_AEpolyReduceTemplate.kPolyReduceHistory;
displayString -replace -value "Preserve hard edges" m_AEpolyReduceTemplate.kPreserveHardEdges;
displayString -replace -value "Preserve mesh borders" m_AEpolyReduceTemplate.kPreserveMeshBorders;
displayString -replace -value "Preserve original vertices" m_AEpolyReduceTemplate.kPreserveOriginalVertices;
displayString -replace -value "Preserve quads" m_AEpolyReduceTemplate.kPreserveQuadLines;
displayString -replace -value "Preserve UV borders" m_AEpolyReduceTemplate.kPreserveUVBorders;
displayString -replace -value "Percentage" m_AEpolyReduceTemplate.kReduceByPercent;
displayString -replace -value "Triangle limit" m_AEpolyReduceTemplate.kReduceTriangleCount;
displayString -replace -value "Vertex limit" m_AEpolyReduceTemplate.kReduceVertexCount;
displayString -replace -value "Shape" m_AEpolyReduceTemplate.kShape;
displayString -replace -value "Sharpness" m_AEpolyReduceTemplate.kSharpness;
displayString -replace -value "Color borders" m_AEpolyReduceTemplate.kSoftPreserveColorBorders;
displayString -replace -value "Crease edges" m_AEpolyReduceTemplate.kSoftPreserveCreaseEdges;
displayString -replace -value "Material borders" m_AEpolyReduceTemplate.kSoftPreserveGroupBorders;
displayString -replace -value "Hard edges" m_AEpolyReduceTemplate.kSoftPreserveHardEdges;
displayString -replace -value "Mesh borders" m_AEpolyReduceTemplate.kSoftPreserveMeshBorders;
displayString -replace -value "UV borders" m_AEpolyReduceTemplate.kSoftPreserveUVBorders;
displayString -replace -value "Note: set preserve quads to < 1.0 to use symmetry" m_AEpolyReduceTemplate.kSymmetryHint;
displayString -replace -value "Symmetry plane XYZ" m_AEpolyReduceTemplate.kSymmetryPlane;
displayString -replace -value "Symmetry tolerance" m_AEpolyReduceTemplate.kSymmetryTolerance;
displayString -replace -value "Reduction method" m_AEpolyReduceTemplate.kTermination;
displayString -replace -value "Reduction Method" m_AEpolyReduceTemplate.kTerminationConditions;
displayString -replace -value "Face compactness" m_AEpolyReduceTemplate.kTriangleCompactness;
displayString -replace -value "Triangle limit" m_AEpolyReduceTemplate.kTriangleCount;
displayString -replace -value "Preserve quads" m_AEpolyReduceTemplate.kTrianglePenaltyWeight;
displayString -replace -value "Triangulate" m_AEpolyReduceTemplate.kTriangulate;
displayString -replace -value "UVs weight" m_AEpolyReduceTemplate.kUVsWeight;
displayString -replace -value "Symmetry type" m_AEpolyReduceTemplate.kUseVirtualSymmetry;
displayString -replace -value "W" m_AEpolyReduceTemplate.kVectorW;
displayString -replace -value "Version" m_AEpolyReduceTemplate.kVersion;
displayString -replace -value "Vertex colors weight" m_AEpolyReduceTemplate.kVertexColorsWeight;
displayString -replace -value "Vertex limit" m_AEpolyReduceTemplate.kVertexCount;
displayString -replace -value "Vertex index map" m_AEpolyReduceTemplate.kVertexMapName;
displayString -replace -value "Weight map coefficient" m_AEpolyReduceTemplate.kVertexWeightCoefficient;
