// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Animation" m_AErenderGlobalsTemplate.kAnimation;
displayString -replace -value "Depth" m_AErenderGlobalsTemplate.kDepth;
displayString -replace -value "Environment Fog" m_AErenderGlobalsTemplate.kEnvironmentFog;
displayString -replace -value "Image" m_AErenderGlobalsTemplate.kImage;
displayString -replace -value "Mask" m_AErenderGlobalsTemplate.kMask;
displayString -replace -value "MEL Callbacks" m_AErenderGlobalsTemplate.kMelCallbacks;
displayString -replace -value "Memory and Performance Options" m_AErenderGlobalsTemplate.kMemoryandPerformanceOptions;
displayString -replace -value "Motion Blur" m_AErenderGlobalsTemplate.kMotionBlur;
displayString -replace -value "New" m_AErenderGlobalsTemplate.kNew;
displayString -replace -value "New" m_AErenderGlobalsTemplate.kNewButton;
displayString -replace -value "Output Extensions" m_AErenderGlobalsTemplate.kOutputExtensions;
displayString -replace -value "Render Active" m_AErenderGlobalsTemplate.kRender;
displayString -replace -value "Render All" m_AErenderGlobalsTemplate.kRenderAll;
displayString -replace -value "Renderable Objects" m_AErenderGlobalsTemplate.kRenderObjects;
displayString -replace -value "Render Quality" m_AErenderGlobalsTemplate.kRenderQuality;
displayString -replace -value "Render Quality + Resolution" m_AErenderGlobalsTemplate.kRenderQualityResolution;
displayString -replace -value "Render Resolution" m_AErenderGlobalsTemplate.kRenderResolution;
displayString -replace -value "Renderable" m_AErenderGlobalsTemplate.kRenderable;
displayString -replace -value "Renderable Objects + Cameras" m_AErenderGlobalsTemplate.kRenderableObjectsCamera;
displayString -replace -value "Special Effects" m_AErenderGlobalsTemplate.kSpecialEffects;
