// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//  Procedure Name:
//	AEtexture2dCommon
//
//  Description:
//	Creates the attribute editor controls without a scroll layout
//	for the texture2d Node
//
//  Input Value:
//	nodeName
//
//  Output Value:
//	None
//

// Add controls for common attributes from TdnTx2d
global proc AEtexture2dCommon ( string $nodeName )
{
	// check on the type of the node
	// to place the correct widgets

	string $type = `nodeType $nodeName`;

	editorTemplate -beginLayout (uiRes("m_AEtexture2dCommon.kColorBalance"));
	// ADSK_CLR_MGT_BEGIN
	if ($type == "file")
	{
		editorTemplate -addControl "exposure";
	}
	else if ($type == "movie")
	{
		editorTemplate -suppress "exposure";
	}
	// ADSK_CLR_MGT_END

	editorTemplate -addControl "defaultColor";
	editorTemplate -addControl "colorGain";
	editorTemplate -addControl "colorOffset";
	editorTemplate -addControl "alphaGain";
	editorTemplate -addControl "alphaOffset";
	if ($type == "cloth" || $type == "ramp" ||
		$type == "stencil" )
	{
		editorTemplate -suppress "alphaIsLuminance";
	}
	else
	{
       	editorTemplate -addControl "alphaIsLuminance";
	}
	editorTemplate -endLayout;

	editorTemplate -beginLayout (uiRes("m_AEtexture2dCommon.kEffects"));
	if ( $type == "bulge" || $type == "cloth" ||
			$type == "ramp" || $type == "water" )
		{
			editorTemplate -suppress "filter";
			editorTemplate -suppress "filterOffset";
		} else {
	        	editorTemplate -addControl "filter";
        		editorTemplate -addControl "filterOffset";
		}
		editorTemplate -addControl "invert";
        	editorTemplate -callCustom "AEcolorRemapNew"
					"AEcolorRemapReplace"
					"outColor";
	editorTemplate -endLayout;
	editorTemplate -beginLayout (uiRes("m_AEtexture2dCommon.kUVCoordinates"));
	editorTemplate -addControl "uvCoord";
	editorTemplate -endLayout;


	// include/call base class/node attributes
	AEdependNodeTemplate $nodeName;
}
