// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

displayString -replace -value "Custom" m_AEVRMatOverrideFlags.kCustom;
displayString -replace -value "Edge Color" m_AEVRMatOverrideFlags.kEdgeColor;
displayString -replace -value "Edge Priority" m_AEVRMatOverrideFlags.kEdgePriority;
displayString -replace -value "Edge Style" m_AEVRMatOverrideFlags.kEdgeStyle;
displayString -replace -value "Edge Weight" m_AEVRMatOverrideFlags.kEdgeWeight;
displayString -replace -value "Default" m_AEVRMatOverrideFlags.kEdgeWeightDefault;
displayString -replace -value "Edge Weight Presets" m_AEVRMatOverrideFlags.kEdgeWeightPresets;
displayString -replace -value "Fill Object" m_AEVRMatOverrideFlags.kFillObject;
displayString -replace -value "Area Gradient and Mesh Gradient fill styles are incompatible with EPS or Adobe(R) Illustrator(R) output format. Setting to Average Color." m_AEVRMatOverrideFlags.kGradientWarn;
displayString -replace -value "Hairline" m_AEVRMatOverrideFlags.kHairline;
displayString -replace -value "Hidden Edges" m_AEVRMatOverrideFlags.kHiddenEdges;
displayString -replace -value "Hidden Edges On Transparent" m_AEVRMatOverrideFlags.kHiddenEdgesOnTransparent;
displayString -replace -value "Outlines At Intersections" m_AEVRMatOverrideFlags.kOutlinesAtIntersections;
displayString -replace -value "Overwrite Default Values" m_AEVRMatOverrideFlags.kOverwriteDefaultValues;
displayString -replace -value "^1spt." m_AEVRMatOverrideFlags.kPtFmt;
displayString -replace -value "Vector Renderer Control" m_AEVRMatOverrideFlags.kVectorRendererControl;
