// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

//
//
// Creation Date:  14 July 2000
//
//  Procedure Name:
//      modelNodeNameScheme	
//
//  Description:
//	    Set or get the values for the current node naming scheme
//
//  Input Arguments:
//		-1 --> query and return what the current settings are
//       0 --> set to 'Retain Same Name for Child Nodes'
//       1 --> set to 'Assign Unique Name to Child Nodes'
//
//  Return Value:
//      0 if 'Retain Same Name for Child Nodes'
//      1 if 'Assign Unique Name to Child Nodes'
//

global proc int modelNodeNameScheme( int $type )
{
	int $val;
	if( -1 == $type ) {
		$val = `optionVar -q modelNodeNameScheme`;
	}
	else {
		optionVar -iv modelNodeNameScheme $type;
		$val = $type;
	}
	return $val;
}

