// Copyright (C) 1997-2014 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

global proc updateLayerManagerPopup( )
//
//
// Creation Date:  Dec2 98
//
//
//  Procedure Name:
//      updateLayerManagerPopup
//
//  Description:
//		This script updates all layer UI whenever
//		the "displayLayerManagerChange" trigger is
//		fired (IE: a new layer manager has been created/deleted).
//
//  Input Arguments:
//      None.
//
//  Return Value:
//      None.
//
{
	string $allManagers[] = `ls -type displayLayerManager`;

	for( $item in $allManagers ){
		string $managerName = $item;
		string $layerEntryName = ( $managerName + "LayerItem" ); 
		if( !`menuItem -exists $layerEntryName` ){
			menuItem -p layerManagerPopup -l $managerName $layerEntryName;
		}
	}
	//
	// If layers were deleted, remove them from the layers
	// option menu.  Do not remove the 'Universe' item.
	//
	string $menuList[] = `optionMenu -q -ils layerManagerPopup`;

	for( $layerMenuItem in $menuList ){
		string $managerName = `menuItem -q -l $layerMenuItem`;

		if( !`objExists $managerName` ){
			deleteUI ( $layerMenuItem );
		}
	}	
}
