import maya

maya.stringTable['y_xgmExternalAPI.kRenamePaletteFolder'] = u'Palette folder renamed.\nNew: %s\nOld: %s'
maya.stringTable['y_xgmExternalAPI.kCannotRenameDescription'] = u'Cannot rename description <%s> to <%s>'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPIErrWrapXgenDeleteDesc'] = u'***Deleting the description from the scene!***'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPIExceptionXgmInterpSetup'] = u'Exception while executing xgmInterpSetup'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPIErrWrapXgenDeleteCol'] = u'***Deleting the collection from the scene!***'
maya.stringTable['y_xgmExternalAPI.kRenameDescriptionFolder'] = u'Description folder renamed.\nNew: %s\nOld: %s'
maya.stringTable['y_xgmExternalAPI.kDescriptionClash'] = u'New description name <%s> is clashing with an existing description on disk and was renamed to <%s>'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPINoColSpecifiedForBinding'] = u'No collection specified for modifying face bindings.'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPIErrWrapXgenCol'] = u'Error wrapping xgen for collection '
maya.stringTable['y_xgmExternalAPI.kCreateXgenDescription2'] = u'Create XGen Description'
maya.stringTable['y_xgmExternalAPI.kInvalidNamespace'] = u'Invalid namespace syntax used in the collection name.'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPINoDescSpecifiedForBinding'] = u'No description specified for modifying face bindings.'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPICannotModifyQuitOnError'] = u'quitOnError cannot be modified from within Maya.'
maya.stringTable['y_xgmExternalAPI.kCollectionNamespace'] = u'Collection namespace <%s> does not match the selected object(s) namespace <%s>'
maya.stringTable['y_xgmExternalAPI.kPaletteClash'] = u'New palette name <%s> is clashing with an existing palette on disk and was renamed to <%s>'
maya.stringTable['y_xgmExternalAPI.kPalPathError'] = u'Cannot get palette Path'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPICouldNotSetInitInterop'] = u'Could not initialize interpolation'
maya.stringTable['y_xgmExternalAPI.kCannotCopyXgenFile'] = u'Cannot copy file from: %s \nto: %s'
maya.stringTable['y_xgmExternalAPI.kCreateXgenDescription3'] = u'Create XGen Description'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPIErrRunningUndoable'] = u'Error while running undoable <%s> : %s'
maya.stringTable['y_xgmExternalAPI.kSelectedObjectsNotPartOfCollection'] = u'Selected object(s) not part of the collection namespace <%s>'
maya.stringTable['y_xgmExternalAPI.kCannotRenamePalette'] = u'Cannot rename palette <%s> to <%s>'
maya.stringTable['y_xgmExternalAPI.kCreateXgenDescription'] = u'Create XGen Description'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPIErrWrapXgenDesc'] = u'Error wrapping xgen for description '
maya.stringTable['y_xgmExternalAPI.kCannotRenamePalette2'] = u'Cannot rename palette <%s> to <%s>'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPIFilesBaked'] = u'The following files were baked:'
maya.stringTable['y_xgmExternalAPI.kXgmExtAPIErrFindingGeo'] = u'Error finding connected geometry for: '
maya.stringTable['y_xgmExternalAPI.kXgmExtAPICouldNotSetActiveType'] = u'Could not set active type'
maya.stringTable['y_xgmExternalAPI.kxgDataPathBroken'] = u'one of xgDataPath for collection <%s> is invalid and needs to be updated: <%s>'

