import maya

maya.stringTable['y_xgCardPrimitiveTab.kBendParamVAnn'] = u'Control where the card bends in the V direction.\n0 is at the center of the card, and 1 is at the edges. Cards bend in two places.'
maya.stringTable['y_xgCardPrimitiveTab.kTwist'] = u'Twist'
maya.stringTable['y_xgCardPrimitiveTab.kTiltN'] = u'Tilt N'
maya.stringTable['y_xgCardPrimitiveTab.kTiltVAnn'] = u'Tilt the card away from the surface normal, but at right angles to Tilt U.'
maya.stringTable['y_xgCardPrimitiveTab.kTiltU'] = u'Tilt U'
maya.stringTable['y_xgCardPrimitiveTab.kTiltV'] = u'Tilt V'
maya.stringTable['y_xgCardPrimitiveTab.kBendU'] = u'Bend U'
maya.stringTable['y_xgCardPrimitiveTab.kBendV'] = u'Bend V'
maya.stringTable['y_xgCardPrimitiveTab.kTiltNAnn'] = u'Magnify how much the card is tilted away from the surface normal by Tilt U and Tilt V.\nIf Tilt U and Tilt V are 0, Tilt N has no effect.'
maya.stringTable['y_xgCardPrimitiveTab.kBendVAnn'] = u'Control how much each card is bent in the V direction.\n0 is no bend, and 1.0 is a 90-degree bend. Cards bend in two places.'
maya.stringTable['y_xgCardPrimitiveTab.kTiltUAnn'] = u'Tilt the card away from the surface normal.\n0 is no tilt, and 1.0 is a 90-degree tilt.'
maya.stringTable['y_xgCardPrimitiveTab.kAroundN'] = u'Around N'
maya.stringTable['y_xgCardPrimitiveTab.kTwistAnn'] = u'Rotate the card around its local normal vector.\n(This vector is affected by Bump, Tilt U, Tilt V, etc.)'
maya.stringTable['y_xgCardPrimitiveTab.kFaceCamera'] = u'Face Camera'
maya.stringTable['y_xgCardPrimitiveTab.kWidthScaleAnn'] = u'Scale the width of each card.'
maya.stringTable['y_xgCardPrimitiveTab.kLength'] = u'Length'
maya.stringTable['y_xgCardPrimitiveTab.kFaceCameraAnn'] = u'Rotate each card to face the camera as directly as possible.'
maya.stringTable['y_xgCardPrimitiveTab.kWidthAnn'] = u'Control the width of each card.'
maya.stringTable['y_xgCardPrimitiveTab.kBendParamUAnn'] = u'Control where the card bends in the U direction.\n0 is at the center of the card, and 1 is at the edges. Cards bend in two places.'
maya.stringTable['y_xgCardPrimitiveTab.kAroundNAnn'] = u'Rotate the card around the surface normal vector.\n(This vector is not affected by Bump, Tilt U, Tilt V, etc.)'
maya.stringTable['y_xgCardPrimitiveTab.kLengthScaleAnn'] = u'Scale the length of each card.'
maya.stringTable['y_xgCardPrimitiveTab.kBendParamU'] = u'Bend Param U'
maya.stringTable['y_xgCardPrimitiveTab.kBendParamV'] = u'Bend Param V'
maya.stringTable['y_xgCardPrimitiveTab.kLengthAnn'] = u'Control the length of each card.'
maya.stringTable['y_xgCardPrimitiveTab.kWidth'] = u'Width'
maya.stringTable['y_xgCardPrimitiveTab.kCard'] = u'Card'
maya.stringTable['y_xgCardPrimitiveTab.kBendUAnn'] = u'Control how much each card is bent in the U direction.\n0 is no bend, and 1.0 is a 90-degree bend. Cards bend in two places.'

