import maya

maya.stringTable['y_xgPrimitiveTab.kCard'] = u'Card'
maya.stringTable['y_xgPrimitiveTab.kNoExtraAttributesForSPrimitive'] = u'No extra attributes for %s primitive.'
maya.stringTable['y_xgPrimitiveTab.kAttachedCurves'] = u'The following curves were attached: '
maya.stringTable['y_xgPrimitiveTab.kRegionMap'] = u'Region Map'
maya.stringTable['y_xgPrimitiveTab.kCreateHairSystem'] = u'Create Hair System'
maya.stringTable['y_xgPrimitiveTab.kPrimitiveTypeAnn'] = u'Control the kind of primitive that this description generates.'
maya.stringTable['y_xgPrimitiveTab.kSpline'] = u'Spline'
maya.stringTable['y_xgPrimitiveTab.kControlUsingAnn'] = u'Sets whether Attributes or Guides control the grooming of this description.\n(Groomable Splines are controlled by Attributes and image maps created by the grooming tools.'
maya.stringTable['y_xgPrimitiveTab.kArchive'] = u'Archive'
maya.stringTable['y_xgPrimitiveTab.kLiveModeAnn'] = u'Read the wire animation from the connected hair system'
maya.stringTable['y_xgPrimitiveTab.kCreateHairSystemAnn'] = u'The guides are used to generate an hair system.'
maya.stringTable['y_xgPrimitiveTab.kCacheFileNameAnn'] = u'Path to the cached guide animation file.'
maya.stringTable['y_xgPrimitiveTab.kSphere'] = u'Sphere'
maya.stringTable['y_xgPrimitiveTab.kGuideAnimation'] = u'Guide Animation'
maya.stringTable['y_xgPrimitiveTab.kPrimitiveType'] = u'Primitive Type'
maya.stringTable['y_xgPrimitiveTab.kLiveMode'] = u'Live Mode'
maya.stringTable['y_xgPrimitiveTab.kRegionMask'] = u'Region Mask'
maya.stringTable['y_xgPrimitiveTab.kMethodAnn'] = u'Method to control instanced primitives.'
maya.stringTable['y_xgPrimitiveTab.kRegionControl'] = u'Region Control'
maya.stringTable['y_xgPrimitiveTab.kPrimTabUnknownType'] = u'Unknown type %s'
maya.stringTable['y_xgPrimitiveTab.kUseAnimation'] = u'Use Animation'
maya.stringTable['y_xgPrimitiveTab.kThereIsNoGuidesWarning'] = u'There is no guides in the current description. Failed to create the hair system.'
maya.stringTable['y_xgPrimitiveTab.kCacheFileName'] = u'Cache File Name'
maya.stringTable['y_xgPrimitiveTab.kAttribute'] = u'Attribute'
maya.stringTable['y_xgPrimitiveTab.kNoCurvesSelected'] = u'No curves selected. Nothing to attach.'
maya.stringTable['y_xgPrimitiveTab.kAttachHairSystem'] = u'Attach Hair System'
maya.stringTable['y_xgPrimitiveTab.kControlUsing'] = u'Control using'
maya.stringTable['y_xgPrimitiveTab.kAttachHairSystemAnn'] = u'The output curves of an hair system are attached and then drive the animation of the wires.'
maya.stringTable['y_xgPrimitiveTab.kGuides'] = u'Guides'
maya.stringTable['y_xgPrimitiveTab.kPrimitiveAttributes'] = u'Primitive Attributes'
maya.stringTable['y_xgPrimitiveTab.kRegionMaskAnn'] = u'Controls the effect of the Region Map.\nYou can attach a texture map to this attribute to control where the region map has greater and lesser effect.'
maya.stringTable['y_xgPrimitiveTab.kRegionMapAnn'] = u'The region map is a texture map that you can attach to this attribute.\nUse region maps to divide your underlying surface into different regions, by painting each region a different color. The guides and grooming in each region only affect the primitives in the same region.'
maya.stringTable['y_xgPrimitiveTab.kUseAnimAnn'] = u'Set to use cached animation guides.'

