import maya

maya.stringTable['y_xgRandomGeneratorTab.kDensity'] = u'Density'
maya.stringTable['y_xgRandomGeneratorTab.kSpecifyPointsTool'] = u'Specify Points Tool'
maya.stringTable['y_xgRandomGeneratorTab.kLoad'] = u'Revert to Last Saved'
maya.stringTable['y_xgRandomGeneratorTab.kPointFileFolder'] = u'Point File Folder'
maya.stringTable['y_xgRandomGeneratorTab.kSpecifyPointsAnn'] = u'Edit the extra points by interactive brush context.'
maya.stringTable['y_xgRandomGeneratorTab.kCompensateForShapeStretching'] = u'Compensate Normals'
maya.stringTable['y_xgRandomGeneratorTab.kCalculatingDensityCompensationMaps'] = u'Calculating density compensation maps.'
maya.stringTable['y_xgRandomGeneratorTab.kRevertToLastSavedAnn'] = u'Load the last-saved points\nfile and use its points'
maya.stringTable['y_xgRandomGeneratorTab.kMask'] = u'Mask'
maya.stringTable['y_xgRandomGeneratorTab.kCompensateUnevenAnn'] = u'Redistribute primitives in areas where the distribution is uneven because the surface has a mix of small and large faces.\nWhen on, you need to click Create Parameterization Map below to create a parameterization map.'
maya.stringTable['y_xgRandomGeneratorTab.kCloseAnn'] = u'Close this window\nwithout saving any\npoints.'
maya.stringTable['y_xgRandomGeneratorTab.kGenerateAnn'] = u'Create or update the map used to compensate for uneven parameterization.\nUpdate this map if the surface shape is altered significantly.'
maya.stringTable['y_xgRandomGeneratorTab.kClearAnn'] = u'Clear the points in the\nview. (Does not affect\nsaved points.)'
maya.stringTable['y_xgRandomGeneratorTab.kSpecifyPoints'] = u'Specify Points...'
maya.stringTable['y_xgRandomGeneratorTab.kCancel'] = u'Close'
maya.stringTable['y_xgRandomGeneratorTab.kPointDirAnn'] = u'Specify a folder to hold the point location file.\nFor most cases, use the default.'
maya.stringTable['y_xgRandomGeneratorTab.kClear'] = u'Clear'
maya.stringTable['y_xgRandomGeneratorTab.kDensityAnn'] = u'Control the number of primitives created by XGen over a given area.'
maya.stringTable['y_xgRandomGeneratorTab.kSave'] = u'Save && Close'
maya.stringTable['y_xgRandomGeneratorTab.kGenerate'] = u'Create Parameterization Map'
maya.stringTable['y_xgRandomGeneratorTab.kRandom'] = u'Random'
maya.stringTable['y_xgRandomGeneratorTab.kCompensateForUnevenParameterization'] = u'Compensate for uneven parameterization'
maya.stringTable['y_xgRandomGeneratorTab.kMorePrimitivesAtAnn'] = u'Use extra points provided via XUV files.'
maya.stringTable['y_xgRandomGeneratorTab.kSaveNCloseAnn'] = u'Save the displayed\npoints to the file and\nclose this window.'
maya.stringTable['y_xgRandomGeneratorTab.kMaskAnn'] = u'This number is a multiplier on the Density.\nUse an expression or image map here to vary the density of primitives over parts of the surface.'
maya.stringTable['y_xgRandomGeneratorTab.kCompensateAnn'] = u'Averages the growth normals for primitives to prevent visible faceting on curved surfaces.\nUse this when the primitive distribution shows obvious face boundaries.'
maya.stringTable['y_xgRandomGeneratorTab.kMorePrimitivesAt'] = u'More Primitives at'
maya.stringTable['y_xgRandomGeneratorTab.kToolDescription'] = u'Click or brush on a model to specify where primitives should be created.\nSpecified points will be stored in an external file.'

