import maya

maya.stringTable['y_xgSpherePrimitiveTab.kSphere'] = u'Sphere'
maya.stringTable['y_xgSpherePrimitiveTab.kTiltU'] = u'Tilt U'
maya.stringTable['y_xgSpherePrimitiveTab.kLengthAnn'] = u'Control the height of each sphere from its base.'
maya.stringTable['y_xgSpherePrimitiveTab.kTiltV'] = u'Tilt V'
maya.stringTable['y_xgSpherePrimitiveTab.kWidthAnn'] = u'Control the width of each sphere in one dimension.'
maya.stringTable['y_xgSpherePrimitiveTab.kDepthScaleAnn'] = u'Scale the width of each sphere in the other dimension.'
maya.stringTable['y_xgSpherePrimitiveTab.kDepthAnn'] = u'Control the width of each sphere in the other dimension.'
maya.stringTable['y_xgSpherePrimitiveTab.kTiltUAnn'] = u'Tilt the sphere away from the surface normal.\n0 is no tilt, and 1.0 is a 90-degree tilt.'
maya.stringTable['y_xgSpherePrimitiveTab.kLength'] = u'Length'
maya.stringTable['y_xgSpherePrimitiveTab.kTwistAnn'] = u'Rotate the sphere around its local normal vector.\n(This vector is affected by Bump, Tilt U, Tilt V, etc.)'
maya.stringTable['y_xgSpherePrimitiveTab.kTiltN'] = u'Tilt N'
maya.stringTable['y_xgSpherePrimitiveTab.kAroundN'] = u'Around N'
maya.stringTable['y_xgSpherePrimitiveTab.kTiltVAnn'] = u'Tilt the sphere away from the surface normal, but at right angles to Tilt U.'
maya.stringTable['y_xgSpherePrimitiveTab.kTiltNAnn'] = u'Magnify how much the sphere is tilted away from the surface normal by Tilt U and Tilt V.\nIf Tilt U and Tilt V are 0, Tilt N has no effect.'
maya.stringTable['y_xgSpherePrimitiveTab.kDepth'] = u'Depth'
maya.stringTable['y_xgSpherePrimitiveTab.kWidth'] = u'Width'
maya.stringTable['y_xgSpherePrimitiveTab.kLengthScaleAnn'] = u'Scale the height of each sphere from its base.'
maya.stringTable['y_xgSpherePrimitiveTab.kTwist'] = u'Twist'
maya.stringTable['y_xgSpherePrimitiveTab.kWidthScaleAnn'] = u'Scale the width of each sphere in one dimension.'
maya.stringTable['y_xgSpherePrimitiveTab.kAboutNAnn'] = u'Rotate the sphere around the surface normal vector.\n(This vector is not affected by Bump, Tilt U, Tilt V, etc.)'

